### PR TITLE
#20627: Increase LayoutSpec stresstest patience

### LINKED ISSUE #20627: FAILED: StreamLayoutSpec
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/6317/consoleFull

```
o]   - when starting from a Source *** FAILED *** (10 seconds, 193 milliseconds)
[info]     A timeout occurred waiting for a future to complete. Queried 36 times, sleeping 15 milliseconds between each query. (StreamLayoutSpec.scala:134)
[info]     org.scalatest.concurrent.Futures$FutureConcept$$anon$1:
[info]     at org.scalatest.concurrent.Futures$FutureConcept$class.tryTryAgain$1(Futures.scala:546)
[info]     at org.scalatest.concurrent.Futures$FutureConcept$class.futureValue(Futures.scala:558)
[info]     at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:74)
[info]     at akka.stream.impl.StreamLayoutSpec$$anonfun$1$$anonfun$apply$mcV$sp$4$$anonfun$apply$mcV$sp$5.apply$mcV$sp(StreamLayoutSpec.scala:134)
[info]     at akka.stream.impl.StreamLayoutSpec$$anonfun$1$$anonfun$apply$mcV$sp$4$$anonfun$apply$mcV$sp$5.apply(StreamLayoutSpec.scala:128)
[info]     at akka.stream.impl.StreamLayoutSpec$$anonfun$1$$anonfun$apply$mcV$sp$4$$anonfun$apply$mcV$sp$5.apply(StreamLayoutSpec.scala:128)
[info]     at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]     at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]     at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]     at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]     at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]     at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[info]     at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]     at akka.testkit.AkkaSpec.withFixture(AkkaSpec.scala:57)
[info]     at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
[info]     at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]     at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]     at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]     at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)
[info]     at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:57)
[info]     at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]     at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]     at scala.collection.immutable.List.foreach(List.scala:381)
[info]     at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]     at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]     at scala.collection.immutable.List.foreach(List.scala:381)
[info]     at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]     at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]     at scala.collection.immutable.List.foreach(List.scala:381)
[info]     at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]     at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
[info]     at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
[info]     at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1021)
[info]     at akka.testkit.AkkaSpec.runTests(AkkaSpec.scala:57)
[info]     at org.scalatest.Suite$class.run(Suite.scala:1424)
[info]     at akka.testkit.AkkaSpec.org$scalatest$WordSpecLike$$super$run(AkkaSpec.scala:57)
[info]     at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
[info]     at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
[info]     at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
[info]     at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1067)
[info]     at akka.testkit.AkkaSpec.org$scalatest$BeforeAndAfterAll$$super$run(AkkaSpec.scala:57)
[info]     at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257)
[info]     at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256)
[info]     at akka.testkit.AkkaSpec.run(AkkaSpec.scala:57)
[info]     at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(F
```

### PR DESCRIPTION
**Pull request by drewhk**
Fixes #20627

### CODE REVIEW

**Comment by johanandren** [comment]
LGTM

File: akka-stream-tests/src/test/scala/akka/stream/impl/StreamLayoutSpec.scala [hunk 1]
```diff
@@ -124,21 +126,23 @@ class StreamLayoutSpec extends AkkaSpec {
     }
 
     "not fail materialization when building a large graph with simple computation" when {
+      // Seen tests run in 9-10 seconds, these test cases are heavy on the GC
```
Comment (patriknw) [inline akka-stream-tests/src/test/scala/akka/stream/impl/StreamLayoutSpec.scala]: yeah, it seems to be very heavy on GC. 
```
2357.321: [GC (Allocation Failure) [PSYoungGen: 593259K->29833K(618496K)] 1925032K->1361613K(2016768K), 0.1259008 secs] [Times: user=1.12 sys=0.02, real=0.13 secs] 
2360.995: [GC (Allocation Failure) --[PSYoungGen: 618121K->618121K(618496K)] 1949901K->2016389K(2016768K), 1.2152092 secs] [Times: user=14.67 sys=7.55, real=1.21 secs] 
2362.210: [Full GC (Ergonomics) [PSYoungGen: 618121K->69251K(618496K)] [ParOldGen: 1398268K->1398243K(1398272K)] 2016389K->1467494K(2016768K), [Metaspace: 372791K->372774K(1368064K)], 3.6699223 secs] [Times: user=89.71 sys=0.77, real=3.67 secs] 
[info]   - when starting from a Source *** FAILED *** (9 seconds, 283 milliseconds)
[info]     A timeout occurred waiting for a future to complete. Queried 20 times, sleeping 15 milliseconds between each query. (StreamLayoutSpec.scala:134)
```

Perhaps we should give it even more time to complete?

What's not so nice with such garbage generating tests is that GC can easily spill over to other tests (later tests or tests running in parallel).

Comment (drewhk) [inline akka-stream-tests/src/test/scala/akka/stream/impl/StreamLayoutSpec.scala]: Unfortunately otherwise you cannot test that we don't exhaust the stack :(

Comment (patriknw) [inline akka-stream-tests/src/test/scala/akka/stream/impl/StreamLayoutSpec.scala]: yes, I'm not suggesting to remove it, but we can keep it mind if we see spurious failures occurring right after this test

increase the PatienceConfig to 20.seconds

**Comment by ktoso** [comment]
LGTM from my end as well btw
