### PR TITLE
str #20049 OutputStreamSource thread leak fixed

### LINKED ISSUE #20049: OutputStreamSource leaks threads
seen after running the tests:
~~~
"OutputStreamSource-akka.test.stream-dispatcher-10" #1792 prio=5 os_prio=31 tid=0x00007fdd410f1000 nid=0x100e3 waiting on condition [0x000000013ad01000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000074dbaac50> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at akka.stream.impl.io.OutputStreamSourceStage$$anon$1$$anon$2$$anonfun$onPull$1.apply(OutputStreamSourceStage.scala:114)
	at akka.stream.impl.io.OutputStreamSourceStage$$anon$1$$anon$2$$anonfun$onPull$1.apply(OutputStreamSourceStage.scala:114)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:405)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
~~~
It looks like the `Future(dataQueue.take())` in `onPull` is never unblocked by putting data into the queue when things are closed.

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #20049

### CODE REVIEW

File: akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala [hunk 1]
```diff
@@ -107,6 +107,8 @@ final private[stream] class OutputStreamSourceStage(writeTimeout: FiniteDuration
           //assuming there can be no further in messages
           downstreamStatus.set(Canceled)
           dataQueue.clear()
+          // if blocked reading, make sure the take() completes
+          dataQueue.put(ByteString())
```
Comment (drewhk) [inline akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala]: um, how does this work?

Comment (johanandren) [inline akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala]: Do you mean the empty `ByteString`? there is a vararg apply, so it will be an empty array of bytes.

Comment (johanandren) [inline akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala]: Or do you mean the unblocking? The future below is blockingly waiting on a `take()`, so we send an element through the queue to make it unblock and notice that the stage is done with its business.

Comment (drewhk) [inline akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala]: No, I mean how does this fix the issue?

Comment (drewhk) [inline akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala]: ok, I see.

**Comment by drewhk** [comment]
LGTM

**Comment by ktoso** [comment]
I was suprised we do the following here:

```
implicit val ex = interpreter.materializer.executionContext
Future(dataQueue.take()).onComplete(downstreamCallback.invoke) // the mentioned take
```

I'd have thought we make sure to use proper blocking-io dispatcher for those like we do in the File ones?

```
val props = FilePublisher.props(f, ioResultPromise, chunkSize, settings.initialInputBufferSize, settings.maxInputBufferSize)
    val dispatcher = context.effectiveAttributes.get[Dispatcher](IODispatcher).dispatcher

```

File: akka-stream-tests/src/test/scala/akka/stream/io/OutputStreamSourceSpec.scala [hunk 2]
```diff
@@ -161,5 +163,26 @@ class OutputStreamSourceSpec extends AkkaSpec(UnboundedMailboxConfig) {
          */
       }
     }
+
+    "not leave blocked threads" in {
+      val (outputStream, probe) = StreamConverters.asOutputStream(timeout)
+        // .addAttributes(ActorAttributes.dispatcher("single-thread-dispatcher"))
```
Comment (ktoso) [inline akka-stream-tests/src/test/scala/akka/stream/io/OutputStreamSourceSpec.scala]: when would one uncomment this? (remove or document)

**Comment by ktoso** [comment]
LGTM, the dispatcher question is a separate issue

File: akka-stream-tests/src/test/scala/akka/stream/io/OutputStreamSourceSpec.scala (hunk 2 above)
Comment (johanandren) [inline akka-stream-tests/src/test/scala/akka/stream/io/OutputStreamSourceSpec.scala]: ups. leftover from trying different options for writing the test
