### PR TITLE
More generous timeout in typed ClusterApiSpec

### LINKED ISSUE #24728: failed: akka.cluster.typed.ClusterApiSpec
https://jenkins.akka.io:8498/job/akka-nightly/5316/testReport/junit/akka.cluster.typed/ClusterApiSpec/A_typed_Cluster_must_join_a_cluster_and_observe_events_from_both_sides/

```
Error Message
org.scalatest.exceptions.TestFailedException: Exiting did not equal Removed
Stacktrace
sbt.ForkMain$ForkError: org.scalatest.exceptions.TestFailedException: Exiting did not equal Removed
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
	at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6798)
	at akka.cluster.typed.ClusterApiSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$3.apply(ClusterApiSpec.scala:96)
	at akka.cluster.typed.ClusterApiSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$3.apply(ClusterApiSpec.scala:96)
	at akka.testkit.typed.internal.TestProbeImpl.poll$1(TestProbeImpl.scala:224)
	at akka.testkit.typed.internal.TestProbeImpl.awaitAssert(TestProbeImpl.scala:238)
	at akka.cluster.typed.ClusterApiSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ClusterApiSpec.scala:95)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
```

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #24728

### CODE REVIEW

**Review by raboof — APPROVED** [review]

File: akka-cluster-typed/src/test/scala/akka/cluster/typed/ClusterApiSpec.scala [hunk 1]
```diff
@@ -105,7 +104,7 @@ class ClusterApiSpec extends ActorTestKit with TypedAkkaSpecWithShutdown with Sc
         node2Probe.expectNoMessage()
 
       } finally {
-        Await.result(system2.terminate(), 3.seconds)
+        Await.result(system2.terminate(), 5.seconds)
```
Comment (chbatey) [inline akka-cluster-typed/src/test/scala/akka/cluster/typed/ClusterApiSpec.scala]: ActorTestkit.shutdown?

**Review by chbatey — APPROVED** [review]
LGTM, maybe change to use testkit to shutdown

File: akka-cluster-typed/src/test/scala/akka/cluster/typed/ClusterApiSpec.scala (hunk 1 above)
Comment (johanandren) [reply akka-cluster-typed/src/test/scala/akka/cluster/typed/ClusterApiSpec.scala]: Good idea.

**Review by ktoso — APPROVED** [review]
