### PR TITLE
Response rendering spec hardening

### LINKED ISSUE #21088: FAILED: ResponseRendererSpec
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/7000/consoleFull

```
[info] - The 'Connection' header should be rendered correctly *** FAILED *** (3 seconds, 18 milliseconds)
[info]   TestFailedException was thrown during property evaluation. (ResponseRendererSpec.scala:573)
[info]     Message: (HTTP/1.0 200 OK

[info]   Server: akka-http/1.0.0

[info]   Date: Thu, 25 Aug 2011 09:10:29 GMT

[info]   Connection: close

[info]   Content-Type: text/plain; charset=UTF-8

[info]   
[info]   ENTITY,Some(false)) did not equal (HTTP/1.0 200 OK

[info]   Server: akka-http/1.0.0

[info]   Date: Thu, 25 Aug 2011 09:10:29 GMT

[info]   Connection: close

[info]   Content-Type: text/plain; charset=UTF-8

[info]   
[info]   ENTITY,Some(true))
[info]     Location: (ResponseRendererSpec.scala:582)
[info]     Occurred at table row 71 (zero based, not counting headings), which had values (
[info]       Req Prot = HttpProtocol(HTTP/1.0),
[info]       HEAD Req = false,
[info]       Req CH = Some(Connection: Keep-Alive),
[info]       Res Prot = HttpProtocol(HTTP/1.0),
[info]       Res CH = Some(Connection: Keep-Alive),
[info]       Res CD = true,
[info]       Ren Conn = Some(Connection: close),
[info]       Close = true
[info]     )
[info]   org.scalatest.exceptions.TableDrivenPropertyCheckFailedException:
[info]   at org.scalatest.prop.TableFor8$$anonfun$apply$37.apply(TableFor1.scala:1626)
[info]   at org.scalatest.prop.TableFor8$$anonfun$apply$37.apply(TableFor1.scala:1617)
[info]   at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
[info]   at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
[info]   at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
[info]   at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
[info]   at org.scalatest.prop.TableFor8.apply(TableFor1.scala:1617)
[info]   at org.scalatest.prop.TableDrivenPropertyChecks$class.forAll(TableDrivenPropertyChecks.scala:462)
[info]   at org.scalatest.prop.TableDrivenPropertyChecks$.forAll(TableDrivenPropertyChecks.scala:665)
[info]   at akka.http.impl.engine.rendering.ResponseRendererSpec$$anonfun$1$$anonfun$apply$mcV$sp$38$$anon$30.<init>(ResponseRendererSpec.scala:573)
[info]   at akka.http.impl.engine.rendering.ResponseRendererSpec$$anonfun$1$$anonfun$apply$mcV$sp$38.apply$mcV$sp(ResponseRendererSpec.scala:461)
[info]   at akka.http.impl.engine.rendering.ResponseRendererSpec$$anonfun$1$$anonfun$apply$mcV$sp$38.apply(ResponseRendererSpec.scala:461)
[info]   at akka.http.impl.engine.rendering.ResponseRendererSpec$$anonfun$1$$anonfun$apply$mcV$sp$38.apply(ResponseRendererSpec.scala:461)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.FreeSpecLike$$anon$1.apply(FreeSpecLike.scala:373)
```

### PR DESCRIPTION
**Pull request by johanandren**
A bit more time between the always-close and the guess-that-the-blueprint-closed timeouts

Fixes  #21088

### CODE REVIEW

**Comment by johanandren** [comment]
Or, well, "Hopefully fixes #..."

File: akka-http-core/src/test/scala/akka/http/impl/engine/rendering/ResponseRendererSpec.scala [hunk 1]
```diff
@@ -620,7 +620,10 @@ class ResponseRendererSpec extends FreeSpec with Matchers with BeforeAndAfterAll
           case Some(close) ⇒
             // we try to find out if the renderer has already flagged completion even without the upstream being completed
             try {
-              Await.ready(wasCompletedFuture, 100.millis)
+              // note how this relates to the groupedWithin timeout above which will always
+              // close the stream, so only streams closed before that was _actually_ closed
+              // by the server blueprint
+              Await.ready(wasCompletedFuture, 150.millis)
```
Comment (patriknw) [inline akka-http-core/src/test/scala/akka/http/impl/engine/rendering/ResponseRendererSpec.scala]: ouch, that is a sensitive test

**Comment by patriknw** [comment]
I don't like it, but it's probably difficult to avoid the timing sensitivity. lgtm

**Comment by johanandren** [comment]
Yeah, I thought about it for a while without coming up with any alternative :(

**Comment by patriknw** [comment]
shall we merge this?

**Comment by johanandren** [comment]
I'm all for it. ;)

**Comment by ktoso** [comment]
LGTM, yeah "meh" but an improvement
