### PR TITLE
Modify CompressionIntegrationSpec to not assume ordering in compression advertisements

### LINKED ISSUE #21965: FAILED: CompressionIntegrationSpec wrap around
https://jenkins.akka.io:8498/job/akka-release-2.4/2/testReport/akka.remote.artery.compress/CompressionIntegrationSpec/wrap_around/

```
dodaj opis
Error Message

104 did not equal 103
Stacktrace

      org.scalatest.exceptions.TestFailedException: 104 did not equal 103
      at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
      at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6798)
      at akka.remote.artery.compress.CompressionIntegrationSpec$$anonfun$3$$anonfun$apply$mcV$sp$23$$anonfun$apply$4.apply(CompressionIntegrationSpec.scala:302)
      at akka.remote.artery.compress.CompressionIntegrationSpec$$anonfun$3$$anonfun$apply$mcV$sp$23$$anonfun$apply$4.apply(CompressionIntegrationSpec.scala:292)
      at akka.testkit.TestKitBase$class.within(TestKit.scala:345)
      at akka.testkit.TestKit.within(TestKit.scala:814)
      at akka.testkit.TestKitBase$class.within(TestKit.scala:359)
      at akka.testkit.TestKit.within(TestKit.scala:814)
      at akka.remote.artery.compress.CompressionIntegrationSpec$$anonfun$3$$anonfun$apply$mcV$sp$23.apply(CompressionIntegrationSpec.scala:292)
      at akka.remote.artery.compress.CompressionIntegrationSpec$$anonfun$3$$anonfun$apply$mcV$sp$23.apply(CompressionIntegrationSpec.scala:285)
      at scala.collection.immutable.Range.foreach(Range.scala:160)
      at akka.remote.artery.compress.CompressionIntegrationSpec$$anonfun$3.apply$mcV$sp(CompressionIntegrationSpec.scala:285)
      at akka.remote.artery.compress.CompressionIntegrationSpec$$anonfun$3.apply(CompressionIntegrationSpec.scala:262)
      at akka.remote.artery.compress.CompressionIntegrationSpec$$anonfun$3.apply(CompressionIntegrationSpec.scala:262)
      at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
      at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
      at org.scalatest.Transformer.apply(Transformer.scala:22)
      at org.scalatest.Transformer.apply(Transformer.scala:20)
      at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
      at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
      at akka.remote.artery.ArteryMultiNodeSpec.withFixture(ArteryMultiNodeSpec.scala:79)
      at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
      at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
      at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
      at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
      at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:59)
      at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
```

### PR DESCRIPTION
**Pull request by drewhk**
Fixes #21965

### CODE REVIEW

File: akka-remote/src/test/scala/akka/remote/artery/compress/CompressionIntegrationSpec.scala [hunk 1]
```diff
@@ -280,29 +280,34 @@ class CompressionIntegrationSpec extends ArteryMultiNodeSpec(CompressionIntegrat
...
+        allRefs.forall(ref ⇒ currentTable.dictionary.contains(ref)) should be(true)
+        currentTable.version should !==(lastVersion)
       }
-
+      lastTable = currentTable
+      (((currentTable.version - lastTable.version) & 0x7F) <= 2) should be(true)
+      lastVersion = lastTable.version
     }
+
+    (lastTable.version < 128) should be(true)
```
Comment (patriknw) [inline akka-remote/src/test/scala/akka/remote/artery/compress/CompressionIntegrationSpec.scala]: better error message if written as

    lastTable.version should be < (128)

File: akka-remote/src/test/scala/akka/remote/artery/compress/CompressionIntegrationSpec.scala [hunk 2]
```diff
@@ -280,29 +280,34 @@ class CompressionIntegrationSpec extends ArteryMultiNodeSpec(CompressionIntegrat
...
-        lastTableVersion = currentTableVersion
-        currentTableVersion should ===(iteration & 0x7F)
+      // discard duplicates with awaitAssert until we receive next version
+      var currentTable: CompressionTable[ActorRef] = null
+      receivedActorRefCompressionTableProbe.awaitAssert {
+        currentTable =
+          receivedActorRefCompressionTableProbe.expectMsgType[Events.ReceivedActorRefCompressionTable](2.seconds).table
+        // Until we get a new version, discard duplicates or old advertisements.
+        // Please note that we might not get the advertisements in order
+        allRefs.forall(ref ⇒ currentTable.dictionary.contains(ref)) should be(true)
```
Comment (patriknw) [inline akka-remote/src/test/scala/akka/remote/artery/compress/CompressionIntegrationSpec.scala]: could this assert be written with some collection/set comparison instead to get better error message if it fails?
I don't know the types here, but something like

    (allRefs -- currentTable.dictionary.keys) should be (Nil)

**Review by patriknw — APPROVED** [review]
LGTM, with optional improvements

File: akka-remote/src/test/scala/akka/remote/artery/compress/CompressionIntegrationSpec.scala (hunk 1 above)
Comment (drewhk) [inline akka-remote/src/test/scala/akka/remote/artery/compress/CompressionIntegrationSpec.scala]: Oh, I couldn't find the proper way to write it. Thanks, this is nicer indeed.

File: akka-remote/src/test/scala/akka/remote/artery/compress/CompressionIntegrationSpec.scala (hunk 2 above)
Comment (drewhk) [inline akka-remote/src/test/scala/akka/remote/artery/compress/CompressionIntegrationSpec.scala]: Ah ok, that might work.

Comment (drewhk) [inline akka-remote/src/test/scala/akka/remote/artery/compress/CompressionIntegrationSpec.scala]: Hm, it is irrelevant, because this is an awaitAssert, so you won't see the error message anyway, but a timeout instead.

Comment (patriknw) [inline akka-remote/src/test/scala/akka/remote/artery/compress/CompressionIntegrationSpec.scala]: I think it normally throws the last exception

Comment (drewhk) [inline akka-remote/src/test/scala/akka/remote/artery/compress/CompressionIntegrationSpec.scala]: No, I got timeouts

Comment (ktoso) [inline akka-remote/src/test/scala/akka/remote/artery/compress/CompressionIntegrationSpec.scala]: yes it throws the last exception if times out

**Review by ktoso — APPROVED** [review]
LGTM

File: akka-remote/src/test/scala/akka/remote/artery/compress/CompressionIntegrationSpec.scala (hunk 2 above)
Comment (ktoso) [inline akka-remote/src/test/scala/akka/remote/artery/compress/CompressionIntegrationSpec.scala]: > No, I got timeouts

Hm... weird but if you say you did :~

```
          case NonFatal(e) ⇒
            if ((now + t) >= stop) throw e
```

thought thats what it does

Comment (drewhk) [inline akka-remote/src/test/scala/akka/remote/artery/compress/CompressionIntegrationSpec.scala]: ah, ok the timeout was from the expectMsg, you are right

**Review by johanandren — APPROVED** [review]
