### PR TITLE
UnfoldResourceSource closing twice on failure

### LINKED ISSUE #24924: Source.unfoldResource runs `close` twice.
Consider the following snippet:

```scala
import akka.actor.ActorSystem
import akka.stream.ActorMaterializer
import akka.stream.scaladsl.{Sink, Source}
import akka.stream.testkit.scaladsl.TestSink

object Test extends App {
  implicit val system = ActorSystem()
  implicit val materializer = ActorMaterializer()

  var count = 0

  def makeSource = {
    Source.unfoldResource[Int, Int](
      () => {
        count = count + 1
        println("obtaining: " + count)
        count
      },
      c => if(c > 5) {
        println("Limit reached!")
        throw new Exception("")
      } else {
        Some(c)
      },
      c => {
        println("releasing: " + c)
        count = count - 1
      }
    ).map(_ * 2)
     .recover { case e => 23 }
  }

  1.to(10).map(_ => makeSource).foreach { s =>
    val p = s.runWith(TestSink.probe)
    p.request(1) // Generate demand.
  }

}
```

Output:

```
obtaining: 1
obtaining: 2
obtaining: 3
obtaining: 4
obtaining: 5
obtaining: 6
Limit reached!
releasing: 6
releasing: 6
obtaining: 5
obtaining: 6
Limit reached!
releasing: 6
releasing: 6
obtaining: 5
obtaining: 6
Limit reached!
releasing: 6
releasing: 6
```

The code creates 10 streams, each of which tries to obtain a resource using `Source.unfoldResource`, does some processing (here a `map`) and `recovers` from any errors. The resource is limited, so after a certain point some of these streams fail to obtain the resource  resulting in `close` passed to `Source.unfoldResource` being called twice in every such case.

Is this the expected and correct behaviour? I would expect it to relese the resource only once and the correct output to be the following:

```
obtaining: 1
obtaining: 2
obtaining: 3
obtaining: 4
obtaining: 5
obtaining: 6
Limit reached!
releasing: 6
obtaining: 6
Limit reached!
releasing: 6
obtaining: 6
Limit reached!
releasing: 6
...
```

Also, moving the `if` further downstream as in the following snippet makes it work as expected:

```scala
// ...
  def makeSource = {
    Source.unfoldResource[Int, Int](
      () => {
        count = count + 1
        println("obtaining: " + count)
        count
      },
      Some(_),
      c => {
        println("releasing: " + c)
        count = count - 1
      }
    ).map { c =>
      if(c > 5) {
        println("Limit reached!")
        throw new Exception("")
      } else {
        c * 2
      }
    }
    .recover { case e => 23 }
  }
// ...
```

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #24924 

Two general test improvement commits first, then actual fix

### CODE REVIEW

File: akka-stream-tests/src/test/scala/akka/stream/scaladsl/UnfoldResourceSourceSpec.scala [hunk 1]
```diff
@@ -24,26 +29,28 @@ class UnfoldResourceSourceSpec extends StreamSpec(UnboundedMailboxConfig) {
   val settings = ActorMaterializerSettings(system).withDispatcher("akka.actor.default-dispatcher")
   implicit val materializer = ActorMaterializer(settings)
 
-  val manyLines = {
+  private val fs = Jimfs.newFileSystem("UnfoldResourceSourceSpec", Configuration.unix())
```
Comment (ktoso) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/UnfoldResourceSourceSpec.scala]: 👍

**Review by chbatey — APPROVED** [review]
LGTM

**Comment by chbatey** [comment]
Travis fails, may need to rebase to get .travis.yml

File: akka-stream/src/main/scala/akka/stream/impl/UnfoldResourceSource.scala [hunk 2]
```diff
@@ -47,6 +47,7 @@ import scala.util.control.NonFatal
         case NonFatal(ex) ⇒ decider(ex) match {
           case Supervision.Stop ⇒
             close(blockingStream)
+            open = false
```
Comment (patriknw) [inline akka-stream/src/main/scala/akka/stream/impl/UnfoldResourceSource.scala]: I think there can still be two invocations if `close` throws, because then `open` is still true in `postStop`. Would be better to set `open = false` before calling `close. Same problem in `def closeStage` and perhaps also in `def restartState`

**Review by patriknw — CHANGES_REQUESTED** [review]

File: akka-stream/src/main/scala/akka/stream/impl/UnfoldResourceSource.scala (hunk 2 above)
Comment (johanandren) [reply akka-stream/src/main/scala/akka/stream/impl/UnfoldResourceSource.scala]: Good point, I'll move it up

Comment (johanandren) [reply akka-stream/src/main/scala/akka/stream/impl/UnfoldResourceSource.scala]: Heh, if I move this place, the other exception-on-close test starts failing, and I must be stupid or something, because I cannot understand why.

The other place was fine to move around and fixed a reproducing test case I wrote.

File: akka-stream/src/main/scala/akka/stream/impl/UnfoldResourceSource.scala [hunk 3]
```diff
@@ -62,6 +64,7 @@ import scala.util.control.NonFatal
 
     private def restartState(): Unit = {
       close(blockingStream)
+      open = false
```
Comment (patriknw) [inline akka-stream/src/main/scala/akka/stream/impl/UnfoldResourceSource.scala]: I'm not sure I understand why this couldn't be before the `close`. What happens if `close` throws here? Wouldn't `postStop` be called and then open is still true and another `close` will be done?

**Review by patriknw — APPROVED** [review]
LGTM
