### PR TITLE
RebalanceWorker should watch shard regions

### LINKED ISSUE #27259: Shard reallocation problems
I see this issue a lot when scaling a cluster down. I think the problem happens when more than one node leaves the cluster at a time. I'll describe the symptom first, here's the logs:

```
02:32:41.620 DEBUG c.l.s.autoscaler.Autoscaler - Scaling down to 2 because desired nodes for user function 1 and desired nodes for request handling 1 is below cluster members 4
02:32:44.901 INFO  a.c.Cluster(akka://statefulserverless-backend) - Cluster Node [akka.tcp://statefulserverless-backend@10.52.14.20:2552] - Exiting confirmed [akka.tcp://statefulserverless-backend@10.52.13.17:2552]
02:32:45.010 INFO  akka.remote.EndpointWriter - AssociationError [akka.tcp://statefulserverless-backend@10.52.14.20:2552] <- [akka.tcp://statefulserverless-backend@10.52.13.17:2552]: Error [Shut down address: akka.tcp://statefulserverless-backend@10.52.13.17:2552] [
akka.remote.ShutDownAssociation: Shut down address: akka.tcp://statefulserverless-backend@10.52.13.17:2552
Caused by: akka.remote.transport.Transport$InvalidAssociationException: The remote system terminated the association because it is shutting down.
]
02:32:46.254 INFO  a.c.s.ClusterSingletonManager - Member removed [akka.tcp://statefulserverless-backend@10.52.13.17:2552]
02:32:46.264 INFO  a.c.s.ClusterSingletonManager - Member removed [akka.tcp://statefulserverless-backend@10.52.13.17:2552]
02:32:52.942 WARN  akka.cluster.sharding.ShardRegion - shopping-cart: Retry request for shard [94] homes from coordinator at [Actor[akka://statefulserverless-backend/system/sharding/shopping-cartCoordinator/singleton/coordinator#1273361376]]. [17] buffered messages.
[snip - above message is repeated 18 times per second, differing only in the shard id and buffered messages]
02:32:53.137 INFO  a.c.Cluster(akka://statefulserverless-backend) - Cluster Node [akka.tcp://statefulserverless-backend@10.52.14.20:2552] - Exiting confirmed [akka.tcp://statefulserverless-backend@10.52.12.18:2552]
02:32:53.225 INFO  akka.remote.EndpointWriter - AssociationError [akka.tcp://statefulserverless-backend@10.52.14.20:2552] <- [akka.tcp://statefulserverless-backend@10.52.12.18:2552]: Error [Shut down address: akka.tcp://statefulserverless-backend@10.52.12.18:2552] [
akka.remote.ShutDownAssociation: Shut down address: akka.tcp://statefulserverless-backend@10.52.12.18:2552
Caused by: akka.remote.transport.Transport$InvalidAssociationException: The remote system terminated the association because it is shutting down.
]
02:32:53.243 INFO  a.c.Cluster(akka://statefulserverless-backend) - Cluster Node [akka.tcp://statefulserverless-backend@10.52.14.20:2552] - is the new leader among reachable nodes (more leaders may exist)
02:32:54.242 INFO  a.c.Cluster(akka://statefulserverless-backend) - Cluster Node [akka.tcp://statefulserverless-backend@10.52.14.20:2552] - Leader is removing confirmed Exiting node [akka.tcp://statefulserverless-backend@10.52.12.18:2552]
02:32:54.250 INFO  a.c.s.ClusterSingletonManager - Member removed [akka.tcp://statefulserverless-backend@10.52.12.18:2552]
02:32:54.255 INFO  a.c.s.ClusterSingletonManager - Member removed [akka.tcp://statefulserverless-backend@10.52.12.18:2552]
02:32:54.942 WARN  akka.cluster.sharding.ShardRegion - shopping-cart: Retry request for shard [94] homes from coordinator at [Actor[akka://statefulserverless-backend/system/sharding/shopping-cartCoordinator/singleton/coordinator#1273361376]]. [17] buffered messages.
[snip - above message is repeated 18 times per second, differing only in the shard id and buffered messages]
```

The 18 retry request warnings are then repeated every second for about 50 seconds, until the last one, 50 seconds after the first message was output:

```
02:33:42.932 WARN  akka.cluster.sharding.ShardRegion - shopping-cart: Retry request for shard [84] homes from coordinator at [Actor[akka://statefulserverless-backend/system/sharding/shopping-cartCoordinator/singleton/coordinator#1273361376]]. [35] buffered messages.
```

And then, everything goes back to normal, the shards start working again, and then 16 seconds after that:

```
02:33:58.432 WARN  a.r.transport.netty.NettyTransport - Remote connection to [null] failed with org.jboss.netty.channel.ConnectTimeoutException: connection timed out: /10.52.12.18:2552
02:33:58.439 WARN  a.remote.ReliableDeliverySupervisor - Association with remote system [akka.tcp://statefulserverless-backend@10.52.12.18:2552] has failed, address is now gated for [5000] ms. Reason: [Association failed with [akka.tcp://statefulserverless-backend@10.52.12.18:2552]] Caused by: [org.jboss.netty.channel.ConnectTimeoutException: connection timed out: /10.52.12.18:2552]
```

So, in the above, `10.52.13.17` shut down first, followed by `10.52.12.18`, but it appears that the node still attempts to communicate with `10.52.12.18` after its left the cluster, hence the last error message?

I suspect what is happening is that during shard allocation after the first node leaves the cluster, shards can be allocated to the second node that is also concurrently leaving, and there is a race condition that means that if that node shuts down while the shards are being allocated to it, the shard coordinator does not attempt to fix that and reallocate for a minute.

### PR DESCRIPTION
**Pull request by jroper**
Fixes #27259

The RebalanceWorker actor needs to watch the shard regions that it's expecting a BeginHandOffAck message from, in case the ShardRegion shuts down before it can receive the BeginHandOff message, preventing hand off.  This can be a problem when two nodes are shut down at about the same time.

### CODE REVIEW

**Comment by jroper** [comment]
I'm not sure if watching all the regions is a problem performance wise. If it is, we could also pass the set of gracefully shutting down regions to the worker, and just watch them, since they are the only ones that, when things are happy, can cause this race condition.

**Comment by jroper** [comment]
I made the change so it only watches gracefully shutting down regions - I figure if a `ShardRegion` terminates that we aren't expecting might terminate, it's probably better to be safe and let hand off time out and be retried, than to just continue.

Also, I added some debug logging that would have made it easier to debug this.

**Comment by jroper** [comment]
Mima failed - is the preference for `private [akka]` breakages to maintain bincompat if possible (it is possible), or to add an exclusion?

**Comment by raboof** [comment]
> is the preference for private [akka] breakages to maintain bincompat if possible (it is possible), or to add an exclusion?
I think it's fine to add an exclusion

File: akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala [hunk 1]
```diff
@@ -433,14 +437,24 @@ object ShardCoordinator {
...
       case BeginHandOffAck(`shard`) =>
-        remaining -= sender()
-        if (remaining.isEmpty) {
-          from ! HandOff(shard)
-          context.become(stoppingShard, discardOld = true)
-        }
+        log.debug("BeginHandOffAck for shard [{}] received from {}", shard, sender())
+        acked(sender())
+      case Terminated(shardRegion) =>
+        log.debug("ShardRegion {} terminated while waiting for BeginHandOfAck for shard [{}]", shardRegion, shard)
```
Comment (patriknw) [inline akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala]: typo: OfAck

**Review by patriknw — APPROVED** [review]
LGTM, good, and that should be safe to do

File: akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala [hunk 2]
```diff
@@ -422,9 +422,13 @@ object ShardCoordinator {
       shard: String,
       from: ActorRef,
       handOffTimeout: FiniteDuration,
-      regions: Set[ActorRef])
-      extends Actor {
+      regions: Set[ActorRef],
+      shuttingDownRegions: Set[ActorRef])
+      extends Actor
+      with ActorLogging {
```
Comment (raboof) [inline akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala]: This needs a `ProblemFilters.exclude[DirectMissingMethodProblem]("akka.cluster.sharding.ShardCoordinator#RebalanceWorker.this")`

File: akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala [hunk 3]
```diff
@@ -456,8 +470,10 @@ object ShardCoordinator {
       shard: String,
       from: ActorRef,
       handOffTimeout: FiniteDuration,
-      regions: Set[ActorRef]): Props =
-    Props(new RebalanceWorker(shard, from, handOffTimeout, regions))
+      regions: Set[ActorRef],
+      // Note: must be a subset of regions
+      shuttingDownRegions: Set[ActorRef]): Props =
```
Comment (raboof) [inline akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala]: `ProblemFilters.exclude[DirectMissingMethodProblem]("akka.cluster.sharding.ShardCoordinator.rebalanceWorkerProps")`

File: akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala [hunk 4]
```diff
@@ -433,14 +437,24 @@ object ShardCoordinator {
 
     def receive = {
       case BeginHandOffAck(`shard`) =>
-        remaining -= sender()
-        if (remaining.isEmpty) {
-          from ! HandOff(shard)
-          context.become(stoppingShard, discardOld = true)
-        }
+        log.debug("BeginHandOffAck for shard [{}] received from {}", shard, sender())
```
Comment (helena) [inline akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala]:
```suggestion
        log.debug("'BeginHandOffAck' for shard [{}] received from {}.", shard, sender())
```

File: akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala [hunk 5]
```diff
@@ -433,14 +437,24 @@ object ShardCoordinator {
...
+        acked(sender())
+      case Terminated(shardRegion) =>
+        log.debug("ShardRegion {} terminated while waiting for BeginHandOffAck for shard [{}]", shardRegion, shard)
```
Comment (helena) [inline akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala]: Same, punctuation is our friend.

File: akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala [hunk 6]
```diff
@@ -433,14 +437,24 @@ object ShardCoordinator {
...
+        acked(shardRegion)
       case ReceiveTimeout => done(ok = false)
     }
 
+    private def acked(shardRegion: ActorRef) = {
+      context.unwatch(shardRegion)
```
Comment (helena) [inline akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala]: 👍

File: akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala (hunk 4 above)
Comment (helena) [reply akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala]: This means receiving a `BeginHandOffAck` calls an `unwatch` in the `acked` function, which makes sense for receiving `Terminated` but less so here.

File: akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala [hunk 7]
```diff
@@ -433,14 +437,24 @@ object ShardCoordinator {
 
     def receive = {
       case BeginHandOffAck(`shard`) =>
-        remaining -= sender()
-        if (remaining.isEmpty) {
-          from ! HandOff(shard)
-          context.become(stoppingShard, discardOld = true)
-        }
+        log.debug("BeginHandOffAck for shard [{}] received from {}", shard, sender())
+        acked(sender())
```
Comment (helena) [inline akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala]: This means receiving a BeginHandOffAck calls an unwatch in the acked function, which makes sense for receiving Terminated but less so here.

File: akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala [hunk 8]
```diff
@@ -456,8 +470,10 @@ object ShardCoordinator {
       shard: String,
       from: ActorRef,
       handOffTimeout: FiniteDuration,
-      regions: Set[ActorRef]): Props =
-    Props(new RebalanceWorker(shard, from, handOffTimeout, regions))
+      regions: Set[ActorRef],
+      // Note: must be a subset of regions
+      shuttingDownRegions: Set[ActorRef]): Props =
+    Props(new RebalanceWorker(shard, from, handOffTimeout, regions, shuttingDownRegions))
```
Comment (helena) [inline akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala]:
```
private[akka] def rebalanceWorkerProps(
  shard: String,
  from: ActorRef,
  handOffTimeout: FiniteDuration,
  regions: Set[ActorRef],
  shuttingDownRegions: Set[ActorRef]): Props = {
    require(shuttingDownRegions.size < regions.size, "'shuttingDownRegions' must be a subset of 'regions'.")
    Props(new RebalanceWorker(shard, from, handOffTimeout, regions, shuttingDownRegions))
}
```

File: akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala (hunk 7 above)
Comment (jroper) [reply akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala]: I think it's the other way around - unwatching is automatic when you received a `Terminated`, but in this case, if a terminating actor sends a `BeginHandOffAck`, we don't want to receive it's `Terminated` afterwards because we've already handled that actor.

Comment (helena) [reply akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala]: Thanks for the explanation 👍

**Review by helena — APPROVED** [review]
LGTM
