### PR TITLE
A bit more generous timeouts in RateTransformationDocSpec 

### LINKED ISSUE #24559: RateTransformationDocSpec
I don't see a gc, but 100ms is a bit tight anyway perhaps?

https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/994/consoleFull

```
[info] RateTransformationDocSpec:
Coroner Thread Count starts at 21 in docs.stream.RateTransformationDocSpec
[info] - conflate should summarize *** FAILED *** (148 milliseconds)
[info]   java.util.concurrent.TimeoutException: Futures timed out after [100 milliseconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:223)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:227)
[info]   at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[info]   at scala.concurrent.Await$.result(package.scala:190)
[info]   at docs.stream.RateTransformationDocSpec$$anonfun$4.apply(RateTransformationDocSpec.scala:41)
[info]   at docs.stream.RateTransformationDocSpec$$anonfun$4.apply(RateTransformationDocSpec.scala:24)
```

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #24559

### CODE REVIEW

File: akka-docs/src/test/scala/docs/stream/RateTransformationDocSpec.scala [hunk 1]
```diff
@@ -16,15 +16,12 @@ import akka.testkit.{ AkkaSpec, TestLatch }
...
-  type Seq[+A] = immutable.Seq[A]
-  val Seq = immutable.Seq
-
   implicit val materializer = ActorMaterializer()
 
   "conflate should summarize" in {
     //#conflate-summarize
     val statsFlow = Flow[Double]
-      .conflateWithSeed(Seq(_))(_ :+ _)
+      .conflateWithSeed(immutable.Seq(_))(_ :+ _)
```
Comment (johanandren) [inline akka-docs/src/test/scala/docs/stream/RateTransformationDocSpec.scala]: As this are in the actual samples (and the alias/companion object ref is not), better show what it is immutable.

File: akka-docs/src/test/scala/docs/stream/RateTransformationDocSpec.scala [hunk 2]
```diff
@@ -38,14 +35,14 @@ class RateTransformationDocSpec extends AkkaSpec {
       .grouped(10)
       .runWith(Sink.head)
 
-    Await.result(fut, 100.millis)
+    fut.futureValue
```
Comment (johanandren) [inline akka-docs/src/test/scala/docs/stream/RateTransformationDocSpec.scala]: This picks up paticenceconfig from AkkaSpec which uses the default timeout

**Review by raboof — APPROVED** [review]

**Review by patriknw — APPROVED** [review]
LGTM
