### PR TITLE
Make flowspec great again drewhk

### LINKED ISSUE #22435: Make FlowSpec work again
It depends on internals in a few cases, hence it is not trivial to make it work (tests a broken interpreter).

### PR DESCRIPTION
**Pull request by drewhk**
Fixes #22435 

Unfortunately getting the "faulty-flow" case working is really really hacky (it was already very hacky before). This test tries to inject an internal failure into the interpreter and check if it is correctly handles, but I am not sure how we can do this in a maintainable way. It is possible to create a new phase just for this purpose (which I tried) but then one needs to build a traversal manually, a phase manually and all these end up in a big mess. Unless someone wants this test badly, I propose to delete it.

### CODE REVIEW

File: akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowSpec.scala [hunk 1]
```diff
@@ -40,48 +40,6 @@ class FlowSpec extends StreamSpec(ConfigFactory.parseString("akka.actor.debug.re
   val identity: Flow[Any, Any, NotUsed] ⇒ Flow[Any, Any, NotUsed] = in ⇒ in.map(e ⇒ e)
   val identity2: Flow[Any, Any, NotUsed] ⇒ Flow[Any, Any, NotUsed] = in ⇒ identity(in)
 
-  // TODO: Reenable these tests
-  //  class BrokenActorInterpreter(_shell: GraphInterpreterShell, brokenMessage: Any)
-  //    extends ActorGraphInterpreter(_shell) {
-  //
-  //    override protected[akka] def aroundReceive(receive: Receive, msg: Any) = {
-  //      msg match {
-  //        case ActorGraphInterpreter.OnNext(_, 0, m) if m == brokenMessage ⇒
```
Comment (drewhk) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowSpec.scala]: this trick now does not work anymore.

File: akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowSpec.scala [hunk 2]
```diff
@@ -40,48 +40,6 @@ class FlowSpec extends StreamSpec(ConfigFactory.parseString("akka.actor.debug.re
...
-  //          throw new NullPointerException(s"I'm so broken [$m]")
-  //        case _ ⇒ super.aroundReceive(receive, msg)
-  //      }
-  //    }
-  //  }
-
-  //  val faultyFlow: Flow[Any, Any, NotUsed] ⇒ Flow[Any, Any, NotUsed] = in ⇒ in.via({
-  //    val stage = fusing.Map({ x: Any ⇒ x })
```
Comment (drewhk) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowSpec.scala]: getting now a Flow to materialize with a broken ActorGraphInterpreter does not work as simply as this. A new materializer phase must be created and properly implemented, emulating a faulty flow. Plus, a Flow wrapping a suitable traversal should be manually created. I am not sure all this hassle is worth it, I can't imagine anybody maintaining this mess after it is written. I am open for any clever ideas, but for now I vote for removing this and the corresponding test altogether.
