### PR TITLE
ContentNegotiation fixes (and breakage)

### LINKED ISSUE #17985: Marshal assumes List for charset negotiation
However, `HttpRequest.acceptedCharsetRanges` may return any other immutable Seq depending on the actual value of ranges in `Accept-Charset`. This is usually not a problem because the header parser only creates Lists at this position. Still, this is a interoperability problem, e.g. with tests where a request may be manually created.

/cc @sirthias

### PR DESCRIPTION
**Pull request by jrudolph**
Fixes #17985. Only fixes the "not run tests part" from #17984.

/cc @sirthias, @2beaucoup

### CODE REVIEW

**Comment by jrudolph** [comment]
This should fail for 13 previously disabled tests. It could either be that
 * the tests are broken (unlikely)
 * the implementation is broken
 * the testing infrastructure is broken (it was broken before the first commit of this PR, so no guarantees...)

**Comment by jrudolph** [comment]
I think this may be an oversight from removing the previous plural `Marshallers` classes, so that the `implicit val marshallers` in the test isn't effective in any way which would be good news because it would mean that maybe only the test infrastructure is broken.

**Comment by jrudolph** [comment]
Changing the test code to

```scala
  trait X // otherwise unknown type, preventing that a `ToEntityMarshaller[X]` is already in scope
  object X extends X
  def testHeaders[U](headers: HttpHeader*)(body: ((ContentType*) ⇒ Option[ContentType]) ⇒ U): U = {
    val request = HttpRequest(headers = headers.toVector)
    body { contentTypes ⇒
      import scala.concurrent.ExecutionContext.Implicits.global
      implicit val marshallers: ToEntityMarshaller[X] =
        Marshaller.oneOf(contentTypes map {
          case ct @ ContentType(mt, Some(cs)) ⇒
            println(s"With cs $cs")
            Marshaller.withFixedCharset(mt, cs)((s: X) ⇒ HttpEntity(ct, "The X"))
          case ContentType(mt, None) ⇒ Marshaller.withOpenCharset(mt)((s: X, cs) ⇒ HttpEntity(ContentType(mt, cs), "The X"))
        }: _*)

      Await.result(Marshal(X).toResponseFor(request)
        .fast.map(response ⇒ Some(response.entity.contentType))
        .fast.recover { case _: Marshal.UnacceptableResponseContentTypeException ⇒ None }, 1.second)
    }
  }
```

makes most tests pass but two.

**Comment by 2beaucoup** [comment]
I'm also suspecting implict failures. (See how the wrong marshaller gets picked up [here](https://github.com/akka/akka/issues/17984#issuecomment-121214765).)

**Comment by jrudolph** [comment]
I think I have a fix.

File: akka-http-tests/src/test/scala/akka/http/scaladsl/marshalling/ContentNegotiationSpec.scala [hunk 1]
```diff
@@ -13,83 +16,88 @@ import MediaTypes._
...
+    "Accept-Charset: UTF-8;q=.2, UTF-16" test { accept ⇒
       accept(`text/plain`) should select(`text/plain`, `UTF-16`)
       accept(`text/plain` withCharset `UTF-8`) should select(`text/plain`, `UTF-8`)
     }
 
-    "Accept-Charset: UTF-8;q=.2" in test { accept ⇒
-      accept(`text/plain`) should select(`text/plain`, `ISO-8859-1`)
+    "Accept-Charset: UTF-8;q=.2" test { accept ⇒
+      // FIXME: which rule would enforce that behavior?
+      // accept(`text/plain`) should select(`text/plain`, `ISO-8859-1`)
```
Comment (jrudolph) [inline akka-http-tests/src/test/scala/akka/http/scaladsl/marshalling/ContentNegotiationSpec.scala]: @sirthias, @2beaucoup any idea, which rule would govern behavior like that?

Comment (2beaucoup) [inline akka-http-tests/src/test/scala/akka/http/scaladsl/marshalling/ContentNegotiationSpec.scala]: Maybe a leftover from 8c8400303fa21112a6764b992fc83bb519e844f2?

Switching to `UTF-8` here (and `ISO-8859-1` below) should be fine.

Comment (jrudolph) [inline akka-http-tests/src/test/scala/akka/http/scaladsl/marshalling/ContentNegotiationSpec.scala]: Ah yes, good find. I guess then we need to turn the test around.

Comment (jrudolph) [inline akka-http-tests/src/test/scala/akka/http/scaladsl/marshalling/ContentNegotiationSpec.scala]: Hmm, but it still makes no sense as choosing an explicit charset should always take that one, right?

Comment (jrudolph) [inline akka-http-tests/src/test/scala/akka/http/scaladsl/marshalling/ContentNegotiationSpec.scala]: I would change it to

```scala
    "Accept-Charset: ISO-8859-1;q=.2" test { accept ⇒
      accept(`text/plain`) should select(`text/plain`, `ISO-8859-1`)
      accept(`text/plain` withCharset `UTF-8`) should reject
    }
```

This would definitely test something else but maybe the test was just bogus?

Comment (jrudolph) [inline akka-http-tests/src/test/scala/akka/http/scaladsl/marshalling/ContentNegotiationSpec.scala]: It seems this test case was transferred from spray's https://github.com/spray/spray/blob/master/spray-http/src/test/scala/spray/http/ContentNegotiationSpec.scala#L79 (which I don't understand either :))

Comment (jrudolph) [inline akka-http-tests/src/test/scala/akka/http/scaladsl/marshalling/ContentNegotiationSpec.scala]: I changed it now to the above suggestion (though, I'm not sure if that test adds something interesting).

Comment (2beaucoup) [inline akka-http-tests/src/test/scala/akka/http/scaladsl/marshalling/ContentNegotiationSpec.scala]: LGTM! I was playing around with that one as well and arrived at the same result. ;)

Looks like the logic changed in that we now reject instead of falling back to the default charset (`ISO-8859-1` back then) in that case.

Comment (jrudolph) [inline akka-http-tests/src/test/scala/akka/http/scaladsl/marshalling/ContentNegotiationSpec.scala]: Cool, so we agree. Thanks again for helping out @2beaucoup :)

File: akka-http-tests/src/test/scala/akka/http/scaladsl/marshalling/ContentNegotiationSpec.scala [hunk 2]
```diff
@@ -13,83 +16,87 @@ import MediaTypes._
 import HttpCharsets._
 
 class ContentNegotiationSpec extends FreeSpec with Matchers {
-
   "Content Negotiation should work properly for requests with header(s)" - {
 
-    "(without headers)" in test { accept ⇒
-      accept(`text/plain`) should select(`text/plain`, `UTF-8`)
+    "(without headers)" test { accept ⇒
```
Comment (ktoso) [inline akka-http-tests/src/test/scala/akka/http/scaladsl/marshalling/ContentNegotiationSpec.scala]: tricky! thanks for noticing!

**Comment by ktoso** [comment]
LGTM, thanks

File: akka-http-tests/src/test/scala/akka/http/scaladsl/marshalling/ContentNegotiationSpec.scala (hunk 1 above)
Comment (sirthias) [inline akka-http-tests/src/test/scala/akka/http/scaladsl/marshalling/ContentNegotiationSpec.scala]: Sorry for being way late to the party here, but I'd like to shine some light on this test and hopefully clear up the confusion.
This test was originally written for [section 14.2 of RFC 2616](http://tools.ietf.org/html/rfc2616#section-14.2), which says:

> If no "*" is present in an Accept-Charset field, then all character sets not explicitly mentioned get a quality value of 0, except for ISO-8859-1, which gets a quality value of 1 if not explicitly mentioned.

However, in the latest specs `ISO-8859-1` doesn't have this special status anymore and the test should therefore fail (as it did). So the fix here was indeed necessary and not incorrect. :)

Comment (jrudolph) [inline akka-http-tests/src/test/scala/akka/http/scaladsl/marshalling/ContentNegotiationSpec.scala]: @sirthias cool, thanks for the explanation and digging that out.

Comment (2beaucoup) [inline akka-http-tests/src/test/scala/akka/http/scaladsl/marshalling/ContentNegotiationSpec.scala]: Ahh, all is well then. Thanks for clarifying @sirthias!

Comment (sirthias) [inline akka-http-tests/src/test/scala/akka/http/scaladsl/marshalling/ContentNegotiationSpec.scala]: To me this proves once more that you can never add too many pointers to the relevant specs right next to the code. If I had put a pointer to RFC2616 section 14.2 next to this test you guys would have figured things out in no time.
