### PR TITLE
=act #17140 FSM: forMax(Inf) can now override stateTimeout

### LINKED ISSUE #17140: Akka-FSM stateTimeout ignores forMax Duration.Inf
Code to reproduce:

```scala
sealed trait State
import scala.concurrent.duration._
import akka.actor._

sealed trait Data
case object Initial extends State
case object Waiting extends State
case object Empty extends Data

class FSMActor extends LoggingFSM[State, Data] {
      startWith(Initial, Empty)
     
      when(Initial) {
        case Event("Wait", _) => goto(Waiting)
      }

      when(Waiting, stateTimeout = 5.seconds) {
        case Event("Message", _) => 
          println(self.path.name + " got message")
          stay() forMax (Duration.Inf)

        case Event(StateTimeout, _) => 
          println(self.path.name + " got StateTimeout :(")
          stay()
      }
}

val system = ActorSystem("system")
val fsm = system.actorOf(Props(new FSMActor), "fsm")
fsm ! "Wait"
fsm ! "Message"
```

Actor shouldn't receive `StateTimeout` message since `stay()` was called with `forMax(Duration.Inf)`.

Version is `2.4-SNAPSHOT`, bug appeared after update on Apr 02.

Related thread on akka-user: https://groups.google.com/forum/#!topic/akka-user/NsAoqPZ2Svo

### PR DESCRIPTION
**Pull request by ktoso**
Resolves #17140 while remaining binary and source compatible

### CODE REVIEW

**Comment by drewhk** [comment]
LGTM

Shoud this be backported to 2.3?

**Comment by ktoso** [comment]
I think so, it can be considered a bug - in the docs we say this should work.

File: akka-actor/src/main/scala/akka/actor/FSM.scala [hunk 1]
```diff
@@ -648,13 +653,18 @@ trait FSM[S, D] extends Actor with Listeners with ActorLogging {
...
-          timeoutFuture = Some(context.system.scheduler.scheduleOnce(t, self, TimeoutMarker(generation)))
-        }
+
+      def scheduleTimeout(d: FiniteDuration): Some[Cancellable] = {
+        import context.dispatcher
+        Some(context.system.scheduler.scheduleOnce(d, self, TimeoutMarker(generation)))
+      }
+
+      currentState.timeout match {
+        case SomeMaxFiniteDuration                    ⇒ // effectively disable stateTimeout
```
Comment (viktorklang) [inline akka-actor/src/main/scala/akka/actor/FSM.scala]: Is this a meaningful distinction given a FiniteDuration of Long.MaxValue - 1?

Comment (ktoso) [inline akka-actor/src/main/scala/akka/actor/FSM.scala]: effectively what I need to express "such big timeout that the akka scheduler would blow up anyway". 
Thought using MaxValue would be cleanest as marker value. I could dig into the scheduler and find it's max and cut-off anything above it to => "effectively never", but that sounds a bit more magic than picking MaxValue as my marker.

Note: Users are not expected to use it, they'd do `forMax(Inf)` which I encode as this MaxValue marker. (Can't change types, if I could we'd change things to Duration from FiniteDuration and we'd be good).

Comment (drewhk) [inline akka-actor/src/main/scala/akka/actor/FSM.scala]: this is just a workaround that the original code did not handle Duration.Inf although the forMax method (L146) accepts a Duration. The proper fix would be to change the signature of State to have a timeout of Option[Duration] instead of Option[FiniteDuration], but that would break binary compatiblility. So Konrad introduced this artifical marker that is introduced at L148 when a Duration.Inf is encountered, and which can be stored in the State case class without changing its signature.

Comment (ktoso) [inline akka-actor/src/main/scala/akka/actor/FSM.scala]: Reason for this marker-hack is the FiniteDuration here: `   final case class State[S, D](stateName: S, stateData: D, timeout: Option[FiniteDuration], ...`)

Comment (viktorklang) [inline akka-actor/src/main/scala/akka/actor/FSM.scala]: Makes total sense. Apologies for barging in here.

Comment (ktoso) [inline akka-actor/src/main/scala/akka/actor/FSM.scala]: Nah, no worries – more often than not such barging in is pretty useful :-)

File: akka-actor/src/main/scala/akka/actor/FSM.scala [hunk 2]
```diff
@@ -141,6 +145,7 @@ object FSM {
      */
     def forMax(timeout: Duration): State[S, D] = timeout match {
       case f: FiniteDuration ⇒ copy(timeout = Some(f))
+      case Duration.Inf      ⇒ copy(timeout = SomeMaxFiniteDuration)
       case _                 ⇒ copy(timeout = None)
```
Comment (kevinmeredith) [inline akka-actor/src/main/scala/akka/actor/FSM.scala]: With the addition of `case Duration.Inf => ...`, isn't this line now dead code?

[Duration](http://www.scala-lang.org/api/2.11.5/index.html#scala.concurrent.duration.Duration)'s docs show that it has 2 children: `FiniteDuration` and `Infinite`.

File: akka-actor/src/main/scala/akka/actor/FSM.scala (hunk 1 above)
Comment (drewhk) [inline akka-actor/src/main/scala/akka/actor/FSM.scala]: but @viktorklang 's comment is valid as in you should put a comment there to explain the "why".

File: akka-actor/src/main/scala/akka/actor/FSM.scala (hunk 2 above)
Comment (rkuhn) [inline akka-actor/src/main/scala/akka/actor/FSM.scala]: There’s negative infinity and also `Undefined`.

File: akka-actor/src/main/scala/akka/actor/FSM.scala (hunk 1 above)
Comment (ktoso) [inline akka-actor/src/main/scala/akka/actor/FSM.scala]: Yes agreed, I'll add one

File: akka-actor/src/main/scala/akka/actor/FSM.scala [hunk 3]
```diff
@@ -1126,7 +1136,7 @@ abstract class AbstractFSM[S, D] extends FSM[S, D] {
    * @return current state descriptor
    */
   final def setTimer(name: String, msg: Any, timeout: FiniteDuration): Unit =
-    setTimer(name, msg, timeout, false);
```
Comment (rkuhn) [inline akka-actor/src/main/scala/akka/actor/FSM.scala]: aargh, my eyes!

File: akka-actor/src/main/scala/akka/actor/FSM.scala [hunk 4]
```diff
@@ -1126,7 +1136,7 @@ abstract class AbstractFSM[S, D] extends FSM[S, D] {
...
+    setTimer(name, msg, timeout, false)
```
Comment (rkuhn) [inline akka-actor/src/main/scala/akka/actor/FSM.scala]: phew, thanks!

Comment (ktoso) [inline akka-actor/src/main/scala/akka/actor/FSM.scala]: got them now bright red in my new color scheme :wink:

**Comment by rkuhn** [comment]
LGTM

File: akka-actor/src/main/scala/akka/actor/FSM.scala (hunk 1 above)
Comment (ktoso) [inline akka-actor/src/main/scala/akka/actor/FSM.scala]: Added a comment explaining the reasoning (and todo - we can fix it once we break compat).

File: akka-actor/src/main/scala/akka/actor/FSM.scala (hunk 2 above)
Comment (ktoso) [inline akka-actor/src/main/scala/akka/actor/FSM.scala]: RE: https://twitter.com/Gentmen/status/586192587654041600
The other mentioned values are not classes but values in `Duration`, as seen here:
https://github.com/scala/scala/blob/2.11.x/src/library/scala/concurrent/duration/Duration.scala#L174
