### PR TITLE
#19637 fix BC issue in AsyncWriteJournal

### LINKED ISSUE #19637: Fix BC issue in AsyncWriteJournal
Manifests in:
```
Caused by: java.lang.AbstractMethodError: akka.contrib.persistence.mongodb.MongoJournal.akka$persistence$journal$AsyncWriteJournal$_setter_$akka$persistence$journal$AsyncWriteJournal$$replayDebugEnabled_$eq(Z)V
	at akka.persistence.journal.AsyncWriteJournal$class.$init$(AsyncWriteJournal.scala:50)
	at akka.contrib.persistence.mongodb.MongoJournal.<init>(MongoJournal.scala:17)
	... 16 more
```
when current persistence plugins are being used with 2.4.2-RC1.

BC issue was introduced in https://github.com/akka/akka/commit/0af98e7bee1312d10979dd2a8ac81a77502c1f43

### PR DESCRIPTION
**Pull request by rkuhn**
fixes #19637

### CODE REVIEW

File: akka-persistence/src/main/scala/akka/persistence/journal/AsyncWriteJournal.scala [hunk 1]
```diff
@@ -47,7 +47,8 @@ trait AsyncWriteJournal extends Actor with WriteJournalBase with AsyncRecovery {
   private def isReplayFilterEnabled: Boolean = replayFilterMode != ReplayFilter.Disabled
   private val replayFilterWindowSize: Int = config.getInt("replay-filter.window-size")
   private val replayFilterMaxOldWriters: Int = config.getInt("replay-filter.max-old-writers")
-  private val replayDebugEnabled: Boolean = config.getBoolean("replay-filter.debug")
+  // cannot be a val due to binary compatibility
+  private def replayDebugEnabled: Boolean = config.getBoolean("replay-filter.debug")
```
Comment (patriknw) [inline akka-persistence/src/main/scala/akka/persistence/journal/AsyncWriteJournal.scala]: would it be possible to make it a `val` inside the `receiveWriteJournal`?
```
final val receiveWriteJournal: Actor.Receive = {
  val replayDebugEnabled: Boolean = config.getBoolean("replay-filter.debug")

  {...
```

Comment (rkuhn) [inline akka-persistence/src/main/scala/akka/persistence/journal/AsyncWriteJournal.scala]: Yes, that would be possible, I think. I didn’t consider accessing the config to be expensive, but now some memories are coming back that it actually was beneficial to cache these lookups. Will change.

File: akka-persistence/src/main/scala/akka/persistence/journal/ReplayFilter.scala [hunk 2]
```diff
@@ -30,6 +30,13 @@ private[akka] object ReplayFilter {
     Props(new ReplayFilter(persistentActor, mode, windowSize, maxOldWriters, debugEnabled))
   }
 
+  // for binary compatibility
+  def props(
+    persistentActor: ActorRef,
+    mode: Mode,
+    windowSize: Int,
+    maxOldWriters: Int): Props = props(persistentActor, mode, windowSize, maxOldWriters, debugEnabled = false)
```
Comment (patriknw) [inline akka-persistence/src/main/scala/akka/persistence/journal/ReplayFilter.scala]: this is INTERNAL API so this should not be needed (we must have some freedom)

File: akka-persistence/src/main/scala/akka/persistence/journal/AsyncWriteJournal.scala (hunk 1 above)
Comment (patriknw) [inline akka-persistence/src/main/scala/akka/persistence/journal/AsyncWriteJournal.scala]: thanks

File: akka-persistence/src/main/scala/akka/persistence/journal/ReplayFilter.scala (hunk 2 above)
Comment (rkuhn) [inline akka-persistence/src/main/scala/akka/persistence/journal/ReplayFilter.scala]: Yes, but on the other hand I do not see much value in breaking compatibility gratuitously.

File: akka-persistence/src/main/scala/akka/persistence/journal/AsyncWriteJournal.scala [hunk 3]
```diff
@@ -55,109 +54,114 @@ trait AsyncWriteJournal extends Actor with WriteJournalBase with AsyncRecovery {
   final def receive = receiveWriteJournal.orElse[Any, Unit](receivePluginInternal)
 
   final val receiveWriteJournal: Actor.Receive = {
-    case WriteMessages(messages, persistentActor, actorInstanceId) ⇒
-      val cctr = resequencerCounter
-      resequencerCounter += messages.foldLeft(0)((acc, m) ⇒ acc + m.size) + 1
+    // cannot be a val in the trait due to binary compatibility
+    val replayDebugEnabled: Boolean = config.getBoolean("replay-filter.debug")
```
Comment (rkuhn) [inline akka-persistence/src/main/scala/akka/persistence/journal/AsyncWriteJournal.scala]: This is the only change, the rest is just indentation (check [here](https://github.com/akka/akka/pull/19644/files?w=1)).

File: akka-persistence/src/main/scala/akka/persistence/journal/ReplayFilter.scala (hunk 2 above)
Comment (patriknw) [inline akka-persistence/src/main/scala/akka/persistence/journal/ReplayFilter.scala]: maintaining superfluous code is a burden

Comment (rkuhn) [inline akka-persistence/src/main/scala/akka/persistence/journal/ReplayFilter.scala]: Yes, of course. All I’m saying is that the cost of breaking compatibility without thinking twice is also not zero—for internal api the cost might be small, which means that a small amount of burden might be justified.

Comment (patriknw) [inline akka-persistence/src/main/scala/akka/persistence/journal/ReplayFilter.scala]: yes, but I'm thinking, now, anyway, not a big deal

**Comment by patriknw** [comment]
LGTM

File: akka-persistence/src/main/scala/akka/persistence/journal/ReplayFilter.scala [hunk 4]
```diff
@@ -46,6 +53,10 @@ private[akka] class ReplayFilter(persistentActor: ActorRef, mode: ReplayFilter.M
   import JournalProtocol._
   import ReplayFilter.{ Warn, Fail, RepairByDiscardOld, Disabled }
 
+  // for binary compatibility
+  def this(persistentActor: ActorRef, mode: ReplayFilter.Mode,
+           windowSize: Int, maxOldWriters: Int) = this(persistentActor, mode, windowSize, maxOldWriters, debugEnabled = false)
+
```
Comment (2m) [inline akka-persistence/src/main/scala/akka/persistence/journal/ReplayFilter.scala]: Do we needs this? Newly added `props` method calls original `props` and not constructor.

Comment (rkuhn) [inline akka-persistence/src/main/scala/akka/persistence/journal/ReplayFilter.scala]: As Patrik argued we do not actually need this, I just removed all exceptions while I was at it because I think that there is also some value in keeping that list short. This is a matter that can be debated, of course.

Comment (2m) [inline akka-persistence/src/main/scala/akka/persistence/journal/ReplayFilter.scala]: I still do not understand. Patrik argued about new `props` method. This is new constructor which is not used anywhere. Why do we need it?

Comment (2m) [inline akka-persistence/src/main/scala/akka/persistence/journal/ReplayFilter.scala]: I see now. It might be called from an older version of akka.

**Comment by 2m** [comment]
LGTM

File: akka-persistence/src/main/scala/akka/persistence/journal/ReplayFilter.scala (hunk 4 above)
Comment (patriknw) [inline akka-persistence/src/main/scala/akka/persistence/journal/ReplayFilter.scala]: None of the changes in this file are really needed since it's internal api, but Roland preferred to make them binary backwards compatible anyway and then all of it should be changed.
