### PR TITLE
Prune version clocks based on merged tombstones when merging 

### LINKED ISSUE #23318: Ending up with too many vector clocks
Some pruning not happening as it should perhaps? Appeared in the nightlies over the weekend, after merging all the things friday.

https://jenkins.akka.io:8498/job/akka-multi-node-repeat/13932/consoleFull

```
[JVM-1] java.lang.IllegalStateException: Too many vector clock entries in gossip state Gossip(members = [Member(address = akka.trttl.gremlin.tcp://MultiDcSpec@a2.moxie:53681, dataCenter = dc2, status = Up), Member(address = akka.trttl.gremlin.tcp://MultiDcSpec@a2.moxie:60170, dataCenter = dc2, status = Up), Member(address = akka.trttl.gremlin.tcp://MultiDcSpec@a4.moxie:60828, dataCenter = dc1, status = Up)], overview = GossipOverview(reachability = [], seen = [UniqueAddress(akka.trttl.gremlin.tcp://MultiDcSpec@a4.moxie:60828,545928382)]), version = VectorClock(4ff491baf31afdcfffb3caa205a8ecf3 -> 1, 602c2526b740ec11feae8fa507e6f350 -> 8, 869516b02d35eb7c34d222fdcc98de38 -> 5, d633377ef2e0f995779c730c5f27bbae -> 3), tombstones = Map(UniqueAddress(akka.trttl.gremlin.tcp://MultiDcSpec@a5.moxie:34905,1926157669) -> 1499450297287, UniqueAddress(akka.trttl.gremlin.tcp://MultiDcSpec@a5.moxie:43278,-1097777188) -> 1499450301143))
[JVM-1] 	at akka.cluster.ClusterCoreDaemon.assertLatestGossip(ClusterDaemon.scala:1242)
[JVM-1] 	at akka.cluster.ClusterCoreDaemon.updateLatestGossip(ClusterDaemon.scala:1237)
[JVM-1] 	at akka.cluster.ClusterCoreDaemon.leaderActionsOnConvergence(ClusterDaemon.scala:1103)
[JVM-1] 	at akka.cluster.ClusterCoreDaemon.leaderActions(ClusterDaemon.scala:968)
[JVM-1] 	at akka.cluster.ClusterCoreDaemon$$anonfun$initialized$1.applyOrElse(ClusterDaemon.scala:459)
[JVM-1] 	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
[JVM-1] 	at akka.actor.Actor$class.aroundReceive(Actor.scala:513)
[JVM-1] 	at akka.cluster.ClusterCoreDaemon.aroundReceive(ClusterDaemon.scala:288)
[JVM-1] 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
[JVM-1] 	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
[JVM-1] 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
[JVM-1] 	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
[JVM-1] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
[JVM-1] 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[JVM-1] 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[JVM-1] 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[JVM-1] 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #23318 (again)

### CODE REVIEW

File: akka-cluster/src/main/scala/akka/cluster/Gossip.scala [hunk 1]
```diff
@@ -154,10 +154,9 @@ private[cluster] final case class Gossip(
 
     // 1. merge sets of tombstones
     val mergedTombstones = tombstones ++ that.tombstones
-    val newTombstonedNodes = mergedTombstones.keySet diff that.tombstones.keySet
```
Comment (raboof) [inline akka-cluster/src/main/scala/akka/cluster/Gossip.scala]: Aaah the old approach would also have worked if this were `mergedTombstones.keySet diff tombstones.keySet` I suppose?

Anyway this is more safe.

File: akka-cluster/src/test/scala/akka/cluster/GossipSpec.scala [hunk 2]
```diff
@@ -340,15 +340,18 @@ class GossipSpec extends WordSpec with Matchers {
...
 
       g.seenBy should not contain (dc1b1.uniqueAddress)
       g.overview.reachability.records.exists(_.observer == dc1b1.uniqueAddress) should be(false)
       g.overview.reachability.records.exists(_.subject == dc1b1.uniqueAddress) should be(false)
-      g.version.versions should have size (0)
 
       // sort order should be kept
       g.members.toList should ===(List(dc1a1, dc2d2))
+      g.version.versions.keySet should not contain (VectorClock.Node(Gossip.vclockName(dc1b1.uniqueAddress)))
+      g.version.versions.keySet should contain(VectorClock.Node(Gossip.vclockName(dc2d2.uniqueAddress)))
```
Comment (raboof) [inline akka-cluster/src/test/scala/akka/cluster/GossipSpec.scala]: Perhaps add a check above that there *are* reachability records for `dc2d2` for completeness, though this is OK.

File: akka-cluster/src/test/scala/akka/cluster/GossipSpec.scala [hunk 3]
```diff
@@ -379,6 +382,35 @@ class GossipSpec extends WordSpec with Matchers {
...
+      gdc2.version.versions.keySet should not contain (VectorClock.Node(vclockName(dc2c1.uniqueAddress)))
+
+      // when we merge the two, the nodes should not be reintroduced
+      val merged1 = gdc2 merge gdc1
+      merged1.members should ===(SortedSet(dc1a1, dc2d1))
+
+      merged1.version.versions.keySet should ===(Set(
+        VectorClock.Node(vclockName(dc1a1.uniqueAddress)),
+        VectorClock.Node(vclockName(dc2d1.uniqueAddress))))
+    }
```
Comment (raboof) [inline akka-cluster/src/test/scala/akka/cluster/GossipSpec.scala]: Nice that this can be tested 'from the outside' without referring to tombstones (after all an implementation detail) at all.

**Review by raboof — APPROVED** [review]

File: akka-cluster/src/main/scala/akka/cluster/Gossip.scala (hunk 1 above)
Comment (johanandren) [inline akka-cluster/src/main/scala/akka/cluster/Gossip.scala]: No, that was the thing, I also thought that perhaps I needed to do a `merged diff (this intersect that)` but that didn't fix the issue either. Not sure what it is I don't get here.

This is suboptimal if there are many tombstones, because even if they don't change much we need to loop over all of them in the next step.

File: akka-cluster/src/test/scala/akka/cluster/GossipSpec.scala (hunk 2 above)
Comment (johanandren) [inline akka-cluster/src/test/scala/akka/cluster/GossipSpec.scala]: There actually are no reachability records at all before this, I'll add.

**Review by ktoso — COMMENTED** [review]
Attempted to see the big picture but not deep enough in the Gossip yet :/ I assume this is basically about pruning based from all the tumbstones, but not quite seeing where this effectively allowed for the leak - the prune will now actually remove more (those that we diffed previously), and that's it?)

**Comment by johanandren** [comment]
@ktoso yeah, pretty much, the test failed when there was a split, a node was removed and the split was healed again, a new split, some a new node added, split healed, then the leader on one side saw the version for the first removed node still in its gossip somehow.

**Comment by johanandren** [comment]
akka-cluster multi node tests green locally

**Comment by johanandren** [comment]
I'm going to go ahead and merge this to see if it stops those repeat jobs from failing.
