### PR TITLE
 #19145 fix FlowGroupBySpec

### LINKED ISSUE #19145: Failed: FlowGroupBySpec
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/4461/consoleFull

### PR DESCRIPTION
**Pull request by rkuhn**
also fix concatSubstreams to have right semantics on groupBy and
introduce mergeSubstreamsWithLimit

fixes #19145

### CODE REVIEW

**Comment by rkuhn** [comment]
@2m @johanandren please review

**Comment by johanandren** [comment]
LGTM

File: akka-stream/src/main/scala/akka/stream/javadsl/SubSource.scala [hunk 1]
```diff
@@ -33,11 +33,24 @@ class SubSource[+Out, +Mat](delegate: scaladsl.SubFlow[Out, Mat, scaladsl.Source
...
 
   /**
+   * Flatten the sub-flows back into the super-flow by performing a merge
+   * with the given breadth limit. This means that only up to `breadth`
+   * substreams will be executed at any given time. Substreams that are not
+   * yet executed are also not materialized, meaning that back-pressure will
+   * be exerted at the operator that creates the substreams when the breadth
+   * limit is reached.
+   */
+  def mergeSubstreamsWithLimit(breadth: Int): Source[Out, Mat] =
```
Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/javadsl/SubSource.scala]: Am I the only one who find it weird to call it WithLimit and then call the limit Breadth?

File: akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala [hunk 2]
```diff
@@ -1057,7 +1054,7 @@ trait FlowOps[+Out, +Mat] {
       override def apply[T](flow: Flow[Out, T, Unit], breadth: Int): Repr[T] =
         deprecatedAndThen[Source[Out, Unit]](Split.after(p.asInstanceOf[Any ⇒ Boolean]))
           .map(_.via(flow))
-          .flatMapConcat(conforms)
+          .via(new FlattenMerge(breadth))
```
Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala]: Would it make sense down the line to cache instances of common breadth?

File: akka-stream/src/main/scala/akka/stream/scaladsl/SubFlow.scala [hunk 3]
```diff
@@ -25,16 +25,29 @@ trait SubFlow[+Out, +Mat, +F[+_], C] extends FlowOps[Out, Mat] {
   def to[M](sink: Graph[SinkShape[Out], M]): C
 
   /**
-   * Flatten the sub-flows back into the super-flow by performing a merge.
+   * Flatten the sub-flows back into the super-flow by performing a merge
+   * without breadth limit.
```
Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/scaladsl/SubFlow.scala]: So unbounded open substreams?

File: akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala (hunk 2 above)
Comment (rkuhn) [inline akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala]: Yes, it would.

File: akka-stream/src/main/scala/akka/stream/scaladsl/SubFlow.scala (hunk 3 above)
Comment (rkuhn) [inline akka-stream/src/main/scala/akka/stream/scaladsl/SubFlow.scala]: Yes, I’ll reword.

File: akka-stream/src/main/scala/akka/stream/javadsl/SubSource.scala (hunk 1 above)
Comment (rkuhn) [inline akka-stream/src/main/scala/akka/stream/javadsl/SubSource.scala]: well, actually it is a breadth limit, but I was shying away from such a long name …

Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/javadsl/SubSource.scala]: I'd probably use 'parallelism'

-- 
Cheers,
√

Comment (rkuhn) [inline akka-stream/src/main/scala/akka/stream/javadsl/SubSource.scala]: That is even longer :-(

Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/javadsl/SubSource.scala]: At least there is precedence in mapAsync for instance.

-- 
Cheers,
√

Comment (rkuhn) [inline akka-stream/src/main/scala/akka/stream/javadsl/SubSource.scala]: Yes, good point; changing to `mergeSubstreamsWithParallelism(parallelism)`.

Comment (hepin1989) [inline akka-stream/src/main/scala/akka/stream/javadsl/SubSource.scala]: I thin we could drop the `WithParallelism`.

Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/javadsl/SubSource.scala]: since mapAsync isn't named mapAsyncWithParallelism I think it's fine to not
name it WithParallelism.

If you are worried about the overload then I wouldn't worry.

-- 
Cheers,
√

Comment (rkuhn) [inline akka-stream/src/main/scala/akka/stream/javadsl/SubSource.scala]: Since this is deadlock country I prefer to keep this restriction obvious and “in your face”.

Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/javadsl/SubSource.scala]: WithDanger

-- 
Cheers,
√
