### PR TITLE
#24752 Fix timestamped versions

### LINKED ISSUE #24752: timestamped snapshots not published
https://jenkins.akka.io:8498/job/akka-publish-nightly/

### PR DESCRIPTION
**Pull request by 2m**
Ideally we should use sbt-dynver, but currently version tagged commits are not part  of the direct history of master. Upon release we fork master and add a commit which only has version change. Then we tag that commit with a release tag. Therefore sbt-dynver can not currently derive version from history.

Fixes #24752

### CODE REVIEW

File: project/AkkaBuild.scala [hunk 1]
```diff
@@ -20,13 +20,15 @@ object AkkaBuild {
 
   lazy val buildSettings = Dependencies.Versions ++ Seq(
     organization := "com.typesafe.akka",
-    version := "2.5-SNAPSHOT")
+    version := (version in ThisBuild).value)
```
Comment (ktoso) [inline project/AkkaBuild.scala]: could you document this a bit more? It seems rather magical where the actual value comes from now

**Review by johanandren — APPROVED** [review]
LGTM

File: project/AkkaBuild.scala (hunk 1 above)
Comment (ktoso) [reply project/AkkaBuild.scala]: ping @2m comment and merge? :)

Comment (2m) [reply project/AkkaBuild.scala]: Okay. But with sbt `inspect` is the king. It shows where values for settings come from more robustly than comments.

Comment (ktoso) [reply project/AkkaBuild.scala]: document intent why we do this so weirdly, and hint at inspect then

Comment (2m) [reply project/AkkaBuild.scala]: Added a comment

File: project/AkkaBuild.scala [hunk 2]
```diff
@@ -20,13 +20,16 @@ object AkkaBuild {
 
   lazy val buildSettings = Dependencies.Versions ++ Seq(
     organization := "com.typesafe.akka",
-    version := "2.5-SNAPSHOT")
+    // use the same value as in the build scope, so it can be overriden by stampVersion
```
Comment (ktoso) [inline project/AkkaBuild.scala]: this helps, thanks! 👍

**Review by ktoso — APPROVED** [review]
Thanks, LGTM

**Review by patriknw — COMMENTED** [review]
thanks
