### PR TITLE
Supervise also deferred initialization

### LINKED ISSUE #24052: Supervision doesn't always apply to deferred behavior
Wrapping a deferred behavior in `Actor.supervise` has no effect, if the factory function of the deferred behavior fails with an exception. This seems to be caused by calling `initialUndefer` in `akka.typed.internal.Restarter.apply`.

I think it is very important that deferred behaviors can be supervised. The DB connector example from the `Actor.supervise` documentation is a great example, because typically the DB connection would be established during starting, i.e. in the factory function.

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #24052

### CODE REVIEW

**Comment by johanandren** [comment]
One thing that struck me now that I have the tests passing, in untyped we always wrap start-failure in `ActorInitializationException` which allows the supervision strategy to discern between on-message-failure and startup failure, should we do that in typed as well perhaps?

**Comment by 2m** [comment]
And the default supervision strategy in untyped would not restart and stop the child on `ActorInitializationException`. Keeping restarting the child when the exception is thrown in the initialization is pointless.

**Comment by johanandren** [comment]
No it's not pointless if the actor represents a DB-connection for example, and connecting fails. I think a backoff+restart or restart with limit is very useful in that scenario (just restart-looping isn't very nice though).

**Comment by johanandren** [comment]
Just a reminder to myself: we decided to always wrap startup exceptions in `ActorInitializationException` before passing it to the supervisor

File: akka-actor-typed/src/main/scala/akka/actor/typed/internal/Restarter.scala [hunk 1]
```diff
@@ -124,6 +113,16 @@ import akka.actor.typed.scaladsl.Actor
...
   override val behavior: Behavior[T], override val loggingEnabled: Boolean) extends Supervisor[T, Thr] {
 
+  def init(ctx: ActorContext[T]) =
+    try {
+      wrap(Behavior.validateAsInitial(Behavior.undefer(behavior, ctx)), afterException = false)
+    } catch {
+      case NonFatal(ex: Thr) ⇒
+        // exception starting the actor, log and try again
+        log(ctx, ex)
+        wrap(behavior, afterException = true).init(ctx)
```
Comment (patriknw) [inline akka-actor-typed/src/main/scala/akka/actor/typed/internal/Restarter.scala]: what does this mean? will it retry forever?

File: akka-actor-typed/src/main/scala/akka/actor/typed/internal/Restarter.scala [hunk 2]
```diff
@@ -161,6 +170,17 @@ import akka.actor.typed.scaladsl.Actor
 
   override def loggingEnabled: Boolean = strategy.loggingEnabled
 
+  override def init(ctx: ActorContext[T]) =
+    try {
+      wrap(Behavior.validateAsInitial(Behavior.undefer(behavior, ctx)), afterException = false)
+    } catch {
+      case NonFatal(ex: Thr) ⇒
+        log(ctx, ex)
+        // we haven't actually wrapped and increased retries yet, so need to compare with +1
```
Comment (patriknw) [inline akka-actor-typed/src/main/scala/akka/actor/typed/internal/Restarter.scala]: when is it incremented?

File: akka-actor-typed-tests/src/test/scala/akka/actor/typed/SupervisionSpec.scala [hunk 3]
```diff
@@ -428,14 +468,122 @@ class SupervisionSpec extends TestKit("SupervisionSpec") with TypedAkkaSpecWithS
...
+      failCount = 1, strategy = SupervisorStrategy.restart) {
+
+      EventFilter[ConstructionFailedException](occurrences = 1).intercept {
+        spawn(behv)
+        probe.expectMsg(StartFailed)
+        probe.expectMsg(Started)
+      }
+    }
+
+    "fail instead of restart when deferred factory throws unhandled" in new FailingUnhandledTestSetup(
```
Comment (patriknw) [inline akka-actor-typed-tests/src/test/scala/akka/actor/typed/SupervisionSpec.scala]: does this mean that if one defines a general exception type, such as `Exception` it will restart infinitely if any such exception is thrown from constructor?

File: akka-actor-typed-tests/src/test/scala/akka/actor/typed/SupervisionSpec.scala [hunk 4]
```diff
@@ -234,14 +231,57 @@ class StubbedSupervisionSpec extends WordSpec with Matchers {
...
+        Actor.empty
+      }
+    }).onFailure[ConstructionFailedException](strategy)
+  }
+
+  class FailingUnhandledTestSetup(strategy: SupervisorStrategy) {
+    val probe = TestProbe[AnyRef]("evt")
+    def behv = supervise(deferred[Command] { _ ⇒
+      probe.ref ! StartFailed
+      throw new RuntimeException("construction failed")
```
[the remark this answers is not in the document]
Comment (johanandren) [reply akka-actor-typed-tests/src/test/scala/akka/actor/typed/SupervisionSpec.scala]: We should have a TestException/TE in this test kit as well.

File: akka-actor-typed-tests/src/test/scala/akka/actor/typed/SupervisionSpec.scala (hunk 3 above)
Comment (johanandren) [reply akka-actor-typed-tests/src/test/scala/akka/actor/typed/SupervisionSpec.scala]: Yeah, this is what was discussed a bit at one of our dailies, not sure it makes sense for `Restart`.

File: akka-actor-typed/src/main/scala/akka/actor/typed/internal/Restarter.scala [hunk 5]
```diff
@@ -34,25 +25,25 @@ import akka.actor.typed.scaladsl.Actor
...
               b, restartCount = 0, blackhole = false)
-          backoffRestarter.asInstanceOf[Behavior[T]]
+          backoffRestarter
+            .asInstanceOf[Supervisor[T, Thr]]
       }
+
+      supervisor.init(c)
     }
 
-  def initialUndefer[T](ctx: ActorContext[T], initialBehavior: Behavior[T]): Behavior[T] =
```
[the remark this answers is not in the document]
Comment (johanandren) [reply akka-actor-typed/src/main/scala/akka/actor/typed/internal/Restarter.scala]: Exactly, as each individual strategy needs to be in control of what happens on exception

File: akka-actor-typed/src/main/scala/akka/actor/typed/internal/Restarter.scala (hunk 1 above)
Comment (johanandren) [reply akka-actor-typed/src/main/scala/akka/actor/typed/internal/Restarter.scala]: Yes, probably a bad idea here as well. A bit mitigated with wrapping with `ActorInitializationError` as that would at least have a explicit separate type, but `resume[Exception]` would still be dangerous.

File: akka-actor-typed/src/main/scala/akka/actor/typed/internal/Restarter.scala (hunk 2 above)
Comment (johanandren) [reply akka-actor-typed/src/main/scala/akka/actor/typed/internal/Restarter.scala]: Inside of wrap, but `undefer` is what throws here, so it never is called

File: akka-actor-typed-tests/src/test/scala/akka/actor/typed/SupervisionSpec.scala (hunk 3 above)
Comment (patriknw) [reply akka-actor-typed-tests/src/test/scala/akka/actor/typed/SupervisionSpec.scala]: ok, you haven't implemented that part yet?
I agree that we must be careful to avoid restart loops.

Comment (johanandren) [reply akka-actor-typed-tests/src/test/scala/akka/actor/typed/SupervisionSpec.scala]: Nope, haven't updated yet

**Comment by johanandren** [comment]
Ideas after some discussions in the team:

*Separate API for init failures:* 
```
.onError[ConnectionFailedException](strategy)
.onInitializationError[ConnectionFailedException](strategy) 
```

Pros: it is explicit and does not surprise you with restart-looping an actor with a broken init logic
Cons: annoying that you have to define the same supervision twice to handle the same error on message and on init. Also requires some more complicated machinery behind the scenes.

*Explicit exception type for init:* 
```
.onError[ConnectionFailedException](strategy)
.onError[ActorInitializationException](strategy)
```
Catching `onError[Exception]` would catch both init and on message (as @ktoso strongly opposed having a special case for `ActorInitializationException`)

Pros: it is explicit and does not surprise you with restart-looping an actor with a broken init logic
Cons: You can not handle the specific init exceptions separately

*automagic catch-both*
``` 
.onError[ConnectionFailedException](...)
```
(We'd not implement supervision for `restart` and `resume` strategies as those would be dangerous)

Pros: nice that you only define once
Cons: You cannot only handle on message or on init failures of the same type, it may be surprising

Ping @patriknw @2m 
I think I'm leaning towards the last one because convenience is king.

**Comment by patriknw** [comment]
I think it will be extremly rare that you want to do anything else than `stop` for init exc, therefore I don't think the separate `onInitializationError` is overkill (will complicate the implementation).

For plain Restart and Resume I can't imagine any case where you want to retry, so for those it makes sense to always stop for init exc.

For other cases (e.g. backoff), it might still be interesting to know if it was from init or not and then I think wrapping in `ActorInitializationException` is ok. If you want special treatment of `ActorInitializationException` you can place an inner supervise with that exception. If you want to treat all the same you can use `Exception`. That leaves the case for more specific ex, e.g. DbConnectionException. We could perhaps also see if the handler matches the unwrapped `ActorInitializationException` if it doesn't match the original exception. That would mean that this would work:

```
Actor.supervise(dbActor).onFailure[DbConnectionException](SupervisorStrategy.backoff)
```

If we do that unwrapping attempt it would backoff for DbConnectionException from both init and normal.

**Comment by johanandren** [comment]
@patriknw I've read your comment a couple of times now and I'm not sure I understand which solution you are arguing for (always stopping for restart and resume I got though).

**Comment by johanandren** [comment]
After another discussion with Patrik: `restart` and `resume` always stop on init failure, for the other strategies the matched exception type applies, just like when supervising failures triggered by messages, no wrapping is applied to the exception, so the following:

```
supervise(deferred).onFailure[DBConnectionException)(restartWithLimit(2, 1.second))
```

Will be applied both if the exception is thrown when starting and as a result of a message. This means that there is currently no way to handle all exceptions but only during actor init, we decided this does not seem very useful and is something to add later if it turns out it is useful.

File: akka-actor-typed-tests/src/test/scala/akka/actor/typed/SupervisionSpec.scala [hunk 6]
```diff
@@ -234,14 +231,57 @@ class StubbedSupervisionSpec extends WordSpec with Matchers {
...
+    akka.loggers = [akka.testkit.TestEventListener]
+  """)) with TypedAkkaSpecWithShutdown {
 
   import SupervisionSpec._
   private val nameCounter = Iterator.from(0)
   private def nextName(prefix: String = "a"): String = s"$prefix-${nameCounter.next()}"
   private val waitTime = 50.millis
 
-  implicit val testSettings = TestKitSettings(system)
+  // FIXME eventfilter support in typed testkit
```
[the remark this answers is not in the document]
Comment (johanandren) [reply akka-actor-typed-tests/src/test/scala/akka/actor/typed/SupervisionSpec.scala]: #24348

File: akka-actor-typed/src/main/scala/akka/actor/typed/internal/Restarter.scala [hunk 7]
```diff
@@ -56,6 +54,16 @@ import akka.actor.typed.scaladsl.Behaviors
 
   protected def loggingEnabled: Boolean
 
+  /**
+   * Invoked when the actor is created (or re-created on restart) this is where a restarter implementation
+   * can provide logic for dealing with exceptions thrown when running any actor initialization logic (undeferring).
+   *
+   * FIXME: there is something with nested supervisors and init/undefer that I'm missing here, figure out what
```
Comment (patriknw) [inline akka-actor-typed/src/main/scala/akka/actor/typed/internal/Restarter.scala]: still relevant?

**Review by patriknw — COMMENTED** [review]
anything remaining here, ready for final review? I think i reviewed it and it's looking good.

File: akka-actor-typed/src/main/scala/akka/actor/typed/internal/Restarter.scala (hunk 7 above)
Comment (johanandren) [reply akka-actor-typed/src/main/scala/akka/actor/typed/internal/Restarter.scala]: I think I explored that and realised it is fine, just forgot to remove the comment. Will do that and rebase.

File: akka-actor-typed-tests/src/test/scala/akka/actor/typed/SupervisionSpec.scala [hunk 8]
```diff
@@ -236,13 +240,55 @@ class StubbedSupervisionSpec extends WordSpec with Matchers {
...
+  """
+    akka.loggers = [akka.testkit.TestEventListener]
+  """)) with TypedAkkaSpecWithShutdown {
 
   import SupervisionSpec._
   private val nameCounter = Iterator.from(0)
   private def nextName(prefix: String = "a"): String = s"$prefix-${nameCounter.next()}"
 
-  implicit val testSettings = TestKitSettings(system)
+  // FIXME eventfilter support in typed testkit
```
Comment (raboof) [inline akka-actor-typed-tests/src/test/scala/akka/actor/typed/SupervisionSpec.scala]: That should work since #24386 right? Maybe leave it as-is and fix in a next PR.

File: akka-actor-typed-tests/src/test/scala/akka/actor/typed/SupervisionSpec.scala (hunk 4 above)
[the remark this answers is not in the document]
Comment (raboof) [reply akka-actor-typed-tests/src/test/scala/akka/actor/typed/SupervisionSpec.scala]: Looks like you added the TE further down in this PR, so you could use it here :)

**Review by raboof — APPROVED** [review]
Looks clear, neat tests

File: akka-actor-typed-tests/src/test/scala/akka/actor/typed/SupervisionSpec.scala (hunk 8 above)
Comment (johanandren) [reply akka-actor-typed-tests/src/test/scala/akka/actor/typed/SupervisionSpec.scala]: Hmm, I think I rather removed it there as the existing impl. depended on typed eventbus which I also removed.

**Comment by johanandren** [comment]
Rebased an ready

**Review by patriknw — APPROVED** [review]
LGTM
