### PR TITLE
=htt #19623 Early response no longer causing push or pull twice errors

### LINKED ISSUE #19623: Stream errors when response is sent early
In Akka 2.4.2-RC1, getting the following error when a response is sent before the request body has been read:

```
[WARN] [01/27/2016 12:19:19.448] [application-akka.actor.default-dispatcher-11] [akka.actor.ActorSystemImpl(application)] Sending 2xx response before end of request was received...
Note that the connection will be closed after this response. Also, many clients will not read early responses!
Consider waiting for the request end before dispatching this response!
[ERROR] [01/27/2016 12:19:19.475] [application-akka.actor.default-dispatcher-6] [akka.actor.ActorSystemImpl(application)] Outgoing response stream error
java.lang.IllegalArgumentException: requirement failed: Cannot push port (SubSource.out) twice
	at scala.Predef$.require(Predef.scala:219)
	at akka.stream.stage.GraphStageLogic.push(GraphStage.scala:439)
	at akka.stream.impl.fusing.SubSource$$anon$3$$anonfun$2.apply(StreamOfStreams.scala:519)
	at akka.stream.impl.fusing.SubSource$$anon$3$$anonfun$2.apply(StreamOfStreams.scala:516)
	at akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:557)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:399)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:549)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:480)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:495)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Also getting this, somewhat similar but different error, triggered in a different test:

```
[WARN] [01/27/2016 12:19:20.544] [application-akka.actor.default-dispatcher-7] [akka.actor.ActorSystemImpl(application)] Sending 2xx response before end of request was received...
Note that the connection will be closed after this response. Also, many clients will not read early responses!
Consider waiting for the request end before dispatching this response!
[ERROR] [01/27/2016 12:19:20.563] [application-akka.actor.default-dispatcher-8] [akka.actor.ActorSystemImpl(application)] Internal server error, sending 500 response
java.lang.IllegalArgumentException: requirement failed: Cannot pull port (RequestStartThenRunIgnore.in) twice
	at scala.Predef$.require(Predef.scala:219)
	at akka.stream.stage.GraphStageLogic.pull(GraphStage.scala:351)
	at akka.http.impl.engine.server.HttpServerBluePrint$PrepareRequests$$anon$4$$anon$6.onPull(HttpServerBluePrint.scala:123)
	at akka.stream.stage.GraphStageLogic$SubSourceOutlet$$anonfun$5.apply(GraphStage.scala:1027)
	at akka.stream.stage.GraphStageLogic$SubSourceOutlet$$anonfun$5.apply(GraphStage.scala:1023)
	at akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:557)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:399)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:549)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:480)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:495)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #19623

### CODE REVIEW

File: akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala [hunk 1]
```diff
@@ -112,31 +119,59 @@ private[http] object HttpServerBluePrint {
...
+
+      setIdleHandlers()
+
+      def setIdleHandlers() {
+        setHandler(in, idle)
+        setHandler(out, new OutHandler {
+          override def onPull(): Unit = {
+            pull(in)
+          }
+        })
```
Comment (rkuhn) [inline akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala]: This handler should also be cached outside, like `idle`.

File: akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala [hunk 2]
```diff
@@ -112,31 +119,59 @@ private[http] object HttpServerBluePrint {
...
+          def onPush(): Unit = {
+            grab(in) match {
+              case MessageEnd ⇒
+                entitySource.complete()
+                setIdleHandlers()
+
+              case x ⇒ entitySource.push(x)
+            }
+          }
+          override def onUpstreamFinish(): Unit = completeStage()
```
Comment (rkuhn) [inline akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala]: This also needs to complete the `entitySource`, as does `onUpstreamFailure`.

File: akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala [hunk 3]
```diff
@@ -112,31 +119,59 @@ private[http] object HttpServerBluePrint {
...
+        })
+        setHandler(out, new OutHandler {
+          override def onPull(): Unit = {
+            // remember this until we are done with the entity
+            // so we can pass it downstream at that point
+            upstreamPullWaiting = true
+          }
```
Comment (rkuhn) [inline akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala]: This one needs to override `onDownstreamFinish` to complete the `entitySource` as well.

File: akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala [hunk 4]
```diff
@@ -112,31 +119,59 @@ private[http] object HttpServerBluePrint {
...
-        override def onPull(): Unit = pull(in)
-      })
+      def streamRequestEntity(creator: (Source[ParserOutput.RequestOutput, NotUsed]) => RequestEntity): RequestEntity = {
+        // stream the request entity until we reach the end of it
+        val entitySource = new SubSourceOutlet[RequestOutput]("EntitySource")
+        entitySource.setHandler(new OutHandler {
+          def onPull(): Unit = {
+            pull(in)
+          }
+        })
```
Comment (rkuhn) [inline akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala]: This can reuse the OutHandler that will be cached for the idle case as well.

File: akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala [hunk 5]
```diff
@@ -112,31 +119,59 @@ private[http] object HttpServerBluePrint {
...
+          }
+          override def onUpstreamFinish(): Unit = completeStage()
+        })
+        setHandler(out, new OutHandler {
+          override def onPull(): Unit = {
+            // remember this until we are done with the entity
+            // so we can pass it downstream at that point
+            upstreamPullWaiting = true
+          }
+        })
```
Comment (rkuhn) [inline akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala]: and this handler can also be cached

File: akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala [hunk 6]
```diff
@@ -96,6 +102,7 @@ private[http] object HttpServerBluePrint {
 
     override def createLogic(inheritedAttributes: Attributes) = new GraphStageLogic(shape) {
```
Comment (rkuhn) [inline akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala]: In order to save even more allocations this logic could extend `InHandler with OutHandler`, putting the idle case on it directly.

**Comment by rkuhn** [comment]
Great work, Johan! I only am sensitive to these substream termination issues because I recently fixed bugs of this kinds over and over again ;-)

File: akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala [hunk 7]
```diff
@@ -89,54 +89,99 @@ private[http] object HttpServerBluePrint {
...
+          }
+        })
+        setHandler(out, new OutHandler {
+          override def onPull(): Unit = {
+            // remember this until we are done with the entity
+            // so we can pass it downstream at that point
+            upstreamPullWaiting = true
+          }
+          override def onDownstreamFinish(): Unit = {
+            entitySource.complete()
```
Comment (rkuhn) [inline akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala]: actually I’d need to think more about this (might be okay for this specific case though): in general not wanting the next request does not imply also not wanting the rest of the current one, so this stage completion might want to be deferred until `setIdleHandlers` tim

File: akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala [hunk 8]
```diff
@@ -89,54 +89,99 @@ private[http] object HttpServerBluePrint {
...
+          override def onUpstreamFailure(ex: Throwable): Unit = {
+            entitySource.fail(ex)
+            failStage(ex)
+          }
+        })
+        setHandler(out, new OutHandler {
+          override def onPull(): Unit = {
+            // remember this until we are done with the entity
+            // so we can pass it downstream at that point
+            upstreamPullWaiting = true
```
Comment (johanandren) [inline akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala]: Ups. comment vs variable name

File: akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala (hunk 7 above)
Comment (johanandren) [inline akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala]: I agree, definitely defer until end of chunked entity

File: akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala [hunk 9]
```diff
@@ -89,54 +89,99 @@ private[http] object HttpServerBluePrint {
...
+              case MessageEnd ⇒
+                entitySource.complete()
+                setIdleHandlers()
+
+              case x ⇒ entitySource.push(x)
+            }
+          }
+          override def onUpstreamFinish(): Unit = {
+            entitySource.complete()
+            completeStage()
```
Comment (johanandren) [inline akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala]: Isn't this actually a failure, if we get a chunked request that is closed before message end is reached, fail the entity source and complete the stage?

Comment (rkuhn) [inline akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala]: Hmm, not sure; this seems safe for now until we learn otherwise.

Comment (johanandren) [inline akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala]: Ok, added a test that documents this assumption. (I think that http://tools.ietf.org/html/rfc7230#section-4.1 says that you must end chunked stream correctly with a "last-chunk" but could not figure out if the parser handles this already, and maybe the responsibility belongs there anyway)

**Comment by drewhk** [comment]
LGTM
