### PR TITLE
#20564 Fix compose method of EmptyModule to be able to Keep.left or right

### LINKED ISSUE #20564: GraphDsl should ignore materialized values from builder.add calls
If I didn't provide any shape via ```GraphDsl.create``` the expected type of the materialized value is ```NotUsed```, the problem occurs if I add for a example a ```Sink.foreach``` with the first ```builder.add``` call.

```scala
      val sink = Sink.foreach[Int](x => println(x))
      val g = RunnableGraph.fromGraph(GraphDSL.create() { implicit builder: GraphDSL.Builder[NotUsed] =>
        import GraphDSL.Implicits._
        val s = builder.add(sink)
        val src = builder.add(Source(1 to 3))
        val flow = builder.add(Flow[Int])

        src ~> flow ~> s

        ClosedShape
      })
      var result = g.run()
```

this throws with
 
```
scala.concurrent.impl.Promise$DefaultPromise cannot be cast to akka.NotUsed
java.lang.ClassCastException: scala.concurrent.impl.Promise$DefaultPromise cannot be cast to akka.NotUsed
```

If you switch the add calls for the sink and source it's working because the source provides the expected materialized value.

### PR DESCRIPTION
**Pull request by drewhk**
... and use the proper version from the GraphDSL depending on whether materialized value must be altered on an import or not.

Fixes #20564

### CODE REVIEW

File: akka-stream/src/main/boilerplate/akka/stream/scaladsl/GraphApply.scala.template [hunk 1]
```diff
@@ -26,7 +26,7 @@ trait GraphApply {
    */
   def create[S <: Shape, Mat](g1: Graph[Shape, Mat])(buildBlock: GraphDSL.Builder[Mat] ⇒ (g1.Shape) ⇒ S): Graph[S, Mat] = {
     val builder = new GraphDSL.Builder
-    val s1 = builder.add(g1)
+    val s1 = builder.add(g1, Keep.right)
```
Comment (drewhk) [inline akka-stream/src/main/boilerplate/akka/stream/scaladsl/GraphApply.scala.template]: We import `g1`, hence we need its materialized value while the current module is `EmptyModule`, so there is no materialized value to keep from it: meaning `Keep.right` is needed.

File: akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala [hunk 2]
```diff
@@ -345,10 +348,32 @@ object StreamLayout {
       if (s != shape) throw new UnsupportedOperationException("cannot replace the shape of the EmptyModule")
       else this
 
-    override def compose(that: Module): Module = that
-
-    override def compose[A, B, C](that: Module, f: (A, B) ⇒ C): Module =
-      throw new UnsupportedOperationException("It is invalid to combine materialized value with EmptyModule")
+    override def compose(that: Module): Module = compose(that, scaladsl.Keep.left)
```
Comment (drewhk) [inline akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: The default was equvalent to `Keep.right`, which is wrong, because:

1. GraphDSL.create() with no imports starts with EmptyModule, so final materialized value should be `NotUsed`
2. Now with `.add(g)` we might add a graph with a materialized value, but since we don't want to alter the final type, so `Keep.left` is the right behavior.

The `Keep.right` version is still needed though in the case of single-graph import, since then `.add(g)` called from the `create()` implementation should replace the materialized value with that of `g`.

File: akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala [hunk 3]
```diff
@@ -345,10 +348,32 @@ object StreamLayout {
...
+
+    override def compose[A, B, C](that: Module, f: (A, B) ⇒ C): Module = {
+      if (f == scaladsl.Keep.right) {
+        that
+      } else if (f == scaladsl.Keep.left) {
```
Comment (patriknw) [inline akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: `==` vs `eq` for those?

What about `javadsl.Keep`?

Comment (ktoso) [inline akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: Sounds like a good time to introduce Keep.isLeft that won't forget about checking javadsl/scaladsl? Such oneliner should be inlined no problem I'd think

Comment (ktoso) [inline akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: Hmm... So technically this is scala `Function`, which can not be the javadsl one, however if someone passed in javadsl.Keep.right then it'd be adapted won't it (on scala 2.12).

Not that that matters, and we don't need to check javadsl here now that I think about it it seems

Comment (drewhk) [inline akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: Guys, this does not need the `javadsl.Keep` parts. The cases these handle (and also in `Module`) is the defaults, and the defaults in Java delegate to Scala.

Comment (patriknw) [inline akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: Thanks for clarifying. I see now that it is taken care of in `combinerToScala`

Comment (drewhk) [inline akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: Also, the `compose` method on Empty module is indirectly called by the GraphDSL, no user provided function can and up here (it throws on anything that is not a Keep.left or right, used to be throw on any usage of this method, see diff).

Comment (drewhk) [inline akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: But `eq` should be used though.

Comment (ktoso) [inline akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: Right, sorry for the confusion :)
