### PR TITLE
#20623 Make sure external (mapped) resources are properly cleaned on shutdown

### LINKED ISSUE #20623: Aeron files are not properly cleaned up
Version: 2.4-ARTERY-M1

I have started one cluser node trying to connect to one other node that is not started yet.

```
09:18:07.346 ERROR  akkaSrc=akka.remote.artery.Association(akka://bluebox)  Outbound control stream to artery://bluebox@localhost:11065 failed. Restarting it. Handshake with [artery://bluebox@localhost:11065] did not complete within 15000 ms - akka.remote.artery.Association(akka://bluebox), akkaThrd=bluebox-akka.actor.default-dispatcher-15, thrd=bluebox-akka.actor.default-dispatcher-4, lgr=a.r.a.Association(akka://bluebox) 
akka.remote.artery.OutboundHandshake$HandshakeTimeoutException: Handshake with [artery://bluebox@localhost:11065] did not complete within 15000 ms
09:18:07.396 ERROR  akkaSrc=akka.remote.artery.Association(akka://bluebox)  Outbound message stream to artery://bluebox@localhost:11065 failed. Restarting it. Handshake with [artery://bluebox@localhost:11065] did not complete within 15000 ms - akka.remote.artery.Association(akka://bluebox), akkaThrd=bluebox-akka.actor.default-dispatcher-9, thrd=bluebox-akka.actor.default-dispatcher-8, lgr=a.r.a.Association(akka://bluebox) 
akka.remote.artery.OutboundHandshake$HandshakeTimeoutException: Handshake with [artery://bluebox@localhost:11065] did not complete within 15000 ms
09:18:14.899 ERROR  akkaSrc=akka.remote.artery.ArteryTransport(akka://bluebox)  Aeron error: 2 observations from 2016-05-25 09:18:11.900+0200 to 2016-05-25 09:18:11.907+0200 for:
 .lang.IllegalStateException: could not delete file C:\Users\mokj\AppData\Local\Temp\aeron-mokj-00561b0a-7753-4c07-9f5d-8c14eff8e6d1\publications\UDP-00000000-0-7f000001-11065-F913AF4F-3-4.logbuffer
	at io.aeron.driver.buffer.MappedRawLog.close(MappedRawLog.java:135)
	at io.aeron.driver.NetworkPublication.close(NetworkPublication.java:161)
	at io.aeron.driver.DriverConductor.onClosePublication(DriverConductor.java:270)
	at io.aeron.driver.cmd.CloseNetworkPublicationCmd.execute(CloseNetworkPublicationCmd.java:32)
	at io.aeron.driver.DriverConductor.onDriverConductorCmd(DriverConductor.java:836)
	at io.aeron.driver.DriverConductor$$Lambda$37/1731526546.accept(Unknown Source)
	at org.agrona.concurrent.OneToOneConcurrentArrayQueue.drain(OneToOneConcurrentArrayQueue.java:106)
	at io.aeron.driver.DriverConductor.doWork(DriverConductor.java:174)
	at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:106)
	at java.lang.Thread.run(Thread.java:745)
     - akka.remote.artery.ArteryTransport(akka://bluebox), akkaThrd=bluebox-akka.actor.default-dispatcher-10, thrd=bluebox-akka.actor.default-dispatcher-10, lgr=a.r.a.ArteryTransport(akka://bluebox) 
09:18:22.407 ERROR  akkaSrc=akka.remote.artery.Association(akka://bluebox)  Outbound control stream to artery://bluebox@localhost:11065 failed. Restarting it. Handshake with [artery://bluebox@localhost:11065] did not complete within 15000 ms - akka.remote.artery.Association(akka://bluebox), akkaThrd=bluebox-akka.actor.default-dispatcher-8, thrd=bluebox-akka.actor.default-dispatcher-15, lgr=a.r.a.Association(akka://bluebox) 
akka.remote.artery.OutboundHandshake$HandshakeTimeoutException: Handshake with [artery://bluebox@localhost:11065] did not complete within 15000 ms
09:18:22.464 ERROR  akkaSrc=akka.remote.artery.Association(akka://bluebox)  Outbound message stream to artery://bluebox@localhost:11065 failed. Restarting it. Handshake with [artery://bluebox@localhost:11065] did not complete within 15000 ms - akka.remote.artery.Association(akka://bluebox), akkaThrd=bluebox-akka.actor.default-dispatcher-11, thrd=bluebox-akka.actor.default-dispatcher-10, lgr=a.r.a.Association(akka://bluebox) 
akka.remote.artery.OutboundHandshake$HandshakeTimeoutException: Handshake with [artery://bluebox@localhost:11065] did not complete within 15000 ms
09:18:29.910 ERROR  akkaSrc=akka.remote.artery.ArteryTransport(akka://bluebox)  Aeron error: 4 observations from 2016-05-25 09:18:11.900+0200 to 2016-05-25 09:18:26.912+0200 for:
 .lang.IllegalStateException: could not delete file C:\Users\mokj\AppData\Local\Temp\aeron-mokj-00561b0a-7753-4c07-9f5d-8c14eff8e6d1\publications\UDP-00000000-0-7f000001-11065-F913AF4F-3-4.logbuffer
	at io.aeron.driver.buffer.MappedRawLog.close(MappedRawLog.java:135)
	at io.aeron.driver.NetworkPublication.close(NetworkPublication.java:161)
	at io.aeron.driver.DriverConductor.onClosePublication(DriverConductor.java:270)
	at io.aeron.driver.cmd.CloseNetworkPublicationCmd.execute(CloseNetworkPublicationCmd.java:32)
	at io.aeron.driver.DriverConductor.onDriverConductorCmd(DriverConductor.java:836)
	at io.aeron.driver.DriverConductor$$Lambda$37/1731526546.accept(Unknown Source)
	at org.agrona.concurrent.OneToOneConcurrentArrayQueue.drain(OneToOneConcurrentArrayQueue.java:106)
	at io.aeron.driver.DriverConductor.doWork(DriverConductor.java:174)
	at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:106)
	at java.lang.Thread.run(Thread.java:745)
     - akka.remote.artery.ArteryTransport(akka://bluebox), akkaThrd=bluebox-akka.actor.default-dispatcher-6, thrd=bluebox-akka.actor.default-dispatcher-6, lgr=a.r.a.ArteryTransport(akka://bluebox) 
```

### PR DESCRIPTION
**Pull request by drewhk**
Make sure mapped files are properly unmapped before attempting to delete them (due to Windows restrictions).

Fixes #20623

### CODE REVIEW

**Comment by drewhk** [comment]
Aaargh, conflicts...

**Comment by drewhk** [comment]
rebased

File: akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala [hunk 1]
```diff
@@ -756,19 +757,29 @@ private[remote] class ArteryTransport(_system: ExtendedActorSystem, _provider: R
...
+      closeExternalResources()
+      Done
+    }
+  }
+
+  private val resourcesCloseDone = new AtomicBoolean(false)
+  private def closeExternalResources(): Unit = {
+    if (resourcesCloseDone.compareAndSet(false, true)) {
       if (aeron != null) aeron.close()
+      areonErrorLog.close()
```
Comment (patriknw) [inline akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala]: `areonErrorLog` might be null

**Comment by patriknw** [comment]
LGTM, after one additional null check

File: akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala (hunk 1 above)
Comment (drewhk) [inline akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala]: thanks, fixing.

File: akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala [hunk 2]
```diff
@@ -756,19 +757,29 @@ private[remote] class ArteryTransport(_system: ExtendedActorSystem, _provider: R
...
       }
+
       topLevelFREvents.loFreq(Transport_FlightRecorderClose, NoMetaData)
 
       flightRecorder.foreach(_.close())
       afrFileChannel.foreach(_.force(true))
       afrFileChannel.foreach(_.close())
       // TODO: Be smarter about this in tests and make it always-on-for prod
       afrFile.foreach(_.delete())
-      Done
```
Comment (drewhk) [inline akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala]: this is just a diff confusion, the correct Done is at L761.

File: akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/AeronStreamLatencySpec.scala [hunk 3]
```diff
@@ -129,6 +130,7 @@ abstract class AeronStreamLatencySpec
     taskRunner.stop()
     aeron.close()
     driver.close()
+    IoUtil.unmap(cncByteBuffer)
```
Comment (ktoso) [inline akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/AeronStreamLatencySpec.scala]: can the above close calls fail? (would it be good to have a finally here?)

Comment (drewhk) [inline akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/AeronStreamLatencySpec.scala]: I think it fails with a JVM crash (if I recall correctly) ;) I can try though.

Comment (ktoso) [inline akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/AeronStreamLatencySpec.scala]: let it crash perhaps then 😉

File: akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/LatencySpec.scala [hunk 4]
```diff
@@ -100,7 +102,16 @@ object LatencySpec extends MultiNodeConfig {
...
       val d = System.nanoTime() - sendTimes.get(count - 1)
-      histogram.recordValue(d)
+      try {
+        histogram.recordValue(d)
+      } catch {
+        case e: ArrayIndexOutOfBoundsException ⇒
+          // Report it only once instead of flooding the console
+          if (!reportedArrayOOB) {
+            e.printStackTrace()
+            reportedArrayOOB = true
```
Comment (ktoso) [inline akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/LatencySpec.scala]: good

File: akka-remote/src/main/java/akka/remote/artery/AeronErrorLog.java [hunk 5]
```diff
@@ -37,26 +37,31 @@
...
       this.cncFile = cncFile;
+      cncByteBuffer = IoUtil.mapExistingFile(cncFile, "cnc");
+      cncMetaDataBuffer = CncFileDescriptor.createMetaDataBuffer(cncByteBuffer);
+      cncVersion = cncMetaDataBuffer.getInt(CncFileDescriptor.cncVersionOffset(0));
+      buffer = CncFileDescriptor.createErrorLogBuffer(cncByteBuffer, cncMetaDataBuffer);
+      dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSSZ");
+
+
+      if (CncFileDescriptor.CNC_VERSION != cncVersion)
+      {
```
Comment (ktoso) [inline akka-remote/src/main/java/akka/remote/artery/AeronErrorLog.java]: heh braces style mix in project now? Nothing major but meh

Comment (ktoso) [inline akka-remote/src/main/java/akka/remote/artery/AeronErrorLog.java]: That reminds me - when do we want to enable the java formatter? It is ready to roll.

**Comment by ktoso** [comment]
LGTM AFAICS

File: akka-remote/src/main/java/akka/remote/artery/AeronErrorLog.java (hunk 5 above)
Comment (drewhk) [inline akka-remote/src/main/java/akka/remote/artery/AeronErrorLog.java]: If you prefer I can reformat the file, but I think we should just remove these and implement them properly in Scala as currently these are mostly copy-pasta.

**Comment by 2m** [comment]
LGTM

File: akka-remote/src/main/java/akka/remote/artery/AeronErrorLog.java (hunk 5 above)
Comment (patriknw) [inline akka-remote/src/main/java/akka/remote/artery/AeronErrorLog.java]: it was copied from Aeron samples, I didn't want to spend time on it until we were sure it was useful, we can indeed convert it later

**Comment by drewhk** [comment]
Yep, segfaults... Because I guess streams are running. Not sure how this can be solved.

File: akka-remote/src/main/java/akka/remote/artery/AeronErrorLog.java (hunk 5 above)
Comment (ktoso) [inline akka-remote/src/main/java/akka/remote/artery/AeronErrorLog.java]: ok, no problem - we should think about when to apply the java formatter

**Comment by ktoso** [comment]
> Yep, segfaults... Because I guess streams are running. Not sure how this can be solved.


Ok, well then nothing we can do about the file there then.

**Comment by drewhk** [comment]
That is not a good answer though. This can easily fill the disk if someone has a testsuite. I can delete manually of course. but for users this can be a big deal. I think about this a bit more.

File: akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/LatencySpec.scala [hunk 6]
```diff
@@ -4,8 +4,9 @@
 package akka.remote.artery
 
 import java.util.concurrent.Executors
-import java.util.concurrent.atomic.AtomicLongArray
+import java.util.concurrent.atomic.{ AtomicBoolean, AtomicLongArray }
```
Comment (johanandren) [inline akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/LatencySpec.scala]: Added but not used?

File: akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala [hunk 7]
```diff
@@ -757,6 +758,7 @@ private[remote] class ArteryTransport(_system: ExtendedActorSystem, _provider: R
         topLevelFREvents.loFreq(Transport_AeronErrorLogTaskStopped, NoMetaData)
       }
       if (aeron != null) aeron.close()
+      if (areonErrorLog != null) areonErrorLog.close()
```
Comment (johanandren) [inline akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala]: doesn't this need the same handling as the media driver closing?

Comment (drewhk) [inline akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala]: WDYM?

File: akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/LatencySpec.scala (hunk 6 above)
Comment (drewhk) [inline akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/LatencySpec.scala]: Can I just leave it for this PR? I don't want to wait for another PR validation :( (unless you find other issues of course)

File: akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala (hunk 7 above)
Comment (johanandren) [inline akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala]: Closing it also from a JVM shutdown hook in case of unclean shutdown.

File: akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/LatencySpec.scala (hunk 6 above)
Comment (johanandren) [inline akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/LatencySpec.scala]: Yah, sure, no damage

File: akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala (hunk 7 above)
Comment (drewhk) [inline akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala]: nope, I just removed it because segfaults ;) (previous PR had it) We will fix that scenario later.

**Comment by patriknw** [comment]
I'm not closing the ticket #20623 since we have more things to follow up on here

**Comment by drewhk** [comment]
Yep, good!
