### PR TITLE
Wip small fixes rk

### LINKED ISSUE #19046: Akka HTTP examples still use ActorSystem.shutdown
http://doc.akka.io/docs/akka-stream-and-http-experimental/2.0-M1/scala/http/routing-dsl/index.html

```
...
bindingFuture
    .flatMap(_.unbind()) // trigger unbinding from the port
    .onComplete(_ ⇒ system.shutdown()) // and shutdown when done
}
```

### LINKED ISSUE #19213: Clarify why NegotiateNewSession.clientAuth is an option
It seems that `ClientAuth` itself has its own `None` type. If this is by design the difference between 

```scala
NegotiateNewSession.clientAuth = None
```

and

```scala
NegotiateNewSession.clientAuth = Some(ClientAuth.None)
```

should be explained in the ScalaDoc.

### LINKED ISSUE #19269: document that Sink.seq is capped at Int.MaxValue elements

### PR DESCRIPTION
**Pull request by rkuhn**
fixes #19269 
fixes #19213 
fixes #19046

### CODE REVIEW

File: akka-http/src/main/scala/akka/http/scaladsl/server/directives/SecurityDirectives.scala [hunk 1]
```diff
@@ -215,6 +215,8 @@ object Credentials {
         new Credentials.Provided(token) {
           def verify(secret: String): Boolean = secret secure_== token
         }
+      case Some(GenericHttpCredentials(scheme, token, params)) =>
+        throw new UnsupportedOperationException("cannot verify generic HTTP credentials")
```
Comment (rkuhn) [inline akka-http/src/main/scala/akka/http/scaladsl/server/directives/SecurityDirectives.scala]: @sirthias @jrudolph is this correct? this used to be a MatchError instead …

File: akka-actor-tests/src/test/scala/akka/io/TcpConnectionSpec.scala [hunk 2]
```diff
@@ -402,7 +402,7 @@ class TcpConnectionSpec extends AkkaSpec("""
 
         connectionHandler.expectMsgType[Received].data.decodeString("ASCII") should ===(vs)
       }
-      finally system.shutdown()
+      finally system.terminate()
```
Comment (viktorklang) [inline akka-actor-tests/src/test/scala/akka/io/TcpConnectionSpec.scala]: At last!

File: akka-bench-jmh/src/main/scala/akka/http/HttpBenchmark.scala [hunk 3]
```diff
@@ -56,7 +56,7 @@ class HttpBenchmark {
   def shutdown() = {
     Await.ready(Http().shutdownAllConnectionPools(), 1.second)
     binding.unbind()
-    system.shutdown()
+    system.terminate()
```
Comment (viktorklang) [inline akka-bench-jmh/src/main/scala/akka/http/HttpBenchmark.scala]: This returns a Future, perhaps use that iso `awaitTermination`?

File: akka-camel/src/test/scala/akka/camel/internal/component/ActorComponentConfigurationTest.scala [hunk 4]
```diff
@@ -17,11 +17,11 @@ class ActorComponentConfigurationTest extends WordSpec with Matchers with Shared
   val component: Component = camel.context.getComponent("akka")
 
   "Endpoint url config should be correctly parsed" in {
-    val actorEndpointConfig = component.createEndpoint("akka://test/user/$a?autoAck=false&replyTimeout=987000000+nanos").asInstanceOf[ActorEndpointConfig]
+    val actorEndpointConfig = component.createEndpoint(s"akka://test/user/$$a?autoAck=false&replyTimeout=987000000+nanos").asInstanceOf[ActorEndpointConfig]
```
Comment (viktorklang) [inline akka-camel/src/test/scala/akka/camel/internal/component/ActorComponentConfigurationTest.scala]: ?

File: akka-docs/rst/java/code/docs/actor/ActorDocTest.java [hunk 5]
```diff
@@ -64,7 +64,7 @@ public static void beforeClass() {
 
   @AfterClass
   public static void afterClass() {
-    system.shutdown();
+    system.terminate();
     system.awaitTermination(Duration.create("5 seconds"));
```
Comment (viktorklang) [inline akka-docs/rst/java/code/docs/actor/ActorDocTest.java]: `Await.result(system.terminate(), Duration.create("5 seconds"))`?

File: akka-http-core/src/test/java/akka/http/javadsl/model/JavaApiTestCases.java [hunk 6]
```diff
@@ -86,14 +86,14 @@ public static Object accessScalaDefinedJavadslContentTypeAndMediaType(ContentTyp
 
     // just for the sake of explicitly touching the interfaces
     if (mediaType.binary()) anything = (akka.http.javadsl.model.MediaType.Binary) mediaType;
-    if (1 == 2) anything = (akka.http.javadsl.model.MediaType.Multipart) mediaType;
```
Comment (viktorklang) [inline akka-http-core/src/test/java/akka/http/javadsl/model/JavaApiTestCases.java]: WAAAT?

File: akka-stream-tests/src/test/scala/akka/stream/actor/ActorSubscriberSpec.scala [hunk 7]
```diff
@@ -25,13 +25,13 @@ object ActorSubscriberSpec {
...
     def receive = {
-      case next @ OnNext(elem)   ⇒ probe ! next
-      case complete @ OnComplete ⇒ probe ! complete
-      case err @ OnError(cause)  ⇒ probe ! err
-      case "ready"               ⇒ request(elements = 2)
-      case "boom"                ⇒ throw new RuntimeException("boom") with NoStackTrace
-      case "requestAndCancel"    ⇒ { request(1); cancel() }
-      case "cancel"              ⇒ cancel()
+      case next @ OnNext(elem)  ⇒ probe ! next
+      case OnComplete           ⇒ probe ! OnComplete
```
Comment (viktorklang) [inline akka-stream-tests/src/test/scala/akka/stream/actor/ActorSubscriberSpec.scala]: May I ask why this change? (given that the one before and after extracts values that it doesn't use)

File: akka-stream-tests/src/test/scala/akka/stream/actor/ActorSubscriberSpec.scala [hunk 8]
```diff
@@ -55,8 +55,8 @@ object ActorSubscriberSpec {
     override val requestStrategy = strat
 
     def receive = {
-      case next @ OnNext(elem)   ⇒ probe ! next
-      case complete @ OnComplete ⇒ probe ! complete
+      case next @ OnNext(elem) ⇒ probe ! next
+      case OnComplete          ⇒ probe ! OnComplete
```
Comment (viktorklang) [inline akka-stream-tests/src/test/scala/akka/stream/actor/ActorSubscriberSpec.scala]: Same here

File: akka-stream-tests/src/test/scala/akka/stream/io/TcpSpec.scala [hunk 9]
```diff
@@ -391,7 +391,7 @@ class TcpSpec extends AkkaSpec("akka.stream.materializer.subscription-timeout.ti
       val result = Source.maybe[ByteString].via(Tcp(system2).outgoingConnection(serverAddress)).runFold(0)(_ + _.size)(mat2)
 
       // Getting rid of existing connection actors by using a blunt instrument
-      system2.actorSelection(akka.io.Tcp(system2).getManager.path / "selectors" / "$a" / "*") ! Kill
+      system2.actorSelection(akka.io.Tcp(system2).getManager.path / "selectors" / s"$$a" / "*") ! Kill
```
Comment (viktorklang) [inline akka-stream-tests/src/test/scala/akka/stream/io/TcpSpec.scala]: ?

File: akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowDispatcherSpec.scala [hunk 10]
```diff
@@ -8,7 +8,7 @@ import akka.stream.testkit.AkkaSpec
 import akka.stream.ActorMaterializer
 import akka.stream.ActorMaterializerSettings
 
-class FlowDispatcherSpec extends AkkaSpec("my-dispatcher = ${akka.test.stream-dispatcher}") {
+class FlowDispatcherSpec extends AkkaSpec(s"my-dispatcher = $${akka.test.stream-dispatcher}") {
```
Comment (viktorklang) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowDispatcherSpec.scala]: ?

File: akka-stream/src/main/scala/akka/stream/impl/fusing/Fusing.scala [hunk 11]
```diff
@@ -504,6 +504,7 @@ private[stream] object Fusing {
     private def removeMapping[T](orig: T, map: ju.Map[T, List[T]]): T =
       map.remove(orig) match {
         case null     ⇒ null.asInstanceOf[T]
+        case Nil      => throw new IllegalStateException("mappings corrupted")
```
Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/Fusing.scala]: What does that mean to the recipient? Bug?

File: akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala [hunk 12]
```diff
@@ -373,7 +371,9 @@ final class Split[T](decision: Split.SplitDecision, p: T ⇒ Boolean) extends Gr
  * INTERNAL API
  */
 object SubSink {
-  val RequestOne = Request(1) // No need to frivolously allocate these
+  sealed trait Command
+  case object RequestOne extends Command
+  case object Cancel extends Command
```
Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala]: Nice!

File: akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala [hunk 13]
```diff
@@ -476,45 +476,45 @@ final class SubSource[T](name: String, private[fusing] val externalCallback: Asy
   val status = new AtomicReference[AnyRef]
```
Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala]: Public?

File: akka-stream/src/main/scala/akka/stream/io/SslTls.scala [hunk 14]
```diff
@@ -380,6 +380,10 @@ sealed trait SslTlsOutbound
  *  - `enabledProtocols` will be passed to `SSLEngine::setEnabledProtocols()`
  *  - `clientAuth` will be passed to `SSLEngine::setWantClientAuth()` or `SSLEngine.setNeedClientAuth()`, respectively
  *  - `sslParameters` will be passed to `SSLEngine::setSSLParameters()`
+ *
+ * Please note that passing `clientAuth = None` means that no change is done
```
Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/io/SslTls.scala]: Wouldn't it be less error-prone if it wasn't an option, and the None behaviour was encoded as a ClientAuth?

File: akka-testkit/src/main/java/akka/testkit/JavaTestKit.java [hunk 15]
```diff
@@ -558,7 +558,7 @@ public ReceiveWhile(Class<T> clazz, Duration max, int messages) {
       this(clazz, max, Duration.Inf(), messages);
     }
 
-    @SuppressWarnings("unchecked")
+    @SuppressWarnings("all")
```
Comment (viktorklang) [inline akka-testkit/src/main/java/akka/testkit/JavaTestKit.java]: `@SuppressWarnings("all"/*the things*/)`

File: akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala (hunk 12 above)
Comment (hepin1989) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala]:
```
object Command{
  case object RequestOne extends Command
  case object Cancel extends Command
}
```
this style?

Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala]: Btw, do these need to be public?

**Comment by rkuhn** [comment]
@viktorklang The answer to most of your questions is “it fixes a warning”. I’ll come back to the others tomorrow.

**Comment by viktorklang** [comment]
@rkuhn :)

File: akka-camel/src/test/scala/akka/camel/internal/component/ActorComponentConfigurationTest.scala (hunk 4 above)
Comment (ktoso) [inline akka-camel/src/test/scala/akka/camel/internal/component/ActorComponentConfigurationTest.scala]: This avoids a warning from scalac about "hey, it looks like you're using interpolation but forgot the s prefix!"

File: akka-http-core/src/test/java/akka/http/javadsl/model/JavaApiTestCases.java (hunk 6 above)
Comment (ktoso) [inline akka-http-core/src/test/java/akka/http/javadsl/model/JavaApiTestCases.java]: it's just a compile spec ;) @rkuhn is right that we don't need the ifs (was refactored from something that actually needed them)

File: akka-http-core/src/test/scala/io/akka/integrationtest/http/HttpModelIntegrationSpec.scala [hunk 16]
```diff
@@ -40,7 +40,7 @@ class HttpModelIntegrationSpec extends WordSpec with Matchers with BeforeAndAfte
   implicit val system = ActorSystem(getClass.getSimpleName, testConf)
   import system.dispatcher
 
-  override def afterAll() = system.shutdown()
+  override def afterAll() = system.terminate()
```
Comment (ktoso) [inline akka-http-core/src/test/scala/io/akka/integrationtest/http/HttpModelIntegrationSpec.scala]: :+1:

File: akka-camel/src/test/scala/akka/camel/internal/component/ActorComponentConfigurationTest.scala (hunk 4 above)
Comment (viktorklang) [inline akka-camel/src/test/scala/akka/camel/internal/component/ActorComponentConfigurationTest.scala]: Is there no way of silencing those w/o work-arounds?

File: akka-http/src/main/scala/akka/http/scaladsl/server/directives/SecurityDirectives.scala (hunk 1 above)
Comment (ktoso) [inline akka-http/src/main/scala/akka/http/scaladsl/server/directives/SecurityDirectives.scala]: yeah, looks right.

File: akka-camel/src/test/scala/akka/camel/internal/component/ActorComponentConfigurationTest.scala (hunk 4 above)
Comment (ktoso) [inline akka-camel/src/test/scala/akka/camel/internal/component/ActorComponentConfigurationTest.scala]: I've been asking Jason since I joined Typesafe ;-)
Sadly not yet AFAIK...

Comment (ktoso) [inline akka-camel/src/test/scala/akka/camel/internal/component/ActorComponentConfigurationTest.scala]: It would have been that warning/deprecation silencing mechanisms that have been talked about since a while.

**Comment by drewhk** [comment]
LGTM, but won't merge. Please rebase.

File: akka-bench-jmh/src/main/scala/akka/http/HttpBenchmark.scala (hunk 3 above)
Comment (rkuhn) [inline akka-bench-jmh/src/main/scala/akka/http/HttpBenchmark.scala]: Yes, changed that everywhere (apart from one place in akka-actor-tests that we can only remove once the deprecated method goes away).

File: akka-http-core/src/test/java/akka/http/javadsl/model/JavaApiTestCases.java (hunk 6 above)
Comment (rkuhn) [inline akka-http-core/src/test/java/akka/http/javadsl/model/JavaApiTestCases.java]: well, and there’s also the case that 1 spontaneously _does_ equal 2 :-)

File: akka-http-core/src/test/scala/io/akka/integrationtest/http/HttpModelIntegrationSpec.scala (hunk 16 above)
Comment (rkuhn) [inline akka-http-core/src/test/scala/io/akka/integrationtest/http/HttpModelIntegrationSpec.scala]: OH NOES! Now we have a Dr. Who reference in PR comments, but there is not yet one in my book …

File: akka-stream-tests/src/test/scala/akka/stream/actor/ActorSubscriberSpec.scala (hunk 7 above)
Comment (rkuhn) [inline akka-stream-tests/src/test/scala/akka/stream/actor/ActorSubscriberSpec.scala]: The compiler: it does not like its own output. Try it, I dare you—I double dare you! :-) (the warning message is actually quite funny, I think)

File: akka-stream/src/main/scala/akka/stream/impl/fusing/Fusing.scala (hunk 11 above)
Comment (rkuhn) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/Fusing.scala]: This is a “can’t happen” situation, only to silence an exhaustiveness warning.

File: akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala (hunk 13 above)
Comment (rkuhn) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala]: good catch

File: akka-stream/src/main/scala/akka/stream/io/SslTls.scala (hunk 14 above)
Comment (rkuhn) [inline akka-stream/src/main/scala/akka/stream/io/SslTls.scala]: I’d find that inconsistent: why treat this value differently than its three companions? An empty Option means “don’t change”, a full one means “please change”.

File: akka-testkit/src/main/java/akka/testkit/JavaTestKit.java (hunk 15 above)
Comment (rkuhn) [inline akka-testkit/src/main/java/akka/testkit/JavaTestKit.java]: This was a weird one, BTW: without it there was an “unchecked warning” warning, and with it there was a “extraneous warning” warning. Luckily there is this big hammer.

File: akka-stream/src/main/scala/akka/stream/io/SslTls.scala (hunk 14 above)
Comment (jrudolph) [inline akka-stream/src/main/scala/akka/stream/io/SslTls.scala]: "Don't change" would only be relevant if there is other code setting that value. Is that the case?

If not, removing this extra bit would simplify the API. However, if something else is changing that setting, it needs to be documented in any case how this setting and other code being able to change the setting relate, i.e. which one would overwrite the other in case this setting is a `Some(ClientAuth)`.

Comment (ktoso) [inline akka-stream/src/main/scala/akka/stream/io/SslTls.scala]: I was moving this today to ssl-config and there I made "don't change the JDK defaults" `ClientAuth.Default`. Note: the defaults are `false` on all possible flags, which I documented there. https://github.com/typesafehub/ssl-config/pull/29/files#diff-f7685010387148dd18233c93cbabf44dR7

Comment (rkuhn) [inline akka-stream/src/main/scala/akka/stream/io/SslTls.scala]: There seems to be some misunderstanding on this class, even though I think it has an extremely descriptive name: this is for _negotiating a new session_, so setting `None` means “don’t change from how the previous session was negotiated”, JDK defaults don’t come into the picture unless we are talking about the very first session, where these values describe indeed the deviation from just using the SslContext alone.

Comment (jrudolph) [inline akka-stream/src/main/scala/akka/stream/io/SslTls.scala]: Thanks, @rkuhn, I see.

Should we still change `HttpContext`?

Comment (rkuhn) [inline akka-stream/src/main/scala/akka/stream/io/SslTls.scala]: @ktoso is currently working on that one, he’ll do the right thing :-)

Comment (ktoso) [inline akka-stream/src/main/scala/akka/stream/io/SslTls.scala]: `HttpsContext` I'm intensely working on since monday as we discussed some in the last http call with @sirthias, effectively making it not require all the values for TLS config that it currently carries, as ssl-config is aimed to be doing that instead. I hope to push a PR today, and see also https://github.com/typesafehub/ssl-config for WIP on that side of things.

I see what you mean @rkuhn will have to double check I keep the wanted semantics.

File: akka-http-core/src/test/scala/io/akka/integrationtest/http/HttpModelIntegrationSpec.scala (hunk 16 above)
Comment (ktoso) [inline akka-http-core/src/test/scala/io/akka/integrationtest/http/HttpModelIntegrationSpec.scala]: I knew you'd enjoy that ;)

**Comment by ktoso** [comment]
LGTM, sadly needs rebase :(

**Comment by rkuhn** [comment]
yes, I’ll rebase one last time :-)

**Comment by rkuhn** [comment]
PLS BUILD

**Comment by rkuhn** [comment]
failure tracked in #19544
