### PR TITLE
fix HubSpec 'MergeHub must immediately cancel' instability

### LINKED ISSUE #30464: HubSpec: MergeHub must immediately cancel new producers while draining
https://github.com/akka/akka/pull/30451/checks?check_run_id=3233793800

```
must immediately cancel new producers while draining *** FAILED *** (2 seconds, 41 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected class akka.stream.testkit.TestSubscriber$OnNext, found class akka.stream.testkit.TestSubscriber$OnComplete$ (OnComplete)
[info]   at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
[info]   at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:572)
[info]   at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:543)
[info]   at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:159)
[info]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:973)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNextN(StreamTestKit.scala:438)
[info]   at akka.stream.scaladsl.HubSpec.f$proxy13$1$$anonfun$1(HubSpec.scala:218)
[info]   at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)
[info]   at akka.stream.scaladsl.HubSpec.f$proxy13$2(HubSpec.scala:223)
[info]   at akka.stream.scaladsl.HubSpec.$init$$$anonfun$16$$anonfun$13(HubSpec.scala:202)```

### PR DESCRIPTION
**Pull request by raboof**
fixes #30464

### CODE REVIEW

File: akka-stream-tests/src/test/scala/akka/stream/scaladsl/HubSpec.scala [hunk 1]
```diff
@@ -199,28 +201,36 @@ class HubSpec extends StreamSpec {
...
       val downstream = TestSubscriber.probe[Int]()
       val (sink, draining) =
         MergeHub.sourceWithDraining[Int](16).take(20).toMat(Sink.fromSubscriber(downstream))(Keep.left).run()
       Source(1 to 10).runWith(sink)
       Source(11 to 20).runWith(sink)
-      draining.drainAndComplete()
 
-      downstream.request(10)
-      val firstBatch = downstream.expectNextN(10)
+      // Give the sources time to fill up the producer buffers before completing (and cancelling the sources)
```
Comment (andreaTP) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/HubSpec.scala:211]: Do you think is possible to wait for a deterministic event/condition?

Comment (raboof) [reply akka-stream-tests/src/test/scala/akka/stream/scaladsl/HubSpec.scala:211]: I don't see a way

Comment (andreaTP) [reply akka-stream-tests/src/test/scala/akka/stream/scaladsl/HubSpec.scala:211]: what about having an `awaitAssert` or `eventually` on the first condition to be met?

Comment (raboof) [reply akka-stream-tests/src/test/scala/akka/stream/scaladsl/HubSpec.scala:211]: On what condition?

The problem we were seeing was (at least I strongly suspect ;) ) that `draining.drainAndComplete()` cancelled the sources before the sourced had had time to fill the buffers of the MergeHub. I don't see what we can wait for or retry to avoid that.

**Review by ignasi35 — APPROVED** [review]
LGTM
