### PR TITLE
Bugfix in VirtualProcessor

### LINKED ISSUE #24581: Empty Flow as RS Processor TCK issue
@jroper found that required_spec109_mustIssueOnSubscribeForNonNullSubscriber sometimes (super rarely, so likely a concurrency issue) may fail with: 

```

[info]   java.lang.AssertionError: Async error during test execution: onSubscribe should be called prior to onComplete always
[info]   at org.testng.Assert.fail(Assert.java:78)
[info]   at org.reactivestreams.tck.TestEnvironment.verifyNoAsyncErrorsNoDelay(TestEnvironment.java:314)
[info]   at org.reactivestreams.tck.PublisherVerification$11.run(PublisherVerification.java:507)
[info]   at org.reactivestreams.tck.PublisherVerification.activePublisherTest(PublisherVerification.java:1138)
[info]   at org.reactivestreams.tck.PublisherVerification.required_spec109_mustIssueOnSubscribeForNonNullSubscriber(PublisherVerification.java:477)
[info]   at org.reactivestreams.tck.IdentityProcessorVerification.required_spec109_mustIssueOnSubscribeForNonNullSubscriber(IdentityProcessorVerification.java:311)
[info]   at akka.stream.tck.EmptyProcessorTest.reproduce(EmptyProcessorTest.scala:19)
[info]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[info]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info]   at java.lang.reflect.Method.invoke(Method.java:498)
[info]   at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
[info]   at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
[info]   at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:846)
[info]   at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1170)
[info]   at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[info]   at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
[info]   at org.testng.TestRunner.runWorkers(TestRunner.java:1147)
[info]   at org.testng.TestRunner.privateRun(TestRunner.java:749)
[info]   at org.testng.TestRunner.run(TestRunner.java:600)
[info]   at org.testng.SuiteRunner.runTest(SuiteRunner.java:317)
[info]   at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:312)
[info]   at org.testng.SuiteRunner.privateRun(SuiteRunner.java:274)
[info]   at org.testng.SuiteRunner.run(SuiteRunner.java:223)
[info]   at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[info]   at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
[info]   at org.testng.TestNG.runSuitesSequentially(TestNG.java:1039)
[info]   at org.testng.TestNG.runSuitesLocally(TestNG.java:964)
[info]   at org.testng.TestNG.run(TestNG.java:900)
[info]   at org.scalatest.testng.TestNGSuiteLike$class.run(TestNGSuiteLike.scala:261)
[info]   at akka.stream.tck.AkkaIdentityProcessorVerification.run(AkkaIdentityProcessorVerification.scala:16)
[info]   at org.scalatest.testng.TestNGSuiteLike$class.runTestNG(TestNGSuiteLike.scala:248)
[info]   at akka.stream.tck.AkkaIdentityProcessorVerification.runTestNG(AkkaIdentityProcessorVerification.scala:16)
[info]   at org.scalatest.testng.TestNGSuiteLike$class.run(TestNGSuiteLike.scala:149)
[info]   at akka.stream.tck.AkkaIdentityProcessorVerification.run(AkkaIdentityProcessorVerification.scala:16)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
[info]   at sbt.ForkMain$Run$2.call(ForkMain.java:300)
[info]   at sbt.ForkMain$Run$2.call(ForkMain.java:290)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]   at java.lang.Thread.run(Thread.java:748)
[info]   Cause: org.reactivestreams.tck.TestEnvironment$Latch$ExpectedClosedLatchException: onSubscribe should be called prior to onComplete always
[info]   at org.reactivestreams.tck.TestEnvironment$Latch.assertClosed(TestEnvironment.java:835)
[info]   at org.reactivestreams.tck.PublisherVerification$11$1.onComplete(PublisherVerification.java:503)
[info]   at akka.stream.impl.ReactiveStreamsCompliance$.tryOnComplete(ReactiveStreamsCompliance.scala:106)
[info]   at akka.stream.impl.VirtualProcessor.onComplete(StreamLayout.scala:201)
[info]   at akka.stream.scaladsl.Flow$$anonfun$toProcessor$1$$anon$1.onComplete(Flow.scala:280)
[info]   at org.reactivestreams.example.unicast.AsyncIterablePublisher$SubscriptionImpl.doSubscribe(AsyncIterablePublisher.java:148)
[info]   at org.reactivestreams.example.unicast.AsyncIterablePublisher$SubscriptionImpl.run(AsyncIterablePublisher.java:221)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]   at java.lang.Thread.run(Thread.java:748)
```

For an empty processor, such as: `Flow[Int].toProcessor.run()`

We've always covered the Publisher side of this and that never failed, there may be something special about the processor we have there. 

Submitting reproducer.

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #24581

### CODE REVIEW

File: akka-stream-tests-tck/src/test/scala/akka/stream/tck/Reproducer.scala [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+  @Test
+  @throws[Throwable]
+  def reproduce(): Unit = {
+    var i = 0
+    while (i < 100000) {
+      System.out.println("Run " + i)
+      this.required_spec109_mustIssueOnSubscribeForNonNullSubscriber()
+      i += 1
+    }
+  }
```
Comment (johanandren) [inline akka-stream-tests-tck/src/test/scala/akka/stream/tck/Reproducer.scala]: I'll remove this, but just to show that it passes the PR-validation (I got this to fail even locally before fix)

File: akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala [hunk 2]
```diff
@@ -120,14 +146,17 @@ import scala.util.control.NonFatal
...
+        case null ⇒
+          if (VirtualProcessor.Debug) println(s"VirtualPublisher#$hashCode(null).onSubscribe.rec($s) -> ${obj.getClass}")
+          if (!compareAndSet(null, obj)) rec(obj)
         case subscriber: Subscriber[_] ⇒
+          if (VirtualProcessor.Debug) println(s"VirtualPublisher#$hashCode($subscriber).onSubscribe.rec($s) moving to both")
           obj match {
             case subscription: Subscription ⇒
-              if (compareAndSet(subscriber, Both.create(subscriber))) establishSubscription(subscriber, subscription)
+              val establishing = Establishing.create(subscriber)
+              if (compareAndSet(subscriber, Both.create(subscriber))) establishSubscription(establishing, subscription)
```
Comment (johanandren) [inline akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: What would happen before is that the state was set to `Both` here, but before `establishSubscription` would get to call `subscriber.onSubscribe` `onComplete` would execute and complete the sub, which would then get an `onSubscribe` call after being completed (that's the spec violation bug).

File: akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala [hunk 3]
```diff
@@ -171,43 +205,67 @@ import scala.util.control.NonFatal
...
         case s: Subscriber[_] ⇒ // spec violation
+          if (VirtualProcessor.Debug) println(s"VirtualPublisher#$hashCode($s).onError(${t.getMessage}) -> Inert")
           getAndSet(Inert) match {
             case Inert ⇒ // nothing to be done
             case _     ⇒ ErrorPublisher(ex, "failed-VirtualProcessor").subscribe(s)
           }
-        case _ ⇒ // spec violation or cancellation race, but nothing we can do
+        case Establishing(s) ⇒
+          // keep trying until subscription established and can complete it
+          if (VirtualProcessor.Debug) println(s"VirtualPublisher#$hashCode($s).onError(${t.getMessage}), loop")
```
Comment (johanandren) [inline akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: Seems I missed the recursion waiting for establish to complete here, but I'm not sure it should the done or my comment is wrong.

File: build.sbt [hunk 4]
```diff
@@ -344,7 +344,7 @@ lazy val streamTestkit = akkaModule("akka-stream-testkit")
 
 lazy val streamTests = akkaModule("akka-stream-tests")
   .dependsOn(streamTestkit % "test->test", remote % "test->test", stream)
-  .settings(Dependencies.streamTests)
+  .settings(Dependencies.streamTests ++ Dependencies.streamTestsTck)
```
Comment (johanandren) [inline build.sbt]: leftover, I'll remove

**Comment by johanandren** [comment]
MiMa failure

File: akka-stream-tests-tck/src/test/scala/akka/stream/tck/Reproducer.scala (hunk 1 above)
Comment (ktoso) [reply akka-stream-tests-tck/src/test/scala/akka/stream/tck/Reproducer.scala]: Ok please remove then :)

File: akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala [hunk 5]
```diff
@@ -98,20 +116,28 @@ import scala.util.control.NonFatal
...
   override def toString: String = s"VirtualProcessor(${this.hashCode()})"
+  if (VirtualProcessor.Debug) println(s"created: $this")
 
   override def subscribe(s: Subscriber[_ >: T]): Unit = {
-    @tailrec def rec(sub: Subscriber[Any]): Unit =
+    @tailrec def rec(sub: Subscriber[Any]): Unit = {
       get() match {
-        case null ⇒ if (!compareAndSet(null, s)) rec(sub)
+        case null ⇒
+          if (VirtualProcessor.Debug) println(s"VirtualPublisher#$hashCode(null).subscribe.rec($s) -> sub")
```
Comment (patriknw) [inline akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: what does `VirtualPublisher#$hashCode` mean in these prints?

no `$` for `sub`?

File: akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala [hunk 6]
```diff
@@ -148,18 +179,21 @@ import scala.util.control.NonFatal
...
     val wrapped = new WrappedSubscription(subscription)
     try {
-      subscriber.onSubscribe(wrapped)
+      if (VirtualProcessor.Debug) println(s"VirtualPublisher#$hashCode.establishSubscription(wrapped)")
+      establishing.sub.onSubscribe(wrapped)
       // Requests will be only allowed once onSubscribe has returned to avoid reentering on an onNext before
       // onSubscribe completed
       wrapped.ungateDemandAndRequestBuffered()
+      if (VirtualProcessor.Debug) println(s"VirtualPublisher#$hashCode.establishSubscription(wrapped) -> Both")
+      set(Both(establishing.sub)) // only place we transition from establishing
```
Comment (patriknw) [inline akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: it can also be (already) in Both, but I guess that is fine

Comment (patriknw) [reply akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: unless it could also have moved to Inert and we are setting it back to Both by this?

File: akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala [hunk 7]
```diff
@@ -283,13 +364,19 @@ import scala.util.control.NonFatal
...
           val current = get()
-          if (current eq PassThrough) real.request(n)
-          else if (!compareAndSet(current, Buffering(current.demand + n))) bufferDemand(n)
+          if (current eq PassThrough) {
+            if (VirtualProcessor.Debug) println(s"VirtualPublisher#${VirtualProcessor.this.hashCode}WrappedSubscription($real).bufferDemand($n) passthrough")
+            real.request(n)
+          } else if (!compareAndSet(current, Buffering(current.demand + n))) {
+            if (VirtualProcessor.Debug) println(s"VirtualPublisher#${VirtualProcessor.this.hashCode}WrappedSubscription($real).bufferDemand($n) buffering")
+            bufferDemand(n)
+          }
```
Comment (patriknw) [inline akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: this is only adding debug logging

File: akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala [hunk 8]
```diff
@@ -171,43 +205,67 @@ import scala.util.control.NonFatal
...
         tryOnComplete(s)
       case s: Subscriber[_] ⇒ // spec violation
+        if (VirtualProcessor.Debug) println(s"VirtualPublisher#$hashCode($s).onComplete -> Inert")
         set(Inert)
         EmptyPublisher.subscribe(s)
-      case _ ⇒ // spec violation or cancellation race, but nothing we can do
+      case Establishing(s) ⇒
+        // keep trying until subscription established and can complete it
+        if (VirtualProcessor.Debug) println(s"VirtualPublisher#$hashCode($s).onComplete, loop")
+        onComplete()
```
[the remark this answers is not in the document]
Comment (patriknw) [reply akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: are we sure that will complete?
is there a risk of live lock (starvation) if several threads ends up spinning here and there is no thread remaining to complete the subscription?

**Review by patriknw — COMMENTED** [review]
this is a scary piece of code, I can't see any immediate bugs but I would not bet much money on that this is completely bug free

File: akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala (hunk 6 above)
Comment (johanandren) [reply akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: It should only be able to go to `Both` by first being `Establishing`, if it isn't I made a mistake somewhere

File: akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala (hunk 5 above)
Comment (johanandren) [reply akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: Just wanted to identify different `VirtualPublisher` instances, so that's why I included the hashcode, when I was trying to figure it out. I think default java Object does a "Type#hashcode" when it `toString`s so mimicked that. The interesting part about sub is already in the string as `$s` is the actual subscription

Not 100% sure we need to leave the debugging in here at all.

File: akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala (hunk 8 above)
[the remark this answers is not in the document]
Comment (johanandren) [reply akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: The only situation it wouldn't complete is if the establishing subscription never completes nor fails, I'm not sure what scenario that would be (or what we could possibly do about it).

I don't know the RS spec good enough to answer the part about several threads. A can several threads call try to complete the same subscriber? @ktoso ?

[the remark this answers is not in the document]
Comment (patriknw) [reply akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: I think it's dangerous to spin and depend on that another thread unlocks the spinning. See for example this discussion https://groups.google.com/d/msg/akka-user/dRxTX8WmWlA/ku-nM0KcHJ8J and https://github.com/akka/akka/issues/17216#issuecomment-93945089

File: akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala (hunk 5 above)
Comment (patriknw) [reply akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: ah, now I see the $h...

File: akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala (hunk 6 above)
Comment (patriknw) [reply akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: if you follow who is calling `establishSubscription` it's one case where it's already `Both` and before that `Subscriber`

File: akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala (hunk 8 above)
[the remark this answers is not in the document]
Comment (johanandren) [reply akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: Thanks for digging that up, had no idea.

I think the solution would be to buffer onComplete, if establishing, rather than spinning, and then having establish trigger the complete if needed when done.

File: akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala (hunk 6 above)
Comment (johanandren) [reply akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: I found that one now while rewriting to not do the spin. So fixed in a push soon.

**Comment by johanandren** [comment]
Ok, take two, if onComplete or onError happens while `Establishing` we try to flag/buffer that, and act on it when establish has completed. No spin lock. 

Ran it with the reproducer and the TCK a couple of iterations, will setup a repeat job to run it over night or so.

**Comment by johanandren** [comment]
Ran on repeat all night with the 100 000 repeater enabled. No failures!

**Comment by ktoso** [comment]
Sounds great, I'll review :)

**Comment by johanandren** [comment]
Failure is MiMa so feel free to review anytime and I'll push MiMa excludes soon

File: akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala (hunk 7 above)
Comment (johanandren) [reply akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: Oh, sorry, didn't catch this, you think I should remove it?

File: akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala [hunk 9]
```diff
@@ -172,43 +242,67 @@ import scala.util.control.NonFatal
...
         set(Inert)
         tryOnComplete(s)
       case s: Subscriber[_] ⇒ // spec violation
+        if (VirtualProcessor.Debug) println(s"VirtualPublisher#$hashCode($s).onComplete -> Inert")
         set(Inert)
         EmptyPublisher.subscribe(s)
-      case _ ⇒ // spec violation or cancellation race, but nothing we can do
+      case est: Establishing ⇒
+        if (VirtualProcessor.Debug) println(s"VirtualPublisher#$hashCode($est).onComplete -> Establishing with buffered complete")
+        if (!est.onCompleteBuffered && !compareAndSet(est, est.copy(onCompleteBuffered = true))) onComplete()
```
Comment (patriknw) [inline akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: Let's see if I get it. Here it's changed to `onCompleteBuffered=true`, which is used in `establishSubscription` iff the cas there fails (meaning it was changed here)

**Review by patriknw — COMMENTED** [review]
started at this for a while, looking good (but very complicated)

File: akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala [hunk 10]
```diff
@@ -172,43 +242,67 @@ import scala.util.control.NonFatal
...
+          if (VirtualProcessor.Debug) println(s"VirtualPublisher#$hashCode($s).onError(${t.getMessage}) -> Inert")
           getAndSet(Inert) match {
             case Inert ⇒ // nothing to be done
             case _     ⇒ ErrorPublisher(ex, "failed-VirtualProcessor").subscribe(s)
           }
-        case _ ⇒ // spec violation or cancellation race, but nothing we can do
+        case est: Establishing ⇒
+          // keep trying until subscription established and can complete it
+          if (VirtualProcessor.Debug) println(s"VirtualPublisher#$hashCode($est).onError(${t.getMessage}), loop")
+          if (!compareAndSet(est, est.copy(onErrorBuffered = OptionVal.Some(ex)))) rec(ex)
```
[the remark this answers is not in the document]
Comment (johanandren) [reply akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: I'm not 100% sure what to do in case of multiple onErrors or if that is even allowed, need to read up on spec

File: akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala (hunk 9 above)
Comment (johanandren) [reply akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: Exactly, we "buffer" the fact that it should complete as soon as establishing completes, and have the establishing thread do the actual onComplete

File: akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala [hunk 11]
```diff
@@ -172,43 +242,67 @@ import scala.util.control.NonFatal
...
           finally if (t == null) throw ex // must throw NPE, rule 2:13
         case s: Subscriber[_] ⇒ // spec violation
+          if (VirtualProcessor.Debug) println(s"VirtualPublisher#$hashCode($s).onError(${t.getMessage}) -> Inert")
           getAndSet(Inert) match {
             case Inert ⇒ // nothing to be done
             case _     ⇒ ErrorPublisher(ex, "failed-VirtualProcessor").subscribe(s)
           }
-        case _ ⇒ // spec violation or cancellation race, but nothing we can do
+        case est: Establishing ⇒
+          // keep trying until subscription established and can complete it
```
[the remark this answers is not in the document]
Comment (johanandren) [reply akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: Ups, I think it's a left over comment from the spinning version. I'll update

File: akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala [hunk 12]
```diff
@@ -148,18 +184,52 @@ import scala.util.control.NonFatal
...
+
+          case Inert ⇒
+            tryCancel(subscription)
+
+          case other ⇒
+            throw new IllegalStateException(s"Unexpected state while establishing: [$other], if this ever happens it is a bug.")
+        }
+      }
+      completeEstablishing()
+
```
[the remark this answers is not in the document]
Comment (johanandren) [reply akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: Ah neat, that makes the normal case cheaper as well, as it's just CAS vs get+cas

File: akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala (hunk 7 above)
Comment (patriknw) [reply akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: no, was only an observation for future reviewers

File: akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala (hunk 10 above)
[the remark this answers is not in the document]
Comment (johanandren) [reply akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: I interpret 1.7 of the spec as if onError/onComplete is both called, or either multiple times that is a spec violation:
> Once a terminal state has been signaled (onError, onComplete) it is REQUIRED that no further signals occur.

I'll change both the `onComplete` and `onFail` to fall into the spec-violation case if either has already happened.

**Comment by johanandren** [comment]
As a person who learns from his earlier mistakes I have set up the repeater test (not in this PR) in a separate branch on top of it, and a job running every 30 minutes. Would be good if someone reviewing this start of next week could look at that job to verify it looks green and disable it. https://jenkins.akka.io:8498/job/akka-local-repeat/

File: akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala (hunk 8 above)
[the remark this answers is not in the document]
Comment (ktoso) [reply akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: It would be illegal to not complete establishing a sub, but it could happen; good to buffer onComplete instead

**Comment by ktoso** [comment]
resolved conflict after Jame's fix in onError handler here; Stared long at impl and looks correct indeed

**Review by ktoso — APPROVED** [review]
LGTM, please see conflict resolution and merge

File: akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala [hunk 13]
```diff
@@ -172,46 +238,66 @@ import scala.util.control.NonFatal
...
             case Inert ⇒ // nothing to be done
             case _     ⇒ ErrorPublisher(ex, "failed-VirtualProcessor").subscribe(s)
           }
-        case _ if t == null ⇒
-          // cancelled before onError(null), must throw NPE, rule 2.13
-          throw ex
-        case _ ⇒ // spec violation or cancellation race, but nothing we can do
+        case est @ Establishing(_, false, OptionVal.None) ⇒
+          if (VirtualProcessor.Debug) println(s"VirtualPublisher#$hashCode($est).onError(${t.getMessage}), loop")
+          if (!compareAndSet(est, est.copy(onErrorBuffered = OptionVal.Some(ex)))) rec(ex)
```
Comment (jroper) [inline akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: Spec violation bug here - if the error is successfully buffered, and the exception was null, then this method doesn't throw an NPE, which it's required to do.
