### PR TITLE
Do not tear down connections on IllegalArgumentException from serializer

### LINKED ISSUE #24910: handle IllegalArgumentException from serializers
NotSerializableException is transparently discarded, but many serializers are also throwing IllegalArgumentException, which should also be also be handled and not tear down the connection.

This is probably only relevant for classic remoting

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #24910

### CODE REVIEW

**Review by patriknw — APPROVED** [review]
LGTM

File: akka-remote/src/test/scala/akka/remote/TransientSerializationErrorSpec.scala [hunk 1]
```diff
@@ -0,0 +1,126 @@
...
+  val port = system.asInstanceOf[ExtendedActorSystem].provider.getDefaultAddress.port.get
+  val sysName = system.name
+  val protocol =
+    if (RARP(system).provider.remoteSettings.Artery.Enabled) "akka"
+    else "akka.tcp"
+
+  val system2 = ActorSystem(system.name, system.settings.config)
+  val system2Address = RARP(system2).provider.getDefaultAddress
+
+  class EchoActor extends Actor {
```
Comment (patriknw) [inline akka-remote/src/test/scala/akka/remote/TransientSerializationErrorSpec.scala]: could use TestActors.echoActor instead

File: akka-remote/src/main/scala/akka/remote/MessageSerializer.scala [hunk 2]
```diff
@@ -17,6 +18,7 @@ import scala.util.control.NonFatal
  *
  * MessageSerializer is a helper for serializing and deserialize messages
  */
+@InternalApi
```
Comment (raboof) [inline akka-remote/src/main/scala/akka/remote/MessageSerializer.scala]: Ah it needs `@InternalApi` because `private[akka]` is not visible from Java, right? Good reminder.

**Review by raboof — APPROVED** [review]
kind of fishy to special-case `IllegalArgumentException` like this, but makes sense in practice so :+1:

File: akka-remote/src/main/scala/akka/remote/MessageSerializer.scala (hunk 2 above)
Comment (johanandren) [reply akka-remote/src/main/scala/akka/remote/MessageSerializer.scala]: Yup!
