### PR TITLE
#25733 close channels from SelectionHandler to make sure they are properly flushed from Selector

### LINKED ISSUE #25733: FAILED akka.io.TcpConnectionSpec on Java 11
There seems to be issues around closing connections, I see UDP tests failing with port already used errors locally also:

https://jenkins.akka.io:8498/job/akka-nightly-jdk11/16/consoleFull

Some of the failures seen locally:
```
[ERROR] [10/04/2018 09:24:18.303] [UdpConnectedIntegrationSpec-akka.actor.default-dispatcher-7] [akka://UdpConnectedIntegrationSpec/system/IO-UDP-FF/selectors/$a/3] Failed to bind UDP channel to endpoint [/127.0.0.1:65070]
java.net.BindException: Address already in use
...
[info] - must be able to unbind and bind again successfully *** FAILED *** (48 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected Bound(/127.0.0.1:65070), found CommandFailed(Bind(Actor[akka://UdpConnectedIntegrationSpec/system/testActor-497#-1328237810],/127.0.0.1:65070,List()))
[info]   at scala.Predef$.assert(Predef.scala:219)
[info]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:403)
[info]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:379)
[info]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:379)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:896)
[info]   at akka.io.UdpConnectedIntegrationSpec.bindUdp(UdpConnectedIntegrationSpec.scala:23)
[info]   at akka.io.UdpConnectedIntegrationSpec.$anonfun$new$4(UdpConnectedIntegrationSpec.scala:88)
```

```
info] - must abort the connection and reply with `Aborted` upon reception of an `Abort` command *** FAILED *** (172 milliseconds)
[info]   Expected exception java.io.IOException to be thrown, but no exception was thrown (TcpConnectionSpec.scala:459)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:138)
[info]   at org.scalatest.MatchersHelper$.checkExpectedException(MatchersHelper.scala:322)
[info]   at org.scalatest.words.ResultOfTheTypeInvocation.thrownBy(ResultOfTheTypeInvocation.scala:39)
[info]   at akka.io.TcpConnectionSpec$$anon$18.$anonfun$new$41(TcpConnectionSpec.scala:459)
[info]   at akka.io.TcpConnectionSpec$EstablishedConnectionTest.$anonfun$run$2(TcpConnectionSpec.scala:992)
[info]   at akka.io.TcpConnectionSpec$UnacceptedConnectionTest.$anonfun$run$1(TcpConnectionSpec.scala:946)
[info]   at akka.io.TcpConnectionSpec$LocalServerTest.run(TcpConnectionSpec.scala:895)
[info]   at akka.io.TcpConnectionSpec$UnacceptedConnectionTest.run(TcpConnectionSpec.scala:943)
[info]   at akka.io.TcpConnectionSpec$EstablishedConnectionTest.run(TcpConnectionSpec.scala:978)
[info]   at akka.io.TcpConnectionSpec$$anon$18.<init>(TcpConnectionSpec.scala:452)
[info]   at akka.io.TcpConnectionSpec.$anonfun$new$40(TcpConnectionSpec.scala:451)
```

```
[info] - must report when peer aborted the connection *** FAILED *** (3 seconds, 73 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class akka.io.Tcp$ErrorClosed
[info]   at scala.Predef$.assert(Predef.scala:219)
[info]   at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:509)
[info]   at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:482)
[info]   at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:482)
[info]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:896)
[info]   at akka.io.TcpConnectionSpec$$anon$22.$anonfun$new$54(TcpConnectionSpec.scala:596)
[info]   at akka.io.TcpConnectionSpec$EstablishedConnectionTest.$anonfun$run$2(TcpConnectionSpec.scala:992)
[info]   at akka.io.TcpConnectionSpec$UnacceptedConnectionTest.$anonfun$run$1(TcpConnectionSpec.scala:946)
[info]   at akka.io.TcpConnectionSpec$LocalServerTest.run(TcpConnectionSpec.scala:895)
[info]   at akka.io.TcpConnectionSpec$UnacceptedConnectionTest.run(TcpConnectionSpec.scala:943)
[info]   at akka.io.TcpConnectionSpec$EstablishedConnectionTest.run(TcpConnectionSpec.scala:978)
[info]   at akka.io.TcpConnectionSpec$$anon$22.<init>(TcpConnectionSpec.scala:593)
[info]   at akka.io.TcpConnectionSpec.$anonfun$new$53(TcpConnectionSpec.scala:592)
```

```
[info] - must report when peer closed the connection when trying to write *** FAILED *** (3 seconds, 77 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class akka.io.Tcp$ErrorClosed
[info]   at scala.Predef$.assert(Predef.scala:219)
[info]   at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:509)
[info]   at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:482)
[info]   at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:482)
[info]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:896)
[info]   at akka.io.TcpConnectionSpec$$anon$23.$anonfun$new$56(TcpConnectionSpec.scala:613)
[info]   at akka.io.TcpConnectionSpec$EstablishedConnectionTest.$anonfun$run$2(TcpConnectionSpec.scala:992)
[info]   at akka.io.TcpConnectionSpec$UnacceptedConnectionTest.$anonfun$run$1(TcpConnectionSpec.scala:946)
[info]   at akka.io.TcpConnectionSpec$LocalServerTest.run(TcpConnectionSpec.scala:895)
[info]   at akka.io.TcpConnectionSpec$UnacceptedConnectionTest.run(TcpConnectionSpec.scala:943)
[info]   at akka.io.TcpConnectionSpec$EstablishedConnectionTest.run(TcpConnectionSpec.scala:978)
```

### PR DESCRIPTION
**Pull request by jrudolph**
This makes sure that we report connection closure only after it has really happened. This is important on JDK 11 (and before on Windows) where a channel is only closed after it is cancelled and flushed from its selector.

Tests in akka-actor-tests are now fixed. Something is still broken in akka-stream.

Fixes #25733, #25913.

### CODE REVIEW

**Comment by jrudolph** [comment]
Seems the stream tests fail because they depend on 

> the invariant that closing of a channel happens-before terminating the associated TcpConnection actor because the closing code may happen only in postStop where we cannot synchronously block until the selector has finally completed the channel closing.

And I tried getting away with not providing that guarantee but seems we might need it.

**Comment by johanandren** [comment]
Are you pursuing some other idea that will work for streams or should I still review this one?

**Comment by jrudolph** [comment]
> Are you pursuing some other idea that will work for streams or should I still review this one?

It should be a smallish update to TcpConnection. But if you wait a while maybe you can review the whole.

**Comment by jrudolph** [comment]
Didn't manage to finish it today. The stream tests are currently super-flaky for me and I haven't found out why.

**Comment by jrudolph** [comment]
Split up fixes unrelated to the selector issue out into #26038. Hopefully both PRs validate separately on JDK8.

This one was rebased and cleaned up. Once PR validation has cleared it, it should be finally ready for review.

File: akka-actor-tests/src/test/scala/akka/io/TcpConnectionSpec.scala [hunk 1]
```diff
@@ -915,9 +923,11 @@ class TcpConnectionSpec extends AkkaSpec("""
       new ChannelRegistration {
         def enableInterest(op: Int): Unit = interestCallReceiver.ref ! op
         def disableInterest(op: Int): Unit = interestCallReceiver.ref ! -op
-        def cancel(): Unit = ()
+        def cancelAndClose(andThen: () ⇒ Unit): Unit = onCancelAndClose(andThen)
```
Comment (jrudolph) [inline akka-actor-tests/src/test/scala/akka/io/TcpConnectionSpec.scala]: Yep, we don't use the real SelectorHandler impl here, so we need to replicated the correct behavior.

File: akka-actor-tests/src/test/scala/akka/io/TcpIntegrationSpec.scala [hunk 2]
```diff
@@ -152,6 +156,13 @@ class TcpIntegrationSpec extends AkkaSpec("""
 
       override def bindOptions = List(SO.SendBufferSize(1024))
       override def connectOptions = List(SO.ReceiveBufferSize(1024))
+
+      serverHandler.send(serverConnection, Close)
```
Comment (jrudolph) [inline akka-actor-tests/src/test/scala/akka/io/TcpIntegrationSpec.scala]: Test was missing cleanup for some reason.

File: akka-actor-tests/src/test/scala/akka/io/TcpListenerSpec.scala [hunk 3]
```diff
@@ -143,13 +145,18 @@ class TcpListenerSpec extends AkkaSpec("""
...
-    registerCallReceiver.expectMsg(if (pullMode) 0 else OP_ACCEPT)
+    val register = registerCallReceiver.expectMsgType[RegisterChannel]
+    register.initialOps should ===(if (pullMode) 0 else OP_ACCEPT)
 
     def bindListener(): Unit = {
       listener ! new ChannelRegistration {
         def enableInterest(op: Int): Unit = interestCallReceiver.ref ! op
         def disableInterest(op: Int): Unit = interestCallReceiver.ref ! -op
-        def cancel(): Unit = ()
+        def cancelAndClose(andThen: () ⇒ Unit): Unit = {
```
Comment (jrudolph) [inline akka-actor-tests/src/test/scala/akka/io/TcpListenerSpec.scala]: Same here, we need to replicate actual implementation.

File: akka-actor/src/main/scala/akka/io/TcpConnection.scala [hunk 4]
```diff
@@ -70,9 +71,9 @@ private[io] abstract class TcpConnection(val tcp: TcpExt, val channel: SocketCha
 
       val info = ConnectionInfo(registration, handler, keepOpenOnPeerClosed, useResumeWriting)
 
-      // if we have resumed reading from pullMode while waiting for Register then register OP_READ interest
-      if (pullMode && !readingSuspended) resumeReading(info)
-      doRead(info, None) // immediately try reading, pullMode is handled by readingSuspended
+      // if we are in push mode or already have resumed reading in pullMode while waiting for Register
+      // then register OP_READ interest
+      if (!pullMode || ( /*pullMode && */ !readingSuspended)) resumeReading(info)
```
Comment (jrudolph) [inline akka-actor/src/main/scala/akka/io/TcpConnection.scala]: Previously, we were calling `doRead` here directly, however, `doRead` may already try to close the connection and call `context.become(unregistering)` which would then be lost if `become` a few lines below.

It seems the `doRead` was an optimization in the first place trying to instantly read something without checking the selector first. Now, we always go through the selector, which is more consistent anyway.

File: akka-actor/src/main/scala/akka/io/TcpListener.scala [hunk 5]
```diff
@@ -98,10 +97,13 @@ private[io] class TcpListener(
 
     case Unbind ⇒
       log.debug("Unbinding endpoint {}", localAddress)
-      channel.close()
-      // see https://github.com/akka/akka/issues/20282
-      if (Helpers.isWindows) registration.enableInterest(1)
```
Comment (jrudolph) [inline akka-actor/src/main/scala/akka/io/TcpListener.scala]: No extra code paths any more for Windows.

File: akka-actor/src/main/scala/akka/io/TcpOutgoingConnection.scala [hunk 6]
```diff
@@ -53,6 +54,7 @@ private[io] class TcpOutgoingConnection(
 
   def receive: Receive = {
     case registration: ChannelRegistration ⇒
+      setRegistration(registration)
```
Comment (jrudolph) [inline akka-actor/src/main/scala/akka/io/TcpOutgoingConnection.scala]: Necessary to keep our registration here early, so we can actually close the connection on error.

**Review by patriknw — APPROVED** [review]
LGTM, as far as I can see

**Comment by jrudolph** [comment]
Running JDK 11 nightly against both this and #26038 in https://jenkins.akka.io:8498/job/akka-nightly-jdk11/80/console.

File: akka-actor/src/main/scala/akka/io/SelectionHandler.scala [hunk 7]
```diff
@@ -208,17 +210,38 @@ private[io] object SelectionHandler {
...
         }
       }
 
-    private def cancelKey(key: SelectionKey): Unit =
+    private def cancelKeyAndClose(key: SelectionKey, andThen: () ⇒ Unit): Unit =
+      execute {
+        new Task {
+          def tryRun(): Unit = {
+            Try(key.cancel())
+            Try(key.channel().close())
```
Comment (johanandren) [inline akka-actor/src/main/scala/akka/io/SelectionHandler.scala]: Is it ok to do the same on Java 8 and 11 with this fix?

**Review by johanandren — APPROVED** [review]
Tests green! LGMT. Fingers crossed for the nightly/repeated tests.

File: akka-actor/src/main/scala/akka/io/SelectionHandler.scala (hunk 7 above)
Comment (jrudolph) [reply akka-actor/src/main/scala/akka/io/SelectionHandler.scala]: Yes, that was the goal. We do a bit more than before on JDK 8. I guess, it's a good change anyway because it might fix https://github.com/akka/akka/issues/25605 as well.
