### PR TITLE
LazySourceSpec: improve 'no demand' test stability

### LINKED ISSUE #30492: LazySourceSpec: never construct the source when there was no demand
Mulitple failures in `LazySourceSpec` in https://github.com/akka/akka/pull/30449/checks?check_run_id=3252611503#step:6:20766:

```
[info] - must never construct the source when there was no demand *** FAILED *** (2 seconds, 13 milliseconds)
[info]   true did not equal false (LazySourceSpec.scala:141)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
[info]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6922)
[info]   at akka.stream.scaladsl.LazySourceSpec.$anonfun$new$35(LazySourceSpec.scala:141)
[info]   at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)
[info]   at akka.stream.scaladsl.LazySourceSpec.$anonfun$new$34(LazySourceSpec.scala:129)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
```

```
[info] - must never construct the source when there was no demand *** FAILED *** (2 seconds, 13 milliseconds)
[info]   true did not equal false (LazySourceSpec.scala:292)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
[info]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6922)
[info]   at akka.stream.scaladsl.LazySourceSpec.$anonfun$new$75(LazySourceSpec.scala:292)
[info]   at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)
[info]   at akka.stream.scaladsl.LazySourceSpec.$anonfun$new$74(LazySourceSpec.scala:277)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
```

### PR DESCRIPTION
**Pull request by raboof**
Perhaps the probe might introduce some internal buffering that doesn't
happen for a 'direct' cancellation?

Hopefully fixes #30492

### CODE REVIEW

File: akka-stream-tests/src/test/scala/akka/stream/scaladsl/LazySourceSpec.scala [hunk 1]
```diff
@@ -37,16 +37,14 @@ class LazySourceSpec extends StreamSpec with DefaultTimeout with ScalaFutures {
...
 
     "never construct the source when there was no demand" in assertAllStagesStopped {
-      val probe = TestSubscriber.probe[Int]()
       val constructed = new AtomicBoolean(false)
       Source
         .lazySingle { () =>
           constructed.set(true)
           1
         }
-        .toMat(Sink.fromSubscriber(probe))(Keep.left)
```
Comment (patriknw) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/LazySourceSpec.scala:47]: ok, maybe fromSubscriber is eagerly pulling? normally one would use `TestSink`, right?

Easier to use `Sink.cancelled` here, indeed.

**Review by patriknw — APPROVED** [review]
LGTM
