### PR TITLE
Snapshot when stages stopped incorrect and can cause crash

### LINKED ISSUE #26902: assertAllStagesStopped triggers ArrayIndexOutOfBoundsException
The stage didn't stop in one of my tests and `assertAllStagesStopped` fails with this for some reason.

This error seems to be triggered by some un-clean termination in Alpakka MQTT Streaming. (See details below)

```
java.lang.ArrayIndexOutOfBoundsException: 67108865
    at akka.stream.impl.fusing.GraphInterpreter.$anonfun$toSnapshot$5(GraphInterpreter.scala:688)
    at akka.stream.impl.fusing.GraphInterpreter.$anonfun$toSnapshot$5$adapted(GraphInterpreter.scala:688)
    at scala.collection.immutable.List.map(List.scala:282)
    at akka.stream.impl.fusing.GraphInterpreter.toSnapshot(GraphInterpreter.scala:688)
    at akka.stream.impl.fusing.GraphInterpreterShell.toSnapshot(ActorGraphInterpreter.scala:657)
    at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.$anonfun$applyOrElse$1(ActorGraphInterpreter.scala:767)
    at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
    at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:319)
    at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:975)
    at scala.collection.TraversableLike.map(TraversableLike.scala:233)
    at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
    at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
    at scala.collection.SetLike.map(SetLike.scala:100)
    at scala.collection.SetLike.map$(SetLike.scala:100)
    at scala.collection.AbstractSet.map(Set.scala:47)
    at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:767)
    at akka.actor.Actor.aroundReceive(Actor.scala:539)
    at akka.actor.Actor.aroundReceive$(Actor.scala:537)
    at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:664)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:610)
    at akka.actor.ActorCell.invoke(ActorCell.scala:579)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
    at akka.dispatch.Mailbox.run(Mailbox.scala:229)
    at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
    at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

On https://github.com/akka/alpakka/pull/1565/commits/4c0989107856ed0dc206faea96339696bd82c62b this error shows *sometimes* during `testOnly *.MqttSourceSpec -- -z unacked`.

The full log shows 
```
   1   │ 2019-05-10 14:47:15,856 INFO  [MqttSourceSpec-akka.actor.default-dispatcher-3] [akka.event.slf4j.Slf4jLogger]  Slf4jLogger started
   2   │ 2019-05-10 14:47:16,331 DEBUG [MqttSourceSpec-akka.actor.default-dispatcher-3] [docs.scaladsl.MqttSourceSpec]  sleeping 2 seconds to make sure we don't get more than expected
   3   │ 2019-05-10 14:47:16,503 DEBUG [MqttSourceSpec-akka.actor.default-dispatcher-16] [docs.scaladsl.MqttSourceSpec]  [client 1 received] Element: one-14:47:16.103
   4   │ 2019-05-10 14:47:16,505 DEBUG [MqttSourceSpec-akka.actor.default-dispatcher-2] [docs.scaladsl.MqttSourceSpec]  acked one-14:47:16.103
   5   │ 2019-05-10 14:47:16,509 DEBUG [MqttSourceSpec-akka.actor.default-dispatcher-2] [docs.scaladsl.MqttSourceSpec]  [client 1 received] Element: two-14:47:16.103
   6   │ 2019-05-10 14:47:16,510 DEBUG [MqttSourceSpec-akka.actor.default-dispatcher-2] [docs.scaladsl.MqttSourceSpec]  acked two-14:47:16.103
   7   │ 2019-05-10 14:47:16,511 DEBUG [MqttSourceSpec-akka.actor.default-dispatcher-14] [docs.scaladsl.MqttSourceSpec]  [client 1 received] Element: three-14:47:16.103
   8   │ 2019-05-10 14:47:18,335 DEBUG [MqttSourceSpec-akka.actor.default-dispatcher-16] [docs.scaladsl.MqttSourceSpec]  [client 1 received] Downstream finished.
   9   │ 2019-05-10 14:47:18,347 INFO  [MqttSourceSpec-akka.actor.default-dispatcher-2] [akka.actor.RepointableActorRef]  Message [akka.stream.alpakka.mqtt.streaming.impl.ClientConnector$ConnectionLost] without sender to Actor[akka://MqttSourceSpec/user/client-connector-1#-1279107321] was not delivered. [1] dead letters encountered. If this is
       │ not an expected behavior, then [Actor[akka://MqttSourceSpec/user/client-connector-1#-1279107321]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
  10   │ 2019-05-10 14:47:18,347 INFO  [MqttSourceSpec-akka.actor.default-dispatcher-2] [akka.actor.RepointableActorRef]  Message [akka.stream.alpakka.mqtt.streaming.impl.ClientConnector$ConnectionLost] without sender to Actor[akka://MqttSourceSpec/user/client-connector-1#-1279107321] was not delivered. [2] dead letters encountered. If this is
       │ not an expected behavior, then [Actor[akka://MqttSourceSpec/user/client-connector-1#-1279107321]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
  11   │ 2019-05-10 14:47:18,350 DEBUG [MqttSourceSpec-akka.actor.default-dispatcher-2] [docs.scaladsl.MqttSourceSpec]  sleeping 2 seconds to make sure we don't get more than expected
  12   │ 2019-05-10 14:47:18,367 DEBUG [MqttSourceSpec-akka.actor.default-dispatcher-2] [docs.scaladsl.MqttSourceSpec]  [client 2 received] Element: three-14:47:16.103
  13   │ 2019-05-10 14:47:18,368 DEBUG [MqttSourceSpec-akka.actor.default-dispatcher-2] [docs.scaladsl.MqttSourceSpec]  [client 2 received] Element: four-14:47:16.103
  14   │ 2019-05-10 14:47:18,368 DEBUG [MqttSourceSpec-akka.actor.default-dispatcher-3] [docs.scaladsl.MqttSourceSpec]  [client 2 received] Element: five-14:47:16.103
  15   │ 2019-05-10 14:47:20,351 DEBUG [MqttSourceSpec-akka.actor.default-dispatcher-16] [docs.scaladsl.MqttSourceSpec]  [client 2 received] Downstream finished.
  16   │ 2019-05-10 14:47:20,861 INFO  [MqttSourceSpec-akka.actor.default-dispatcher-15] [akka.actor.RepointableActorRef]  Message [akka.stream.alpakka.mqtt.streaming.impl.RemotePacketRouter$Unregister] without sender to Actor[akka://MqttSourceSpec/user/client-consumer-packet-id-allocator-0#906428085] was not delivered. [3] dead letters encount
       │ ered. If this is not an expected behavior, then [Actor[akka://MqttSourceSpec/user/client-consumer-packet-id-allocator-0#906428085]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
  17   │ 2019-05-10 14:47:25,859 ERROR [MqttSourceSpec-akka.actor.default-dispatcher-15] [akka.actor.OneForOneStrategy]  67108865
  18   │ java.lang.ArrayIndexOutOfBoundsException: 67108865
  19   │     at akka.stream.impl.fusing.GraphInterpreter.$anonfun$toSnapshot$5(GraphInterpreter.scala:688)
  20   │     at akka.stream.impl.fusing.GraphInterpreter.$anonfun$toSnapshot$5$adapted(GraphInterpreter.scala:688)
  21   │     at scala.collection.immutable.List.map(List.scala:282)
  22   │     at akka.stream.impl.fusing.GraphInterpreter.toSnapshot(GraphInterpreter.scala:688)
  23   │     at akka.stream.impl.fusing.GraphInterpreterShell.toSnapshot(ActorGraphInterpreter.scala:657)
  24   │     at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.$anonfun$applyOrElse$1(ActorGraphInterpreter.scala:767)
  25   │     at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
  26   │     at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:319)
  27   │     at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:975)
  28   │     at scala.collection.TraversableLike.map(TraversableLike.scala:233)
  29   │     at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
  30   │     at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
  31   │     at scala.collection.SetLike.map(SetLike.scala:100)
  32   │     at scala.collection.SetLike.map$(SetLike.scala:100)
  33   │     at scala.collection.AbstractSet.map(Set.scala:47)
  34   │     at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:767)
  35   │     at akka.actor.Actor.aroundReceive(Actor.scala:539)
  36   │     at akka.actor.Actor.aroundReceive$(Actor.scala:537)
  37   │     at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:664)
  38   │     at akka.actor.ActorCell.receiveMessage(ActorCell.scala:610)
  39   │     at akka.actor.ActorCell.invoke(ActorCell.scala:579)
  40   │     at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
  41   │     at akka.dispatch.Mailbox.run(Mailbox.scala:229)
  42   │     at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
  43   │     at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
  44   │     at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
  45   │     at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
  46   │     at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #26902

### CODE REVIEW

File: akka-stream/src/main/scala/akka/stream/impl/ActorMaterializerImpl.scala [hunk 1]
```diff
@@ -209,6 +214,28 @@ private[akka] class SubFusingActorMaterializerImpl(
...
+      implicit val scheduler = context.system.scheduler
+      val futureSnapshots: Iterable[Future[Option[StreamSnapshot]]] =
+        context.children.map(
+          child =>
+            retry(
+              { () =>
+                (child ? ActorGraphInterpreter.Snapshot).mapTo[StreamSnapshot].map(s => Some(s)).recover {
+                  case ex: AskTimeoutException
+                      if ex.getMessage
+                        .contains("had already been terminated") || context.child(child.path.name).isEmpty =>
```
Comment (patriknw) [inline akka-stream/src/main/scala/akka/stream/impl/ActorMaterializerImpl.scala]: accessing `context.child` from inside Future `recover`? can we retry all requests instead if one fails?

File: akka-stream/src/main/scala/akka/stream/impl/ActorMaterializerImpl.scala [hunk 2]
```diff
@@ -209,6 +214,28 @@ private[akka] class SubFusingActorMaterializerImpl(
...
+      // the child/stream stopped, and we do retry
+      implicit val timeout: Timeout = 1.second
+      implicit val scheduler = context.system.scheduler
+      val futureSnapshots: Iterable[Future[Option[StreamSnapshot]]] =
+        context.children.map(
+          child =>
+            retry(
+              { () =>
+                (child ? ActorGraphInterpreter.Snapshot).mapTo[StreamSnapshot].map(s => Some(s)).recover {
+                  case ex: AskTimeoutException
```
Comment (patriknw) [inline akka-stream/src/main/scala/akka/stream/impl/ActorMaterializerImpl.scala]: can this fail for other reasons than timeout? if not, I don't see how the `retry` comes into the picture

File: akka-stream/src/main/scala/akka/stream/impl/ActorMaterializerImpl.scala (hunk 1 above)
Comment (johanandren) [reply akka-stream/src/main/scala/akka/stream/impl/ActorMaterializerImpl.scala]: Ups, had bad luck while thinking there... 

Yeah, retry everything from start should work as long as the set of children isn't rapidly changing, then it'l just continue failing.

File: akka-stream/src/main/scala/akka/stream/impl/ActorMaterializerImpl.scala (hunk 2 above)
Comment (johanandren) [reply akka-stream/src/main/scala/akka/stream/impl/ActorMaterializerImpl.scala]: Yes, that'd be an actual timeout. Will rework and change.

File: akka-stream/src/main/scala/akka/stream/impl/ActorMaterializerImpl.scala [hunk 3]
```diff
@@ -209,10 +214,29 @@ private[akka] class SubFusingActorMaterializerImpl(
...
+    implicit val timeout: Timeout = 1.second
+    def takeSnapshot() = {
+      val futureSnapshots =
+        context.children.toList.map(child => (child ? ActorGraphInterpreter.Snapshot).mapTo[StreamSnapshot])
+      Future.sequence(futureSnapshots)
+    }
+
+    // If the timeout hits it is likely because one of the streams stopped between looking at the list
+    // of children and asking it for a snapshot. We retry the entire snapshot in that case
+    retry(() => takeSnapshot(), 3, 200.millis)
```
Comment (patriknw) [inline akka-stream/src/main/scala/akka/stream/impl/ActorMaterializerImpl.scala]: what is the purpose of delay between retries? things are moving and we hope it's more stable after a while?

File: akka-stream/src/main/scala/akka/stream/snapshot/MaterializerState.scala [hunk 4]
```diff
@@ -41,11 +41,9 @@ object MaterializerState {
   @InternalApi
   private[akka] def requestFromSupervisor(supervisor: ActorRef)(
       implicit ec: ExecutionContext): Future[immutable.Seq[StreamSnapshot]] = {
-    // FIXME arbitrary timeout
+    // Arbitrary timeout: operation should always be quick, when it times out it will be because the materializer stopped
     implicit val timeout: Timeout = 10.seconds
-    (supervisor ? StreamSupervisor.GetChildren)
-      .mapTo[StreamSupervisor.Children]
-      .flatMap(msg => Future.sequence(msg.children.toVector.map(requestFromChild)))
+    (supervisor ? StreamSupervisor.GetChildrenSnapshots).mapTo[StreamSupervisor.ChildrenSnapshots].map(_.seq)
```
Comment (patriknw) [inline akka-stream/src/main/scala/akka/stream/snapshot/MaterializerState.scala]: ok, if all retry attempts fail that will send back a `Status.Failure`, which fail this outer Future

**Review by patriknw — APPROVED** [review]
LGTM

File: akka-stream/src/main/scala/akka/stream/impl/ActorMaterializerImpl.scala (hunk 3 above)
Comment (johanandren) [reply akka-stream/src/main/scala/akka/stream/impl/ActorMaterializerImpl.scala]: That was my thinking but thinking about it again I don't the original thinking was very good thinking.

Comment (patriknw) [reply akka-stream/src/main/scala/akka/stream/impl/ActorMaterializerImpl.scala]: yup, probably not needed because it has already waited 1.second (AskTimeout)

File: akka-stream-tests/src/test/scala/akka/stream/snapshot/MaterializerStateSpec.scala [hunk 5]
```diff
@@ -16,16 +17,85 @@ class MaterializerStateSpec extends StreamSpec {
...
     "snapshot a running stream" in {
       implicit val mat = ActorMaterializer()
-      Source.maybe[Int].map(_.toString).zipWithIndex.runWith(Sink.seq)
+      try {
+        Source.maybe[Int].map(_.toString).zipWithIndex.runWith(Sink.seq)
 
-      awaitAssert({
-        val snapshot = MaterializerState.streamSnapshots(mat).futureValue
+        awaitAssert({
+          val snapshot = MaterializerState.streamSnapshots(mat).futureValue
```
Comment (chbatey) [inline akka-stream-tests/src/test/scala/akka/stream/snapshot/MaterializerStateSpec.scala]: TIL that this existed :)

File: akka-stream-tests/src/test/scala/akka/stream/snapshot/MaterializerStateSpec.scala [hunk 6]
```diff
@@ -16,16 +17,85 @@ class MaterializerStateSpec extends StreamSpec {
...
+          .single("one")
+          .concat(Source.maybe[String]) // make sure we leave it running
+          .runWith(probe)
+        out.requestNext("one")
+        awaitAssert({
+          val snapshot = MaterializerState.streamSnapshots(mat).futureValue
+          snapshot should have size (1)
+          snapshot.head.activeInterpreters should have size (1)
+          snapshot.head.activeInterpreters.head.stoppedLogics should have size (2) // Source.single and a detach
+        }, 3.seconds)
```
Comment (chbatey) [inline akka-stream-tests/src/test/scala/akka/stream/snapshot/MaterializerStateSpec.scala]: why not remainingOrDefault?

File: akka-stream/src/main/scala/akka/stream/impl/ActorMaterializerImpl.scala [hunk 7]
```diff
@@ -209,10 +214,29 @@ private[akka] class SubFusingActorMaterializerImpl(
       context.asInstanceOf[ActorCell].removeFunctionRef(ref)
     case GetChildren =>
       sender() ! Children(context.children.toSet)
+    case GetChildrenSnapshots =>
+      takeSnapshotsOfChildren().map(ChildrenSnapshots.apply _).pipeTo(sender())
```
Comment (chbatey) [inline akka-stream/src/main/scala/akka/stream/impl/ActorMaterializerImpl.scala]: `_` not needed?

File: akka-stream/src/main/scala/akka/stream/impl/ActorMaterializerImpl.scala [hunk 8]
```diff
@@ -177,6 +179,9 @@ private[akka] class SubFusingActorMaterializerImpl(
       extends DeadLetterSuppression
       with NoSerializationVerificationNeeded
 
+  case object GetChildrenSnapshots
```
Comment (chbatey) [inline akka-stream/src/main/scala/akka/stream/impl/ActorMaterializerImpl.scala]: NoSerialization and dead letter supression as used in ask?

**Review by chbatey — APPROVED** [review]
LGTM based on my limited knowledge of this area

File: akka-stream/src/main/scala/akka/stream/impl/ActorMaterializerImpl.scala (hunk 7 above)
Comment (johanandren) [reply akka-stream/src/main/scala/akka/stream/impl/ActorMaterializerImpl.scala]: I think it is for 2.13
