### PR TITLE
=act #16327 fix blockOn requirement failure

### LINKED ISSUE #16327: IllegalStateException in akka.dispatch.BatchingExecutor$Batch.run
Our application provides REST interface to database storage. User uploads data via HTTP interface, we store it to JDBC and then do some additional logic that processes uploaded data. HTTP interface is implemented via Spray 1.3.2; Akka version 2.3.6 (but I have seen this problem in previous 2.3.x). We do not use akka-streams.

We create and then stop an some number of actors per upload; also we use transformation operations on Future in context dispatcher.

Sometimes we see this exception in our logs:

```
[incident-daemon-system-akka.actor.default-dispatcher-233] ERROR akka.dispatch.Dispatcher - exception in sameThreadExecutionContext (a.d.Dispatcher)
java.lang.IllegalStateException: exception in sameThreadExecutionContext
        at akka.dispatch.ExecutionContexts$sameThreadExecutionContext$.reportFailure(Future.scala:76)
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
        at scala.concurrent.Promise$class.complete(Promise.scala:55)
        at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67)
        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82)
        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
        at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.IllegalArgumentException: requirement failed
        at scala.Predef$.require(Predef.scala:207)
        at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:55)
        at akka.dispatch.ExecutionContexts$sameThreadExecutionContext$.unbatchedExecute(Future.scala:74)
        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:76)
        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82)
        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
        at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58)
        at akka.dispatch.ExecutionContexts$sameThreadExecutionContext$.unbatchedExecute(Future.scala:74)
        at akka.dispatch.BatchingExecutor$class.execute(BatchingExecutor.scala:110)
        at akka.dispatch.ExecutionContexts$sameThreadExecutionContext$.execute(Future.scala:73)
        ... 19 common frames omitted
```

We see this exception when client continuously uploads large number of objects (about a million). I do not know the way to reproduce this bug (other that posting a lot of data and waiting before the problem occurs).

### PR DESCRIPTION
**Pull request by rkuhn**
The problem was that resubmitUnbatched can destroy the contents of
parentBlockContext, leading to the observed requirement failure in
blockOn.

fixes #16327 

needs forward-port to master

### CODE REVIEW

**Comment by patriknw** [comment]
I don't know why pr validation is not picking up this.

**Comment by patriknw** [comment]
PLS BUILD

File: akka-actor/src/main/scala/akka/dispatch/BatchingExecutor.scala [hunk 1]
```diff
@@ -89,21 +89,22 @@ private[akka] trait BatchingExecutor extends Executor {
...
-          parentBlockContext = null
-        }
+        } finally _tasksLocal.remove()
+        parentBlockContext = null
       }
     }
 
     override def blockOn[T](thunk: ⇒ T)(implicit permission: CanAwait): T = {
+      // need to rescue the parent BC before re-running this Batch
+      val parent = parentBlockContext
```
Comment (viktorklang) [inline akka-actor/src/main/scala/akka/dispatch/BatchingExecutor.scala]: `require(parent ne null)`?

File: akka-actor/src/main/scala/akka/dispatch/BatchingExecutor.scala [hunk 2]
```diff
@@ -89,21 +89,22 @@ private[akka] trait BatchingExecutor extends Executor {
...
+      parentBlockContext = null
```
Comment (viktorklang) [inline akka-actor/src/main/scala/akka/dispatch/BatchingExecutor.scala]: Haven't swapped this functionality into my head yet (espresso still not in blood stream), why is it safe/desirable to null it out here?

**Comment by drewhk** [comment]
You said that this is deterministic under certain scenarios. Can you add a test-case?

**Comment by rkuhn** [comment]
@drewhk Right, I only realized this after pushing the PR, I’ll see what I can do (and if my hunch was right).

File: akka-actor/src/main/scala/akka/dispatch/BatchingExecutor.scala (hunk 1 above)
Comment (rkuhn) [inline akka-actor/src/main/scala/akka/dispatch/BatchingExecutor.scala]: Nope, that line would not help any: either we have a bug that needs fixing, and then an NPE would tell the same story, or we don’t have a bug.

File: akka-actor/src/main/scala/akka/dispatch/BatchingExecutor.scala (hunk 2 above)
Comment (rkuhn) [inline akka-actor/src/main/scala/akka/dispatch/BatchingExecutor.scala]: To make a clean slate: resubmitUnbatched may or may not schedule this Batch to run, so don’t retain a reference in either case.

File: akka-actor/src/main/scala/akka/dispatch/BatchingExecutor.scala (hunk 1 above)
Comment (viktorklang) [inline akka-actor/src/main/scala/akka/dispatch/BatchingExecutor.scala]: Yes, and no. an assertion documents intent. An NPe does not.

File: akka-actor/src/main/scala/akka/dispatch/BatchingExecutor.scala [hunk 3]
```diff
@@ -89,21 +89,22 @@ private[akka] trait BatchingExecutor extends Executor {
...
           case t: Throwable ⇒
+            parentBlockContext = null
             resubmitUnbatched()
             throw t
-        } finally {
-          _tasksLocal.remove()
-          parentBlockContext = null
-        }
+        } finally _tasksLocal.remove()
+        parentBlockContext = null
```
Comment (viktorklang) [inline akka-actor/src/main/scala/akka/dispatch/BatchingExecutor.scala]: Is it intentional to put this outside of the `finally` and if so, that might be good to document on this line.

File: akka-actor/src/main/scala/akka/dispatch/BatchingExecutor.scala (hunk 2 above)
Comment (viktorklang) [inline akka-actor/src/main/scala/akka/dispatch/BatchingExecutor.scala]: Ok, that makes sense.

File: akka-actor/src/main/scala/akka/dispatch/BatchingExecutor.scala (hunk 1 above)
Comment (rkuhn) [inline akka-actor/src/main/scala/akka/dispatch/BatchingExecutor.scala]: Here I disagree: dereferencing `parent` clearly documents the intent that it is not assumed to be `null`, the code cannot possibly work without this, and the intended program semantics are that this is always non-`null`. We have countless uses of variables in our codebase that do not `require(x ne null)` before dereferencing `x`, why is this one different?

File: akka-actor/src/main/scala/akka/dispatch/BatchingExecutor.scala (hunk 3 above)
Comment (rkuhn) [inline akka-actor/src/main/scala/akka/dispatch/BatchingExecutor.scala]: Yes, very much intentional: we _must not_ modify `parentBlockContext` after `resubmitUnbatched()`, I’ll add a comment.

File: akka-actor/src/main/scala/akka/dispatch/BatchingExecutor.scala (hunk 1 above)
Comment (viktorklang) [inline akka-actor/src/main/scala/akka/dispatch/BatchingExecutor.scala]: That is a very fair objection, given the impact of bugs in this code I think extra precaution/clarity/design intent makes sense. But you're the boss :)

**Comment by ktoso** [comment]
PLS BUILD

**Comment by rkuhn** [comment]
Please re-review, the fix is completely different (the other was not sufficient) and there is a test now.

File: akka-actor/src/main/scala/akka/dispatch/BatchingExecutor.scala [hunk 4]
```diff
@@ -78,22 +78,23 @@ private[akka] trait BatchingExecutor extends Executor {
...
   private[this] final class BlockableBatch extends AbstractBatch with BlockContext {
-    private var parentBlockContext: BlockContext = _
     // this method runs in the delegate ExecutionContext's thread
     override final def run(): Unit = {
       require(_tasksLocal.get eq null)
       _tasksLocal set this // Install ourselves as the current batch
-      val prevBlockContext = BlockContext.current
+      val prevBlockContext = _blockContext.get
+      _blockContext.set(BlockContext.current)
       BlockContext.withBlockContext(this) {
```
Comment (viktorklang) [inline akka-actor/src/main/scala/akka/dispatch/BatchingExecutor.scala]: Doesn't `withBlockContext` already handle `prev` itself?

Also, when you fix this bug you'll want to forward-port it to Scala: https://github.com/scala/scala/blob/2.11.x/src/library/scala/concurrent/BatchingExecutor.scala

Comment (rkuhn) [inline akka-actor/src/main/scala/akka/dispatch/BatchingExecutor.scala]: Well, we cannot access the stack frame of `withBlockContext`, so we cannot use that knowledge here AFAICS. And yes, Scala needs to be fixed as well. BTW, why doesn’t the Scala version have the non-Blockable version as well?

Comment (viktorklang) [inline akka-actor/src/main/scala/akka/dispatch/BatchingExecutor.scala]: TBH I don't know right now, there were fixes made against the stdlib version. I think looking at the last changes to the Akka one and comparing that to the last cahnges to the Scala one could give a couple of hints as to what's most "current".

Comment (rkuhn) [inline akka-actor/src/main/scala/akka/dispatch/BatchingExecutor.scala]: Issue created: https://issues.scala-lang.org/browse/SI-9304

Comment (hepin1989) [inline akka-actor/src/main/scala/akka/dispatch/BatchingExecutor.scala]: DynamicVariable?

Comment (rkuhn) [inline akka-actor/src/main/scala/akka/dispatch/BatchingExecutor.scala]: All of these closure allocations make me sad. Perhaps, some day, we can optimize them away in the distant future, but it does not look like that today. It is a shame that the optimizer cannot be used due to binary compatibility constraints.

Comment (drewhk) [inline akka-actor/src/main/scala/akka/dispatch/BatchingExecutor.scala]: end users of Akka can use the optimizer though.

Comment (rkuhn) [inline akka-actor/src/main/scala/akka/dispatch/BatchingExecutor.scala]: … and by doing so opt out of binary compatibility, plus that won’t fix the internal usage of `getOrElse` or `DynamicVariable` in Akka.

Comment (drewhk) [inline akka-actor/src/main/scala/akka/dispatch/BatchingExecutor.scala]: > … and by doing so opt out of binary compatibility

Yes, that is their choice.

Comment (hepin1989) [inline akka-actor/src/main/scala/akka/dispatch/BatchingExecutor.scala]: thanks.

**Comment by patriknw** [comment]
LGTM

**Comment by drewhk** [comment]
LGTM

**Comment by rkuhn** [comment]
Failure due to me being surprised by `private[this] val` generating a public setter (!) and getter, added filters to MiMa for this.

**Comment by patriknw** [comment]
wat, isn't it better to use `private val` then. I know `private[this]` is more idiomatic scala, but...
