### PR TITLE
Typed deathpact supervision

### LINKED ISSUE #24488: DeathPactException cannot be supervised
When an actor watches another and does not handle the `Terminated` signal, it throws a `DeathPactException`, this is somewhat surprising for a user not handled by supervision, so 

```
Behaviors.supervise(watchingActor)
 .onFailure[DeathPactException](restart)
```

Does nothing, and instead the `watchingActor` stops.

Not sure if we can pull it off, but would be nice if it did work. Maybe also related to the adapters/ask transformations throwing vs supervision.

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #24488

Not quite sure this is a good idea...

### CODE REVIEW

File: akka-actor-typed/src/main/scala/akka/actor/typed/Behavior.scala [hunk 1]
```diff
@@ -320,8 +320,14 @@ object Behavior {
...
-  def interpretSignal[T](behavior: Behavior[T], ctx: ActorContext[T], signal: Signal): Behavior[T] =
-    interpret(behavior, ctx, signal)
+  def interpretSignal[T](behavior: Behavior[T], ctx: ActorContext[T], signal: Signal): Behavior[T] = {
+    val result = interpret(behavior, ctx, signal)
+    // we need to throw here to allow supervision of deathpact exception
+    signal match {
+      case Terminated(ref) if result == UnhandledBehavior ⇒ throw DeathPactException(ref)
+      case _ ⇒ result
+    }
+  }
```
Comment (johanandren) [inline akka-actor-typed/src/main/scala/akka/actor/typed/Behavior.scala]: This way, the `DPE` comes from inside the behavior stack, instead of from the `ActorAdapter` and is covered by supervision.

**Review by chbatey — APPROVED** [review]
LGTM

I don't have a strong opinion as to whether this is useful or whether not dealing with a Terminated you did a watch for is a programming bug.

**Review by patriknw — APPROVED** [review]
LGTM, this is rather consistent with the semantics in untyped. There it's only handled in the `defaultDecider` so if you install another strategy with another decider it will not be treated special.

One difference is that in untyped the default supervision is to restart, so it's less likely that one replaces the default supervision strategy in untyped.

In typed I guess `.onFailure[Throwable](SupervisorStrategy.restart))` will often be used, and that will also cause restart of `DeathPactException`.
