### PR TITLE
Exception from receiveRecover should stop the PersistentActor #24192

### LINKED ISSUE #24192: Exception from receiveRecover should stop the PersistentActor
Otherwise it will enter restart loop, with default supervision.

### PR DESCRIPTION
**Pull request by ryota-sakamoto**
fix #24192

### CODE REVIEW

**Comment by johanandren** [comment]
Test failure seems related

**Comment by ryota-sakamoto** [comment]
Thank you
I will add a test and fix

File: akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala [hunk 1]
```diff
@@ -459,7 +459,12 @@ private[persistence] trait Eventsourced extends Snapshotter with PersistenceStas
     }
 
     private val recoveryBehavior: Receive = {
-      val _receiveRecover = receiveRecover
+      val _receiveRecover = try receiveRecover catch {
+        case NonFatal(e) ⇒
+          try onRecoveryFailure(e, Some(e))
+          finally context.stop(self)
```
Comment (patriknw) [inline akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala]: Call `returnRecoveryPermit()` here.

File: akka-persistence/src/test/scala/akka/persistence/PersistentActorSpec.scala [hunk 2]
```diff
@@ -663,6 +663,18 @@ object PersistentActorSpec {
       case Cmd(d) ⇒ persist(Evt(d))(updateState)
     }
   }
+
+  class ExceptionActor(name: String) extends ExamplePersistentActor(name) {
+    override def receiveCommand = commonBehavior
+    override def receiveRecover = {
+      case _ ⇒ throw new Exception("boom")
```
Comment (patriknw) [inline akka-persistence/src/test/scala/akka/persistence/PersistentActorSpec.scala]: use `TestException` instead, to avoid the scary stack traces in the log

File: akka-persistence/src/test/scala/akka/persistence/PersistentActorSpec.scala [hunk 3]
```diff
@@ -663,6 +663,18 @@ object PersistentActorSpec {
...
+    }
+  }
+
+  class ExceptionActor2(name: String) extends ExamplePersistentActor(name) {
+    override def receiveCommand = commonBehavior
+    override def receiveRecover = throw new Exception("boom")
```
Comment (patriknw) [inline akka-persistence/src/test/scala/akka/persistence/PersistentActorSpec.scala]: TestException

File: akka-persistence/src/test/scala/akka/persistence/RecoveryPermitterSpec.scala [hunk 4]
```diff
@@ -169,11 +169,6 @@ class RecoveryPermitterSpec extends PersistenceSpec(ConfigFactory.parseString(
       val persistentActor = system.actorOf(testProps("p3", p3.ref, throwFromRecoveryCompleted = true))
       p3.expectMsg(RecoveryCompleted)
       p3.expectMsg("postStop")
-      // it's restarting
-      (1 to 5).foreach { _ ⇒
-        p3.expectMsg(RecoveryCompleted)
-        p3.expectMsg("postStop")
-      }
```
Comment (patriknw) [inline akka-persistence/src/test/scala/akka/persistence/RecoveryPermitterSpec.scala]: Why was this changed? I can't see that something in the implementation was changed for this test case. Here the exception is thrown inside the Receive, not when creating the Receive.

File: akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala (hunk 1 above)
Comment (patriknw) [reply akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala]: When looking at the code in Eventsourced.scala I think there are a few more places where we stop without returning the permit. I will follow up on that in a separate PR.

**Review by patriknw — CHANGES_REQUESTED** [review]

**Comment by ktoso** [comment]
Refs #24192 (please include comment with issue number to establish link of PR to the issue)

**Comment by ryota-sakamoto** [comment]
Thanks review
I will fix

**Comment by ryota-sakamoto** [comment]
@johanandren @patriknw 
Hi.I am fixing test now.
I have a question.

Exception from RecoveryCompleted.
This is restart loop.
```Scala
class ExceptionActor(name: String) extends ExamplePersistentActor(name) {
    override def receiveCommand = commonBehavior
    override def receiveRecover = {
      case RecoveryCompleted ⇒ throw new TestException("boom")
      case _                 ⇒
    }
  }
```
Where does it catch the exception?

in below case?
```Scala
case RecoverySuccess(highestSeqNr) ⇒
```

or below catch?
```Scala
} catch {
        case NonFatal(e) ⇒
          returnRecoveryPermit()
          throw e
      }
```

**Comment by patriknw** [comment]
it will be caught in https://github.com/akka/akka/blob/master/akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala#L585
and then re-throws. Handled by ordinary supervision, i.e. restart by default.

I think that is fine. It's like you would throw for each incoming command, also not a good idea.

**Comment by ryota-sakamoto** [comment]
Thank you for answer

File: akka-persistence/src/test/scala/akka/persistence/RecoveryPermitterSpec.scala (hunk 4 above)
Comment (ryota-sakamoto) [reply akka-persistence/src/test/scala/akka/persistence/RecoveryPermitterSpec.scala]: Sorry .I had misunderstood.

**Review by patriknw — APPROVED** [review]
LGTM

**Review by johanandren — APPROVED** [review]
LGTM, thanks!
