### PR TITLE
Merge grabs empty input

### LINKED ISSUE #21138: Grabbing from closed input port in Merge
```
requirement failed: Cannot get element from already empty input port (Merge.in1)
java.lang.IllegalArgumentException: requirement failed: Cannot get element from already empty input port (Merge.in1)
at scala.Predef$.require(Predef.scala:224)
at akka.stream.stage.GraphStageLogic.grab(GraphStage.scala:381)
at akka.stream.scaladsl.Merge$$anon$1.akka$stream$scaladsl$Merge$$anon$$dequeueAndDispatch(Graph.scala:65)
```

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #21138

### CODE REVIEW

File: akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowMergeSpec.scala [hunk 1]
```diff
@@ -96,5 +96,30 @@ class FlowMergeSpec extends BaseTwoStreamsSetup {
...
+      up1.ensureSubscription()
+      up2.ensureSubscription()
+      down.ensureSubscription()
+
+      up1.expectRequest()
+      up2.expectRequest()
+      up1.sendNext(7)
+      up2.sendNext(8)
+      up2.sendComplete()
+      down.request(1)
```
Comment (drewhk) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowMergeSpec.scala]: there is some race here, between the complete and the request right?

Comment (johanandren) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowMergeSpec.scala]: Yeah, `8` comes in through `in2` which gets queued as out is not ready, it then cancels which closes `in2`, but the it stays in the queue and as soon as down requests an element it gets `in2` from the queue and tries to grab from it.

Comment (drewhk) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowMergeSpec.scala]: well, I mean in the test ;)

Comment (johanandren) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowMergeSpec.scala]: Ah, yeah, maybe, did fail consistently on my machine before I fixed the bug though. Not sure how I can make the test non-racey, you have an idea?

Comment (johanandren) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowMergeSpec.scala]: I mean, I'd have to touch the internals of the stage somehow, to know that the request has been handled before sending the complete?

Comment (drewhk) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowMergeSpec.scala]: You can't really enforce non-racyness here :( In test where it mattered I had to add a sleep. Since this test will not fail no matter how the race works out, I guess it is fine to leave it as is, maybe add a comment.

File: akka-stream/src/main/scala/akka/stream/scaladsl/Graph.scala [hunk 2]
```diff
@@ -60,11 +59,21 @@ final class Merge[T] private (val inputPorts: Int, val eagerComplete: Boolean) e
...
+    @tailrec
     private def dequeueAndDispatch(): Unit = {
       val in = pendingQueue.dequeue()
-      push(out, grab(in))
-      if (upstreamsClosed && !pending) completeStage()
-      else tryPull(in)
+      if (in == null) {
+        // in is null if we reached the end of the queue
+        if (upstreamsClosed) completeStage()
+      } else if (isAvailable(in)) {
```
Comment (drewhk) [inline akka-stream/src/main/scala/akka/stream/scaladsl/Graph.scala]: not `!isClosed(in)`?

File: akka-stream/src/main/scala/akka/stream/scaladsl/Graph.scala [hunk 3]
```diff
@@ -60,11 +59,21 @@ final class Merge[T] private (val inputPorts: Int, val eagerComplete: Boolean) e
...
+        push(out, grab(in))
+        if (upstreamsClosed && !pending) completeStage()
+        else tryPull(in)
```
Comment (drewhk) [inline akka-stream/src/main/scala/akka/stream/scaladsl/Graph.scala]: no need to tryPull, you can safely pull here because of isAvailable(in).

File: akka-stream/src/main/scala/akka/stream/scaladsl/Graph.scala (hunk 2 above)
Comment (johanandren) [inline akka-stream/src/main/scala/akka/stream/scaladsl/Graph.scala]: Hmm. I used this since the original error was "trying to grab from empty in". Maybe close is more clear.

Comment (drewhk) [inline akka-stream/src/main/scala/akka/stream/scaladsl/Graph.scala]: ah, ok, then this might be the right one, since this implies grab() is safe

Comment (johanandren) [inline akka-stream/src/main/scala/akka/stream/scaladsl/Graph.scala]: I changed it as it being closed is the reason for discarding it when going through the queue.

**Comment by patriknw** [comment]
LGTM

**Comment by johanandren** [comment]
PLS BUILD

**Comment by johanandren** [comment]
(likely unrelated jenkins-slowness related failures)

**Comment by drewhk** [comment]
LGTM

**Comment by johanandren** [comment]
Hmm. Seems I broke something because it's the same test failures again.
