### PR TITLE
Race condition fix for Test{Sink/Source}Stage

### LINKED ISSUE #20737: FAILED: OutputStreamSourceSpec
https://jenkins.akka.io:8498/job/akka-nightly/3392/consoleFull

```
[info] - must throw IOException when writing to the stream after the subscriber has cancelled the reactive stream *** FAILED *** (37 milliseconds)
[info]   Expected exception java.lang.Exception to be thrown, but no exception was thrown. (OutputStreamSourceSpec.scala:161)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:495)
[info]   at org.scalatest.Assertions$.newAssertionFailedException(Assertions.scala:1538)
[info]   at org.scalatest.Assertions$.checkExpectedException(Assertions.scala:1582)
[info]   at org.scalatest.words.ResultOfTheTypeInvocation.thrownBy(ResultOfTheTypeInvocation.scala:38)
```

### PR DESCRIPTION
**Pull request by johanandren**
Hopefully fixes #20737

Let's see what you think of this. 

My thinking: there was a race in the TestSinkStage/TestSourceStage where it would signal to the probe that it finished, canceled etc before it actually called the callback on the stage, so that should cause a race when used like in `OutputStreamSourceSpec` which does:

```
s.cancel()
sourceProbe.expectMsg(GraphStageMessages.DownstreamFinish)
the[Exception] thrownBy outputStream.write(bytesArray) shouldBe a[IOException]
```

We could get the `DownstreamFinish` before it actually had happened. I'm guessing that the reversed order is what we always want.

### CODE REVIEW

File: akka-stream-testkit/src/main/scala/akka/stream/testkit/TestGraphStage.scala [hunk 1]
```diff
@@ -40,22 +49,38 @@ private[testkit] class TestSinkStage[T, M](
         inHandler.onPush()
```
Comment (patriknw) [inline akka-stream-testkit/src/main/scala/akka/stream/testkit/TestGraphStage.scala]: what about `Push`? should we always send to the probe afterwards?

Comment (johanandren) [inline akka-stream-testkit/src/main/scala/akka/stream/testkit/TestGraphStage.scala]: I couldn't decide about push and pull and what it means there so opinions are welcome.

**Comment by ktoso** [comment]
PLS BUILD

**Comment by johanandren** [comment]
Previous failure was mima + random.

**Comment by ktoso** [comment]
I missed the mima thing, sorry - please fix the compatibility then :)

**Comment by drewhk** [comment]
I am not sure if this fixes anything. If the two events are in race, but independent, then both assertions will succeed independently of order. Am I missing something?

**Comment by johanandren** [comment]
When the test source/sink emits the `DownstreamFinish` before calling the actual stage logic that will make the `sourceProbe.expectMsg(GraphStageMessages.DownstreamFinish)` pass, possibly before the stage has had the chance to actually do it's thing with the input/outputstream. Signalling `DownstreamFinish` after the stage callback will let the stage react on the finish first and will make the assertion always work as expected.

**Comment by johanandren** [comment]
rebased on top of master

File: akka-stream-testkit/src/main/scala/akka/stream/testkit/TestGraphStage.scala (hunk 1 above)
Comment (patriknw) [inline akka-stream-testkit/src/main/scala/akka/stream/testkit/TestGraphStage.scala]: if we don't have a reason for doing it differently I think there can be some value in doing it in the same way for all of them

Comment (johanandren) [inline akka-stream-testkit/src/main/scala/akka/stream/testkit/TestGraphStage.scala]: Ok, will update this one as well then!

**Comment by ktoso** [comment]
@johanandren's rationale seems sound, LGTM I guess hm.

**Comment by johanandren** [comment]
What about this? Will likely fail waiting probes nicely with an unexpected message telling us that the stage failed and only sends the stage event messages if the stage callbacks succeeds.

**Comment by johanandren** [comment]
rebased on master

**Review by drewhk — APPROVED** [review]
please rebase and merge
