### PR TITLE
Harden RateTransformationDocSpec: Use test patience rather than hadcode

### LINKED ISSUE #26262: Failed: RateTransformationDocSpec
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/14552/testReport/junit/docs.stream/RateTransformationDocSpec/extrapolate_should_send_seed_first/

```
java.util.concurrent.TimeoutException: Futures timed out after [100 milliseconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
	at scala.concurrent.Await$.$anonfun$result$1(package.scala:219)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
	at scala.concurrent.Await$.result(package.scala:146)
	at docs.stream.RateTransformationDocSpec.$anonfun$new$17(RateTransformationDocSpec.scala:91)
```

### PR DESCRIPTION
**Pull request by chbatey**
Fixes #26262

### CODE REVIEW

File: akka-docs/src/test/scala/docs/stream/RateTransformationDocSpec.scala [hunk 1]
```diff
@@ -88,7 +89,7 @@ class RateTransformationDocSpec extends AkkaSpec {
       .grouped(10)
       .runWith(Sink.head)
 
-    val extrapolated = Await.result(fut, 100.millis)
+    val extrapolated = fut.futureValue
```
Comment (patriknw) [inline akka-docs/src/test/scala/docs/stream/RateTransformationDocSpec.scala]: `remainingOrDefault` would also have been ok

**Review by patriknw — APPROVED** [review]
LGTM

**Review by johanandren — APPROVED** [review]
LGTM
