### PR TITLE
Bugfix and cleanup of UnfoldResourceAsync 

### LINKED ISSUE #24119: Failed: UnfoldResourceAsyncSourceSpec
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/10946/testReport/junit/akka.stream.scaladsl/UnfoldResourceAsyncSourceSpec/Unfold_Resource_Async_Source_must_close_resource_when_stream_is_abruptly_terminated/

```
java.util.concurrent.TimeoutException: Timeout of 3 seconds with time factor of 1.0
	at akka.testkit.TestLatch.ready(TestLatch.scala:41)
	at akka.testkit.TestLatch.ready(TestLatch.scala:26)
	at scala.concurrent.Await$$anonfun$ready$1.apply(package.scala:169)
	at scala.concurrent.Await$$anonfun$ready$1.apply(package.scala:169)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.Await$.ready(package.scala:169)
	at akka.stream.scaladsl.UnfoldResourceAsyncSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$12.apply(UnfoldResourceAsyncSourceSpec.scala:281)
	at akka.stream.scaladsl.UnfoldResourceAsyncSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$12.apply(UnfoldResourceAsyncSourceSpec.scala:263)
```

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #24119

### CODE REVIEW

File: akka-stream/src/main/scala/akka/stream/impl/UnfoldResourceSourceAsync.scala [hunk 1]
```diff
@@ -27,83 +26,86 @@ import scala.util.control.NonFatal
...
+          } catch errorHandler
+        case None ⇒
+        // we got a pull but there is no connection, we are either
+        // currently connecting/reconnecting and then the read will be triggered when connection completes,
+        // or shutting down and then the pull does not matter anyway
       }
 
-    override def onDownstreamFinish(): Unit = closeStage()
-
-    private def closeAndThen(f: () ⇒ Unit): Unit = {
```
Comment (johanandren) [inline akka-stream/src/main/scala/akka/stream/impl/UnfoldResourceSourceAsync.scala]: I think this abstraction just made the logic harder to follow, so I removed it.

File: akka-stream/src/main/scala/akka/stream/impl/UnfoldResourceSourceAsync.scala [hunk 2]
```diff
@@ -27,83 +26,86 @@ import scala.util.control.NonFatal
...
-      val closedCallback = getAsyncCallback[Try[Done]] {
-        case scala.util.Success(_) ⇒
-          open = false
-          f()
-        case scala.util.Failure(t) ⇒
-          open = false
-          failStage(t)
-      }
+    override def postStop(): Unit = {
+      if (state.isDefined) close(state.get)
```
Comment (johanandren) [inline akka-stream/src/main/scala/akka/stream/impl/UnfoldResourceSourceAsync.scala]: We don't wait for close here, this should be the actual bug fix guaranteeing that we always close the stage (old logic did incorrect dance with async callback inside `closeStage`/`closeAndThen`)

File: akka-stream/src/main/scala/akka/stream/impl/UnfoldResourceSourceAsync.scala [hunk 3]
```diff
@@ -27,83 +26,86 @@ import scala.util.control.NonFatal
...
-      try {
-        create().onComplete(createdCallback.invoke)
-      } catch {
-        case NonFatal(ex) ⇒ failStage(ex)
-      }
-    }
-
-    private def onResourceReady(f: (S) ⇒ Unit): Unit = resource.future.foreach(f)
+    private lazy val decider = inheritedAttributes.get[SupervisionStrategy].map(_.decider).getOrElse(Supervision.stoppingDecider)
+    private implicit def ec = ActorMaterializerHelper.downcast(materializer).system.dispatcher
```
Comment (johanandren) [inline akka-stream/src/main/scala/akka/stream/impl/UnfoldResourceSourceAsync.scala]: I'm not convinced that no future code would throw in this stage, so better not use the same-thread one

File: akka-stream/src/main/scala/akka/stream/impl/UnfoldResourceSourceAsync.scala [hunk 4]
```diff
@@ -27,83 +26,86 @@ import scala.util.control.NonFatal
...
-        })
+    private def restartResource(): Unit = {
+      state match {
+        case Some(resource) ⇒
+          // wait for the resource to close before restarting
+          close(resource).onComplete(getAsyncCallback[Try[Done]] {
+            case Success(Done) ⇒
+              createResource()
+            case Failure(ex) ⇒ errorHandler(ex)
+          }.invoke)
```
Comment (johanandren) [inline akka-stream/src/main/scala/akka/stream/impl/UnfoldResourceSourceAsync.scala]: Restart should be seldom  enough that it is fine to create a async-callback each time

File: akka-stream/src/main/scala/akka/stream/impl/UnfoldResourceSourceAsync.scala (hunk 2 above)
Comment (chbatey) [inline akka-stream/src/main/scala/akka/stream/impl/UnfoldResourceSourceAsync.scala]: Could be written as   `state.foreach(close(_))` rather than a `get` but up to you

**Review by chbatey — APPROVED** [review]
Looks a lot better, one Q and one Nit

File: akka-stream/src/main/scala/akka/stream/impl/UnfoldResourceSourceAsync.scala (hunk 2 above)
Comment (johanandren) [reply akka-stream/src/main/scala/akka/stream/impl/UnfoldResourceSourceAsync.scala]: Yeah, I guess that would be fine here, stuck in saving-the-allocation-mode

File: akka-stream/src/main/scala/akka/stream/impl/UnfoldResourceSourceAsync.scala [hunk 5]
```diff
@@ -27,83 +26,86 @@ import scala.util.control.NonFatal
...
+    override def preStart(): Unit = createResource()
+
+    override def onPull(): Unit =
+      state match {
+        case Some(resource) ⇒
+          try {
+            readData(resource).onComplete(readCallback)
+          } catch errorHandler
+        case None ⇒
+        // we got a pull but there is no connection, we are either
```
[the remark this answers is not in the document]
Comment (johanandren) [reply akka-stream/src/main/scala/akka/stream/impl/UnfoldResourceSourceAsync.scala]: Ah, I renamed all inner access to resource, but forgot this comment. I'll fix.

File: akka-stream/src/main/scala/akka/stream/impl/UnfoldResourceSourceAsync.scala [hunk 6]
```diff
@@ -27,83 +26,86 @@ import scala.util.control.NonFatal
...
 
-    val errorHandler: PartialFunction[Throwable, Unit] = {
+    private val errorHandler: PartialFunction[Throwable, Unit] = {
       case NonFatal(ex) ⇒ decider(ex) match {
         case Supervision.Stop ⇒
-          onResourceReady(close(_))
           failStage(ex)
-        case Supervision.Restart ⇒ restartState()
+        case Supervision.Restart ⇒ restartResource()
         case Supervision.Resume  ⇒ onPull()
```
[the remark this answers is not in the document]
Comment (johanandren) [reply akka-stream/src/main/scala/akka/stream/impl/UnfoldResourceSourceAsync.scala]: Can only happen when we pulled and that failed and therefore we should always be able to pull/push here.

File: akka-stream/src/main/scala/akka/stream/impl/UnfoldResourceSourceAsync.scala [hunk 7]
```diff
@@ -27,83 +26,86 @@ import scala.util.control.NonFatal
...
+            case Some(resource) ⇒
+              close(resource).onComplete(getAsyncCallback[Try[Done]] {
+                case Success(Done) ⇒ completeStage()
+                case Failure(ex)   ⇒ failStage(ex)
+              }.invoke)
+              state = None
+
+            case None ⇒
+              // cannot happen, but for good measure
+              throw new IllegalStateException("Reached end of data but there is no connection")
```
Comment (2m) [inline akka-stream/src/main/scala/akka/stream/impl/UnfoldResourceSourceAsync.scala]: Here also s/connection/resource/

File: akka-stream-tests/src/test/scala/akka/stream/scaladsl/UnfoldResourceAsyncSourceSpec.scala [hunk 8]
```diff
@@ -245,6 +245,64 @@ class UnfoldResourceAsyncSourceSpec extends StreamSpec(UnboundedMailboxConfig) {
...
+          else Future.failed(TE("start-error")),
+        reader ⇒ throw TE("read-error"),
+        _ ⇒ Future.successful(Done)
+      ).withAttributes(ActorAttributes.supervisionStrategy(Supervision.restartingDecider))
+        .runWith(Sink.fromSubscriber(out))
+
+      out.request(1)
+      out.expectError().getMessage should ===("start-error")
+    }
+
```
Comment (chbatey) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/UnfoldResourceAsyncSourceSpec.scala]: Nice :+1:

**Review by patriknw — APPROVED** [review]
LGTM
