### PR TITLE
Java flow dsl lower bounds

### LINKED ISSUE #24368: Lower type bounds in Java flow DSL not working
The following java code should not compile in my opinion, but it does:

    import akka.Done;
    import akka.NotUsed;
    import akka.actor.ActorSystem;
    import akka.stream.ActorMaterializer;
    import akka.stream.javadsl.Source;
    
    import java.util.concurrent.CompletionStage;
    import java.util.concurrent.ExecutionException;
    
    public class AkkaPlayground {
    
        public static void main(String[] args) throws ExecutionException, InterruptedException {
            Source<String, NotUsed> stringSource = Source.single("");
            Source<Integer, NotUsed> intSource = Source.single(1);
    
            Source<Integer, NotUsed> shouldNotBePossible =
                    stringSource.mergeSorted(intSource, Integer::compare);
    
            CompletionStage<Done> done = shouldNotBePossible.runForeach(
                    i -> {}, ActorMaterializer.create(ActorSystem.create()));
    
            // throws class cast exception (wrapped in Execution exception)
            done.toCompletableFuture().get();
        }
    }

Seems like it could be an issue with how Java interprets the Scala generics so perhaps not fixable without converting akka.stream.javadsl.Source to a java source file.

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #24368

A bit on the fence about this, not source compatible and quite invasive.

However, the current situation is that methods that looks like they have a bound actually do not provide any type safety at all, for example this compiles fine and blows up later:

```
Source<Apple, NotUsed> apples = ???
Source<Dogs, NotUsed> dogs = ???
Source<Dogs, NotUsed> wat = apples.prepend(dogs)
```

### CODE REVIEW

File: akka-stream/src/main/scala/akka/stream/javadsl/Source.scala [hunk 1]
```diff
@@ -445,6 +445,27 @@ object Source {
...
 
+  /**
+   * Upcast a stream of elements to a stream of supertypes of that element. Useful in combination with
+   * fan-in combinators where you do not want to pay the cost of casting each element in a `map`.
+   *
+   * Example:
+   *
+   * {{{
+   * Source<Apple, NotUsed> apples = null;
+   * Source<Orange, NotUsed> oranges = null;
```
Comment (patriknw) [inline akka-stream/src/main/scala/akka/stream/javadsl/Source.scala]: perhaps use `Source.empty` in such examples instead of null

File: akka-stream/src/main/scala/akka/stream/scaladsl/BidiFlow.scala [hunk 2]
```diff
@@ -14,7 +14,8 @@ final class BidiFlow[-I1, +O1, -I2, +O2, +Mat](
   override val shape:            BidiShape[I1, O1, I2, O2]
 ) extends Graph[BidiShape[I1, O1, I2, O2], Mat] {
 
-  def asJava: javadsl.BidiFlow[I1, O1, I2, O2, Mat] = new javadsl.BidiFlow(this)
+  def asJava[JI1 <: I1, JO1 >: O1, JI2 <: I2, JO2 >: O2, JMat >: Mat]: javadsl.BidiFlow[JI1, JO1, JI2, JO2, JMat] =
```
Comment (patriknw) [inline akka-stream/src/main/scala/akka/stream/scaladsl/BidiFlow.scala]: that's some signature

**Review by patriknw — APPROVED** [review]
LGTM, I guess

File: akka-stream/src/main/scala/akka/stream/javadsl/Source.scala (hunk 1 above)
Comment (johanandren) [reply akka-stream/src/main/scala/akka/stream/javadsl/Source.scala]: Ups, yes, indeed, copy pasta from the test.

File: akka-stream/src/main/scala/akka/stream/scaladsl/BidiFlow.scala (hunk 2 above)
Comment (johanandren) [reply akka-stream/src/main/scala/akka/stream/scaladsl/BidiFlow.scala]: ;(

**Review by jrudolph — COMMENTED** [review]
IMO the change is the right way to go, the question is under which conditions we can pull it off.

I also tried things back when @johanandren was working on it to find out whether there are better solutions but it seems that Java doesn't offer anything better. I guess the main reason why there is no better support in Java is that most collections are mutable and therefore must be invariant so the support for covariant data types is just too limited.

I wonder though, if this isn't a bug in the Scala compiler as well because it creates unsafe generic signatures. Shouldn't it create generic signatures that are just not usable from Java instead of bailing out and silently allowing unsafe usage?

**Comment by jrudolph** [comment]
Needs, rebasing/merging btw.

**Review by 2m — APPROVED** [review]
LGTM. I see how removing these lower type bounds also required removing co/contra ascriptions from the type parameters in Source/Flow/Sink/etc.

Also needs a rebase.
