### PR TITLE
=con #16946 Make ReliableProxyMultiJvmSpec not reuse proxy actor name

### LINKED ISSUE #16946: FAILED: ReliableProxyMultiJvm
```
[JVM-1] - must stop proxy if target stops and no reconnection *** FAILED ***
[JVM-1]   akka.actor.InvalidActorNameException: actor name [proxy] is not unique!
[JVM-1]   at akka.actor.dungeon.ChildrenContainer$TerminatingChildrenContainer.reserve(ChildrenContainer.scala:192)
[JVM-1]   at akka.actor.dungeon.Children$class.reserveChild(Children.scala:76)
[JVM-1]   at akka.actor.ActorCell.reserveChild(ActorCell.scala:369)
[JVM-1]   at akka.actor.dungeon.Children$class.makeChild(Children.scala:202)
[JVM-1]   at akka.actor.dungeon.Children$class.attachChild(Children.scala:41)
[JVM-1]   at akka.actor.ActorCell.attachChild(ActorCell.scala:369)
[JVM-1]   at akka.actor.ActorSystemImpl.actorOf(ActorSystem.scala:586)
[JVM-1]   at akka.contrib.pattern.ReliableProxySpec$$anonfun$1$$anonfun$apply$mcV$sp$38$$anonfun$apply$mcV$sp$39.apply$mcV$sp(ReliableProxySpec.scala:292)
[JVM-1]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:338)
[JVM-1]   at akka.contrib.pattern.ReliableProxySpec$$anonfun$1$$anonfun$apply$mcV$sp$38.apply$mcV$sp(ReliableProxySpec.scala:288)
[JVM-1]   ...
[JVM-1] [ERROR] [02/26/2015 08:36:18.495] [ReliableProxySpec-akka.actor.default-dispatcher-3] [akka://ReliableProxySpec/user/controller/barriers] RoleName(local) tried to enter 'after-each' while we were waiting for 'test7a' (akka.remote.testconductor.BarrierCoordinator$WrongBarrier)
[JVM-1] [WARN] [02/26/2015 08:36:18.501] [ReliableProxySpec-akka.actor.default-dispatcher-14] [akka://ReliableProxySpec/user/controller/barriers] cannot remove RoleName(local): no client to remove
[JVM-2] - must stop proxy if target stops and no reconnection *** FAILED ***
[JVM-2]   java.lang.RuntimeException: barrier failed: test7a
[JVM-2]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:211)
[JVM-2]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:186)
[JVM-2]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
[JVM-2]   at akka.actor.FSM$class.processEvent(FSM.scala:621)
[JVM-2]   at akka.remote.testconductor.ClientFSM.akka$actor$LoggingFSM$$super$processEvent(Player.scala:147)
[JVM-2]   at akka.actor.LoggingFSM$class.processEvent(FSM.scala:752)
[JVM-2]   at akka.remote.testconductor.ClientFSM.processEvent(Player.scala:147)
[JVM-2]   at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:615)
[JVM-2]   at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:609)
[JVM-2]   at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
```

https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2109

### PR DESCRIPTION
**Pull request by bantonsson**
Fixes #16946

### CODE REVIEW

File: akka-contrib/src/multi-jvm/scala/akka/contrib/pattern/ReliableProxySpec.scala [hunk 1]
```diff
@@ -59,9 +59,22 @@ class ReliableProxySpec extends MultiNodeSpec(ReliableProxySpec) with STMultiNod
...
   def stopProxy(): Unit = {
-    proxy ! FSM.UnsubscribeTransitionCallBack(testActor)
-    system stop proxy
-    expectMsgType[Terminated]
+    val oldProxy = proxy
+    oldProxy ! FSM.UnsubscribeTransitionCallBack(testActor)
+    system stop oldProxy
+    expectMsgPF(Duration.Undefined, "Terminated " + oldProxy) {
+      case Terminated(`oldProxy`) ⇒
+    }
```
Comment (patriknw) [inline akka-contrib/src/multi-jvm/scala/akka/contrib/pattern/ReliableProxySpec.scala]: `expectTerminated`?

File: akka-contrib/src/multi-jvm/scala/akka/contrib/pattern/ReliableProxySpec.scala [hunk 2]
```diff
@@ -59,9 +59,22 @@ class ReliableProxySpec extends MultiNodeSpec(ReliableProxySpec) with STMultiNod
...
+    // try to make really sure that the proxy actor name is available again
+    var id = 0
+    awaitCond({
+      id += 1
+      ActorSelection(proxy, Nil) ! Identify(id)
+      receiveOne(Duration.Undefined) match {
+        case ActorIdentity(id, None)             ⇒ true
+        case ActorIdentity(id, Some(`oldProxy`)) ⇒ false
+      }
```
Comment (patriknw) [inline akka-contrib/src/multi-jvm/scala/akka/contrib/pattern/ReliableProxySpec.scala]: why not `expectMsg(ActorIdentity(id, None))`?

I don't think the `id` counter is important here

Comment (bantonsson) [inline akka-contrib/src/multi-jvm/scala/akka/contrib/pattern/ReliableProxySpec.scala]: Because I don't want to fail if I get back `Some` I want to try again.

File: akka-contrib/src/multi-jvm/scala/akka/contrib/pattern/ReliableProxySpec.scala (hunk 1 above)
Comment (bantonsson) [inline akka-contrib/src/multi-jvm/scala/akka/contrib/pattern/ReliableProxySpec.scala]: Yes, definitely.

File: akka-contrib/src/multi-jvm/scala/akka/contrib/pattern/ReliableProxySpec.scala (hunk 2 above)
Comment (bantonsson) [inline akka-contrib/src/multi-jvm/scala/akka/contrib/pattern/ReliableProxySpec.scala]: And yes, the id is not important since i forgot the backticks anyway.

**Comment by bantonsson** [comment]
Sorry for the first fix. My head wasn't on right when I did it. Much simpler now. Just don't reuse the name, since we don't need to.

File: akka-contrib/src/multi-jvm/scala/akka/contrib/pattern/ReliableProxySpec.scala (hunk 2 above)
Comment (patriknw) [inline akka-contrib/src/multi-jvm/scala/akka/contrib/pattern/ReliableProxySpec.scala]: `awaitAssert` and `expectMsg(ActorIdentity(_, None))` would work, but nevermind

**Comment by patriknw** [comment]
LGTM :-)
