### PR TITLE
=fil #16657 Fixes being unable to roll over filebasedmailbox journal on some OSes

### LINKED ISSUE #16657: On some operating systems (deprecated) FileBasedMailbox keeps growing ignoring rollover
On some operating systems the (deprecated since 2.3.0 came out) FileBasedMailbox can fail performing the rollover due to os-specific "move file" method being called, quote:

```
"Many aspects of the behavior of this method are inherently platform-dependent: 
The rename operation might not be able to move a file from one filesystem to another, 
it might not be atomic, **and it might not succeed if a file with the destination abstract pathname
already exists**. The return value should always be checked to make sure that the rename operation 
was successful" 
```

Turns out on Windows and *some* *NIX systems this method fails to replace the new file with the rolled over file. Fixing this means adding an explicit delete before we perform the file move.

### PR DESCRIPTION
**Pull request by ktoso**
We simply must delete before the rename.

Resolves #16657

### CODE REVIEW

File: akka-durable-mailboxes/akka-file-mailbox/src/main/scala/akka/actor/mailbox/filebased/filequeue/Journal.scala [hunk 1]
```diff
@@ -86,14 +86,15 @@ class Journal(queuePath: String, syncJournal: ⇒ Boolean, log: LoggingAdapter)
       add(false, item)
     }
     if (syncJournal) writer.force(false)
-    writer.close
-    tmpFile.renameTo(queueFile)
-    open
+    writer.close()
+    // as renameTo is not guaranteed to be able to overwrite the target file, delete it explicitly
+    try queueFile.delete() finally tmpFile.renameTo(queueFile)
```
Comment (drewhk) [inline akka-durable-mailboxes/akka-file-mailbox/src/main/scala/akka/actor/mailbox/filebased/filequeue/Journal.scala]: do we really need the finally here? Can we expect the rename to succeed if the delete fails?

Comment (ktoso) [inline akka-durable-mailboxes/akka-file-mailbox/src/main/scala/akka/actor/mailbox/filebased/filequeue/Journal.scala]: yeah it's not really needed - actually first PRed without and then had "oh maybe it won't hurt to add it" moment. 
delete should not throw in any case (except security exceptions) actually.

Comment (ktoso) [inline akka-durable-mailboxes/akka-file-mailbox/src/main/scala/akka/actor/mailbox/filebased/filequeue/Journal.scala]: finally is no more.

**Comment by patriknw** [comment]
LGTM
looks harmless

**Comment by hepin1989** [comment]
how about the scala-asm

**Comment by hepin1989** [comment]
how about the using https://github.com/jsuereth/scala-arm

**Comment by ktoso** [comment]
Asm or scala-arm? I don't think this fix warrants adding a new dependency.

**Comment by ktoso** [comment]
And it's a deprecated module anyway, so pure maintenance mode - as little changes as possible. Thanks for the idea though, scala-arm certainly is rather nice :-)

**Comment by hepin1989** [comment]
sorry for the typo,work to mid night,mess my head up :P

**Comment by patriknw** [comment]
mergin this so it's included in the weekend repeat job
