### PR TITLE
Harden BindCanonicalAddressSpec

### LINKED ISSUE #25403: Failed: BindCanonicalAddressSpec (artery)
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/1156/testReport/junit/akka.remote.artery/BindCanonicalAddressSpec/artery_with_tcp_transport_should_bind_to_a_random_port_but_remoting_accepts_from_a_specified_port/

```
Error Message
org.scalatest.exceptions.TestFailedException: List(akka://sys@127.0.1.1:44765) contained element akka://sys@127.0.1.1:44765
Stacktrace
sbt.ForkMain$ForkError: org.scalatest.exceptions.TestFailedException: List(akka://sys@127.0.1.1:44765) contained element akka://sys@127.0.1.1:44765
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:346)
	at org.scalatest.words.ResultOfNotWordForAny.contain(ResultOfNotWordForAny.scala:475)
	at akka.remote.artery.BindCanonicalAddressBehaviors$$anonfun$arteryConnectionTest$2.apply(BindCanonicalAddressSpec.scala:49)
	at akka.remote.artery.BindCanonicalAddressBehaviors$$anonfun$arteryConnectionTest$2.apply(BindCanonicalAddressSpec.scala:37)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
```

### PR DESCRIPTION
**Pull request by chbatey**
The randomly selected port by Artery could be the same as the randomly
selected port the test generates.

Fixes #25403

### CODE REVIEW

File: akka-remote/src/test/scala/akka/remote/artery/BindCanonicalAddressSpec.scala [hunk 1]
```diff
@@ -46,7 +48,10 @@ trait BindCanonicalAddressBehaviors {
       implicit val sys = ActorSystem("sys", config.withFallback(commonConfig))
 
       getExternal should ===(address.toAkkaAddress("akka"))
-      getInternal should not contain (address.toAkkaAddress("akka"))
+      // May have selected the same random port
+      if (!getInternal.headOption.exists(_.port.exists(randomPort ⇒ randomPort == address.getPort))) {
+        getInternal should not contain address.toAkkaAddress("akka")
+      }
```
Comment (johanandren) [inline akka-remote/src/test/scala/akka/remote/artery/BindCanonicalAddressSpec.scala]: Wouldn't this also make the test pass if the functionality was broken? The assortment that if bind-port isn't the same as this random port then check that they aren't the same seems fishy.

Comment (chbatey) [reply akka-remote/src/test/scala/akka/remote/artery/BindCanonicalAddressSpec.scala]: Yeah you're right this is crappy. Not sure how to make this test reliable

Comment (johanandren) [reply akka-remote/src/test/scala/akka/remote/artery/BindCanonicalAddressSpec.scala]: Maybe if it retried the bind in this case, then we would catch if it got broken but in the event it randomly chose the same port that'd pass?

Comment (chbatey) [reply akka-remote/src/test/scala/akka/remote/artery/BindCanonicalAddressSpec.scala]: Yeah, that decreases the odds, will do it

**Review by johanandren — APPROVED** [review]

File: akka-remote/src/test/scala/akka/remote/artery/BindCanonicalAddressSpec.scala [hunk 2]
```diff
@@ -46,8 +46,16 @@ trait BindCanonicalAddressBehaviors {
       implicit val sys = ActorSystem("sys", config.withFallback(commonConfig))
 
       getExternal should ===(address.toAkkaAddress("akka"))
-      getInternal should not contain (address.toAkkaAddress("akka"))
-
+      // May have selected the same random port - bind another in that case while the other still has the canonical port
+      val internals = if (!getInternal.headOption.exists(_.port.exists(randomPort ⇒ randomPort == address.getPort))) {
```
Comment (raboof) [inline akka-remote/src/test/scala/akka/remote/artery/BindCanonicalAddressSpec.scala]: Perhaps `if (getInternal.flatMap(_.port).map(_ == address.getPort).getOrElse(false))`?

**Review by raboof — APPROVED** [review]
