### PR TITLE
=str - 19327 - Fixes race condition in InputStreamSinkSpec

### LINKED ISSUE #19327: Flaky test InputStreamSinkSpec
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/4696/consoleFull
```
[info] - must fill up buffer by default *** FAILED *** (38 milliseconds)
[info]   Array(77, 42, -94) did not equal ByteString(-82, 117, -102) (InputStreamSinkSpec.scala:149)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6356)
[info]   at akka.stream.io.InputStreamSinkSpec$$anonfun$1$$anonfun$apply$mcV$sp$11$$anonfun$apply$mcV$sp$12.apply$mcV$sp(InputStreamSinkSpec.scala:149)
[info]   at akka.stream.io.InputStreamSinkSpec$$anonfun$1$$anonfun$apply$mcV$sp$11$$anonfun$apply$mcV$sp$12.apply(InputStreamSinkSpec.scala:138)
[info]   at akka.stream.io.InputStreamSinkSpec$$anonfun$1$$anonfun$apply$mcV$sp$11$$anonfun$apply$mcV$sp$12.apply(InputStreamSinkSpec.scala:138)
[info]   at akka.stream.testkit.Utils$.assertAllStagesStopped(Utils.scala:26)
[info]   at akka.stream.io.InputStreamSinkSpec$$anonfun$1$$anonfun$apply$mcV$sp$11.apply$mcV$sp(InputStreamSinkSpec.scala:138)
[info]   at akka.stream.io.InputStreamSinkSpec$$anonfun$1$$anonfun$apply$mcV$sp$11.apply(InputStreamSinkSpec.scala:138)
```

### PR DESCRIPTION
**Pull request by viktorklang**
- Cleanup of that spec

Fixes #19327

### CODE REVIEW

File: akka-stream-tests/src/test/scala/akka/stream/io/InputStreamSinkSpec.scala [hunk 1]
```diff
@@ -124,70 +114,55 @@ class InputStreamSinkSpec extends AkkaSpec(UnboundedMailboxConfig) {
...
     }
 
     "fill up buffer by default" in assertAllStagesStopped {
-      val array2 = randomArray(3)
-      val inputStream = Source(byteString :: ByteString(array2) :: Nil).runWith(StreamConverters.asInputStream())
-
-      val arr1 = newArray()
-      val arr2 = newArray()
-      val f1 = Future(inputStream.read(arr1))
-      val f2 = Future(inputStream.read(arr2))
```
Comment (viktorklang) [inline akka-stream-tests/src/test/scala/akka/stream/io/InputStreamSinkSpec.scala]: these two reads could get interleaved

**Comment by ktoso** [comment]
LGTM, thanks @viktorklang!
