### PR TITLE
Accept TTL values of 0 in CachePolicy (#26427)

### LINKED ISSUE #26427: CachePolicy value throws exception if duration is zero
As mentioned in Gitter: https://gitter.im/akka/akka?at=5c6eb4eeddaa310c89c93f4b

In Akka 2.5.19, using Akka HTTP client with the Async DNS resolver, the CachePolicy throws the exception below, saying that TTL values must be a positive value. This is a result of parsing a resource record that probably has a TTL of 0s.

I'm quite new to the [RFC1035](https://www.ietf.org/rfc/rfc1035.txt) standard for DNS, but giving it a quick read, it says that the TTL in a Resouce Record may be 0, indicating that the implementation in `CachePolicy` is wrong. The simple solution would be to change the check in `CachePolicy` from `<=` to `<`. I'll open up a PR for that.

```
[ERROR] [default-akka.actor.default-dispatcher-109003] (akka.actor.OneForOneStrategy): TTL values must be a positive value.
java.lang.IllegalArgumentException: TTL values must be a positive value.
	at akka.io.dns.CachePolicy$Ttl.<init>(CachePolicy.scala:22)
	at akka.io.dns.CachePolicy$Ttl$.fromPositive(CachePolicy.scala:39)
	at akka.io.dns.ResourceRecord$.parse(DnsResourceRecords.scala:133)
	at akka.io.dns.internal.Message$.$anonfun$parse$4(DnsMessage.scala:139)
	at scala.util.Try$.apply(Try.scala:213)
	at akka.io.dns.internal.Message$.$anonfun$parse$3(DnsMessage.scala:139)
	at akka.io.dns.internal.Message$.$anonfun$parse$3$adapted(DnsMessage.scala:139)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
	at scala.collection.immutable.Range.foreach(Range.scala:158)
	at scala.collection.TraversableLike.map(TraversableLike.scala:237)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at akka.io.dns.internal.Message$.parse(DnsMessage.scala:139)
	at akka.io.dns.internal.DnsClient$$anonfun$ready$1.applyOrElse(DnsClient.scala:114)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.io.dns.internal.DnsClient.aroundReceive(DnsClient.scala:37)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

### PR DESCRIPTION
**Pull request by agboom**
As per RFC spec https://www.ietf.org/rfc/rfc1035.txt (Section 3.2.1)

Fixes #26427

### CODE REVIEW

**Comment by johanandren** [comment]
OK TO TEST

**Comment by johanandren** [comment]
Actually I think a 0 value should rather lead to `akka.io.dns.CachePolicy.Never` than being parsed into a `Ttl` instance.

**Comment by agboom** [comment]
@johanandren That's a good point. Would it also be sensible to put it in `Ttl.fromPositive`? In other words: should the `Ttl` constructor itself interpret 0 seconds to be a `Never` policy? Or would that be the wrong abstraction, since `CachePolicy` might not be limited to DNS caching? I'm still learning about this part of Akka, so excuse my obvious questions.

**Comment by johanandren** [comment]
I think it belongs with the parsing rather. When used from code I think it is better if the user API is to refer to the `CachePolicy.Never` directly if that is what is intended.

**Comment by agboom** [comment]
@johanandren This would be a more disruptive change, since every Record parser expects a `Ttl` instead of a `CachePolicy`. Is this by design or can I safely change the `Ttl` type in `ResourceRecord` to `CachePolicy`?

**Comment by agboom** [comment]
It seems that the DnsResolver depends on a Ttl value in the ResourceRecord, so I'm not sure if this is desired.

**Comment by agboom** [comment]
Since the DnsCache uses the abstract `CachePolicy` again, I could select the minimum cache policy in `AsyncDnsResolver`, where Never < Ttl(value) < Forever. This could be easily resolved with an `Ordering[CachePolicy]`. Correct me if I'm wrong.

**Comment by johanandren** [comment]
Hmmm, ouch.

I'm not 100% sure then, let's pull the original authors into the discussion and see what they think.

Ping @chbatey @ignasi35

File: akka-actor/src/main/scala/akka/io/dns/DnsResourceRecords.scala [hunk 1]
```diff
@@ -15,28 +15,28 @@ import akka.util.{ ByteIterator, ByteString, unused }
 import scala.annotation.switch
 import scala.concurrent.duration._
 
-sealed abstract class ResourceRecord(val name: String, val ttl: Ttl, val recType: Short, val recClass: Short)
+sealed abstract class ResourceRecord(val name: String, val cachePolicy: CachePolicy, val recType: Short, val recClass: Short)
```
Comment (johanandren) [inline akka-actor/src/main/scala/akka/io/dns/DnsResourceRecords.scala]: I like this better because it seems to align with the actual protocol better, but I may be missing some consequence of it.

Comment (agboom) [reply akka-actor/src/main/scala/akka/io/dns/DnsResourceRecords.scala]: On the one hand it might follow the semantics of the RFC standard less strictly, because the RFC states that a TTL is a 32 bit integer. On the other hand it allows to model the interpretation of the TTL as documented in 3.2.1:
> Zero values are interpreted to mean that the RR can only be used for the transaction in progress, and should not be cached.
However, it also allows a RR with a `Forever` TTL and I'm not sure if that's desired.

**Comment by agboom** [comment]
Ok, I see that my latest commit triggered a binary compatibility check failure. This is probably due to the constructor change in `ResourceRecord`?

File: akka-actor/src/main/scala/akka/io/dns/DnsResourceRecords.scala (hunk 1 above)
Comment (patriknw) [reply akka-actor/src/main/scala/akka/io/dns/DnsResourceRecords.scala]: I wouldn't like to do such a big change, again. This API has been moving so much and we just marked it as stable. Can't we solve it in a way that is backwards compatible, like just accepting that Ttl can be zero?

Comment (johanandren) [reply akka-actor/src/main/scala/akka/io/dns/DnsResourceRecords.scala]: Ok, let's do that, sorry for leading you in a different direction @agboom

Comment (patriknw) [reply akka-actor/src/main/scala/akka/io/dns/DnsResourceRecords.scala]: to clarify: `fromPositive` should still not accept zero (would be weird naming), if needed we can add a new factory method for the zero case `Ttl.never`

Comment (agboom) [reply akka-actor/src/main/scala/akka/io/dns/DnsResourceRecords.scala]: Ok, I'll revert the previous commit and implement as you suggested. No problem @johanandren, that's how I've learned something :)

File: akka-actor/src/main/scala/akka/io/dns/CachePolicy.scala [hunk 2]
```diff
@@ -15,7 +15,7 @@ object CachePolicy {
   case object Forever extends CachePolicy
 
   final class Ttl private (val value: FiniteDuration) extends CachePolicy {
-    if (value <= Duration.Zero) throw new IllegalArgumentException(s"TTL values must be a positive value.")
+    if (value < Duration.Zero) throw new IllegalArgumentException(s"TTL values must be a positive value.")
```
Comment (patriknw) [inline akka-actor/src/main/scala/akka/io/dns/CachePolicy.scala]: I think we should add the more strict check in `fromPositive` and add a separate factory method for the zero Ttl.

```
    def fromPositive(value: FiniteDuration): Ttl = {
      if (value <= Duration.Zero) throw new IllegalArgumentException(s"TTL values must be a positive value.")
      new Ttl(value)
    }

    def never: Ttl = new Ttl(Duration.Zero)
```

Do we also have to change somewhere else where `fromPositive` is used, such as in `ResourceRecord.parse`? There it could use `new Ttl` instead of the value can be 0.

Comment (agboom) [reply akka-actor/src/main/scala/akka/io/dns/CachePolicy.scala]: @patriknw Yes, sorry I was getting around to that. I was just pondering about the mathematical meaning of "positive values". Depending on the context, zero is neither positive nor negative, but in the set of real numbers there's a subset called strictly positive real numbers. [Source](https://proofwiki.org/wiki/Definition:Strictly_Positive). 

I'll push a new commit shortly.

**Comment by agboom** [comment]
Is a unit test desired for parsing a RR with a TTL value of zero?

**Comment by johanandren** [comment]
I think a test would be good

**Comment by johanandren** [comment]
PLS BUILD

**Review by patriknw — APPROVED** [review]
LGTM

**Review by johanandren — APPROVED** [review]

**Comment by johanandren** [comment]
Why is it waiting for travis for three days?

**Comment by johanandren** [comment]
PLS BUILD

**Comment by patriknw** [comment]
will probably fail on formatting now

**Comment by patriknw** [comment]
PLS BUILD

**Comment by raboof** [comment]
@agboom unfortunately it looks like this needs a round of scalafmt formatting - would you like to do that or shall we take care of that?

**Comment by agboom** [comment]
@raboof I'll take a look at it. I see that there are some conflicts with my fork and origin, so I'll fix those too.

**Comment by agboom** [comment]
Somehow my local SBT does not pick up the new scalafmt formatting rules. All instances of `=>` are replaced with `⇒`. I branched from the most recent commit (17c80b). Am I missing something?

**Comment by johanandren** [comment]
Did you remember to `reload` (or restart sbt)?

**Comment by agboom** [comment]
@johanandren You're right, I wasn't paying attention :grimacing:

**Comment by agboom** [comment]
I'd like to add a test for the new `Ttl` zero value. There is no existing `CachePolicySpec` or sth. Is the `AsyncDnsResolverIntegrationSpec` a sensible place to test this?

**Comment by agboom** [comment]
Rats, it still isn't correctly formatted

**Comment by patriknw** [comment]
scalafmtAll in the projects you changed (or where it complains, I think something slipped into master)

**Comment by patriknw** [comment]
PLS BUILD

**Comment by agboom** [comment]
I reran `scalafmtAll` for the entire project, so it should be good now

**Comment by johanandren** [comment]
PLS BUILD

**Comment by johanandren** [comment]
Not sure what is up with travis, if it's the reporting back that doesn't work or it actually didn't run...

**Comment by johanandren** [comment]
PLS BUILD

**Comment by patriknw** [comment]
Note that pls build is only understood by jenkins. Travis requires click-rebuild.

**Comment by johanandren** [comment]
Ah, my bad, I thought it triggers both. I can't find this PR in travis not sure what is going on.

**Comment by patriknw** [comment]
strange, I'll close and re-open to trigger a new one

**Comment by johanandren** [comment]
Alright, all lights green!
