### PR TITLE
Fail all stages on abrupt termination

### LINKED ISSUE #22652: Source.unfoldResource may leak resources
Consider the following program:
```scala

import akka.actor.{Actor, ActorSystem, PoisonPill, Props}
import akka.stream.scaladsl.{Sink, Source}
import akka.stream.{ActorMaterializer, KillSwitches}

class MyActor extends Actor {
  implicit val materializer = ActorMaterializer()
  val killSwitch            = KillSwitches.shared("kill")

  override def preStart() =
    Source
      .unfoldResource[String, String]({ () =>
        println("## Opened")
        "resource"
      }, { _ =>
        Thread.sleep(1000L)
        Some("OnNext")
      }, _ => println("## Closed"))
      .via(killSwitch.flow[String])
      .runWith(Sink.foreach(m => self ! m))

  override def postStop() = {
    killSwitch.shutdown()
    super.postStop()
  }

  override def receive = {
    case any => println(s"Received $any")
  }
}

object Test extends App {
  implicit val system = ActorSystem()
  println("starting")
  val ref = system.actorOf(Props(classOf[MyActor]))
  Thread.sleep(5000L)
  println("killing the actor")
  ref ! PoisonPill
}
```

`## Closed` will never be printed

The key part is `ActorMaterializer()` capturing current actor's context as an `ActorRefFactory`. When the actor gets killed, no proper stream lifecycle methods are executed.

Akka version is 2.4.17

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #22652 in a general way, somewhat like how @avakhrenev proposed the fix. When the abrupt termination is triggered the source stages are failed and that failure is propagated through the graph.

### CODE REVIEW

File: akka-stream/src/main/scala/akka/stream/impl/fusing/ActorGraphInterpreter.scala [hunk 1]
```diff
@@ -605,6 +605,14 @@ import scala.util.control.NonFatal
     // call has no effect and therefore does the right thing: nothing.
     try {
       inputs.foreach(_.onInternalError(reason))
+      // fail all sources
+      logics.foreach { logic ⇒
+        // source
+        if (logic.inCount == 0 && logic.outCount > 0) {
+          logic.failStage(reason)
+          interpreter.finalizeStage(logic)
```
Comment (johanandren) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/ActorGraphInterpreter.scala]: As the stage is failed, `postStop` and `afterPostStop` will not be called in the `interpreter.finish()` call, so we do it here to make sure.

File: akka-stream/src/main/scala/akka/stream/impl/fusing/ActorGraphInterpreter.scala [hunk 2]
```diff
@@ -605,6 +605,14 @@ import scala.util.control.NonFatal
     // call has no effect and therefore does the right thing: nothing.
     try {
       inputs.foreach(_.onInternalError(reason))
+      // fail all sources
+      logics.foreach { logic ⇒
+        // source
+        if (logic.inCount == 0 && logic.outCount > 0) {
```
Comment (jrudolph) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/ActorGraphInterpreter.scala]: What's the rationale for this condition? Why not just run it for all stages which are not yet finished?

Comment (johanandren) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/ActorGraphInterpreter.scala]: Only failing sources as they will propagate the failure downstream, if I just go through the logics it happens to the stages in random order (not quite sure if that matters, it just seemed more tidy and according to the existing logic, which only failed cross-boundary inputs).

Comment (jrudolph) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/ActorGraphInterpreter.scala]: I see. Still the complete set of things that this method does seems weird. I think the logic you try here belongs into `interpreter.finish`.

File: akka-stream/src/main/scala/akka/stream/impl/fusing/ActorGraphInterpreter.scala (hunk 1 above)
Comment (jrudolph) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/ActorGraphInterpreter.scala]: That might be a bug of `interpreter.finish` (which is only used from here). How do you prevent that `postStop` isn't called another time if it was already called before?

File: akka-stream/src/main/scala/akka/stream/impl/fusing/ActorGraphInterpreter.scala (hunk 2 above)
Comment (jrudolph) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/ActorGraphInterpreter.scala]: Also, I think the original comment is still valid. All sink stages or stages where `onUpstreamFailure` doesn't propagate will still only have `postStop` called but not `onDownstreamFinish`.

**Review by jrudolph — COMMENTED** [review]
I had a few comments. For me the fix seems plausible but not a comprehensive solution that will catch all those problems (as described in the comments).

Also we should document the behavior that is expected for a GraphStage:

It is guaranteed that for every port a completion function will be called
 * either `onUpstreamComplete` or `onUpstreamFailure` for an `InPort`
 * `onDownstreamFailure` for an `OutPort`

For resource cleanup `postStop` should be preferred because it will be called in any case.

File: akka-stream/src/main/scala/akka/stream/impl/fusing/ActorGraphInterpreter.scala (hunk 2 above)
Comment (johanandren) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/ActorGraphInterpreter.scala]: Finish does not know about the exception, so it cannot fail the stages. If we'd separate the fail from the stop, AFAICS the `finish()` method has no way to differentiate between already stopped stages and stages that are "halfway" stopped because of the failure.

One thing I just realised though based on your last comment is if stages stop the propagation this does not work and we need to go through all stages and fail them as it is impossible to recover in this case.

Comment (jrudolph) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/ActorGraphInterpreter.scala]: `finish` is only used from here, so you could make it know whatever it needs ;)

**Comment by johanandren** [comment]
I think I have realised it does such a guarantee does not make sense (back to square one). When a logic is failed it cancels its upstream and fails its downstream, the handlers of the logic itself never gets failed, then the stage is marked to stop (`setKeepGoing(false)`). 

I think the only thing we can guarantee is that `postStop` will be called.

**Comment by jrudolph** [comment]
> When a logic is failed it cancels its upstream and fails its downstream, the handlers of the logic itself never gets failed,

Ah, that's something I thought before as well but dismissed when I looked at `completeStage` and `failStage`. But you are right, after `completeStage` or `failStage` has been called no further handlers will be called afterwards aside from `*postStop`.

**Comment by johanandren** [comment]
This means that unless a stage got a failure from upstream it can never know it stopped because of a failure, so it can close resources but not signal failure outside of the stage, for example with `ActorRefBackpressureSinkStage` we'd want to signal failure to the actor, but the best we can do is to keep track if we already sent complete/fail and send a generic fail without the actual exception.

Not sure if this important for many other stages though.

**Comment by jrudolph** [comment]
That's right, but it seems only tangential to the problem at hand. It always itched me that RS `cancel` and our `onDownstreamFinish` cannot transport a reason for cancellation but that's basically a known issue. (I guess we could add it in our own world of GraphStage / GraphInterpreter by actually transmitting a reason but would have to throw that away at RS boundaries.)

**Comment by johanandren** [comment]
Ok, after discussion and thinking about it, I cannot find a safe general solution, which is a shame because it is really easy to miss that a stage will not see upstream failure, finish nor downstream cancel. 

I have instead hand-fixed all those stages listed in the ticket.

**Comment by avakhrenev** [comment]
Ok. Thak you @johanandren!

File: akka-stream/src/main/scala/akka/stream/impl/Sinks.scala [hunk 3]
```diff
@@ -255,6 +255,12 @@ import akka.util.OptionVal
         failStage(ex)
       }
 
+      override def postStop(): Unit = {
+        if (!p.isCompleted) {
+          p.failure(new AbruptStageTerminationException(this))
```
Comment (patriknw) [inline akka-stream/src/main/scala/akka/stream/impl/Sinks.scala]: but perhaps you want to save the allocation, ok, ignore this

Comment (patriknw) [inline akka-stream/src/main/scala/akka/stream/impl/Sinks.scala]: but remove the superfluous braces

File: akka-stream/src/main/scala/akka/stream/impl/Sources.scala [hunk 4]
```diff
@@ -306,38 +319,49 @@ import scala.util.control.NonFatal
...
       resource = Promise[S]()
       createStream(true)
     })
-    private def closeStage(): Unit = closeAndThen(completeStage _)
+    private def closeStage(): Unit = closeAndThen(completeStage)
+
+    override def postStop(): Unit = {
+      if (open) {
+        closeStage()
+      }
```
Comment (patriknw) [inline akka-stream/src/main/scala/akka/stream/impl/Sources.scala]: superfluous braces

File: akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala [hunk 5]
```diff
@@ -217,9 +217,13 @@ object GraphStageLogic {
...
- *  The stage logic is always once all its input and output ports have been closed, i.e. it is not possible to
- *  keep the stage alive for further processing once it does not have any open ports. This can be changed by
- *  overriding `keepGoingAfterAllPortsClosed` to return true.
+ * The stage logic is completed once all its input and output ports have been closed. This can be changed by
+ * setting `setKeepGoing` to true.
+ *
+ * The `postStop` lifecycle hook on the logic itself is called once all ports are closed. This is the only tear down
+ * callback that is guaranteed to happen, if the actor system or the materializer is terminated the handlers may never
+ * see any callbacks to `onUpstreamFailure`, `onUpstreamFinish` or `onDownstreamFinish`. Therefore stage resource
+ * cleanup should always be done in `postStop`.
```
Comment (patriknw) [inline akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala]: there are probably a few mistakes of this in alpakka (I have not checked)

**Review by patriknw — CHANGES_REQUESTED** [review]
looking good, a few minor adjustments
add/change something in reference docs also?

File: akka-stream/src/main/scala/akka/stream/impl/Sinks.scala (hunk 3 above)
Comment (hepin1989) [inline akka-stream/src/main/scala/akka/stream/impl/Sinks.scala]: I love the brace of the if block.

Comment (patriknw) [inline akka-stream/src/main/scala/akka/stream/impl/Sinks.scala]: I love less lines of code to maintain, doesn't add any readability advantage for such one-liners

File: akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowOnCompleteSpec.scala [hunk 6]
```diff
@@ -78,6 +78,18 @@ class FlowOnCompleteSpec extends StreamSpec with ScriptedTest {
       onCompleteProbe.expectMsg(Success(Done))
     }
 
+    "yield error on abrupt termination" in assertAllStagesStopped {
+      val mat = ActorMaterializer()
```
Comment (johanandren) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowOnCompleteSpec.scala]: Oh, thanks for pointing that out. I think I'll just remove the assertAllStages in that case, since I know the materializer is killed.

File: akka-stream/src/main/scala/akka/stream/ActorMaterializer.scala [hunk 7]
```diff
@@ -221,6 +222,15 @@ class MaterializationException(msg: String, cause: Throwable = null) extends Run
 final case class AbruptTerminationException(actor: ActorRef)
   extends RuntimeException(s"Processor actor [$actor] terminated abruptly") with NoStackTrace
 
+/**
+ * Signal that the stage was abruptly terminated, usually seen as a call to `postStop` of the `GraphStageLogic` without
+ * any of the handler callbacks seeing completion, cancellation or failure from up or downstream. This can happen when
```
Comment (johanandren) [inline akka-stream/src/main/scala/akka/stream/ActorMaterializer.scala]: I'm not sure what more precise would be in this context?

**Comment by johanandren** [comment]
Good idea to add something to the docs.

File: akka-stream/src/main/scala/akka/stream/ActorMaterializer.scala (hunk 7 above)
Comment (patriknw) [inline akka-stream/src/main/scala/akka/stream/ActorMaterializer.scala]: I mean that we should always spell out that cancellations come from downstream and failures come from upstream.

"cancellation from downstream or failure from upstream"

Comment (johanandren) [inline akka-stream/src/main/scala/akka/stream/ActorMaterializer.scala]: Ah, ok, will fix.

File: akka-docs/rst/java/stream/stream-customize.rst [hunk 8]
```diff
@@ -469,3 +469,15 @@ stage as state of an actor, and the callbacks as the ``receive`` block of the ac
...
+
+
+Resources and the stage lifecycle
+=================================
+
+If a stage manages a resource with a lifecycle, for example objects that needs to be shutdown when it is not
+used anymore, returned to a pool etc. it is important to make sure this will happen in all circumstances when the stage
+shuts down.
+
+Cleaning up resources should be done in ``GraphStageLogic.postStop` and not in the ``InHandler`` and ``InHandler``
```
Comment (jrudolph) [inline akka-docs/rst/java/stream/stream-customize.rst]: Should read

    ``InHandler`` and ``OutHandler``

Comment (johanandren) [inline akka-docs/rst/java/stream/stream-customize.rst]: argh

File: akka-docs/rst/java/stream/stream-customize.rst [hunk 9]
```diff
@@ -469,3 +469,15 @@ stage as state of an actor, and the callbacks as the ``receive`` block of the ac
...
+callbacks. The reason for this is that when the ``Materializer`` is shutdown or the ``ActorSystem`` is terminated while
+a stream is still running this leads to an "abrupt termination" and none of the callbacks are invoked.
```
Comment (jrudolph) [inline akka-docs/rst/java/stream/stream-customize.rst]: FWIW: it's not only then, but also when `completeStage` or `failStage` is called in a stage. E.g. the default implementation of `OutHandler.onDownstreamFinish` will call `completeStage`.

File: akka-docs/rst/scala/stream/stream-customize.rst [hunk 10]
```diff
@@ -480,6 +480,17 @@ stage as state of an actor, and the callbacks as the ``receive`` block of the ac
...
   behavior.
 
+Resources and the stage lifecycle
+=================================
+
+If a stage manages a resource with a lifecycle, for example objects that needs to be shutdown when it is not
+used anymore, returned to a pool etc. it is important to make sure this will happen in all circumstances when the stage
+shuts down.
+
+Cleaning up resources should be done in ``GraphStageLogic.postStop` and not in the ``InHandler`` and ``InHandler``
```
Comment (jrudolph) [inline akka-docs/rst/scala/stream/stream-customize.rst]: see above

File: akka-docs/rst/java/stream/stream-customize.rst (hunk 9 above)
Comment (johanandren) [inline akka-docs/rst/java/stream/stream-customize.rst]: Ah, ofc, when the stage is the "source" of the completion/failure...

**Review by jrudolph — APPROVED** [review]
LGTM. Thanks for going through the pain and fixing all of those manually.

File: akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala [hunk 11]
```diff
@@ -538,7 +542,7 @@ abstract class GraphStageLogic private[stream] (val inCount: Int, val outCount:
 
   /**
    * Automatically invokes [[cancel()]] or [[complete()]] on all the input or output ports that have been called,
-   * then stops the stage, then [[postStop()]] is called.
+   * then marks the stage as stopped.
```
Comment (ktoso) [inline akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala]: Wasn't this PR about making postStop always be invoked?

**Comment by ktoso** [comment]
Nitpicked around a bit

File: akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala (hunk 11 above)
Comment (johanandren) [inline akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala]: No, about not all stages cleaning up their resources in when abruptly terminated (because they did it in the handler hooks only).

File: akka-docs/rst/java/stream/stream-customize.rst [hunk 12]
```diff
@@ -469,3 +469,17 @@ stage as state of an actor, and the callbacks as the ``receive`` block of the ac
...
+
+
+Resources and the stage lifecycle
+=================================
+
+If a stage manages a resource with a lifecycle, for example objects that needs to be shutdown when it is not
+used anymore, returned to a pool etc. it is important to make sure this will happen in all circumstances when the stage
+shuts down.
+
+Cleaning up resources should be done in ``GraphStageLogic.postStop` and not in the ``InHandler`` and ``OutHandler``
```
Comment (johanandren) [inline akka-docs/rst/java/stream/stream-customize.rst]: god damn restructured text, I'm not going to miss you

File: akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala (hunk 11 above)
Comment (ktoso) [inline akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala]: I see, good then

**Review by ktoso — COMMENTED** [review]
LGTM

**Review by patriknw — APPROVED** [review]
LGTM
