### PR TITLE
Subscribing twice should cancel second subscriber

### LINKED ISSUE #24719: Reactive Streams spec violation - flatMapConcat violates 2.5
The subscriber passed to publishers produced by flatMapConcat functions does not `cancel` additional subscriptions passed to it. This violates reactive streams spec 2.5:

> A Subscriber MUST call Subscription.cancel() on the given Subscription after an onSubscribe signal if it already has an active Subscription.

This reproduces the violation:

```java
import akka.Done;
import akka.actor.ActorSystem;
import akka.stream.ActorMaterializer;
import akka.stream.Materializer;
import akka.stream.javadsl.Source;
import akka.stream.scaladsl.Sink;
import org.reactivestreams.Subscription;

import java.util.concurrent.CompletableFuture;

public class Reproducer {
  public static void main(String... args) throws Exception {
    ActorSystem system = ActorSystem.create();
    Materializer materializer = ActorMaterializer.create(system);

    try {

      CompletableFuture<Done> done = new CompletableFuture<>();

      Source.single(
          Source.fromPublisher(subscriber -> {
            subscriber.onSubscribe(new Subscription() {
              @Override
              public void request(long n) {
              }
              @Override
              public void cancel() {
              }
            });
            subscriber.onSubscribe(new Subscription() {
              @Override
              public void request(long n) {
                done.completeExceptionally(new IllegalStateException("request should not have been invoked"));
              }
              @Override
              public void cancel() {
                done.complete(Done.getInstance());
              }
            });
          })
      ).flatMapConcat(s -> s).runWith(Sink.ignore(), materializer);

      done.get();

    } finally {
      system.terminate();
    }
  }
}
```

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #24719

### CODE REVIEW

**Comment by jroper** [comment]
It may be worth adding a TCK blackbox (or whitebox if there's a straight forward way to do it) subscriber verification, that's how I picked this up, the rough approach I used to for the blackbox verification was:

```scala
override def createSubscriber() = {
  val subscriber = Promise[Subscriber[Int]]()
  Source.single(Source.fromPublisher(new Publisher[Int] {
    def subscriber(s : Subscriber[_ >: Int]) = subscriber.success(s)
  }).flatMapConcat(identity).runWith(Sink.ignore)
  Await.result(subscriber, 1.second)
}
```

**Comment by ktoso** [comment]
+1, we should add a TCK one for what potentialy did reproduce this

File: akka-stream/src/main/scala/akka/stream/impl/fusing/ActorGraphInterpreter.scala [hunk 1]
```diff
@@ -204,6 +204,8 @@ import scala.util.control.NonFatal
       } else if (downstreamCanceled) {
         upstreamCompleted = true
         tryCancel(subscription)
+      } else if (upstream != null) { // reactive streams spec 2.5
+        tryCancel(subscription)
```
Comment (ktoso) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/ActorGraphInterpreter.scala]: nice simple fix; good

**Review by ktoso — APPROVED** [review]
LGTM, would add a TCK test excercising flatMapConcat

**Comment by johanandren** [comment]
I added a TCK-test but that didn't exercise this bug, so that's why I left it out. But I can definitely add it back.

**Comment by johanandren** [comment]
Meh, formatting/copyright fail.

File: akka-stream/src/main/scala/akka/stream/impl/fusing/ActorGraphInterpreter.scala (hunk 1 above)
Comment (hepin1989) [reply akka-stream/src/main/scala/akka/stream/impl/fusing/ActorGraphInterpreter.scala]: Should add TCK for every kind of Source ,Flow and Sink?

Comment (ktoso) [reply akka-stream/src/main/scala/akka/stream/impl/fusing/ActorGraphInterpreter.scala]: We have... also, since akka streams is interpreted it does not make much of a difference - since the rules are protected by the interpreter. We know what we’re doing here

**Review by 2m — APPROVED** [review]
LGTM!
