### PR TITLE
Harden PrimitiveStateSpec: Expect termination before starting next actor

### LINKED ISSUE #25958: Failed: PrimitiveStateSpec
https://jenkins.akka.io:8498/job/akka-nightly/6069/testReport/junit/akka.persistence.typed.scaladsl/PrimitiveStateSpec/A_typed_persistent_actor_with_primitive_state_must_persist_events_and_update_state/

```
Error Message

java.lang.AssertionError: assertion failed: expected eventHandler:1:2, found onRecoveryCompleted:1

Stacktrace

sbt.ForkMain$ForkError: java.lang.AssertionError: assertion failed: expected eventHandler:1:2, found onRecoveryCompleted:1
	at scala.Predef$.assert(Predef.scala:219)
	at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage_internal(TestProbeImpl.scala:138)
	at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage(TestProbeImpl.scala:121)
	at akka.persistence.typed.scaladsl.PrimitiveStateSpec.$anonfun$new$2(PrimitiveStateSpec.scala:60)
	at akka.persistence.typed.scaladsl.PrimitiveStateSpec$$Lambda$967/1239911049.apply(Unknown Source)
```

### PR DESCRIPTION
**Pull request by chbatey**
Event handelr is called before persist so without this we may start
before the event is persisted. Expecting termination means that the
-1 is received so we know the persist is complete.

Fixes #25958

### CODE REVIEW

File: akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PrimitiveStateSpec.scala [hunk 1]
```diff
@@ -54,6 +54,8 @@ class PrimitiveStateSpec extends ScalaTestWithActorTestKit(PrimitiveStateSpec.co
       probe.expectMessage("eventHandler:1:2")
 
       ref1 ! -1
+      probe.expectTerminated(ref1)
+
       val ref2 = testKit.spawn(b)
       // eventHandler from reply
```
Comment (patriknw) [inline akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PrimitiveStateSpec.scala]: replay

File: akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PrimitiveStateSpec.scala [hunk 2]
```diff
@@ -54,6 +54,8 @@ class PrimitiveStateSpec extends ScalaTestWithActorTestKit(PrimitiveStateSpec.co
       probe.expectMessage("eventHandler:1:2")
 
       ref1 ! -1
+      probe.expectTerminated(ref1)
```
Comment (patriknw) [inline akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PrimitiveStateSpec.scala]: The failure was
```
java.lang.AssertionError: assertion failed: expected eventHandler:1:2, found onRecoveryCompleted:1
```

The event handler is actually invoked before persisting so next actor is started before 2 has been persisted and therefore only replays 1 and then `onRecoveryCompleted:1`.

Good!

**Review by patriknw — APPROVED** [review]
LGTM

File: akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PrimitiveStateSpec.scala (hunk 2 above)
Comment (chbatey) [reply akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PrimitiveStateSpec.scala]: Yup :+1:

**Review by johanandren — APPROVED** [review]
LGTM
