### PR TITLE
Fix TcpConnection error handling

### LINKED ISSUE #30509: TcpIntegrationSpec: should properly handle connection abort from client side
(there are a couple of other `TcpIntegrationSpec` failures that could be duplicates, but let's confirm that first)

https://github.com/akka/akka/runs/3278202293?check_suite_focus=true

```
[info] - should properly handle connection abort from client side *** FAILED *** (3 seconds, 46 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class akka.io.Tcp$ErrorClosed
[info]   at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
[info]   at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:571)
[info]   at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:543)
[info]   at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:159)
[info]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:973)
[info]   at akka.io.TcpIntegrationSpec$$anon$2.<init>(TcpIntegrationSpec.scala:49)
[info]   at akka.io.TcpIntegrationSpec.f$proxy3$1(TcpIntegrationSpec.scala:52)
[info]   at akka.io.TcpIntegrationSpec.$init$$$anonfun$4$$anonfun$3(TcpIntegrationSpec.scala:45)
```

### PR DESCRIPTION
**Pull request by raboof**
`resumeReading` can fail, and in that case will `become(unregistering)`.
Previously `become(connected(info))` would interfere with that.

Likely fixes #30509 and #30474. #30435 looks similar but might be something
different.

### CODE REVIEW

File: akka-actor/src/main/scala/akka/io/TcpConnection.scala [hunk 1]
```diff
@@ -74,11 +74,12 @@ private[io] abstract class TcpConnection(val tcp: TcpExt, val channel: SocketCha
...
       val info = ConnectionInfo(registration, handler, keepOpenOnPeerClosed, useResumeWriting)
 
+      context.setReceiveTimeout(Duration.Undefined)
+      context.become(connected(info))
+
       // if we are in push mode or already have resumed reading in pullMode while waiting for Register
       // then register OP_READ interest
       if (!pullMode || (/*pullMode && */ !readingSuspended)) resumeReading(info, None)
-      context.setReceiveTimeout(Duration.Undefined)
-      context.become(connected(info))
```
Comment (patriknw) [inline akka-actor/src/main/scala/akka/io/TcpConnection.scala:81]: Looks like the right thing to do, just curious to understand more...

> resumeReading can fail, and in that case will become(unregistering)

I don't understand what is handling that error. I see unregistring via stopWith, but how is that called via resumeReading?

Comment (raboof) [reply akka-actor/src/main/scala/akka/io/TcpConnection.scala:81]: `resumeReading` -> `doRead` -> `handleError` (in the 'catch' of the block starting with a call to `innerRead`) -> `stopWith`.

(I didn't find this by reading the code, but by logging a stacktrace in the repeat-job at #30510 ;) )

Comment (patriknw) [reply akka-actor/src/main/scala/akka/io/TcpConnection.scala:81]: right in front of me, I didn't see `doRead` - thanks

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by patriknw** [comment]
I closed the linked issues. Let's re-open or create new if they occur again.
