### PR TITLE
Delay operator emit early fix

### LINKED ISSUE #28269: Failed: FlowDelaySpec
https://jenkins.akka.io:8498/job/akka-nightly/7153/
https://jenkins.akka.io:8498/job/akka-multi-node/3764/
https://jenkins.akka.io:8498/job/akka-multi-node/3765/testReport/junit/akka.stream.scaladsl/FlowDelaySpec/A_Delay_must_not_throw_NPE_when_using_EmitEarly_and_buffer_is_full/
https://jenkins.akka.io:8498/job/akka-nightly-2.13/364/testReport/junit/akka.stream.scaladsl/FlowDelaySpec/A_Delay_must_not_throw_NPE_when_using_EmitEarly_and_buffer_is_full/
https://jenkins.akka.io:8498/job/akka-nightly/7151/testReport/junit/akka.stream.scaladsl/FlowDelaySpec/A_Delay_must_not_throw_NPE_when_using_EmitEarly_and_buffer_is_full/

```
 Vector(1, 2, 3, 4, 5, 6, 8) did not equal Range.Inclusive(1, 2, 3, 4, 5, 6, 7, 8, 9)
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:343)
	at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6859)
	at akka.stream.scaladsl.FlowDelaySpec.$anonfun$new$33(FlowDelaySpec.scala:269)
```

Looks like it started happening after #25000 was merged yesterday

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #28269

### CODE REVIEW

File: akka-stream/src/main/scala/akka/stream/OverflowStrategy.scala [hunk 1]
```diff
@@ -88,7 +88,7 @@ private[akka] object OverflowStrategies {
    * INTERNAL API
    */
   private[akka] case object EmitEarly extends DelayOverflowStrategy {
-    private[akka] override def isBackpressure: Boolean = false
+    private[akka] override def isBackpressure: Boolean = true
```
Comment (johanandren) [inline akka-stream/src/main/scala/akka/stream/OverflowStrategy.scala]: It's not really no-backpressure, it can't pull and emit early unless downstream is ready

File: akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala [hunk 2]
```diff
@@ -1697,40 +1697,49 @@ private[stream] object Collect {
...
+              if (isTimerActive(TimerName)) {
+                cancelTimer(TimerName)
+              }
 
               push(out, buffer.dequeue()._2)
               grabAndPull()
               completeIfReady()
+            } else {
+              throw new IllegalStateException(
+                "Was configured to emitEarly and got element when out is not ready and buffer is full, should not be possible.")
```
Comment (johanandren) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala]: This would happen before, and leave the element in the input port

File: akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala [hunk 3]
```diff
@@ -1768,39 +1777,41 @@ private[stream] object Collect {
...
           }
         }
       }
 
-      private def pullCondition: Boolean =
-        !overflowStrategy.isBackpressure || buffer.used < size
+      private def shouldPull: Boolean =
+        buffer.used < size || !overflowStrategy.isBackpressure ||
+        // we can only emit early if output is ready
+        (overflowStrategy == EmitEarly && isAvailable(out))
```
Comment (johanandren) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala]: Now we only pull on `EmitEarly` if out is ready and we actually can emit early.

File: akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala [hunk 4]
```diff
@@ -1601,8 +1601,10 @@ trait FlowOps[+Out, +Mat] {
    * @param of time to shift all messages
    * @param strategy Strategy that is used when incoming elements cannot fit inside the buffer
    */
-  def delay(of: FiniteDuration, strategy: DelayOverflowStrategy = DelayOverflowStrategy.dropTail): Repr[Out] =
-    via(new Delay[Out](() => DelayStrategy.fixedDelay(of), strategy))
+  def delay(of: FiniteDuration, strategy: DelayOverflowStrategy = DelayOverflowStrategy.dropTail): Repr[Out] = {
+    val fixedDelay = DelayStrategy.fixedDelay(of)
```
Comment (johanandren) [inline akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala]: We can reuse this across materializations for fixedDelay, it is immutable.

File: akka-stream/src/main/scala/akka/stream/OverflowStrategy.scala (hunk 1 above)
Comment (raboof) [reply akka-stream/src/main/scala/akka/stream/OverflowStrategy.scala]: Hmm, while I get it is 'not no-backpressure' this still seems a bit counter-intuitive... otoh without it the condition below would be something like `!isBackpressure && (s != EmitEarly || isAvailable(out))` which is not too readable either. OK since it's private :+1:

**Review by raboof — APPROVED** [review]

File: akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala [hunk 5]
```diff
@@ -1697,40 +1697,49 @@ private[stream] object Collect {
     }
 }
 
+/**
+ * INTERNAL API
+ */
+@InternalApi object Delay {
+  private val TimerName = "DelayedTimer"
```
Comment (patriknw) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala]: might be more efficient with `case object`, but maybe not important

**Review by patriknw — APPROVED** [review]
LGTM
