### PR TITLE
Java 9 Unsafe access to String value type mismatch.

### LINKED ISSUE #23702: Akka Remote issue with Artery and Java 9
Got the following exception at startup:
```
ERROR 14:01:06,265 Encoder - Failed to serialize message [akka.remote.artery.OutboundHandshake$HandshakeReq].
java.lang.ClassCastException: [B cannot be cast to [C
    at akka.remote.artery.EnvelopeBuffer.writeLiteral(BufferPool.scala:502) ~[akka-remote_2.12-2.5.4.jar:?]
    at akka.remote.artery.EnvelopeBuffer.writeHeader(BufferPool.scala:414) ~[akka-remote_2.12-2.5.4.jar:?]
    at akka.remote.MessageSerializer$.serializeForArtery(MessageSerializer.scala:84) ~[akka-remote_2.12-2.5.4.jar:?]
    at akka.remote.artery.Encoder$$anon$2.onPush(Codecs.scala:125) ~[akka-remote_2.12-2.5.4.jar:?]
    at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:499) ~[akka-stream_2.12-2.5.4.jar:?]
    at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:462) ~[akka-stream_2.12-2.5.4.jar:?]
    at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:368) ~[akka-stream_2.12-2.5.4.jar:?]
    at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:571) ~[akka-stream_2.12-2.5.4.jar:?]
    at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:457) ~[akka-stream_2.12-2.5.4.jar:?]
    at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:546) ~[akka-stream_2.12-2.5.4.jar:?]
    at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:725) ~[akka-stream_2.12-2.5.4.jar:?]
    at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:740) ~[akka-stream_2.12-2.5.4.jar:?]
    at akka.actor.Actor.aroundReceive(Actor.scala:514) ~[akka-actor_2.12-2.5.4.jar:?]
    at akka.actor.Actor.aroundReceive$(Actor.scala:512) ~[akka-actor_2.12-2.5.4.jar:?]
    at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:650) ~[akka-stream_2.12-2.5.4.jar:?]
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527) ~[akka-actor_2.12-2.5.4.jar:?]
    at akka.actor.ActorCell.invoke(ActorCell.scala:496) ~[akka-actor_2.12-2.5.4.jar:?]
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) ~[akka-actor_2.12-2.5.4.jar:?]
    at akka.dispatch.Mailbox.run(Mailbox.scala:224) ~[akka-actor_2.12-2.5.4.jar:?]
    at akka.dispatch.Mailbox.exec(Mailbox.scala:234) ~[akka-actor_2.12-2.5.4.jar:?]
    at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[akka-actor_2.12-2.5.4.jar:?]
    at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[akka-actor_2.12-2.5.4.jar:?]
    at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[akka-actor_2.12-2.5.4.jar:?]
    at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[akka-actor_2.12-2.5.4.jar:?]
```

### PR DESCRIPTION
**Pull request by guidomedina**
It needs to account for both Java 8 and 9 where the types are `char[]` and `byte[]` respectively.
Fixes #23702

### CODE REVIEW

**Comment by johanandren** [comment]
OK TO TEST

File: akka-actor/src/main/scala/akka/util/Unsafe.java [hunk 1]
```diff
@@ -23,8 +27,66 @@
...
+                stream(System.getProperty("java.specification.version").split("\\.")).
+                mapToInt(Integer::parseInt).
+                toArray();
+            javaVersion = version[0] == 1 ? version[1] : version[0];
         } catch (Throwable t) {
             throw new ExceptionInInitializerError(t);
         }
     }
+
+    public static void copyUSAsciiStrToBytes(String str, byte[] bytes) {
```
Comment (patriknw) [inline akka-actor/src/main/scala/akka/util/Unsafe.java]: s/Str/String/

File: akka-actor/src/main/scala/akka/util/Unsafe.java [hunk 2]
```diff
@@ -23,8 +27,66 @@
...
+        if (javaVersion > 8) {
+            final byte[] chars = (byte[]) instance.getObject(str, stringValueFieldOffset);
+            System.arraycopy(chars, 0, bytes, 0, chars.length);
+        } else {
+            final char[] chars = (char[]) instance.getObject(str, stringValueFieldOffset);
+            int i = 0;
+            while (i < chars.length) {
+                bytes[i] = (byte) chars[i++];
+            }
+        }
```
Comment (patriknw) [inline akka-actor/src/main/scala/akka/util/Unsafe.java]: Another way would be to check the type of `instance.getObject(str, stringValueFieldOffset)` with `instanceof` and select what to do based on that instead of the java version. Should have pretty much equal performance and might be more tolerant for other jvm implementations.

File: akka-remote/src/main/scala/akka/remote/artery/LruBoundedCache.scala [hunk 3]
```diff
@@ -3,39 +3,19 @@
...
+import akka.util.Unsafe
 
 import scala.annotation.tailrec
 import scala.reflect.ClassTag
 
 /**
  * INTERNAL API
  */
+@deprecated(message = "Use akka.util.Unsafe instead", since = "2.5.5")
 private[remote] object FastHash {
```
Comment (patriknw) [inline akka-remote/src/main/scala/akka/remote/artery/LruBoundedCache.scala]: this is internal API, so we can just remove it, and change all calls to `Unsafe.fastHash`

File: akka-actor/src/main/scala/akka/util/Unsafe.java [hunk 4]
```diff
@@ -23,8 +27,66 @@
...
+                long y = s1;
+
+                // Xorshift128+ round
+                s0 = y;
+                x ^= x << 23;
+                y ^= y >>> 26;
+                x ^= x >>> 17;
+                s1 = x ^ y;
+            }
+        }
```
Comment (patriknw) [inline akka-actor/src/main/scala/akka/util/Unsafe.java]: I guess it's not possible to DRY this without performance penalty.

* converting to `long[]` would mean another loop
* there is no common type for `byte[]` and `char[]` aside from `Object[]` and that would mean boxing

**Review by patriknw — COMMENTED** [review]
looking good, with a possible alternative that we could discuss

File: akka-actor/src/main/scala/akka/util/Unsafe.java (hunk 2 above)
Comment (guidomedina) [reply akka-actor/src/main/scala/akka/util/Unsafe.java]: `javaVersion` is a constant once calculated which might cause the JIT to remove one branch of the code and leaving a straight call to either Java 8 or 9 branch, that I don't think we will get with `instanceof`

I thought about it but then, being a documented property, is not so bad IMHO.

File: akka-remote/src/main/scala/akka/remote/artery/LruBoundedCache.scala (hunk 3 above)
Comment (guidomedina) [reply akka-remote/src/main/scala/akka/remote/artery/LruBoundedCache.scala]: Will remove, I left it because binary compatibility broke.

File: akka-remote/src/main/scala/akka/remote/artery/BufferPool.scala [hunk 5]
```diff
@@ -93,7 +88,7 @@ private[remote] object EnvelopeBuffer {
   val UsAscii = Charset.forName("US-ASCII")
```
Comment (guidomedina) [inline akka-remote/src/main/scala/akka/remote/artery/BufferPool.scala]: The next two `val`s are not needed but they broke binary compatibility, I would like very much to remove them.

**Comment by guidomedina** [comment]
@patriknw see 2nd commit for INTERNAL APIs, I will squash at the end for the sake of making diff easier.

File: akka-actor/src/main/scala/akka/util/Unsafe.java (hunk 4 above)
Comment (guidomedina) [reply akka-actor/src/main/scala/akka/util/Unsafe.java]: It crossed my mind to use `System.arraycopy` treating both as `Object`s but `char` = 2 bytes and `byte` = 1 byte.

File: akka-actor/src/main/scala/akka/util/Unsafe.java (hunk 1 above)
Comment (guidomedina) [reply akka-actor/src/main/scala/akka/util/Unsafe.java]: Do you mean `String Str` instead of `String str`? since it is a Java class I used the camel case convention?

**Comment by guidomedina** [comment]
After removing unused internal case class and 2 vals this is what is binary incompatible, which is all part of the 2nd commit, let me know if this is OK, or suggest alternative:
```
[info] akka-remote: found 4 potential binary incompatibilities while checking against com.typesafe.akka:akka-remote_2.11:2.5.0  (filtered 4)
[error]  * object akka.remote.artery.FastHash does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[MissingClassProblem]("akka.remote.artery.FastHash$")
[error]  * class akka.remote.artery.FastHash does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[MissingClassProblem]("akka.remote.artery.FastHash")
[error]  * method StringValueFieldOffset()Long in object akka.remote.artery.EnvelopeBuffer does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("akka.remote.artery.EnvelopeBuffer.StringValueFieldOffset")
[error]  * method UsAscii()java.nio.charset.Charset in object akka.remote.artery.EnvelopeBuffer does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("akka.remote.artery.EnvelopeBuffer.UsAscii")
```

**Comment by patriknw** [comment]
you can add those to akka-remote/src/main/mima-filters/2.5.4.backwards.excludes

**Comment by guidomedina** [comment]
Done and squashed everything back to  1 commit.

**Review by patriknw — APPROVED** [review]
LGTM

**Review by raboof — APPROVED** [review]

File: akka-actor/src/main/scala/akka/util/Unsafe.java (hunk 1 above)
Comment (ktoso) [reply akka-actor/src/main/scala/akka/util/Unsafe.java]: In the method name "StringToBytes" :)

**Comment by ktoso** [comment]
LGTM, and I'll follow up during the week with splitting it up into separate classes.

**Review by ktoso — APPROVED** [review]

File: akka-actor/src/main/scala/akka/util/Unsafe.java (hunk 1 above)
Comment (guidomedina) [reply akka-actor/src/main/scala/akka/util/Unsafe.java]: Can rename from `copyUSAsciiStrToBytes` to `copyStringToBytes` with the caveat that for Java 8 non-US ASCII are going to be truncated of their char representation needs more than 1 char.

Hence the preservation of `USAscii` in the name

Comment (patriknw) [reply akka-actor/src/main/scala/akka/util/Unsafe.java]: I meant `copyUSAsciiStringToBytes`, but it doesn't matter. Thanks for great contribution.

**Comment by gervaisb** [comment]
Hello there, I am reopening this old discussion because the line below broke my dreams:

    stringValueFieldOffset = instance.objectFieldOffset(String.class.getDeclaredField("value"));

I would like to run Akka on Android (8) but there is no `value` field in `String` in Android:

> // BEGIN Android-changed: The character data is managed by the runtime.
    // We only keep track of the length here and compression here. This has several consequences
    // throughout this class:
    //  - References to value[i] are replaced by charAt(i).
    //  - References to value.length are replaced by calls to length().
    //  - Sometimes the result of length() is assigned to a local variable to avoid repeated calls.
    //  - We skip several attempts at optimization where the values field was assigned to a local
    //    variable to avoid the getfield opcode.
    // These changes are not all marked individually.
    //
    // private final char value[];

Thus the line fail with:

    Caused by: java.lang.NoSuchFieldException: No field value in class Ljava/lang/String; (declaration of 'java.lang.String' appears in /system/framework/core-oj.jar)
        at java.lang.Class.getDeclaredField(Native Method)
        at akka.util.Unsafe.(Unsafe.java:36)

So. I would like to understand the reason behind the optimisations in `copyUSAsciiStrToBytes` and `fastHash`. And, maybe open a new PR to handle a "default" case that will use the public String API : `getBytes()` and `getChars()` in case the `stringValueFieldOffset` cannot be resolved.

What do you think?

**Comment by raboof** [comment]
> I would like to understand the reason behind the optimisations in `copyUSAsciiStrToBytes` and `fastHash`.

I don't think there is a particular reason beyond 'this came up a lot in hot paths during profiling/performance work so we want it to be fast' ;)

> maybe open a new PR to handle a "default" case that will use the public String API : `getBytes()` and `getChars()` in case the `stringValueFieldOffset` cannot be resolved

I don't think any of the current main contributors use Android, so we can't promise much hands-on help here, but if you can propose a fallback that does not hurt performance or introduce too much extra complexity, I think that could be interesting!

**Comment by hepin1989** [comment]
@gervaisb @raboof I know that the netty project does some platform checking as :
https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/internal/PlatformDependent0.java#L916

**Comment by gervaisb** [comment]
Thanks @hepin1989 for the link. Actually I was more thinking to implement a default strategy that will be applied in any cases where the optimisations are not applicable.

My personal point of view is that those who use Akka on such « non standard » systems can accept some performance degradation. Anyway, it is still better to have it working slower than not working at all. 

Do you (the community) prefer a specific Android strategy or a default one ?

**Comment by hepin1989** [comment]
Btw what the usercase for you to using Akka on Android? I was an Android dev :) @gervaisb

**Comment by patriknw** [comment]
> I don't think any of the current main contributors use Android, so we can't promise much hands-on help here, but if you can propose a fallback that does not hurt performance or introduce too much extra complexity, I think that could be interesting!

👍 

@gervaisb If I'm not mistaken, this could be a fairly small change. We already have a few strategies there for different environments. I think the issue you see is at this line https://github.com/akka/akka/blob/main/akka-actor/src/main/scala/akka/util/Unsafe.java#L36

That error can probably be caught and then fall back to `copyUSAsciiStrToBytesAlgorithm = 0`.

**Comment by gervaisb** [comment]
@patriknw Indeed that's the problematic line. And it seems that falling back to `copyUSAsciiStrToBytesAlgorithm = 0` will effectively solve this issue. 

Can someone here do this minor change or do you expect a PR from me (knowing that I have to set up everything)?

**Comment by patriknw** [comment]
We welcome contributions, and that's typically the quickest way to get things done in a OSS project. As Arnout said we are not testing with Android, so we can't guarantee anything and you might run into more things. That said, if it's too difficult for you we can probably make this change.

**Comment by steplica** [comment]
> > I don't think any of the current main contributors use Android, so we can't promise much hands-on help here, but if you can propose a fallback that does not hurt performance or introduce too much extra complexity, I think that could be interesting!
> 
> 👍
> 
> @gervaisb If I'm not mistaken, this could be a fairly small change. We already have a few strategies there for different environments. I think the issue you see is at this line https://github.com/akka/akka/blob/main/akka-actor/src/main/scala/akka/util/Unsafe.java#L36
> 
> That error can probably be caught and then fall back to `copyUSAsciiStrToBytesAlgorithm = 0`.

I'm also seeing this exact issue using akka-actor_2.11 `2.5.32` on a Tomcat application.
