### PR TITLE
Balancer should not push to a closed out #20943

### LINKED ISSUE #20943: Cannot push port (Balance.out8) twice
I'm getting this error using Akka Streams 2.4.8. I am not sure where it comes from, the stacktrace does not tell much:

```
[ERROR] [07/12/2016 14:02:27.093] [default-akka.actor.default-dispatcher-248] [akka://default/user/StreamSupervisor-18/flow-18-21-unknown-operation] Error in stage [Balance]: requirement failed: Cannot push port (Balance.out8) twice
java.lang.IllegalArgumentException: requirement failed: Cannot push port (Balance.out8) twice
        at scala.Predef$.require(Predef.scala:219)
        at akka.stream.stage.GraphStageLogic.push(GraphStage.scala:436)
        at akka.stream.scaladsl.Balance$$anon$17.akka$stream$scaladsl$Balance$$anon$$dequeueAndDispatch(Graph.scala:613)
        at akka.stream.scaladsl.Balance$$anon$17$$anon$18.onPush(Graph.scala:618)
        at akka.stream.impl.fusing.GraphInterpreter.processElement$1(GraphInterpreter.scala:590)
        at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:601)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:542)
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471)
        at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:410)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

I am using a [balancer](http://doc.akka.io/docs/akka/2.4.8/scala/stream/stream-cookbook.html#cookbook-balance-scala) to distribute lines processing from a file source.

### PR DESCRIPTION
**Pull request by johanandren**
Fixes  #20943

### CODE REVIEW

File: akka-stream/src/main/scala/akka/stream/scaladsl/Graph.scala [hunk 1]
```diff
@@ -610,8 +610,16 @@ final class Balance[T](val outputPorts: Int, waitForAllDownstreams: Boolean) ext
 
     private def dequeueAndDispatch(): Unit = {
       val out = pendingQueue.dequeue()
-      push(out, grab(in))
-      if (!noPending) pull(in)
+      if (out ne null) {
```
Comment (drewhk) [inline akka-stream/src/main/scala/akka/stream/scaladsl/Graph.scala]: add a comment, that this can happen because of the reentrancy in line L620 (we thrown out an "out" and there is no new one)

File: akka-stream/src/main/scala/akka/stream/scaladsl/Graph.scala [hunk 2]
```diff
@@ -610,8 +610,16 @@ final class Balance[T](val outputPorts: Int, waitForAllDownstreams: Boolean) ext
...
+        // the out triggering the pull may since closed
+        if (!isClosed(out)) {
+          push(out, grab(in))
+          if (!noPending) pull(in)
+        } else {
+          // try to find one that isn't closed in that case
+          dequeueAndDispatch()
```
Comment (drewhk) [inline akka-stream/src/main/scala/akka/stream/scaladsl/Graph.scala]: make it tailrec since it is private?

File: akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphBalanceSpec.scala [hunk 3]
```diff
@@ -256,6 +257,36 @@ class GraphBalanceSpec extends StreamSpec {
...
+      val sub2 = c2.expectSubscription()
+
+      sub1.request(1)
+      p1.expectRequest(bsub, 16)
+      bsub.sendNext(1)
+      c1.expectNext(1)
+
+      sub2.request(1)
+      sub2.cancel()
+      bsub.sendNext(2)
```
Comment (drewhk) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphBalanceSpec.scala]: above test is racy due to the fuzzer. This is not necessarily bad, just pointing out.

**Comment by drewhk** [comment]
LGTM, small nitpicks

File: akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphBalanceSpec.scala (hunk 3 above)
Comment (johanandren) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphBalanceSpec.scala]: Seems to fail consequently on my machine without the fix though. Should I run this test case without the fuzzer perhaps, just to be sure?

Comment (drewhk) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphBalanceSpec.scala]: ah, I know why. It is the Push-Pull chasing support which interferes here. I forgot to turn it off when fuzzing is on. Not a catastrophy. (with normal fuzzing it might be that the sendNext arrives before the cancel as they are concurrent)

**Comment by patriknw** [comment]
LGTM
