### PR TITLE
Fix double push message in sub source

### LINKED ISSUE #23929: SubSourceOutlet push should fail eagerly
As observed in akka/akka-http#1515, calling `outlet.push` will not fail directly but only later when the push is processed on the other side of the async boundary. On that side the error message has lost any context.

Afaics the fix might be as simple as checking `available` before pushing here:

https://github.com/akka/akka/blob/c663623300b30b1d748efb0ce7545e1eed8e0a08/akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala#L1224

### PR DESCRIPTION
**Pull request by mattsu6666**
fixes https://github.com/akka/akka/issues/23929

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
That's from the hakkathon in Tokyo! Thanks a lot Mattsu-san!

**Comment by ktoso** [comment]
Failure seems unrelated, was https://github.com/akka/akka/issues/24087

**Comment by ktoso** [comment]
PLS BUILD

**Comment by ktoso** [comment]
I added the name to the message aed0588ef3af340c066e7c433c55d5437a20ffe8 FYI @mattsu6  :)

**Comment by mattsu6** [comment]
Thank you, I check the code and fix it later

File: akka-stream-tests/src/test/scala/akka/stream/impl/GraphStageLogicSpec.scala [hunk 1]
```diff
@@ -32,6 +35,29 @@ class GraphStageLogicSpec extends StreamSpec with GraphInterpreterSpecKit {
     }
   }
 
+  class substreamEmit extends GraphStage[SourceShape[Source[Int, NotUsed]]] {
```
Comment (2m) [inline akka-stream-tests/src/test/scala/akka/stream/impl/GraphStageLogicSpec.scala]: Class names should start with a capital letter.

**Review by 2m — APPROVED** [review]
LGTM. Just a one small nitpitck.

**Comment by lightbend-cla-validator** [comment]
Hi @mattsu6,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

File: akka-stream-tests/src/test/scala/akka/stream/impl/GraphStageLogicSpec.scala (hunk 1 above)
Comment (mattsu6) [reply akka-stream-tests/src/test/scala/akka/stream/impl/GraphStageLogicSpec.scala]: Thank you for pointing it out.
I changed class name.

**Comment by ktoso** [comment]
Failure was the javac issue

File: akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala [hunk 2]
```diff
@@ -1361,6 +1361,7 @@ abstract class GraphStageLogic private[stream] (val inCount: Int, val outCount:
      * Push to this output port.
      */
     def push(elem: T): Unit = {
+      require(isAvailable, s"Cannot push port ($this) twice, or before it being pulled")
```
Comment (johanandren) [inline akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala]: I think we should have an `if (isAvailable) { throw ... }` here instead of allocating a closure/lambda (second parameter) for every element that is pushed.

**Review by johanandren — DISMISSED** [review]
Good fix, but I think we should avoid an allocation there.

File: akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala (hunk 2 above)
Comment (ktoso) [reply akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala]: Ok, we can do that in all places in the GraphStage then to be consistent -- I'll apply that and merge

**Comment by ktoso** [comment]
So I have the fix ready for what @johanandren commented on, but we need @mattsu6 to confirm the Contributor License Agreement before we can merge anyway: http://www.lightbend.com/contribute/cla

It's pretty simple @mattsu6, you just need to confirm on the above website using your github account that you're ok with contributing this source to Akka. Please do so and let us know, once that's done we can merge this PR (and I have the follow up ready)

**Review by ktoso — APPROVED** [review]

File: akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala (hunk 2 above)
Comment (patriknw) [reply akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala]: yes, that is important, should not be merged before that is fixed

**Review by patriknw — DISMISSED** [review]

**Comment by mattsu6** [comment]
@ktoso I just accepted that CLA.
Thanks for everyone for review and fixes!

But I dont know why we should change `apply()` to `if-statement`.
 `require()` and `if ... throw Exception` are not same mean?

**Comment by johanandren** [comment]
the second parameter of `require` is a by-name parameter, this is implemented in Scala by making it a function, this means that every time require is called a `Function0[String]` is created and passed to it, this is not an issue in most cases, but in a hot path such as element-push in streams it can be devastating as each element causes an allocation, and then the object needs to be garbage collected.

If you instead use a
```
if (!something) {
  throw new IllegalStateException("something was not right")
}
```

Nothing is allocated unless the check is true. You could see it as manually unfolding the logic of `require`.

**Comment by mattsu6** [comment]
Thank you for explanation! I understood.

**Comment by ktoso** [comment]
Confirmed CLA and will merge my follow up that changes the require's to if's

**Comment by ktoso** [comment]
For reference the PR with the require => ifs was merged: https://github.com/akka/akka/pull/24094
