### PR TITLE
Make sure it is obvious ctx.stop(non-child) does not work

### LINKED ISSUE #18524: ActorContext.stop only for child actors?
The parameter of `ActorContext.stop` is called `child` – is it not possible to stop other actors?

Also, maybe it would be nicer to use a polymorphic method to avoid `ActorRef[Nothing]`:

``` scala
def stop[A](actor: ActorRef[A]): Boolean
```

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #18524

### CODE REVIEW

File: akka-testkit-typed/src/main/scala/akka/testkit/typed/StubbedActorContext.scala [hunk 1]
```diff
@@ -81,9 +81,9 @@ private[akka] final class FunctionRef[-T](
    * Do not actually stop the child inbox, only simulate the liveness check.
    * Removal is asynchronous, explicit removeInbox is needed from outside afterwards.
    */
-  override def stop[U](child: ActorRef[U]): Boolean = {
+  override def stop[U](child: ActorRef[U]): Unit = {
```
Comment (raboof) [inline akka-testkit-typed/src/main/scala/akka/testkit/typed/StubbedActorContext.scala]: This implementation can be scrapped entirely (and the comment updated) now, right?

File: akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorContextAdapter.scala [hunk 2]
```diff
@@ -37,9 +37,14 @@ import akka.actor.typed.Behavior.UntypedBehavior
         untyped.child(child.path.name) match {
           case Some(`c`) ⇒
             untyped.stop(c)
-            true
+          case _ if child.path.parent != self.path ⇒
```
Comment (raboof) [inline akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorContextAdapter.scala]: 👍

File: akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorContextAdapter.scala [hunk 3]
```diff
@@ -28,7 +28,7 @@ import akka.actor.typed.Behavior.UntypedBehavior
     ActorContextAdapter.spawnAnonymous(untyped, behavior, props)
   override def spawn[U](behavior: Behavior[U], name: String, props: Props = Props.empty) =
     ActorContextAdapter.spawn(untyped, behavior, name, props)
-  override def stop[U](child: ActorRef[U]): Boolean =
+  override def stop[U](child: ActorRef[U]): Unit =
```
Comment (raboof) [inline akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorContextAdapter.scala]: Perhaps we might still want to keep the Boolean return value to expose whether the child had already been stopped? Not sure about the use case though, why did we have that?

Comment (johanandren) [reply akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorContextAdapter.scala]: Can't hink of why it was useful except for to test the internal path that was tekan.

File: akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorContextAdapter.scala (hunk 2 above)
Comment (johanandren) [reply akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorContextAdapter.scala]: Oh, wait, if the ref has the same name as a child this will break

**Comment by johanandren** [comment]
screen shot 2018-01-23 at 13 28 38

Thank you, formatting check...

File: akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/ActorContext.scala [hunk 4]
```diff
@@ -95,12 +95,11 @@ trait ActorContext[T] {
 
   /**
    * Force the child Actor under the given name to terminate after it finishes
-   * processing its current message. Nothing happens if the ActorRef does not
-   * refer to a current child actor.
+   * processing its current message. Nothing happens if the ActorRef is a child that is already stopped.
    *
-   * @return whether the passed-in [[ActorRef]] points to a current child Actor
+   * @throws IllegalArgumentException if the given actor ref is not a direct child of this actor
```
Comment (patriknw) [inline akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/ActorContext.scala]: also clarify that it will not throw if the given child actor is already stopped, i.e. it's idempotent

**Review by patriknw — COMMENTED** [review]
LGTM, with one small doc clarification.

Regarding keeping the Boolean for the case of if the child was already stopped. I think that for that rare case one can use `ctx.child` before calling stop.

File: akka-actor-typed-tests/src/test/scala/akka/actor/typed/ActorContextSpec.scala [hunk 5]
```diff
@@ -122,8 +122,12 @@ object ActorContextSpec {
           case Stop ⇒
             Behaviors.stopped
           case Kill(ref, replyTo) ⇒
-            if (ctx.stop(ref)) replyTo ! Killed
-            else replyTo ! NotKilled
+            try {
```
Comment (chbatey) [inline akka-actor-typed-tests/src/test/scala/akka/actor/typed/ActorContextSpec.scala]: I think you should refactor this test, maybe re-write it using our testkit :trollface:

File: akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorContextAdapter.scala [hunk 6]
```diff
@@ -28,20 +28,27 @@ import akka.actor.typed.Behavior.UntypedBehavior
...
+        case c ⇒
+          untyped.child(child.path.name) match {
+            case Some(`c`) ⇒
+              untyped.stop(c)
+            case _ ⇒
+            // child that was already stopped
+          }
+      }
+    } else {
+      throw new IllegalArgumentException(
```
Comment (chbatey) [inline akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorContextAdapter.scala]: +1

**Review by chbatey — APPROVED** [review]
LGTM

best branch name ever

File: akka-actor-typed-tests/src/test/scala/akka/actor/typed/ActorContextSpec.scala (hunk 5 above)
Comment (johanandren) [reply akka-actor-typed-tests/src/test/scala/akka/actor/typed/ActorContextSpec.scala]: I'm saving it for you.

File: akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/ActorContext.scala (hunk 4 above)
Comment (johanandren) [reply akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/ActorContext.scala]: Sentence above says: `Nothing happens if the ActorRef is a child that is already stopped.`

File: akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorContextAdapter.scala (hunk 6 above)
Comment (ktoso) [reply akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorContextAdapter.scala]: I kind of would want a specific error type here

**Review by ktoso — APPROVED** [review]
LGTM, one nitpick (would love to have specific exception types for such things)

File: akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorContextAdapter.scala (hunk 6 above)
Comment (johanandren) [reply akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorContextAdapter.scala]: Why, this would be triggered by incorrect code, it's not like you could ever recover from it (except by changing your code, and I don't think we have a supervisor doing that ;), https://github.com/munificent/vigil )

Comment (ktoso) [reply akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorContextAdapter.scala]: For understandability really. First thing I look at in failures is the exception type, it it already explains what went wrong then the message continues on to explain why etc

Comment (chbatey) [reply akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorContextAdapter.scala]: I'm on the fence, it is a programming error that really is an IllegalArgument and it'll be very obvious from the message what is wrong

Comment (ktoso) [reply akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorContextAdapter.scala]: `IllegalStopOfNonChildException extends IAE`
