### PR TITLE
Multi dc split brain test incorrect

### LINKED ISSUE #23288: MultiTeamSplitBrainMultiJvmSpec doesn't do what you think it does
D'oh:

```
class MultiTeamSplitBrainMultiJvmNode1 extends MultiTeamSpec
```

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #23288

### CODE REVIEW

File: akka-cluster/src/multi-jvm/scala/akka/cluster/MultiDcSplitBrainSpec.scala [hunk 1]
```diff
@@ -15,28 +16,29 @@ object MultiDcSplitBrainMultiJvmSpec extends MultiNodeConfig {
   val third = role("third")
   val fourth = role("fourth")
 
-  commonConfig(MultiNodeClusterSpec.clusterConfig)
+  commonConfig(ConfigFactory.parseString(
+    """
+      akka.loglevel = INFO
+      akka.cluster.run-coordinated-shutdown-when-down = off
```
Comment (patriknw) [inline akka-cluster/src/multi-jvm/scala/akka/cluster/MultiDcSplitBrainSpec.scala]: that should already be disabled by `src/test/resources.conf`

**Review by patriknw — APPROVED** [review]
LGTM, with one comment

File: akka-cluster/src/multi-jvm/scala/akka/cluster/MultiDcSplitBrainSpec.scala (hunk 1 above)
Comment (johanandren) [inline akka-cluster/src/multi-jvm/scala/akka/cluster/MultiDcSplitBrainSpec.scala]: Oh, got a weird fail with this log entry:
```
[JVM-1] [ERROR] [07/05/2017 10:59:52.425] [MultiDcSplitBrainSpec-akka.actor.default-dispatcher-4] [akka://MultiDcSplitBrainSpec/user/controller/barriers] unannounced disconnect of RoleName(fourth) (akka.remote.testconductor.BarrierCoordinator$ClientLost: unannounced disconnect of RoleName(fourth))
```
That I thought was because of it being enabled.

Comment (johanandren) [inline akka-cluster/src/multi-jvm/scala/akka/cluster/MultiDcSplitBrainSpec.scala]: Could it be a `resource.conf` override class path race?
