### PR TITLE
Also dilate the initial delay when testing timeouts in akka-stream-testkit

### LINKED ISSUE #30559: failed: StreamTestKitSpec
https://github.com/akka/akka/pull/30551/checks?check_run_id=3383191019#step:5:4597

```
[info] - must #expectNextWithTimeoutPF should fail after timeout when element delayed *** FAILED *** (199 milliseconds)
4598
[info]   Expected exception java.lang.AssertionError to be thrown, but no exception was thrown (StreamTestKitSpec.scala:122)
4599
[info]   org.scalatest.exceptions.TestFailedException:
4600
[info]   at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:472)
4601
[info]   at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:471)
4602
[info]   at akka.testkit.AkkaSpec.newAssertionFailedException(AkkaSpec.scala:54)
4603
[info]   at org.scalatest.Assertions.intercept(Assertions.scala:766)
4604
[info]   at org.scalatest.Assertions.intercept$(Assertions.scala:746)
4605
[info]   at akka.testkit.AkkaSpec.intercept(AkkaSpec.scala:54)
4606
[info]   at akka.stream.testkit.StreamTestKitSpec.$anonfun$new$23(StreamTestKitSpec.scala:122)
```

### PR DESCRIPTION
**Pull request by marcospereira**
Internally, `akka.testkit.TestProbe` dilates the given timeout using `-Dakka.test.timefactor`. Because of that, the initial delay also needs to be dilated.﻿

### CODE REVIEW

File: akka-stream-testkit/src/test/scala/akka/stream/testkit/StreamTestKitSpec.scala [hunk 1]
```diff
@@ -121,13 +122,17 @@ class StreamTestKitSpec extends AkkaSpec {
     "#expectNextWithTimeoutPF should fail after timeout when element delayed" in {
       intercept[AssertionError] {
         val timeout = 100.millis
-        val overTimeout = timeout + 50.millis
+        // Initial delay is over the timeout so an exception will be thrown.
+        // It also needs to be dilated since the testkit will eventually dilate
+        // the timeout accordingly to `-Dakka.test.timefactor` value.
```
Comment (octonato) [inline akka-stream-testkit/src/test/scala/akka/stream/testkit/StreamTestKitSpec.scala:127]: not essential for the PR, but I found the text here confusing. For example, "Initial delay is over the timeout". Do you mean "Initial delay is higher than the timeout"?

Also, why you say it will eventually dilate the timeout. I think you mean that it will dilate the timeout, no?

**Review by octonato — APPROVED** [review]
LGTM, but left comment about the comments in code. Maybe a second pass to make it more clear is needed.

File: akka-stream-testkit/src/test/scala/akka/stream/testkit/StreamTestKitSpec.scala (hunk 1 above)
Comment (marcospereira) [reply akka-stream-testkit/src/test/scala/akka/stream/testkit/StreamTestKitSpec.scala]: @octonato, see the comments now. I think they are clearer now.

File: akka-stream-testkit/src/test/scala/akka/stream/testkit/StreamTestKitSpec.scala [hunk 2]
```diff
@@ -121,13 +122,17 @@ class StreamTestKitSpec extends AkkaSpec {
     "#expectNextWithTimeoutPF should fail after timeout when element delayed" in {
       intercept[AssertionError] {
         val timeout = 100.millis
-        val overTimeout = timeout + 50.millis
+        // Initial delay is longer than the timeout so an exception will be thrown.
+        // It also needs to be dilated since the testkit will dilate the timeout
+        // accordingly to `-Dakka.test.timefactor` value.
+        val initialDelay = (timeout * 2).dilated
```
Comment (marcospereira) [inline akka-stream-testkit/src/test/scala/akka/stream/testkit/StreamTestKitSpec.scala:128]: This is now also doubling the timeout so that the tests will have a larger difference between values.

File: project/Paradox.scala [hunk 3]
```diff
@@ -69,11 +71,14 @@ object Paradox {
 
   val groupsSettings = Seq(Compile / paradoxGroups := Map("Language" -> Seq("Scala", "Java")))
 
+  val parsingSettings = Seq(Compile / paradoxParsingTimeout := 5.seconds)
```
Comment (marcospereira) [inline project/Paradox.scala:74]: I got a failure when running paradox here:

https://github.com/akka/akka/runs/3402299906?check_suite_focus=true#step:5:14828

I'm increasing the timeout to see if it helps, but also, I've fixed minor issues on the page where the error occurred

**Comment by marcospereira** [comment]
GH Actions pull request tests are failing for another reason:

https://github.com/akka/akka/pull/30561/checks?check_run_id=3403442366#step:5:19214

Cause is already documented here: https://github.com/akka/akka/issues/30532

**Comment by marcospereira** [comment]
@octonato I'm converting this to draft because I will move some of the changes to other pull requests later.

File: akka-stream-testkit/src/test/scala/akka/stream/testkit/StreamTestKitSpec.scala (hunk 2 above)
Comment (patriknw) [reply akka-stream-testkit/src/test/scala/akka/stream/testkit/StreamTestKitSpec.scala:128]: yes, there is no reason to make this too short

**Review by patriknw — APPROVED** [review]
LGTM
