### PR TITLE
Fix memory leak in watchWith (#26625)

### LINKED ISSUE #26625: watchWith memory leak
I'm investigating a memory leak we're seeing with our services using Akka 2.5.21.

We're using the [mqtt-streaming](https://github.com/akka/alpakka/tree/master/mqtt-streaming/src) connector, which is written in Akka Typed, and uses `context.watchWith` to watch an actor and receive a custom domain message when it terminates.

This appears to be causing a memory leak, as the entry in `DeathWatch`'s `terminatedQueued` is never removed. That set is only cleaned when a `Terminated` is received, which never happens when using `watchWith`.

I'll be submitting a PR shortly with a fix for this leak.

### PR DESCRIPTION
**Pull request by longshorej**
Instead of delivering the custom message, store it locally and then deliver it when the Terminated instance is received.

This ensures that `terminatedQueued` is properly cleaned when `watchWith` is used.

Fixes #26625

### CODE REVIEW

**Comment by longshorej** [comment]
Here's a screenshot of an application of our before this change:



And here's one after (CPU drop at the end is because it finished processing)

File: akka-actor/src/main/scala/akka/actor/dungeon/DeathWatch.scala [hunk 1]
```diff
@@ -81,15 +81,16 @@ private[akka] trait DeathWatch { this: ActorCell =>
...
+          terminatedQueuedFor(actor, optionalMessage)
         }
     }
     if (childrenRefs.getByRef(actor).isDefined) handleChildTerminated(actor)
   }
 
-  private[akka] def terminatedQueuedFor(subject: ActorRef): Unit =
-    terminatedQueued += subject
+  private[akka] def terminatedQueuedFor(subject: ActorRef, customMessage: Option[Any]): Unit =
+    if (!terminatedQueued.contains(subject))
```
Comment (longshorej) [inline akka-actor/src/main/scala/akka/actor/dungeon/DeathWatch.scala]: This check is to ensure that the `terminatedQueuedFor` invoked in `Stash#enqueueFirst` doesn't replace a potential custom message.

**Comment by longshorej** [comment]
CI tests passed, but MiMa issues. I haven't much experience with MiMa, so any advice would be appreciated!

```
[03-28 00:21:28.999] [info] All tests passed.
[03-28 00:21:29.002] [info] Passed: Total 708, Failed 0, Errors 0, Passed 708, Ignored 6, Pending 1
[03-28 00:21:36.051] [error] java.lang.RuntimeException: akka-actor: Binary compatibility check failed!
[03-28 00:21:36.051] [error] 	at scala.sys.package$.error(package.scala:26)
[03-28 00:21:36.051] [error] 	at com.typesafe.tools.mima.plugin.SbtMima$.reportModuleErrors(SbtMima.scala:83)
[03-28 00:21:36.051] [error] 	at com.typesafe.tools.mima.plugin.MimaPlugin$.$anonfun$mimaReportSettings$9(MimaPlugin.scala:76)
[03-28 00:21:36.051] [error] 	at com.typesafe.tools.mima.plugin.MimaPlugin$.$anonfun$mimaReportSettings$9$adapted(MimaPlugin.scala:59)
[03-28 00:21:36.051] [error] 	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:230)
[03-28 00:21:36.051] [error] 	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:461)
[03-28 00:21:36.051] [error] 	at com.typesafe.tools.mima.plugin.MimaPlugin$.$anonfun$mimaReportSettings$8(MimaPlugin.scala:59)
[03-28 00:21:36.051] [error] 	at com.typesafe.tools.mima.plugin.MimaPlugin$.$anonfun$mimaReportSettings$8$adapted(MimaPlugin.scala:44)
[03-28 00:21:36.051] [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[03-28 00:21:36.051] [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[03-28 00:21:36.051] [error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[03-28 00:21:36.051] [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[03-28 00:21:36.051] [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[03-28 00:21:36.051] [error] 	at sbt.Execute.work(Execute.scala:278)
[03-28 00:21:36.051] [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[03-28 00:21:36.051] [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[03-28 00:21:36.051] [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[03-28 00:21:36.051] [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[03-28 00:21:36.051] [error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[03-28 00:21:36.051] [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[03-28 00:21:36.051] [error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[03-28 00:21:36.051] [error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[03-28 00:21:36.051] [error] 	at java.lang.Thread.run(Thread.java:748)
[03-28 00:21:36.055] [error] (akka-actor / mimaReportBinaryIssues) akka-actor: Binary compatibility check failed!
```

**Comment by johanandren** [comment]
These are the actual MiMa warnings: 
```
[03-28 00:06:14.482] [error]  * method terminatedQueuedFor(akka.actor.ActorRef)Unit in class akka.actor.ActorCell does not have a correspondent in current version
[03-28 00:06:14.482] [error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("akka.actor.ActorCell.terminatedQueuedFor")
[03-28 00:06:14.483] [error]  * method terminatedQueuedFor(akka.actor.ActorRef)Unit in interface akka.actor.dungeon.DeathWatch does not have a correspondent in current version
[03-28 00:06:14.483] [error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("akka.actor.dungeon.DeathWatch.terminatedQueuedFor")
[03-28 00:06:14.483] [error]  * abstract synthetic method akka$actor$dungeon$DeathWatch$$terminatedQueued()scala.collection.immutable.Map in interface akka.actor.dungeon.DeathWatch is present only in current version
[03-28 00:06:14.483] [error]    filter with: ProblemFilters.exclude[ReversedMissingMethodProblem]("akka.actor.dungeon.DeathWatch.akka$actor$dungeon$DeathWatch$$terminatedQueued")
[03-28 00:06:14.483] [error]  * abstract synthetic method akka$actor$dungeon$DeathWatch$$terminatedQueued_=(scala.collection.immutable.Map)Unit in interface akka.actor.dungeon.DeathWatch is present only in current version
[03-28 00:06:14.483] [error]    filter with: ProblemFilters.exclude[ReversedMissingMethodProblem]("akka.actor.dungeon.DeathWatch.akka$actor$dungeon$DeathWatch$$terminatedQueued_=")
```

I think all changes are internal (`ActorCell` is and `dungeon` for sure is) so it should be safe to whitelist those as described in https://github.com/akka/akka/blob/master/CONTRIBUTING.md#binary-compatibility

File: akka-actor/src/main/scala/akka/actor/dungeon/DeathWatch.scala [hunk 2]
```diff
@@ -56,14 +56,14 @@ private[akka] trait DeathWatch { this: ActorCell =>
...
       }
-      terminatedQueued = removeFromSet(a, terminatedQueued)
+      terminatedQueued = removeFromMap(a, terminatedQueued)
       a
   }
 
   protected def receivedTerminated(t: Terminated): Unit =
-    if (terminatedQueued(t.actor)) {
+    terminatedQueued.get(t.actor).foreach { optionalMessage ⇒
       terminatedQueued -= t.actor // here we know that it is the SAME ref which was put in
```
Comment (patriknw) [inline akka-actor/src/main/scala/akka/actor/dungeon/DeathWatch.scala]: was this the leak? when it was a custom message the `receivedTerminated` was never invoked and therefore the `terminatedQueued` wasn't cleared

File: akka-actor/src/main/scala/akka/actor/dungeon/DeathWatch.scala [hunk 3]
```diff
@@ -81,15 +81,16 @@ private[akka] trait DeathWatch { this: ActorCell =>
           watching = removeFromMap(actor, watching)
         }
         if (!isTerminating) {
-          self.tell(optionalMessage.getOrElse(Terminated(actor)(existenceConfirmed, addressTerminated)), actor)
-          terminatedQueuedFor(actor)
+          self.tell(Terminated(actor)(existenceConfirmed, addressTerminated), actor)
```
Comment (patriknw) [inline akka-actor/src/main/scala/akka/actor/dungeon/DeathWatch.scala]: This looks more correct than before since it follows the same code path all the way as the `Terminated` message, e.g. there could have been an unwatch inbetween here and the actual delivery of the custom message.

**Review by patriknw — APPROVED** [review]
LGTM, I have reviewed carefully and it looks correct

**Comment by patriknw** [comment]
@longshorej Thanks for investigating and fixing this important bug

File: akka-actor/src/main/scala/akka/actor/dungeon/DeathWatch.scala (hunk 2 above)
Comment (longshorej) [reply akka-actor/src/main/scala/akka/actor/dungeon/DeathWatch.scala]: Yep! Thanks for the quick review!

**Review by johanandren — APPROVED** [review]
LGTM, thanks @longshorej !

**Review by raboof — APPROVED** [review]
Indeed more consistent to have the `Terminated` go through `autoReceiveMessage` for custom termination messages as well, and plausible that this fixes the leak. Thanks!

**Comment by patriknw** [comment]
Let's merge after validation has completed

**Comment by longshorej** [comment]
Thanks!
