### PR TITLE
#20142: Fix implicit sender closure in TcpConnectionsStage

### LINKED ISSUE #20142: ServerBinding.unbind() throws exception if the actor system has already stopped
The ```unbind``` method of ```akka.http.scaladsl.Http.ServerBinding``` seems to throw a ```StageActorRefNotInitializedException```, if it's called after the actor system has been already terminated. This can happen in practice, if a shutdown hook is registered (with ```scala.sys.addShutdownHook```) to call ```unbind```. I guess the expected behavior would be for ```unbind``` to be a no-op in this case.

This is the stack trace with a synthetic example (https://github.com/durban/akka-typed-examples/blob/9cec09c6786f6edf8bc242b2ec3f74450026f624/src/main/scala/com/example/http/Unbinding.scala):
```
[error] (run-main-0) akka.stream.stage.GraphStageLogic$StageActorRefNotInitializedException: You must first call getStageActorRef, to initialize the Actors behaviour
akka.stream.stage.GraphStageLogic$StageActorRefNotInitializedException: You must first call getStageActorRef, to initialize the Actors behaviour
        at akka.stream.stage.GraphStageLogic.stageActor(GraphStage.scala:878)
        at akka.stream.impl.io.ConnectionSourceStage$$anon$1.self(TcpStages.scala:51)
        at akka.stream.impl.io.ConnectionSourceStage$$anon$1$$anonfun$akka$stream$impl$io$ConnectionSourceStage$$anon$$receive$1.apply(TcpStages.scala:69)
        at akka.stream.impl.io.ConnectionSourceStage$$anon$1$$anonfun$akka$stream$impl$io$ConnectionSourceStage$$anon$$receive$1.apply(TcpStages.scala:69)
        at akka.stream.scaladsl.Tcp$ServerBinding.unbind(Tcp.scala:27)
        at akka.http.scaladsl.HttpExt$$anonfun$bind$2$$anonfun$apply$2$$anonfun$apply$3.apply(Http.scala:91)
        at akka.http.scaladsl.HttpExt$$anonfun$bind$2$$anonfun$apply$2$$anonfun$apply$3.apply(Http.scala:91)
        at akka.http.scaladsl.Http$ServerBinding.unbind(Http.scala:680)
        at com.example.http.Unbinding$.main(Unbinding.scala:29)
        at com.example.http.Unbinding.main(Unbinding.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
```

### PR DESCRIPTION
**Pull request by drewhk**
Fixes #20142

### CODE REVIEW

File: akka-stream/src/main/scala/akka/stream/impl/io/TcpStages.scala [hunk 1]
```diff
@@ -64,8 +64,13 @@ private[stream] class ConnectionSourceStage(val tcpManager: ActorRef,
             listener = sender
             stageActor.watch(listener)
             if (isAvailable(out)) listener ! ResumeAccepting(1)
-            val target = self
-            bindingPromise.success(ServerBinding(localAddress)(() ⇒ { target ! Unbind; unbindPromise.future }))
+            val thisStage = self
+            bindingPromise.success(ServerBinding(localAddress)(() ⇒ {
+              // Beware, sender must be explicit since stageActor.ref will be invalid to access after the stage
+              // stopped.
+              thisStage.tell(Unbind, thisStage)
```
Comment (patriknw) [inline akka-stream/src/main/scala/akka/stream/impl/io/TcpStages.scala]: great!

**Comment by patriknw** [comment]
LGTM
