### PR TITLE
=htc #17187 fix illegal request entities not producing the right error response

### LINKED ISSUE #17187: 500 ISE for Client Side Error
akka-http M5

If you submit a HEAD request which has an entity body, you get back a 500 Internal Server Error.  The exception that triggers this is a require stating "Requests with this method must have an empty entity".

This requirement can only be satisfied by a client however, so a 4xx series error seems more appropriate here?

```
cc2 [ERROR] [04/13/2015 16:01:07.698] [cloud-controller-akka.actor.default-dispatcher-27] [ActorSystem(cloud-controller)] Internal server error, sending 500 response
cc2 java.lang.IllegalArgumentException: requirement failed: Requests with this method must have an empty entity
cc2 	at scala.Predef$.require(Predef.scala:219)
cc2 	at akka.http.model.HttpRequest.<init>(HttpMessage.scala:133)
cc2 	at akka.http.engine.server.HttpServer$$anonfun$6.apply(HttpServer.scala:87)
cc2 	at akka.http.engine.server.HttpServer$$anonfun$6.apply(HttpServer.scala:83)
cc2 	at akka.stream.impl.fusing.Map.onPush(Ops.scala:16)
cc2 	at akka.stream.impl.fusing.OneBoundedInterpreter$$anon$1.run(Interpreter.scala:317)
cc2 	at akka.stream.impl.fusing.OneBoundedInterpreter$State$class.progress(Interpreter.scala:224)
cc2 	at akka.stream.impl.fusing.OneBoundedInterpreter$$anon$1.progress(Interpreter.scala:315)
cc2 	at akka.stream.impl.fusing.OneBoundedInterpreter.akka$stream$impl$fusing$OneBoundedInterpreter$$execute(Interpreter.scala:447)
cc2 	at akka.stream.impl.fusing.OneBoundedInterpreter$$anon$6.push(Interpreter.scala:535)
cc2 	at akka.stream.impl.fusing.BatchingActorInputBoundary$$anonfun$upstreamRunning$1.applyOrElse(ActorInterpreter.scala:139)
cc2 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
cc2 	at akka.stream.impl.SubReceive.apply(Transfer.scala:16)
cc2 	at akka.stream.impl.SubReceive.apply(Transfer.scala:12)
cc2 	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
cc2 	at akka.stream.impl.SubReceive.applyOrElse(Transfer.scala:12)
cc2 	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
cc2 	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
cc2 	at akka.stream.impl.fusing.ActorInterpreter.aroundReceive(ActorInterpreter.scala:310)
cc2 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
cc2 	at akka.actor.ActorCell.invoke_aroundBody0(ActorCell.scala:487)
cc2 	at akka.actor.ActorCell$AjcClosure1.run(ActorCell.scala:1)
cc2 	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
cc2 	at akka.kamon.instrumentation.ActorCellInstrumentation$$anonfun$aroundBehaviourInvoke$1.apply(ActorCellInstrumentation.scala:62)
cc2 	at kamon.trace.Tracer$.withContext(Tracer.scala:56)
cc2 	at akka.kamon.instrumentation.ActorCellInstrumentation.aroundBehaviourInvoke(ActorCellInstrumentation.scala:61)
cc2 	at akka.actor.ActorCell.invoke(ActorCell.scala:483)
cc2 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
cc2 	at akka.dispatch.Mailbox.run(Mailbox.scala:221)
cc2 	at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
cc2 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
cc2 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
cc2 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
cc2 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

### PR DESCRIPTION
**Pull request by sirthias**
Fixes #17187.

/cc @jrudolph

### CODE REVIEW

**Comment by drewhk** [comment]
LGTM

File: akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpRequestParser.scala [hunk 1]
```diff
@@ -177,6 +179,9 @@ private[http] class HttpRequestParser(_settings: ParserSettings,
             parseFixedLengthBody(contentLength, closeAfterResponseCompletion)(input, bodyStart)
           }
 
+        case Some(_) if !method.isEntityAccepted ⇒
```
Comment (jrudolph) [inline akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpRequestParser.scala]: FWIW Is a `Transfer-Encoding` header generally forbidden for those methods? It seems, it is by this sentence [from RFC 7230](http://tools.ietf.org/html/rfc7230#section-3.3):

> The presence of a message body in a request is signaled by a Content-Length or Transfer-Encoding header field.

File: akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpRequestParser.scala [hunk 2]
```diff
@@ -177,6 +179,9 @@ private[http] class HttpRequestParser(_settings: ParserSettings,
...
+          failMessageStart(UnprocessableEntity, s"${method.name} requests must not have an entity")
```
Comment (jrudolph) [inline akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpRequestParser.scala]: There's a slight possibility to DRY things up here a bit ;)

**Comment by jrudolph** [comment]
LGTM otherwise.

File: akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpRequestParser.scala (hunk 1 above)
Comment (sirthias) [inline akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpRequestParser.scala]: Yes, make take would be so as well. The `Transfer-Encoding` header always contains meta info on the message entity. So, if there is no entity a `Transfer-Encoding` header makes no sense.

File: akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpRequestParser.scala (hunk 2 above)
Comment (sirthias) [inline akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpRequestParser.scala]: Yeah, but since it wouldn't save a single line I went for the duplication instead... :)

**Comment by sirthias** [comment]
Fixed broken test causing the validation error before.

File: akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpRequestParser.scala [hunk 3]
```diff
@@ -167,6 +167,8 @@ private[http] class HttpRequestParser(_settings: ParserSettings,
             emitRequestStart(emptyEntity(cth))
             setCompletionHandling(HttpMessageParser.CompletionOk)
             startNewMessage(input, bodyStart)
+          } else if (!method.isEntityAccepted) {
+            failMessageStart(UnprocessableEntity, s"${method.name} requests must not have an entity")
```
Comment (2beaucoup) [inline akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpRequestParser.scala]: Should the `isEntityAccepted` check get removed [here](https://github.com/akka/akka/blob/release-2.3-dev/akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpMessage.scala#L144) then?

Comment (sirthias) [inline akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpRequestParser.scala]: No, I'd vote to keep it there.
The `require` in the `HttpRequest` makes sure that we find problems like the one fixed here.
Also, it protects users from creating illegal requests in the first place.

Comment (2beaucoup) [inline akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpRequestParser.scala]: I was thinking about https://github.com/akka/akka/issues/17214 which might be out of scope here.

**Comment by drewhk** [comment]
is it merge ready?

File: akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpRequestParser.scala (hunk 3 above)
Comment (sirthias) [inline akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpRequestParser.scala]: Yes, that's another question that I wanted to keep out of this fix here.

**Comment by sirthias** [comment]
@drewhk Yes, all good from my side.

**Comment by drewhk** [comment]
thanks!
