### PR TITLE
=htc Simplify and fix pool gateway synchronization

### LINKED ISSUE #20032: User-provided materializer will be used to create system wide objects
`Http().singleRequest()` creates or reuses a cached connection stored in a ActorSystem-wide pool. However, this connection is created using the user-provided materializer. If this materializer is tied to an actor through its `context`, other actors will no longer be able to contact the same host/port after the initial materializer has been shutdown.

This is likely to happen if the user has a `implicit val materializer = ActorMaterializer()(context)` in their actor.

ActorSystem-wide cached objects should be created using a materializer with an ActorSystem scope instead of the materializer provided by the caller.

The following example illustrates the problem:

``` scala
import akka.actor.ActorSystem
import akka.http.scaladsl.Http
import akka.http.scaladsl.model.{HttpRequest, HttpResponse}
import akka.stream.ActorMaterializer
import akka.stream.scaladsl.Flow
import org.specs2.mutable._

import scala.concurrent.Await
import scala.concurrent.duration._

class MaterializerSpec extends Specification {

  implicit val system = ActorSystem("test-system")
  implicit val dispatcher = system.dispatcher
  val systemMaterializer = ActorMaterializer()(system)

  val handler = Flow[HttpRequest].map(_ => new HttpResponse())
  val bindingFuture = Http().bindAndHandle(handler, "localhost", 0)(systemMaterializer)
  val port = Await.result(bindingFuture.map(_.localAddress.getPort), 1.second)
  val uri = s"http://localhost:$port"

  "non-global materializer should not be globally stored" in {

    {
      implicit val localMaterializer = ActorMaterializer()(system)
      // The local materializer will wrongly be used to create an ActorSystem-wide connection
      // in the cached connection pool.
      val response = Await.result(Http().singleRequest(new HttpRequest(uri = uri)), 1.second)
      localMaterializer.shutdown()
      response.status.intValue() must be equalTo 200
    }
    {
      implicit val localMaterializer = ActorMaterializer()(system)
      // The following request will fail with a timeout because the local materializer of the
      // first request has been used to create the cached connection in the connection pool.
      //
      // Commenting the local materializer shutdown above will make it work as the previous
      // materializer would still be alive.

      // Using a request to another host/port will also work as a new connection will be
      // created in the connection pool with this local materializer.
      val response = Await.result(Http().singleRequest(new HttpRequest(uri = uri)), 1.second)
      localMaterializer.shutdown()
      response.status.intValue() must be equalTo 200
    }
  }
}
```

### LINKED ISSUE #20071: akka-http client PoolGateway stuck in spinloop, eventually using 100% CPU
Unfortunately, I don't currently know *why* or *how* it happens, but it is possible for the `state` in a `PoolGateway` to be set to a `NewIncarnation(newGatewayFuture)`, where `newGatewayFuture` is a `FastFuture.successful(..)` of it self.

In other words, at https://github.com/akka/akka/blob/master/akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala#L57, `this == previousIncarnation`. By attaching a debugger to the process I've added a breakpoint that doesn't suspend, but only logs `this` and `previousIncarnation`, and it keeps logging the following:

    this: akka.http.impl.engine.client.PoolGateway@79fcbcef - previous: akka.http.impl.engine.client.PoolGateway@79fcbcef
    this: akka.http.impl.engine.client.PoolGateway@1df76436 - previous: akka.http.impl.engine.client.PoolGateway@1df76436
    this: akka.http.impl.engine.client.PoolGateway@516279e7 - previous: akka.http.impl.engine.client.PoolGateway@516279e7
    this: akka.http.impl.engine.client.PoolGateway@79fcbcef - previous: akka.http.impl.engine.client.PoolGateway@79fcbcef
    this: akka.http.impl.engine.client.PoolGateway@1df76436 - previous: akka.http.impl.engine.client.PoolGateway@1df76436
    this: akka.http.impl.engine.client.PoolGateway@516279e7 - previous: akka.http.impl.engine.client.PoolGateway@516279e7

I'm guessing it's a race condition somewhere as it does not happen often, but when it does, the thread that's running calling the method will spin.

Observations from canary-ing it in production is that it can take a long time before it occurs (last time for me it took 90 hours under moderate workload for it to happen to the first thread), but just a few hours until there were four requests spinning (on a server with four cpu cores.). Hopefully that observation may help in finding the cause.

I'm seeing this using the following version(s):

    "com.typesafe.akka:akka-actor_2.11:2.4.2",
    "com.typesafe.akka:akka-http-core_2.11:2.4.2",
    "com.typesafe.akka:akka-http-experimental_2.11:2.4.2",
    "com.typesafe.akka:akka-parsing_2.11:2.4.2",
    "com.typesafe.akka:akka-stream_2.11:2.4.2",

### LINKED ISSUE #20080: Separate host connection pools might be reunited later
If the user creates two `newHostConnectionPool()` with the same settings, it gets two independent pools with a given number of `max-connections` (one `PoolGateway`/`PoolInterfaceActor` per pool).

However, if those two pools are shutdown because `idle-timeout` is reached, they will both be replaced by a new incarnation of the same `PoolGateway`/`PoolInterfaceActor` (obtained from `Http().cachedGateway(hcps)`) and will have their connections shared while they were created independently. As a consequence, whereas the user could queue up to `max-connections*2` requests originally, they can now only queue up to `max-connections` before an error is thrown.

The new pools should be created without using the pool cache.

### LINKED ISSUE #20081: Remove race condition documented in PoolInterfaceActor
The pool recreation mechanism after an idle timeout has a race condition which is documented in `PoolInterfaceActor.scala`:

```
// Note that this forwarding will stop when we receive completion from the pool flow
// (because we stop ourselves then), so there is a very small chance of a request ending
// up as a dead letter if the sending thread gets interrupted for a long time right before
// the `ref ! PoolRequest(...)` in the PoolGateway
```

This race condition should be removed, as it might lead to a lockup in user code as the request will never receive a response, even after the programmed timeouts have expired.

### PR DESCRIPTION
**Pull request by samueltardieu**
Rewrite the pool gateway synchronization so that:
- The collapsing chain of gateways and the cache in HttpExt have been replaced by a PoolMasterActor which takes care of orchestrating the various PoolInterfaceActor.
- The documented race condition in PoolInterfaceActor is gone. No PoolInterfaceActor will receive new requests after the gateway shutdown has been initiated (fix #20081).
- A gateway created by newHostConnectionPool is never merged with the cached pools (fix #20080).
- A gateway created by newHostConnectionPool will use the given materializer for every incarnation of the PoolInterfaceActor. Gateways pointing to cached connection pools will use an ActorSystem-wide gateway (fix #20032).
- By construction, the bug where the collapsing chain of gateways can contain dependency loops no longer exists (fix #20071).

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by samueltardieu** [comment]
Rebased

**Comment by viktorklang** [comment]
What were the alternate solutions explored prior to choosing the lockbased one?

**Comment by samueltardieu** [comment]
I tried to keep a solution based on CAS (plus a loop at shutdown time) as was done before, but I couldn't remove the race condition present at https://github.com/akka/akka/blob/master/akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala#L60 : if a context switch happens just before this line, we might in the meantime have sent a shutdown message to the pool interface actor (this is documented at https://github.com/akka/akka/blob/master/akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolInterfaceActor.scala#L130-L133). The result might be very bad, as the client will never be notified that the request did not get through, not even through the various timeouts set on the request.

The only bulletproof solution I found for this issue was to ensure that once the shutdown message has been sent to the interface actor, no new request can be sent to it as the actor will not have a chance to forward it back to the gateway. We really need an atomic "check gateway state / send request to pool interface actor if ok" test here. We could use an extra actor to serialize the requests, but that would be much more costly than using a short-lived lock.

**Comment by viktorklang** [comment]
@samueltardieu was it considered to go through an actor instead of going though a lock?

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala [hunk 1]
```diff
@@ -4,24 +4,26 @@
...
 import akka.stream.Materializer
 
+import scala.concurrent.{ Future, Promise }
+
 private object PoolGateway {
 
   sealed trait State
   final case class Running(interfaceActorRef: ActorRef,
-                           shutdownStartedPromise: Promise[Done],
+                           shutdownStartedPromise: Option[Promise[Done]],
```
Comment (viktorklang) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala]: Why is this an option rather than introducing a ShutdownStarted data type?

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala [hunk 2]
```diff
@@ -39,56 +41,74 @@ private object PoolGateway {
...
-    new AtomicReference[State](Running(ref, _shutdownStartedPromise, shutdownCompletedPromise))
+    Running(ref, _shutdownStartedPromise, shutdownCompletedPromise)
   }
 
-  def currentState: Any = state.get() // enables test access
+  private[this] val lock = new ReentrantLock(true)
 
-  def apply(request: HttpRequest, previousIncarnation: PoolGateway = null): Future[HttpResponse] =
-    state.get match {
+  def currentState: Any = state // enables test access
```
Comment (viktorklang) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala]: This is not threadsafe

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala [hunk 3]
```diff
@@ -39,56 +41,74 @@ private object PoolGateway {
...
+
+  private def setCurrentState(newState: State) = {
```
Comment (viktorklang) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala]: return type

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala [hunk 4]
```diff
@@ -39,56 +41,74 @@ private object PoolGateway {
...
+    lock.unlock()
+  }
+
+  def apply(request: HttpRequest, previousIncarnation: PoolGateway = null): Future[HttpResponse] = {
+    lock.lock()
+    state match {
       case Running(ref, _, _) ⇒
         val responsePromise = Promise[HttpResponse]()
         ref ! PoolInterfaceActor.PoolRequest(request, responsePromise)
+        lock.unlock()
```
Comment (viktorklang) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala]: unlock may not get called if Running-extractor throws, or if it cannot allocate a Promise of PoolRequest or if !-throws.

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala [hunk 5]
```diff
@@ -39,56 +41,74 @@ private object PoolGateway {
...
-          apply(request)
-        }
+      case IsShutdown(shutdownCompleted, recreateFromCache) ⇒
+        // Delay starting the next pool incarnation until the current pool has completed its shutdown.
+        // If this gateway was created through the gateway cache, go through the cache again.
+        val newGatewayFuture = shutdownCompleted.flatMap(_ ⇒
+          if (recreateFromCache) FastFuture.successful(new PoolGateway(hcps))
+          else Http().cachedGateway(hcps))
+        state = NewIncarnation(newGatewayFuture)
+        lock.unlock()
```
Comment (viktorklang) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala]: Multiple reasons why this might not get called

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala [hunk 6]
```diff
@@ -39,56 +41,74 @@ private object PoolGateway {
...
+    lock.lock()
+    state match {
       case x @ Running(ref, shutdownStartedPromise, shutdownCompletedPromise) ⇒
-        if (state.compareAndSet(x, IsShutdown(shutdownCompletedPromise.future))) {
-          shutdownStartedPromise.success(Done) // trigger cache removal
-          ref ! PoolInterfaceActor.Shutdown
-          shutdownCompletedPromise.future
-        } else shutdown() // CAS loop (not a spinlock)
+        state = IsShutdown(shutdownCompletedPromise.future, shutdownStartedPromise.isDefined)
+        lock.unlock()
```
Comment (viktorklang) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala]: might not get called

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala [hunk 7]
```diff
@@ -39,56 +41,74 @@ private object PoolGateway {
...
+        shutdownCompletedPromise.future
 
-      case IsShutdown(x)                    ⇒ x
+      case IsShutdown(x, _) ⇒
+        lock.unlock()
+        x
 
-      case NewIncarnation(newGatewayFuture) ⇒ newGatewayFuture.flatMap(_.shutdownAux())
+      case NewIncarnation(newGatewayFuture) ⇒
+        lock.unlock()
```
Comment (viktorklang) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala]: might not get called

**Comment by samueltardieu** [comment]
@viktorklang Yes, it is mentioned in the last sentence of my previous reply.

Using an actor to replace the lock could be done in two ways:

1. We use an actor per pool interface to replace the lock. Right now, the user can keep a reference onto the gateway as long as they want, even if the gateway has been shutdown. This is why there is a mechanism to build a collapsing chain of gateways corresponding to the successive incarnations of the gateway and their respective pool interface actor. Right now (before and after the proposed change), the non-collapsed part of the chain is reclaimed by the GC when the user drop its last reference to the pool. We would have no way of shutting down the locking actor when the last reference is dropped, so we would leak actors.
2. We use a unique actor to represent the locks for all the pools. In this case, we are adding contention between the various pools while they are kept independent from each other with the lock.

Both ways seem to cause more problems than they solve.

**Comment by viktorklang** [comment]
@samueltardieu The difference is that by using a single actor there is no actual blocking. whereas with the lock-based approach there is locking for both reads and writes. Also, what's the difference in performance and maintainability?

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala [hunk 8]
```diff
@@ -39,56 +41,74 @@ private object PoolGateway {
...
+  private[this] var state: State = {
     val shutdownCompletedPromise = Promise[Done]()
     val props = Props(new PoolInterfaceActor(hcps, shutdownCompletedPromise, this)).withDeploy(Deploy.local)
     val ref = system.actorOf(props, PoolInterfaceActor.name.next())
-    new AtomicReference[State](Running(ref, _shutdownStartedPromise, shutdownCompletedPromise))
+    Running(ref, _shutdownStartedPromise, shutdownCompletedPromise)
   }
 
-  def currentState: Any = state.get() // enables test access
+  private[this] val lock = new ReentrantLock(true)
```
Comment (viktorklang) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala]: why true?

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala [hunk 9]
```diff
@@ -39,56 +41,74 @@ private object PoolGateway {
...
-                                _shutdownStartedPromise: Promise[Done])( // constructor arg only
+                                _shutdownStartedPromise: Option[Promise[Done]] = None)( // used for cache invalidation
                                   implicit system: ActorSystem, fm: Materializer) {
   import PoolGateway._
   import fm.executionContext
 
-  private val state = {
+  private[this] var state: State = {
     val shutdownCompletedPromise = Promise[Done]()
     val props = Props(new PoolInterfaceActor(hcps, shutdownCompletedPromise, this)).withDeploy(Deploy.local)
```
Comment (viktorklang) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala]: This leaks `this` to another thread ( the actor's thread) before fully constructed.

**Comment by samueltardieu** [comment]
Performance wise, the lock is held for very short periods of time (it is never used as reentrant and does not contain blocking operations as far as I can tell). The parts between the lock are (in code order) one of:

- new request when gateway is up: compare state / create Promise / send message
- new request when gateway has been shut down: compare state / map existing future  / set state
- new request when gateway has a new incarnation: compare state / map existing future / set state, followed by (at most once per old/new incarnation pair to collapse the chain): set state
- shutdown when gateway is up: compare state / set state
- shutdown when gateway has been shut down: compare state
- shutdown when gateway has a new incarnation: compare state

However, the Actor approach has a certain appeal if the actor was in charge of maintaining the relationships between the gateway and the pool interface actors and may be able to handle the state of those actors quite elegantly. I'll try come up with a comparaison after my afternoon meetings, I'll keep you posted.

**Comment by viktorklang** [comment]
@samueltardieu Looking forward to hearing more. (also, time holding the lock is impacted by thread scheduling artifacts). Since were talking about things aimed at Java8, I suspect a StampedLock would be more scalable than ReentrantLock if you indeed do not rely on reentrancy.

**Comment by samueltardieu** [comment]
@viktorklang Indeed the actor-based solution looks more elegant.

How/when can I stop the `PoolMasterActor` created in `HttpExt`? `Http().shutdownAllConnectionPools()` could terminate it, but the documentation implies that new pools can be started after this call. I don't know if this is a shortcoming of the previous implementation (total termination was not feasible, so document it) or if this is a feature.

**Comment by viktorklang** [comment]
@samueltardieu Does it need to be stopped? (It will be stopped when the ActorSystem shuts down)

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala [hunk 10]
```diff
@@ -0,0 +1,140 @@
...
+  /**
+   * Start a new pool interface actor, register it in our maps, and watch its death.
+   *
+   * @param gateway the pool gateway this pool corresponds to
+   * @param fm the materializer to use for this pool
+   * @return the newly created actor ref
+   */
+  private[this] def startPoolInterfaceActor(gateway: PoolGateway)(implicit fm: Materializer): ActorRef = {
+    val props = Props(new PoolInterfaceActor(gateway)).withDeploy(Deploy.local)
+    val ref = context.system.actorOf(props, PoolInterfaceActor.name.next())
```
Comment (viktorklang) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala]: why below system?

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala [hunk 11]
```diff
@@ -0,0 +1,140 @@
...
+
+  def receive = {
+
+    // Start or restart a pool without sending it a request. This is used to ensure that
+    // freshly created pools will be ready to serve requests immediately.
+    case s @ StartPool(gateway, materializer) ⇒
+      poolStatus.get(gateway) match {
+        case Some(PoolInterfaceRunning(_)) ⇒
+        case Some(PoolInterfaceShuttingDown(shutdownCompletedPromise)) ⇒
+          shutdownCompletedPromise.future.foreach(_ ⇒ self ! s)
```
Comment (viktorklang) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala]: what if this Future failed?

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala [hunk 12]
```diff
@@ -0,0 +1,140 @@
...
+  private[this] var poolInterfaces = Map[ActorRef, PoolGateway]()
+
+  /**
+   * Start a new pool interface actor, register it in our maps, and watch its death.
+   *
+   * @param gateway the pool gateway this pool corresponds to
+   * @param fm the materializer to use for this pool
+   * @return the newly created actor ref
+   */
+  private[this] def startPoolInterfaceActor(gateway: PoolGateway)(implicit fm: Materializer): ActorRef = {
```
Comment (viktorklang) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala]: What if there's already an InterfaceActor for the given poolgateway?

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala [hunk 13]
```diff
@@ -0,0 +1,140 @@
...
+    poolStatus += gateway -> PoolInterfaceRunning(ref)
+    poolInterfaces += ref -> gateway
+    context.watch(ref)
+  }
+
+  def receive = {
+
+    // Start or restart a pool without sending it a request. This is used to ensure that
+    // freshly created pools will be ready to serve requests immediately.
+    case s @ StartPool(gateway, materializer) ⇒
```
Comment (viktorklang) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala]: I think the receive-block might be more clear if it is modeled as a state machine.

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala [hunk 14]
```diff
@@ -0,0 +1,140 @@
...
+    // Shutdown a pool and signal its termination.
+    case Shutdown(gateway, shutdownCompletedPromise) ⇒
+      poolStatus.get(gateway).foreach {
+        case PoolInterfaceRunning(ref) ⇒
+          ref ! PoolInterfaceActor.Shutdown
+          poolStatus += gateway -> PoolInterfaceShuttingDown(shutdownCompletedPromise)
+        case PoolInterfaceShuttingDown(formerPromise) ⇒
+          shutdownCompletedPromise.completeWith(formerPromise.future)
+        case _ ⇒
+          shutdownCompletedPromise.success(Done)
```
Comment (viktorklang) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala]: If the `shutdownCompletedPromise` has already been completed, then this line will throw an exception.

**Comment by samueltardieu** [comment]
No, it doesn't. And shouldn't in fact.

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala [hunk 15]
```diff
@@ -0,0 +1,140 @@
...
+      }
+
+    // Shutdown all known pools and signal their termination.
+    case ShutdownAll(shutdownCompletedPromise) ⇒
+      val allGateways = poolStatus.keys
+      val counter = new AtomicInteger(allGateways.size)
+      for (gateway ← allGateways)
+        gateway.shutdown().foreach(_ ⇒ if (counter.decrementAndGet() == 0) shutdownCompletedPromise.success(Done))
```
Comment (viktorklang) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala]: This: 

~~~scala
val allGateways = poolStatus.keys
 +      val counter = new AtomicInteger(allGateways.size)
 +      for (gateway ← allGateways)
 +        gateway.shutdown().foreach(_ ⇒ if (counter.decrementAndGet() == 0) shutdownCompletedPromise.success(Done))
~~~

can be written as:
~~~
def shutdown(remaining: Iterator[PoolGateway]): Unit =
if (remaining.hasNext) i.next().shutdown().onComplete { _ => shutdown(i) } else shutdownCompletedPromise.success(Done)

shutdown(poolStatus.keysIterator)
~~~

Do you also need to clear the poolStatus map?

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala [hunk 16]
```diff
@@ -0,0 +1,140 @@
...
+
+    // When a pool actor terminate, signal its termination and remove it from our maps.
+    case Terminated(ref) ⇒
+      poolInterfaces.get(ref).foreach { gateway ⇒
+        poolStatus.get(gateway) match {
+          case Some(PoolInterfaceShuttingDown(shutdownCompletedPromise)) ⇒
+            shutdownCompletedPromise.success(Done)
+          case _ ⇒
```
Comment (viktorklang) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala]: Why do we ignore this case?

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala [hunk 17]
```diff
@@ -0,0 +1,140 @@
...
+ * and are marked as being shared. This is the case for example for gateways obtained through
+ * [[HttpExt.cachedHostConnectionPool]]. Some other gateways are not shared, such as those obtained through
+ * [[HttpExt.newHostConnectionPool]], and will have their dedicated restartable pool.
+ *
+ */
+private[http] class PoolMasterActor extends Actor {
+
+  import PoolMasterActor._
+
+  private[this] implicit val dispatcher = context.dispatcher
```
Comment (viktorklang) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala]: I'd avoid this, rather import `context.dispatcher` as close to where the ExecutionContext is needed as possible (to make it easier to reason about what parts uses it)

**Comment by viktorklang** [comment]
@samueltardieu Thanks. I like what you're doing.

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala (hunk 10 above)
Comment (samueltardieu) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala]: This is where they were created before. But I agree, this would make more sense to create them under the pool master now that it exists.

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala (hunk 11 above)
Comment (samueltardieu) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala]: It cannot fail, the shutdown will always be successful. Even if it did not take place (which should never happen), the future would just never be completed.

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala (hunk 12 above)
Comment (samueltardieu) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala]: This is an internal private method which is only called when the interface actor for this gateway (or an equivalent one through `.equals`) does not already exist. Would you want me to add an extra comment to it?

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala (hunk 13 above)
Comment (samueltardieu) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala]: It is not really one, and moreover it handles all the interface actors at once, so this would neither be easy nor elegant to model with a FSM. However, I will add comments describing the life cycle of a pool interface actor as seen by the pool master actor.

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala (hunk 12 above)
Comment (viktorklang) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala]: No, is it either A) a bug (in which it should be handled) or B) a feature (in which case the desired outcome is not immediately obvious to me)

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala (hunk 10 above)
Comment (viktorklang) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala]: agreed!

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala (hunk 13 above)
Comment (viktorklang) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala]: You don't need to model it as an Akka FSM, `context.become` may be succinct enough :)

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala (hunk 11 above)
Comment (viktorklang) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala]: But that assumption is not encoded here. So if someone changes the implementation down the line, and that assumption doesn't hold anymore, it will be a silent bug, will it not?

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala [hunk 18]
```diff
@@ -0,0 +1,140 @@
...
+
+  case class StartPool(gateway: PoolGateway, materializer: Materializer) extends NoSerializationVerificationNeeded
+  case class SendRequest(gateway: PoolGateway, request: HttpRequest, responsePromise: Promise[HttpResponse], materializer: Materializer)
+    extends NoSerializationVerificationNeeded
+  case class Shutdown(gateway: PoolGateway, shutdownCompletedPromise: Promise[Done]) extends NoSerializationVerificationNeeded with DeadLetterSuppression
+  case class ShutdownAll(shutdownCompletedPromise: Promise[Done]) extends NoSerializationVerificationNeeded with DeadLetterSuppression
+
+  // Testing only.
+  case class PoolStatus(gateway: PoolGateway, statusPromise: Promise[Option[PoolInterfaceStatus]]) extends NoSerializationVerificationNeeded
+  case class PoolSize(sizePromise: Promise[Int]) extends NoSerializationVerificationNeeded
```
Comment (viktorklang) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala]: Add `final` for all the case classes.

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala (hunk 14 above)
Comment (samueltardieu) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala]: I don't see how this would happen. The promise can be completed it three exclusive ways;
- immediately if the gateway does not exist;
- as a completion of an existing promise;
- after being put into a `PoolInterfaceShuttingDown`, and it is only extracted from it in the `Terminated` message.

Or maybe your concern is that an already completed promise could be given to this actor? This should not happen, because the promise is created in the `PoolGateway` which is a private object.

Comment (viktorklang) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala]: My point is that if it is not a desired effect to have an exception thrown here if the Promise is already completed, it should use `trySuccess`, and optionally checking the returned boolean and logging if it is unexpected.

(This is akin to not want to allow buffer overruns :))

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala (hunk 15 above)
Comment (samueltardieu) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala]: No need to clear the maps: we just start the shutdown of the various gateways, and when it is done the maps will be cleared of the corresponding entries.

The alternate way you're proposing to shutdown the gateways waits for one pool to be shutdown before going to the next. This is not a good idea, as a pool might take a long time to shutdown if it is handling ongoing connections.

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala (hunk 16 above)
Comment (samueltardieu) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala]: An interface pool actor terminates without warning: apart from marking this pool as dead (to be able to restart it), there is nothing else we can do.

The two ignored cases are "pool running and abruptly stopped" and "unknown actor terminates". The first one might need an error in the log, the second one can never happen.

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala (hunk 17 above)
Comment (samueltardieu) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala]: Ok, will do.

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala (hunk 15 above)
Comment (viktorklang) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala]: Solved:
~~~
def track(remaining: Iterator[Future[Done]]): Unit =
if (remaining.hasNext) i.next().onComplete { _ => track(i) } else shutdownCompletedPromise.success(Done)
track(poolStatus.keys.map(_.shutdown()))
~~~

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala (hunk 16 above)
Comment (viktorklang) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala]: Add the two skipped states and a comment as to why, :)

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala (hunk 11 above)
Comment (samueltardieu) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala]: Faire enough. Will use `andThen` instead.

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala (hunk 12 above)
Comment (samueltardieu) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala]: Ok, will throw `IllegalStateException` in this case with an informative error message.

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala (hunk 13 above)
Comment (samueltardieu) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala]: Sure, but I still don't get it: this is really not a state machine, as any of those events can happen at any time. You may receive `StartPool` for a pool followed by either something else for this pool (but you don't have to) or a message for another pool. Each message is dispatched independently, even if the state of each pool could be modeled as a tiny state machine in itself, but the receive function would never change.

Comment (viktorklang) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala]: Ok, then I probably misunderstood the code. Thanks for clarifying!

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala (hunk 14 above)
Comment (samueltardieu) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala]: Ok.

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala (hunk 15 above)
Comment (samueltardieu) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala]: I'll use this, I like the idea of chaining the futures rather than decrementing a counter.

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala (hunk 16 above)
Comment (samueltardieu) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala]: Ok.

**Comment by samueltardieu** [comment]
@viktorklang I'll push the fixes as separate commits on the branch to ease review, to be squashed later.

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala [hunk 19]
```diff
@@ -4,91 +4,85 @@
...
+   */
+  def apply(request: HttpRequest): Future[HttpResponse] = {
+    val responsePromise = Promise[HttpResponse]()
+    gatewayRef ! SendRequest(this, request, responsePromise, fm)
+    responsePromise.future
+  }
 
-  private val state = {
+  /**
+   * Start the corresponding pool to make it ready to serve requests.
```
Comment (viktorklang) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala]: Perhaps document that this is an idempotent operation?

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala [hunk 20]
```diff
@@ -4,91 +4,85 @@
...
+   *
+   * @return the gateway itself
+   */
+  def startPool(): PoolGateway = {
+    gatewayRef ! StartPool(this, fm)
+    this
+  }
+
+  /**
+   * Shutdown the corresponding pool and signal its termination. The pool can be restarted by sending a new request
```
Comment (viktorklang) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala]: Document that this is an idempotent operation?

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala [hunk 21]
```diff
@@ -4,91 +4,85 @@
...
-    val ref = system.actorOf(props, PoolInterfaceActor.name.next())
-    new AtomicReference[State](Running(ref, _shutdownStartedPromise, shutdownCompletedPromise))
+    gatewayRef ! Shutdown(this, shutdownCompletedPromise)
+    shutdownCompletedPromise.future
+  }
+
+  override def toString = s"PoolGateway(hcps = $hcps)"
+
+  // Testing only.
+  def poolStatus(): Future[Option[PoolInterfaceStatus]] = {
```
Comment (viktorklang) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala]: If this is truly for testing purposes, shouldn't this have an access modifier and a comment about it being INTERNAL API?

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala [hunk 22]
```diff
@@ -0,0 +1,145 @@
...
+ * The [[PoolMasterActor]] provides a layer of indirection between a [[PoolGateway]], which represents a pool,
+ * and the [[PoolInterfaceActor]] instances which are created on-demand and stopped after an idle-timeout.
+ *
+ * Several [[PoolGateway]] objects may be mapped to the same pool if they have the same [[HostConnectionPoolSetup]]
+ * and are marked as being shared. This is the case for example for gateways obtained through
+ * [[HttpExt.cachedHostConnectionPool]]. Some other gateways are not shared, such as those obtained through
+ * [[HttpExt.newHostConnectionPool]], and will have their dedicated restartable pool.
+ *
+ */
+private[http] class PoolMasterActor extends Actor with ActorLogging {
```
Comment (viktorklang) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala]: final?

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala [hunk 23]
```diff
@@ -0,0 +1,145 @@
...
+   * Start a new pool interface actor, register it in our maps, and watch its death. No actor should
+   * currently exist for this pool.
+   *
+   * @param gateway the pool gateway this pool corresponds to
+   * @param fm the materializer to use for this pool
+   * @return the newly created actor ref
+   */
+  private[this] def startPoolInterfaceActor(gateway: PoolGateway)(implicit fm: Materializer): ActorRef = {
+    if (poolStatus.contains(gateway)) {
+      throw new IllegalStateException(s"pool interface actor for $gateway already exists")
```
Comment (viktorklang) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala]: Note that this will crash the actor and send it to the supervisor.

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala (hunk 19 above)
Comment (samueltardieu) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala]: Ok.

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala (hunk 20 above)
Comment (samueltardieu) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala]: Ok.

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala (hunk 21 above)
Comment (samueltardieu) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala]: Yes. I can restrict it to `private[client]`, and `Http().poolSize()` to `private[scaladsl]`.

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala (hunk 22 above)
Comment (samueltardieu) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala]: Ok.

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala (hunk 23 above)
Comment (samueltardieu) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala]: Yes, but I already feel that this is over-engineered: this method is only called if `poolStatus.get(gateway)` is `None`. If somebody modifies the code despite the documentation and the explicit redundant test in the method, I sure hope that this will break instead of failing silently.

**Comment by samueltardieu** [comment]
@viktorklang If you don't have any more comments for the time being, tell me and I'll resubmit a squashed version.

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala [hunk 24]
```diff
@@ -4,91 +4,89 @@
...
 
-      case IsShutdown(x)                    ⇒ x
+  sealed trait GatewayIdentifier
+  case object SharedGateway extends GatewayIdentifier
+  final case class UniqueGateway(id: Long) extends GatewayIdentifier
 
-      case NewIncarnation(newGatewayFuture) ⇒ newGatewayFuture.flatMap(_.shutdownAux())
-    }
+  private[this] val uniqueGatewayId = new AtomicLong(0)
+  def newUniqueGatewayIdentifier = UniqueGateway(uniqueGatewayId.incrementAndGet())
```
Comment (viktorklang) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala]: Since the gateways are all children of the same parent actor, I don't think this AtomicLong is needed anymore.
A single var in the parent actor would be sufficient

Comment (samueltardieu) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala]: The gateways are objects, which are created independently by the `Http()` object, possibly in parallel. The *pools* are children of the master actor, but gateways must be able to get a unique id that will be used to identify them.

This identifier is used to differentiate between gateways to pools with identical `HostConnectionPoolSetup`. Those pools are either shared (created through `Http().cachedHostConnectionPool(…)` for example, or by `Http().singleRequest(…)`, in which case their gateways use the common identifier `SharedGateway`. However, if the user creates two `Http().newHostConnectionPool(…)` with the same `HostConnectionPoolSetup`, those pools must not be merged as their `max-connections` parameter shall be interpreted per pool, not globally.

This is why those non-shared gateways need to have a unique identifier which, together with the `HostConnectionPoolSetup`, ensures that requests get addressed to the right pool.

Comment (viktorklang) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala]: Thanks, makes total sense. I should probably try to get some sleep and not
review more code today :)

**Comment by samueltardieu** [comment]
Rebased.

**Comment by drewhk** [comment]
Unstash and revisit https://github.com/akka/akka/pull/20190#issuecomment-204353829 once this gets merged

**Comment by samueltardieu** [comment]
Indeed, this PR fixes #20071 by construction as the collapsing chain of gateways and the associated race condition will no longer exist.

**Comment by drewhk** [comment]
Ok, good to know then

**Comment by samueltardieu** [comment]
Updated description.

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala [hunk 25]
```diff
@@ -0,0 +1,151 @@
+package akka.http.impl.engine.client
```
Comment (ktoso) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala]: minor (I'll add) missing license header

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala [hunk 26]
```diff
@@ -0,0 +1,151 @@
...
+  def receive = {
+
+    // Start or restart a pool without sending it a request. This is used to ensure that
+    // freshly created pools will be ready to serve requests immediately.
+    case s @ StartPool(gateway, materializer) ⇒
+      poolStatus.get(gateway) match {
+        case Some(PoolInterfaceRunning(_)) ⇒
+        case Some(PoolInterfaceShuttingDown(shutdownCompletedPromise)) ⇒
+          // Pool is being shutdown. When this is done, start the pool again.
+          shutdownCompletedPromise.future.onComplete(_ ⇒ self ! s)(context.dispatcher)
```
Comment (ktoso) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala]: good :+1:

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala [hunk 27]
```diff
@@ -0,0 +1,151 @@
...
+ * The [[PoolMasterActor]] provides a layer of indirection between a [[PoolGateway]], which represents a pool,
+ * and the [[PoolInterfaceActor]] instances which are created on-demand and stopped after an idle-timeout.
+ *
+ * Several [[PoolGateway]] objects may be mapped to the same pool if they have the same [[HostConnectionPoolSetup]]
+ * and are marked as being shared. This is the case for example for gateways obtained through
+ * [[HttpExt.cachedHostConnectionPool]]. Some other gateways are not shared, such as those obtained through
+ * [[HttpExt.newHostConnectionPool]], and will have their dedicated restartable pool.
+ *
+ */
+private[http] final class PoolMasterActor extends Actor with ActorLogging {
```
Comment (ktoso) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala]: we always need to mark with "INTERNAL API" as well, since for Java it looks like `public` when `private[x]` is used.

File: akka-http-core/src/test/scala/akka/http/impl/engine/client/ConnectionPoolSpec.scala [hunk 28]
```diff
@@ -207,20 +210,17 @@ class ConnectionPoolSpec extends AkkaSpec("""
...
 
     "transparently restart after idle shutdown" in new TestSetup() {
       val (requestIn, responseOut, responseOutSub, hcp) = cachedHostConnectionPool[Int](idleTimeout = 1.second)
 
-      val gateway = Await.result(hcp.gatewayFuture, 500.millis)
-      val PoolGateway.Running(_, _, shutdownCompletedPromise) = gateway.currentState
-      Await.result(shutdownCompletedPromise.future, 1500.millis) // verify shutdown completed
+      val gateway = hcp.gateway
+      Await.result(gateway.poolStatus(), 1500.millis).get shouldBe a[PoolInterfaceRunning]
+      awaitCond({ Await.result(gateway.poolStatus(), 1500.millis).isEmpty }, 1500.millis)
```
Comment (ktoso) [inline akka-http-core/src/test/scala/akka/http/impl/engine/client/ConnectionPoolSpec.scala]: outer timeout larger, inner smaller I'd propose here

**Comment by ktoso** [comment]
Looks very good, some minor things found but the logic expressed as Actor looks very nice and valid.
I want to give the HttpExt another read but need to move to somewhere else now, sounds like we may merge this today even. Thanks @samueltardieu

File: akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala [hunk 29]
```diff
@@ -613,6 +588,13 @@ class HttpExt(private val config: Config)(implicit val system: ActorSystem) exte
       case hctx: HttpsConnectionContext ⇒ TLS(hctx.sslContext, hctx.firstSession, role, hostInfo = hostInfo)
       case other                        ⇒ TLSPlacebo() // if it's not HTTPS, we don't enable SSL/TLS
     }
+
+  /** For testing only. */
+  private[scaladsl] def poolSize: Future[Int] = {
```
Comment (ktoso) [inline akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala]: `/** INTERNAL API*/`

File: akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala [hunk 30]
```diff
@@ -545,64 +547,37 @@ class HttpExt(private val config: Config)(implicit val system: ActorSystem) exte
...
-                            settings: ConnectionPoolSettings, connectionContext: ConnectionContext,
-                            log: LoggingAdapter)(implicit fm: Materializer): Future[PoolGateway] =
+  private def sharedGateway(request: HttpRequest, settings: ConnectionPoolSettings, connectionContext: ConnectionContext, log: LoggingAdapter): PoolGateway = {
     if (request.uri.scheme.nonEmpty && request.uri.authority.nonEmpty) {
       val httpsCtx = if (request.uri.scheme.equalsIgnoreCase("https")) connectionContext else ConnectionContext.noEncryption()
       val setup = ConnectionPoolSetup(settings, httpsCtx, log)
       val host = request.uri.authority.host.toString()
       val hcps = HostConnectionPoolSetup(host, request.uri.effectivePort, setup)
-      cachedGateway(hcps)
+      sharedGateway(hcps)
```
Comment (ktoso) [inline akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala]: right

File: akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala [hunk 31]
```diff
@@ -190,6 +191,9 @@ class HttpExt(private val config: Config)(implicit val system: ActorSystem) exte
 
   // ** CLIENT ** //
 
+  private[this] val poolMasterActorRef = system.actorOf(Props(new PoolMasterActor).withDeploy(Deploy.local), "pool-master")
```
Comment (ktoso) [inline akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala]: `PoolMasterActor.props` to be consistent with our codebase

File: akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala [hunk 32]
```diff
@@ -190,6 +191,9 @@ class HttpExt(private val config: Config)(implicit val system: ActorSystem) exte
...
+  private[this] val systemMaterializer = ActorMaterializer()
```
Comment (ktoso) [inline akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala]: This touches the somewhere else touched upon topic of 'then we should allow configuring it',
but we can tackle that along the way from here on

**Comment by samueltardieu** [comment]
Now that you can easily squash merges, I've added fixes for your remarks as additional commits.

**Comment by ktoso** [comment]
PLS BUILD

**Comment by ktoso** [comment]
Great contrib, thanks a lot @samueltardieu :+1:
