### PR TITLE
Behavior.orElse start the other behavior

### LINKED ISSUE #25841: Behavior#orElse fails for Deferred
Hi,

Akka Typed will fail when using `orElse` on `Deferred` behavior (by using `Behaviors.setup()`) with the following error:

```
java.lang.IllegalArgumentException: deferred [Deferred(Behaviors.scala:43)] should not be passed to interpreter
```

It seems like `Behavior` objects will not be properly started when using `orElse` . The code below will reproduce the problem:

```java
import akka.actor.typed.ActorSystem;
import akka.actor.typed.Behavior;
import akka.actor.typed.javadsl.Behaviors;

public class Main {
    public static void main(String[] args) {
        final Behavior<Object> behavior = Behaviors.setup(ctx -> Behaviors.empty())
            .orElse(Behaviors.receiveMessage(msg -> { 
                System.out.println(msg); 
                return Behaviors.same(); 
            }));

        final ActorSystem<Object> system = ActorSystem.create(behavior, "hello");
        system.tell(1);
    }
}
```

Is this expected behavior?

### PR DESCRIPTION
**Pull request by chbatey**
* Switches to using an interceptor

Fixes #25841

### CODE REVIEW

File: akka-actor-typed/src/main/scala/akka/actor/typed/internal/BehaviorImpl.scala [hunk 1]
```diff
@@ -64,17 +64,25 @@ import akka.actor.typed.scaladsl.{ ActorContext ⇒ SAC }
   def intercept[O, I](interceptor: BehaviorInterceptor[O, I])(behavior: Behavior[I]): Behavior[O] =
     InterceptorImpl(interceptor, behavior)
 
-  class OrElseBehavior[T](first: Behavior[T], second: Behavior[T]) extends ExtensibleBehavior[T] {
-    override def receive(ctx: AC[T], msg: T): Behavior[T] = {
-      Behavior.interpretMessage(first, ctx, msg) match {
-        case _: UnhandledBehavior.type ⇒ Behavior.interpretMessage(second, ctx, msg)
-        case handled                   ⇒ handled
+  class OrElseInterceptor[T](next: Behavior[T]) extends BehaviorInterceptor[T, T] {
```
Comment (patriknw) [inline akka-actor-typed/src/main/scala/akka/actor/typed/internal/BehaviorImpl.scala]: it's not implementing `isSame` so how does this work when returning new `orElse` behaviors and such?
see `InterceptSpec` and issue https://github.com/akka/akka/issues/25504

Comment (chbatey) [reply akka-actor-typed/src/main/scala/akka/actor/typed/internal/BehaviorImpl.scala]: Ah indeed and there's no logical way to know it is the same Or and there's no real wrapping going on. I'll revert this to be an extensible behaviour and start it in a deferred.

File: akka-actor-typed-tests/src/test/scala/akka/actor/typed/OrElseStubbedSpec.scala [hunk 2]
```diff
@@ -0,0 +1,165 @@
...
+ * Copyright (C) 2017-2018 Lightbend Inc. <https://www.lightbend.com>
+ */
+
+package akka.actor.typed
+
+import akka.actor.typed.scaladsl.Behaviors
+import akka.actor.testkit.typed.scaladsl._
+import org.scalatest.{ Matchers, WordSpec, WordSpecLike }
+
+object OrElseStubbedSpec {
```
Comment (patriknw) [inline akka-actor-typed-tests/src/test/scala/akka/actor/typed/OrElseStubbedSpec.scala]: since this file also contains `OrElseSpec` I think the file rename should be reverted

File: akka-actor-typed/src/main/scala/akka/actor/typed/Behavior.scala [hunk 3]
```diff
@@ -51,7 +51,10 @@ sealed abstract class Behavior[T] { behavior ⇒
    *
    *  @param that the fallback `Behavior`
    */
-  final def orElse(that: Behavior[T]): Behavior[T] = new OrElseBehavior[T](this, that)
+  final def orElse(that: Behavior[T]): Behavior[T] = Behavior.DeferredBehavior[T] { ctx ⇒
+    val orElse = new OrElseBehavior[T](this, that)
+    orElse.start(ctx)
```
Comment (patriknw) [inline akka-actor-typed/src/main/scala/akka/actor/typed/Behavior.scala]: is that indirection needed?

```
new OrElseBehavior[T](Behavior.start(this, ctx), Behavior.start(that, ctx))
```

**Review by patriknw — COMMENTED** [review]
looking good, some nitpick

File: akka-actor-typed/src/main/scala/akka/actor/typed/Behavior.scala (hunk 3 above)
Comment (chbatey) [reply akka-actor-typed/src/main/scala/akka/actor/typed/Behavior.scala]: Doh, was staring at the Interceptor for too long

**Review by patriknw — APPROVED** [review]
LGTM

**Review by helena — APPROVED** [review]
LGTM

File: akka-actor-typed-tests/src/test/scala/akka/actor/typed/OrElseSpec.scala [hunk 4]
```diff
@@ -6,14 +6,20 @@ package akka.actor.typed
...
-object OrElseSpec {
   sealed trait Ping
+
   case class Ping1(replyTo: ActorRef[Pong]) extends Ping
+
   case class Ping2(replyTo: ActorRef[Pong]) extends Ping
+
   case class Ping3(replyTo: ActorRef[Pong]) extends Ping
+
+  case class PingInfinite(replyTo: ActorRef[Pong]) extends Ping
```
[the remark this answers is not in the document]
Comment (chbatey) [reply akka-actor-typed-tests/src/test/scala/akka/actor/typed/OrElseSpec.scala]: :+1: often don't have my final hat on for final case classes

[the remark this answers is not in the document]
Comment (chbatey) [reply akka-actor-typed-tests/src/test/scala/akka/actor/typed/OrElseSpec.scala]: ^ in test
