### PR TITLE
Merging did not prune vector clocks for tombstoned nodes 

### LINKED ISSUE #23318: Ending up with too many vector clocks
Some pruning not happening as it should perhaps? Appeared in the nightlies over the weekend, after merging all the things friday.

https://jenkins.akka.io:8498/job/akka-multi-node-repeat/13932/consoleFull

```
[JVM-1] java.lang.IllegalStateException: Too many vector clock entries in gossip state Gossip(members = [Member(address = akka.trttl.gremlin.tcp://MultiDcSpec@a2.moxie:53681, dataCenter = dc2, status = Up), Member(address = akka.trttl.gremlin.tcp://MultiDcSpec@a2.moxie:60170, dataCenter = dc2, status = Up), Member(address = akka.trttl.gremlin.tcp://MultiDcSpec@a4.moxie:60828, dataCenter = dc1, status = Up)], overview = GossipOverview(reachability = [], seen = [UniqueAddress(akka.trttl.gremlin.tcp://MultiDcSpec@a4.moxie:60828,545928382)]), version = VectorClock(4ff491baf31afdcfffb3caa205a8ecf3 -> 1, 602c2526b740ec11feae8fa507e6f350 -> 8, 869516b02d35eb7c34d222fdcc98de38 -> 5, d633377ef2e0f995779c730c5f27bbae -> 3), tombstones = Map(UniqueAddress(akka.trttl.gremlin.tcp://MultiDcSpec@a5.moxie:34905,1926157669) -> 1499450297287, UniqueAddress(akka.trttl.gremlin.tcp://MultiDcSpec@a5.moxie:43278,-1097777188) -> 1499450301143))
[JVM-1] 	at akka.cluster.ClusterCoreDaemon.assertLatestGossip(ClusterDaemon.scala:1242)
[JVM-1] 	at akka.cluster.ClusterCoreDaemon.updateLatestGossip(ClusterDaemon.scala:1237)
[JVM-1] 	at akka.cluster.ClusterCoreDaemon.leaderActionsOnConvergence(ClusterDaemon.scala:1103)
[JVM-1] 	at akka.cluster.ClusterCoreDaemon.leaderActions(ClusterDaemon.scala:968)
[JVM-1] 	at akka.cluster.ClusterCoreDaemon$$anonfun$initialized$1.applyOrElse(ClusterDaemon.scala:459)
[JVM-1] 	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
[JVM-1] 	at akka.actor.Actor$class.aroundReceive(Actor.scala:513)
[JVM-1] 	at akka.cluster.ClusterCoreDaemon.aroundReceive(ClusterDaemon.scala:288)
[JVM-1] 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
[JVM-1] 	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
[JVM-1] 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
[JVM-1] 	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
[JVM-1] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
[JVM-1] 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[JVM-1] 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[JVM-1] 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[JVM-1] 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #23318 (I think)

### CODE REVIEW

File: akka-cluster/src/main/scala/akka/cluster/ClusterDaemon.scala [hunk 1]
```diff
@@ -1349,8 +1337,8 @@ private[cluster] final class FirstSeedNodeProcess(seedNodes: immutable.IndexedSe
  *
  */
 private[cluster] final class JoinSeedNodeProcess(seedNodes: immutable.IndexedSeq[Address]) extends Actor with ActorLogging {
-  import InternalClusterAction._
   import ClusterUserAction.JoinTo
+  import InternalClusterAction._
```
Comment (johanandren) [inline akka-cluster/src/main/scala/akka/cluster/ClusterDaemon.scala]: IntelliJ fix import did this. Unrelated.

File: akka-cluster/src/main/scala/akka/cluster/Gossip.scala [hunk 2]
```diff
@@ -22,6 +22,8 @@ private[cluster] object Gossip {
   def apply(members: immutable.SortedSet[Member]) =
     if (members.isEmpty) empty else empty.copy(members = members)
 
+  def vclockName(node: UniqueAddress): String = s"${node.address}-${node.longUid}"
+
```
Comment (johanandren) [inline akka-cluster/src/main/scala/akka/cluster/Gossip.scala]: Moved it here because it didn't make sense to have a dependency back to `ClusterDaemon` from `Gossip`

File: akka-cluster/src/main/scala/akka/cluster/Gossip.scala [hunk 3]
```diff
@@ -150,11 +152,14 @@ private[cluster] final case class Gossip(
...
-
-    // 2. merge sets of tombstones
+    // 1. merge sets of tombstones
     val mergedTombstones = tombstones ++ that.tombstones
+    val newTombstonedNodes = mergedTombstones.keySet diff that.tombstones.keySet
+
+    // 2. merge vector clocks (but remove entries for tombstoned nodes)
+    val mergedVClock = newTombstonedNodes.foldLeft(this.version merge that.version) { (vclock, node) ⇒
+      vclock.prune(VectorClock.Node(Gossip.vclockName(node)))
+    }
```
Comment (johanandren) [inline akka-cluster/src/main/scala/akka/cluster/Gossip.scala]: This is the thing, we didn't prune versions using the tombstones, so removed nodes vector clocks stayed in the gossip.

**Review by raboof — APPROVED** [review]
Change looks reasonable to me! (Too bad about the churn in imports, new order doesn't look like a particular improvement either, but OK :) )

File: akka-cluster/src/main/scala/akka/cluster/Gossip.scala [hunk 4]
```diff
@@ -228,7 +233,7 @@ private[cluster] final case class Gossip(
     // and will propagate as is if there are no other changes on other nodes.
     // If other concurrent changes on other nodes (e.g. join) the pruning is also
     // taken care of when receiving gossips.
-    val newVersion = version.prune(VectorClock.Node(ClusterCoreDaemon.vclockName(node)))
+    val newVersion = version.prune(VectorClock.Node(Gossip.vclockName(node)))
```
Comment (ktoso) [inline akka-cluster/src/main/scala/akka/cluster/Gossip.scala]: good move

File: akka-cluster/src/main/scala/akka/cluster/Gossip.scala (hunk 3 above)
Comment (ktoso) [inline akka-cluster/src/main/scala/akka/cluster/Gossip.scala]: I see, good catch

**Review by ktoso — APPROVED** [review]
LGTM, looks good :)

File: akka-cluster/src/main/scala/akka/cluster/ClusterDaemon.scala (hunk 1 above)
Comment (ktoso) [inline akka-cluster/src/main/scala/akka/cluster/ClusterDaemon.scala]: I guess you could just `git checkout wip-multi-dc-dev --  akka-cluster/src/main/scala/akka/cluster/ClusterDaemon.scala` to avoid changes in this file in this PR? Not mendatory but would be nice.

Comment (johanandren) [inline akka-cluster/src/main/scala/akka/cluster/ClusterDaemon.scala]: Yeah, I'll do that, there were loads of unused imports though, that's the reason I did it in the first place.

**Comment by johanandren** [comment]
Ups, a bit too quick on the trigger finger there, the build failed because of the merge though, so should be ok.
