### PR TITLE
=act #17690 add additional validation for name param in RootActorPath

### LINKED ISSUE #17690: No consistency in actorSelection for ActorPath & String
Does work
```scala
val path = RootActorPath(address, "/user/sharding/*Coordinator/singleton/*")
system.actorSelection(   path.toString   ) ! Identify("singleton")
```

Does NOT work
```scala
val path = RootActorPath(address, "/user/sharding/*Coordinator/singleton/*")
system.actorSelection(   path   ) ! Identify("singleton")
```

### PR DESCRIPTION
**Pull request by ktoso**
The `RootActorPath` is a very specific thing - the ref to the root Actor.
The use case described in #17690 worked (after toString-ing) by accident, and we should not allow constructing such RootActorPath - the parameter is a name which may not include path separators (same as path element).

Resolves #17690

### CODE REVIEW

File: akka-actor/src/main/scala/akka/actor/ActorPath.scala [hunk 1]
```diff
@@ -254,6 +254,10 @@ sealed trait ActorPath extends Comparable[ActorPath] with Serializable {
  */
 @SerialVersionUID(1L)
 final case class RootActorPath(address: Address, name: String = "/") extends ActorPath {
+  require(name.length == 1 || name.indexOf('/', 1) == -1,
```
Comment (t3hnar) [inline akka-actor/src/main/scala/akka/actor/ActorPath.scala]: oh...that will break a lot of stuff... I think you should put a note into migration guide

Comment (t3hnar) [inline akka-actor/src/main/scala/akka/actor/ActorPath.scala]: You know that I can still have `/user/blabla/*` there with a `copy` method ;)

Comment (ktoso) [inline akka-actor/src/main/scala/akka/actor/ActorPath.scala]: - note in migration guide might not hurt, sure;
- nope, you can't - `copy` calls the constructor - thus the `require` will catch such attempts

**Comment by ktoso** [comment]
Added migration guide

**Comment by ktoso** [comment]
Any more reviewers?

**Comment by patriknw** [comment]
LGTM
