### PR TITLE
Fail fast on null messages in Akka Typed

### LINKED ISSUE #23796: Typed actor doesn't stop after exception
actor-typed version: 2.5.6
scala version: 2.12.3
 
I have a pretty simple code:
```scala
import akka.typed._
import akka.typed.scaladsl.Actor

object Main {
  def main(args: Array[String]): Unit = {
    import TestActor._
    implicit val system: ActorSystem[TestActor.Request] = ActorSystem(mainActor, "system")
    for(i <- 0 to 3){
      system ! Request(s"msg $i")
    }
    system ! Request("bomb") // or Request(null)`
    Thread.sleep(2000)
    system ! Request("msg after exception") // should not will be printed
    Thread.sleep(1000)
    System.exit(0)
  }
}

object TestActor {
  final case class Request(whom: String)

  val mainActor: Behavior[Request] = Actor.deferred[Request]{ ctx =>
    val pr = ctx.spawn(printer, "printer")
    Actor.immutable[Request] { (ctx, msg) =>
      pr.tell(msg.whom)
      Actor.same
    }
  }

  private val printer = Actor.immutable[String]{ (ctx, msg) =>
    msg match {
      case "bomb" | null =>
        throw new NullPointerException("boom")
        Actor.same[String]
      case text =>
        println(text)
        Actor.same[String]
    }
  }
}
```
When i send `bomb` message to actor, as a planned, it was stopped, because documentation said ` Untyped actors are by default restarted when an exception is thrown. The default for typed actors is instead to stop the failing actor.`

But, if i send `Request(null)`, instead of `Request("bomb")`, actor throw exception and with some **chance** (approximately 80%) print "msg after exception". Full output:
```
msg 0
msg 1
msg 2
msg 3
[ERROR] [10/08/2017 15:03:35.724] [system-akka.actor.default-dispatcher-3] [akka://system/user/printer] swallowing exception during message send
java.lang.NullPointerException
	at java.util.concurrent.ConcurrentLinkedQueue.checkNotNull(ConcurrentLinkedQueue.java:920)
	at java.util.concurrent.ConcurrentLinkedQueue.offer(ConcurrentLinkedQueue.java:327)
	at java.util.concurrent.ConcurrentLinkedQueue.add(ConcurrentLinkedQueue.java:297)
	at akka.typed.internal.ActorCell.send(ActorCell.scala:218)
	at akka.typed.internal.LocalActorRef.tell(ActorRefImpl.scala:58)
	at TestActor$.$anonfun$mainActor$2(Main.scala:25)
	at akka.typed.internal.BehaviorImpl$ImmutableBehavior.receiveMessage(BehaviorImpl.scala:74)
	at akka.typed.Behavior$.interpret(Behavior.scala:290)
	at akka.typed.Behavior$.interpretMessage(Behavior.scala:268)
	at akka.typed.internal.ActorCell.processMessage(ActorCell.scala:403)
	at akka.typed.internal.ActorCell.process$1(ActorCell.scala:289)
	at akka.typed.internal.ActorCell.run(ActorCell.scala:298)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

msg after exception
```
May be, it's happen because internal actor engine can't handle `null` in normal way, but that behavior should be documented or actor should be stopping.

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #23796

### CODE REVIEW

**Review by raboof — APPROVED** [review]

File: akka-typed/src/main/scala/akka/typed/Behavior.scala [hunk 1]
```diff
@@ -275,6 +277,7 @@ object Behavior {
 
   private def interpret[T](behavior: Behavior[T], ctx: ActorContext[T], msg: Any): Behavior[T] =
     behavior match {
+      case null ⇒ throw new InvalidMessageException("[null] is not an allowed message")
```
Comment (patriknw) [inline akka-typed/src/main/scala/akka/typed/Behavior.scala]: this is matching on the `behavior` not the message

**Review by patriknw — APPROVED** [review]
LGTM

File: akka-typed/src/main/scala/akka/typed/Behavior.scala (hunk 1 above)
Comment (johanandren) [reply akka-typed/src/main/scala/akka/typed/Behavior.scala]: D'oh!
