### PR TITLE
Fix CoronerSpec instability

### LINKED ISSUE #13976: FAILED: CoronerSpec (deadlock detection)
imported from https://www.assembla.com/spaces/akka/tickets/3976

https://jenkins.akka.io:8498/job/akka-multi-node/728/consoleFull

<pre><code>
[info] CoronerSpec:
[info] A Coroner
[info] - must generate a report if enough time passes (468 milliseconds)
[info] - must not generate a report if cancelled early (2 milliseconds)
[info] - must display thread counts if enabled (2 milliseconds)
[info] - must display deadlock information in its report *** FAILED *** (365 milliseconds)
[info]   ":
[info]   None
[info]   " did not include substring "deadlock-thread-a" (CoronerSpec.scala:126)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
[info]   at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:5980)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6014)
[info]   at akka.testkit.CoronerSpec$$anonfun$1$$anonfun$apply$mcV$sp$4.apply$mcV$sp(CoronerSpec.scala:126)
[info]   at akka.testkit.CoronerSpec$$anonfun$1$$anonfun$apply$mcV$sp$4.apply(CoronerSpec.scala:58)
[info]   at akka.testkit.CoronerSpec$$anonfun$1$$anonfun$apply$mcV$sp$4.apply(CoronerSpec.scala:58)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:942)
[info]   at org.scalatest.Suite$class.withFixture(Suite.scala:1121)
[info]   at org.scalatest.WordSpec.withFixture(WordSpec.scala:1882)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:939)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:951)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:951)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:951)
[info]   at org.scalatest.WordSpec.runTest(WordSpec.scala:1882)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1010)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1010)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:318)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:318)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
[info]   at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1010)
[info]   at org.scalatest.WordSpec.runTests(WordSpec.scala:1882)
[info]   at org.scalatest.Suite$class.run(Suite.scala:1423)
[info]   at org.scalatest.WordSpec.org$scalatest$WordSpecLike$$super$run(WordSpec.scala:1882)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1056)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1056)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
[info]   at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1056)
[info]   at org.scalatest.WordSpec.run(WordSpec.scala:1882)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:444)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:651)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:84)
[info]   at sbt.TestRunner.run(TestFramework.scala:94)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:219)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:219)
[info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:207)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:219)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:219)
[info]   at sbt.TestFunction.apply(TestFramework.scala:224)
[info]   at sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:211)
[info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:217)
[info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:217)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:45)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:45)
[info]   at sbt.std.Transform$$anon$4.work(System.scala:64)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
[info]   at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
[info]   at sbt.Execute.work(Execute.scala:244)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
[info]   at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
[info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
[info]   at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:166)
[info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
[info]   at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:166)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[info]   at java.lang.Thread.run(Thread.java:701)
</code></pre>

### PR DESCRIPTION
**Pull request by raboof**
Tested in https://github.com/akka/akka/pull/30437 that indeed looking at
the threads 'too soon' might miss a deadlock.

Fixes #13976

### CODE REVIEW

File: akka-testkit/src/test/scala/akka/testkit/Coroner.scala [hunk 1]
```diff
@@ -144,6 +144,11 @@ object Coroner {
                 #Heap usage: ${memMx.getHeapMemoryUsage()}
                 #Non-heap usage: ${memMx.getNonHeapMemoryUsage()}""".stripMargin('#'))
 
+    // If we look too soon, we've seen the JVM report a thread
+    // (in that case deadlock-thread-a from CoronerSpec)
+    // waiting on the lock while no thread seemed to be holding it
+    Thread.sleep(300)
```
Comment (ignasi35) [inline akka-testkit/src/test/scala/akka/testkit/Coroner.scala:150]: Oh wow. That's a hell of an extra-cost. 😞

**Review by ignasi35 — APPROVED** [review]

File: akka-testkit/src/test/scala/akka/testkit/Coroner.scala (hunk 1 above)
Comment (ignasi35) [reply akka-testkit/src/test/scala/akka/testkit/Coroner.scala:150]: Hmm, this cost only will be paid in case the report is printed (which is very rare).
