### PR TITLE
#23951 Fail materialized future of IO stages when stream fails

### LINKED ISSUE #23951: Fail materialized future in FileIO.toPath API when IO operation fails
Right now it materializes to a `Future[IOResult]`. Contrary to expectations, it will not return a failed future when the operation fails but it will return an `IOResult` with a failed status field. It should also be configurable what should happen with files that haven't been completely written.

### PR DESCRIPTION
**Pull request by 2m**
Fixes #23951

### CODE REVIEW

File: akka-stream/src/main/scala/akka/stream/IOResult.scala [hunk 1]
```diff
@@ -48,3 +50,10 @@ object IOResult {
   def createFailed(count: Long, ex: Throwable): IOResult =
     new IOResult(count, Failure(ex))
 }
+
+/**
+ * This exception signals that a stream has been completed by an onError signal
+ * while there was still IO operations in progress.
+ */
+final case class AbruptIOTerminationException(ioResult: IOResult, cause: Throwable)
```
Comment (johanandren) [inline akka-stream/src/main/scala/akka/stream/IOResult.scala]: Ah, neat providing the IOResult even on failure.

**Review by johanandren — APPROVED** [review]

File: akka-stream/src/main/scala/akka/stream/IOResult.scala (hunk 1 above)
Comment (2m) [reply akka-stream/src/main/scala/akka/stream/IOResult.scala]: Yea. It could be the case that some data has already been written to the file when stream fails. So I figured it would be good to still expose that information.

**Review by patriknw — APPROVED** [review]
LGTM
