### PR TITLE
Materialized value injected per materialization 

### LINKED ISSUE #23577: materializedValue of GraphDSL.Builder emits unexpected value
Unless I'm misunderstanding something about graph materialization and builders, the `materializedValue` outlet of `GraphDSL.Builder` can emit a seemingly "outdated" value. The code to reproduce this behavior is as follows.
```scala
val ctr = new AtomicInteger(0)
val flow = Flow[Int].mapMaterializedValue { _ =>
  ctr.getAndIncrement()
}

/*
 *      +---------------------+
 *      |   result graph      |
 *      |                     |
 *      |         +-------+   |
 *      | CTR ~~~>|       |   |
 *      |         | merge |~~~|~~~> out
 * in ~~|~~~~~~~~>|       |   |
 *      |         +-------+   |
 *      +---------------------+
 */
val graph = GraphDSL.create(flow) { implicit builder => flow =>
  import GraphDSL.Implicits._
  val merge = builder.add(Merge[Int](2))
  builder.materializedValue ~> merge.inSeq(0)
  flow.out ~> merge.inSeq(1)
  FlowShape(flow.in, merge.out)
}

val (m1, f1) = Source(List(11, 12, 13)).viaMat(graph)(Keep.right).toMat(Sink.foreach(println))(Keep.both).run()
f1.futureValue
println(s"Mat 1: ${m1}")
val (m2, f2) = Source(List(21, 22, 23)).viaMat(graph)(Keep.right).toMat(Sink.foreach(println))(Keep.both).run()
f2.futureValue
println(s"Mat 2: ${m2}")

println(s"Counter: ${ctr.get()}")
```

The relevant part of the output is this:
```
0
11
12
13
Mat 1: 0
0 // <- this is the issue
21
22
23
Mat 2: 1
Counter: 2
```

The unexpected behavior is the second "0" line in the output. I would expect that line to be "1".

What I'm trying to do is to have a counter, which is incremented on every materialization of the graph (and access the correct value of that counter inside the graph). The output shows, that the counter was in fact incremented as expected. Also, the materialized values are also correct (the "Mat 1" and "Mat 2" lines). However, inside the stream, the accessed materialized value seems to be "outdated" during the second materialization.

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #23577

Credits go to @jrudolph who suggested the solution.

### CODE REVIEW

File: akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphMatValueSpec.scala [hunk 1]
```diff
@@ -16,193 +18,186 @@ class GraphMatValueSpec extends StreamSpec {
...
-          var result = g.run()
-
-          expectMsg("side effect!")
-
-        }
+  "A Graph with materialized value" must {
+
+    val settings = ActorMaterializerSettings(system)
+      .withInputBuffer(initialSize = 2, maxSize = 16)
+    implicit val materializer = ActorMaterializer(settings)
```
Comment (johanandren) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphMatValueSpec.scala]: This changed because there is no non-fused anymore.

**Review by 2m — APPROVED** [review]

**Review by ktoso — APPROVED** [review]
LGTM 👍
