### PR TITLE
Expected behavior on Terminated with orElse signal handling

### LINKED ISSUE #26518: Akka Typed Behavior.orElse appears does not propagate termination signals
We have some code that receives into its behaviour and uses `orElse` so that another behaviour's signal handler can continue handling signals i.e.:

```
      Behaviors
        .receive[T] {...}
        .orElse(behavior) // handle signals immediately
```

What we're seeing is that the signal handling of `behavior` isn't called. The specific signal in use here is `Terminated`.

The API doc for `orElse` states:

>  Composes this `Behavior with a fallback `Behavior` which is used when this `Behavior` doesn't handle the message or signal...

However, in the case of the `Terminated` signal, this isn't the case. Looking at the code of `Behavior`, I see the following:

```
  def interpretSignal[T](behavior: Behavior[T], ctx: TypedActorContext[T], signal: Signal): Behavior[T] = {
    val result = interpret(behavior, ctx, signal)
    // we need to throw here to allow supervision of deathpact exception
    signal match {
      case Terminated(ref) if result == UnhandledBehavior ⇒ throw DeathPactException(ref)
      case _ ⇒ result
    }
  }
```

This appears to handle the termination signal especially, as the comment states. However, it also appears that the `orElse` behavior doesn't get the opportunity to execute.

Relevant code example: https://github.com/akka/alpakka/pull/1577/files#diff-a2dfb01266e608741b917c05b6a7e07aR26

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #26518

### CODE REVIEW

**Comment by patriknw** [comment]
you seem to miss the formatting several times, why don't you enable format on save in IntelliJ? https://github.com/akka/akka/blob/master/CONTRIBUTING.md#scala-style

**Comment by johanandren** [comment]
I have it enabled, not sure why it isn't quite working.

**Comment by johanandren** [comment]
Aha! Had missed the recommendation to use nightly plugin.

File: akka-actor-typed/src/main/scala/akka/actor/typed/internal/BehaviorImpl.scala [hunk 1]
```diff
@@ -76,7 +76,17 @@ import akka.actor.typed.scaladsl.{ ActorContext => SAC }
...
 
     override def receiveSignal(ctx: AC[T], msg: Signal): Behavior[T] = {
-      Behavior.interpretSignal(first, ctx, msg) match {
+      val result: Behavior[T] = try {
+        Behavior.interpretSignal(first, ctx, msg)
+      } catch {
+        case _: DeathPactException =>
+          // since we don't know what kind of concrete Behavior `first` is, if it is intercepted etc.
+          // the only way we can fallback to second behavior if Terminated wasn't handled is to
+          // catch the DeathPact here and pretend like it was just `unhandled`
```
Comment (patriknw) [inline akka-actor-typed/src/main/scala/akka/actor/typed/internal/BehaviorImpl.scala]: one way would be to look for it in `handleSignal` in ActorAdapter but then it would bypass intermediate supervisor, so this is better

**Review by patriknw — APPROVED** [review]
LGTM

**Review by chbatey — APPROVED** [review]
LGTM
