### PR TITLE
#28810 Ensure no SubscriptionTimeout schedule leak in FanoutProcessorImpl

### LINKED ISSUE #28810: [2.6.x] FanoutProcessorImpl leaks SubscriptionTimeout message schedule (dead-letter pollution)
[On this line](https://github.com/akka/akka/blob/bf6576ce79bde15385ea90304e1af43dd25444f3/akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala#L127), `FanoutProcessorImpl` schedules a `SubscriptionTimeout` message to `self`, but never cancels the schedule if the actor terminates before the timeout duration (defaults to 5s).  As a consequence, it becomes a dead-letter and the application will be heavily polluted with dead-letter warnings that look like this:

`[INFO] [akkaDeadLetter][03/25/2020 18:54:12.585] [reproducer-akka.actor.default-dispatcher-5] [akka://reproducer/system/Materializers/StreamSupervisor-0/flow-0-1-fanoutPublisherSink] Message [akka.stream.impl.ActorProcessorImpl$SubscriptionTimeout$] from Actor[akka://reproducer/system/Materializers/StreamSupervisor-0/flow-0-1-fanoutPublisherSink#-553970889] to Actor[akka://reproducer/system/Materializers/StreamSupervisor-0/flow-0-1-fanoutPublisherSink#-553970889] was not delivered. [1] dead letters encountered. If this is not an expected behavior then Actor[akka://reproducer/system/Materializers/StreamSupervisor-0/flow-0-1-fanoutPublisherSink#-553970889] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.`

This becomes severe when an application has a high frequency of short-lived streams, with each stream lasts less than 5 seconds.

Here's a simple reproducer:

```
import akka.actor.ActorSystem
import akka.stream.scaladsl.Source

object Reproducer {
  def main(args: Array[String]): Unit = {
    implicit val as: ActorSystem = ActorSystem("reproducer")
    val (_, s) = Source
      .single(1)
      .preMaterialize()
    s.runForeach(println)
    // Dead-letter log will print out 5s later
  }
}
```

### PR DESCRIPTION
**Pull request by nktpro**
Simply make use of `akka.actor.Timers` trait which cleans up all pending timers when the actor terminates early. Resolves #28810

### CODE REVIEW

File: akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala [hunk 1]
```diff
@@ -118,13 +119,14 @@ import org.reactivestreams.Subscriber
 /**
  * INTERNAL API
  */
-@InternalApi private[akka] class FanoutProcessorImpl(attributes: Attributes) extends ActorProcessorImpl(attributes) {
+@InternalApi private[akka] class FanoutProcessorImpl(attributes: Attributes)
```
Comment (patriknw) [inline akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala]: just a note: only used by `asPublisher(fanout = true)`

File: akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala [hunk 2]
```diff
@@ -118,13 +119,14 @@ import org.reactivestreams.Subscriber
...
+    extends ActorProcessorImpl(attributes)
+    with ActorTimers {
```
Comment (patriknw) [inline akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala]: adds a bit of weight and `aroundReceive` to the FanoutProcessorImpl, but that should be ok

alternative would be to keep track of the Cancellable, and cancel it in postStop

**Review by patriknw — APPROVED** [review]
LGTM, unless someone is concerned about small performance cost

**Review by patriknw — APPROVED** [review]
LGTM 2

File: akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala [hunk 3]
```diff
@@ -120,14 +120,11 @@ import org.reactivestreams.Subscriber
...
-    if (mode != StreamSubscriptionTimeoutTerminationMode.noop) {
-      import context.dispatcher
-      context.system.scheduler.scheduleOnce(timeout, self, ActorProcessorImpl.SubscriptionTimeout)
-    }
-    mode
-  }
+  val StreamSubscriptionTimeout(timeout, timeoutMode) = attributes.mandatoryAttribute[StreamSubscriptionTimeout]
+  val timeoutTimer = if (timeoutMode != StreamSubscriptionTimeoutTerminationMode.noop) {
+    import context.dispatcher
+    Some(context.system.scheduler.scheduleOnce(timeout, self, ActorProcessorImpl.SubscriptionTimeout))
```
Comment (johanandren) [inline akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala]: Can be an `akka.util.OptionVal` instead to avoid the alloc.

File: akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala [hunk 4]
```diff
@@ -145,6 +142,11 @@ import org.reactivestreams.Subscriber
     primaryOutputs.complete()
   }
 
+  override def postStop(): Unit = {
+    super.postStop()
+    timeoutTimer.foreach(_.cancel())
```
Comment (johanandren) [inline akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala]: pattern match instead of foreah avoids another alloc here, probably not super important though

**Comment by johanandren** [comment]
OK TO TEST

**Review by johanandren — APPROVED** [review]
LGTM, thanks!
