### PR TITLE
Disallow nested mixed widen usages 

### LINKED ISSUE #25604: Recursive use of widen
WidenSpec has the note "sadly the only "same" we can know is if it is the same PF".
If the PF is written inline, which is the most common way, the test will fail and the problem with growing behavior stacks.

Follow up on #25575 

I wonder if it wouldn't be better to limit `widen` to only one, i.e. `isSame` based on instanceof?

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #25604

I decided to leave the option of using the same instance of pf which is then deduplicated, since we know that is safe, even if that isn't how people normally use pfs.

### CODE REVIEW

File: akka-actor-typed-tests/src/test/scala/akka/actor/typed/WidenSpec.scala [hunk 1]
```diff
@@ -36,11 +46,14 @@ class WidenSpec extends ScalaTestWithActorTestKit with WordSpecLike {
       val probe = TestProbe[String]()
       val ref = spawn(intToString(probe.ref))
 
-      ref ! 42
-      ref ! 13
-      ref ! 43
-      probe.expectMessage("42")
-      probe.expectMessage("43")
+      // non-convertible/filtered message 13 is logged as warning
```
Comment (patriknw) [inline akka-actor-typed-tests/src/test/scala/akka/actor/typed/WidenSpec.scala]: ok, should it? I thought it was a feature of `widen` to be able to filter, or why is it a partial function? change to debug logging?

File: akka-actor-typed/src/main/scala/akka/actor/typed/internal/InterceptorImpl.scala [hunk 2]
```diff
@@ -138,9 +138,14 @@ private[akka] final case class WidenedInterceptor[O, I](matcher: PartialFunction
...
 
   override def isSame(other: BehaviorInterceptor[Any, Any]): Boolean = other match {
-    // can only be elimintated if it is the same partial function
+    // If they use the same pf instance we can allow it, to have one way to workaround defining
+    // "recursive" narrowed behaviors.
     case WidenedInterceptor(`matcher`) ⇒ true
-    case _                             ⇒ false
+    case WidenedInterceptor(otherMatcher) ⇒
+      // there is no safe way to allow this
+      throw new IllegalStateException("Widen can only be used one time in the same behavior stack. " +
```
Comment (patriknw) [inline akka-actor-typed/src/main/scala/akka/actor/typed/internal/InterceptorImpl.scala]: will this result in infinite restart loop if unlimited `SupervisorStrategy.restart` is used?

should we have protection against restart loops by treating unlimited -1 as not really unlimited but with a very hight limit such as 10000 restarts within 1 second?

wdyt @chbatey

**Review by patriknw — COMMENTED** [review]
some semi-related questions...

**Review by chbatey — APPROVED** [review]
LGTM

File: akka-actor-typed/src/main/scala/akka/actor/typed/internal/InterceptorImpl.scala (hunk 2 above)
Comment (patriknw) [reply akka-actor-typed/src/main/scala/akka/actor/typed/internal/InterceptorImpl.scala]: Good, then it would have to be a new message triggering the exception again. Probably ok to leave the unlimited. It’s not a problem we have heard of for untyped.

File: akka-actor-typed-tests/src/test/scala/akka/actor/typed/WidenSpec.scala (hunk 1 above)
Comment (johanandren) [reply akka-actor-typed-tests/src/test/scala/akka/actor/typed/WidenSpec.scala]: I thought this was something already present in master and just wanted to silence it, but now that I double check that the warning log entry is actually introduced by this PR. I'll look into how that happened.

Comment (johanandren) [reply akka-actor-typed-tests/src/test/scala/akka/actor/typed/WidenSpec.scala]: Yeah, Chris is right, it is because the TestEventListener for some reason logs `unhandled` messages as `warning`. I'll update the comment and keep the silencer.

**Review by patriknw — APPROVED** [review]
LGTM
