### PR TITLE
Failing tcp spec fix

### LINKED ISSUE #21377: FAILED akka.stream.io.TcpSpec
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4157/consoleFull

```
[info] - must not shut down connections after the connection stream cancelled *** FAILED *** (3 seconds, 49 milliseconds)
[info]   akka.stream.StreamTcpException: The connection closed with error: Connection reset by peer
```

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #21377

Also, boyscout overflow, eliminated a bunch of short timeouts and used more idiomatic scalatest usage for dealing with futures.

### CODE REVIEW

File: akka-stream-tests/src/test/scala/akka/stream/io/TcpSpec.scala [hunk 1]
```diff
@@ -488,34 +490,39 @@ class TcpSpec extends StreamSpec("akka.stream.materializer.subscription-timeout.
...
-      Tcp().bind(address.getHostName, address.getPort).take(1).runForeach { tcp ⇒
+      val (futureBinding, _) = Tcp().bind(address.getHostName, address.getPort).take(1).toMat(Sink.foreach { tcp ⇒
         Thread.sleep(1000) // we're testing here to see if it survives such race
         tcp.flow.join(Flow[ByteString]).run()
-      }
+      })(Keep.both)
+        .run()
+
+      // make sure server is running first
+      futureBinding.futureValue
```
Comment (johanandren) [inline akka-stream-tests/src/test/scala/akka/stream/io/TcpSpec.scala]: this is the actual fix, race with server not being started

File: akka-stream-tests/src/test/scala/akka/stream/io/TcpSpec.scala [hunk 2]
```diff
@@ -525,24 +532,27 @@ class TcpSpec extends StreamSpec("akka.stream.materializer.subscription-timeout.
...
-        .runForeach(_.flow.join(Flow[ByteString]).run())
 
-      val folder = Source(immutable.Iterable.fill(100)(ByteString(0)))
+      val (serverBound, serverDone) = Tcp().bind(address.getHostName, address.getPort)
+        .viaMat(takeTwoAndDropSecond)(Keep.left)
+        .toMat(Sink.foreach(_.flow.join(Flow[ByteString]).run()))(Keep.both)
+        .run()
+
+      // make sure server has started
+      serverBound.futureValue
```
Comment (johanandren) [inline akka-stream-tests/src/test/scala/akka/stream/io/TcpSpec.scala]: and fix applied here as well, for good measure

**Comment by ktoso** [comment]
LGTM

**Review by 2m — APPROVED** [review]

**Review by drewhk — APPROVED** [review]
