### PR TITLE
Patience config for typed tests 

### LINKED ISSUE #22859: Provide a patience conf for typed tests
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/9090/ failed because of the default timeout which is too short, we should provide a default PatienceConf for `.futureValue` in some base type for the tests like we do for untyped.

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #22859

### CODE REVIEW

File: akka-typed-tests/src/test/scala/akka/typed/TypedSpec.scala [hunk 1]
```diff
@@ -32,12 +32,18 @@ import akka.typed.scaladsl.AskPattern
...
 
 /**
  * Helper class for writing tests for typed Actors with ScalaTest.
  */
 @RunWith(classOf[org.scalatest.junit.JUnitRunner])
-class TypedSpecSetup extends RefSpec with Matchers with BeforeAndAfterAll with ScalaFutures with TypeCheckedTripleEquals
+class TypedSpecSetup extends RefSpec with Matchers with BeforeAndAfterAll with ScalaFutures with TypeCheckedTripleEquals {
+
+  // TODO hook this up with config like in akka-testkit/AkkaSpec?
+  implicit val akkaPatience = PatienceConfig(3.seconds, Span(100, org.scalatest.time.Millis))
```
Comment (patriknw) [inline akka-typed-tests/src/test/scala/akka/typed/TypedSpec.scala]: there is already something in TypedSpec, is that placed wrong and should be removed?
```
implicit val patience = PatienceConfig(3.seconds)
```

Comment (johanandren) [inline akka-typed-tests/src/test/scala/akka/typed/TypedSpec.scala]: Ah, I came from a test that did not inherit `TypedSpec`, because of not tying the test to a single actor system, so I'll remove that `PatienceConf` make sure we only have this one (`TypedSpec` inherits this class)

**Review by patriknw — APPROVED** [review]
LGTM

**Review by ktoso — APPROVED** [review]
LGTM
