### PR TITLE
Fix race in AkkaProtocolSpec

### LINKED ISSUE #26974: failed: AkkaProtocolSpec
https://jenkins.akka.io:8498/job/akka-nightly-jdk11/236

```
[info] - must in outbound mode delay readiness until hadnshake finished *** FAILED *** (4 milliseconds)
[info]   false did not equal true (AkkaProtocolSpec.scala:233)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:343)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6859)
[info]   at akka.remote.classic.transport.AkkaProtocolSpec.$anonfun$new$10(AkkaProtocolSpec.scala:233)

```

### PR DESCRIPTION
**Pull request by chbatey**
The heartbeat happens after the send associate in
AkkaProtocolTransport so test can't assume the heartbeat
has happened.

Fixes #26974

### CODE REVIEW

File: akka-remote/src/main/scala/akka/remote/transport/AkkaProtocolTransport.scala [hunk 1]
```diff
@@ -446,7 +446,7 @@ private[remote] class ProtocolStateActor(
           stop(FSM.Failure(ForbiddenUidReason))
 
         case Associate(handshakeInfo) =>
-          failureDetector.heartbeat()
+//          failureDetector.heartbeat()
```
Comment (raboof) [inline akka-remote/src/main/scala/akka/remote/transport/AkkaProtocolTransport.scala]: Was this intentionally part of this PR?

**Review by raboof — COMMENTED** [review]
I think one change slipped in, other than that LGTM!

File: akka-remote/src/main/scala/akka/remote/transport/AkkaProtocolTransport.scala (hunk 1 above)
Comment (chbatey) [reply akka-remote/src/main/scala/akka/remote/transport/AkkaProtocolTransport.scala]: hah no, that was making sure i had the right failure

Comment (chbatey) [reply akka-remote/src/main/scala/akka/remote/transport/AkkaProtocolTransport.scala]: (it wasn't this one)

**Review by jrudolph — APPROVED** [review]
LGTM

**Review by helena — APPROVED** [review]
LGTM
