### PR TITLE
Use embedded media driver for StressSpec

### LINKED ISSUE #27030: Failed: aeron-StressSpec
```
Failed to start media driver in [target/aeron-StressSpec]: CnC file is created but not initialised
```

https://jenkins.akka.io:8498/job/akka-nightly/6592/consoleText

### PR DESCRIPTION
**Pull request by chbatey**
The current setup starts a media driver for each JVM in the same
directory which is caused the cnc file to be courruped in some way
so that the client in Akka timed out waiting for it to be initialized.

This test is disabled for Artery, see
https://github.com/akka/akka/issues/21810 so all it does is startup
and then end the test right away.

Will look at enabling the test again separately.

Fixes #27030

### CODE REVIEW

File: akka-cluster/src/multi-jvm/scala/akka/cluster/StressSpec.scala [hunk 1]
```diff
@@ -676,11 +674,7 @@ class StressMultiJvmNode12 extends StressSpec
 class StressMultiJvmNode13 extends StressSpec
 
 abstract class StressSpec
-    extends MultiNodeSpec({
-      // Aeron media driver must be started before ActorSystem
-      SharedMediaDriverSupport.startMediaDriver(StressMultiJvmSpec)
-      StressMultiJvmSpec
-    })
```
Comment (patriknw) [inline akka-cluster/src/multi-jvm/scala/akka/cluster/StressSpec.scala]: ok, strange that this started failing. Did we update Aeron version. `SharedMediaDriverSupport.startMediaDriver` is supposed to start only one.

Comment (patriknw) [reply akka-cluster/src/multi-jvm/scala/akka/cluster/StressSpec.scala]: One thing that should be added to `SharedMediaDriverSupport.startMediaDriver` is to only start media driver if the transport is "aeron-udp"

Comment (chbatey) [reply akka-cluster/src/multi-jvm/scala/akka/cluster/StressSpec.scala]: Nope we didn't upgrade recently. This has only failed once this way in all of time. I assume a race in isDriverInactive to starting it. I didn't re-create it locally.

Comment (chbatey) [reply akka-cluster/src/multi-jvm/scala/akka/cluster/StressSpec.scala]: > One thing that should be added to SharedMediaDriverSupport.startMediaDriver is to only start media driver if the transport is "aeron-udp"

:+1:

File: akka-cluster/src/multi-jvm/scala/akka/cluster/SharedMediaDriverSupport.scala [hunk 2]
```diff
@@ -48,7 +48,7 @@ object SharedMediaDriverSupport {
           })
           catch {
             case NonFatal(e) =>
-              println(e.getMessage)
+              println("Exception checking isDriverActive: " + e.getMessage)
```
Comment (helena) [inline akka-cluster/src/multi-jvm/scala/akka/cluster/SharedMediaDriverSupport.scala]: Is there a static logger we can use versus `println`? Nit on `println` in tests if avoidable.

Comment (chbatey) [reply akka-cluster/src/multi-jvm/scala/akka/cluster/SharedMediaDriverSupport.scala]: Not AFAIK, they need an actor system

**Review by jrudolph — APPROVED** [review]
Is this PR still valid? LGTM

**Review by raboof — APPROVED** [review]
doesn't seem to happen often, but if this is safer then :+1:
