### PR TITLE
Wip stream testkit fixes rk

### LINKED ISSUE #19377: Akka Streams TestKit - expectNext when no element panics about "null"
Instead it should say "no element received within timeout"

### PR DESCRIPTION
**Pull request by rkuhn**
fixes #19377 and #19326 (the latter to be forward-ported to master)

### CODE REVIEW

File: akka-stream-testkit/src/main/scala/akka/stream/testkit/StreamTestKit.scala [hunk 1]
```diff
@@ -251,9 +251,13 @@ object TestSubscriber {
     /**
      * Expect and return a stream element.
      */
-    def expectNext(): I = probe.receiveOne(probe.remaining) match {
-      case OnNext(elem) ⇒ elem.asInstanceOf[I]
-      case other        ⇒ throw new AssertionError("expected OnNext, found " + other)
+    def expectNext(): I = {
+      val t = probe.remainingOr(probe.testKitSettings.SingleExpectDefaultTimeout.dilated)
+      probe.receiveOne(t) match {
+        case null         ⇒ throw new AssertionError(s"Expected OnNext(_), yet no element signaled during $t")
```
Comment (drewhk) [inline akka-stream-testkit/src/main/scala/akka/stream/testkit/StreamTestKit.scala]: good

**Comment by drewhk** [comment]
LGTM

**Comment by patriknw** [comment]
LGTM, thanks
