### PR TITLE
Use dedicated message for PersistentShardCoodinator termination instead of PoisonPill

### LINKED ISSUE #28093: Possible split-brain of ShardCoordinators during oldest node restart
Hello,

We have encountered following issue when cluster oldest node got restarted. We use akka-cluster and after oldest node got restarted it looks that we had some kind of split-brain condition. Couple of `PersistentShardCoordinator`s could not recover with following error:
```
2019-10-23 06:03:33,976 ERROR a.c.s.PersistentShardCoordinator Exception in receiveRecover when replaying event type [akka.cluster.sharding.ShardCoordinator$Internal$ShardHomeAllocated] with sequence number [2104] for persistenceId [/sharding/SessionsCoordinator].
java.lang.IllegalArgumentException: requirement failed: Shard [98] already allocated...
```

Our guess on scenario is as follows:
1. We had slowed down write to Cassandra (for whatever reason), so it took more time for `PersistentShardCoordinator` to persist its state
2. While persisting of state was still in progress, `ShardCoordinator` migrated to other node and managed to recover (I think this is possible due to usage of `PoisonPill` as termination message in `ClusterSingletonManager`)
3. New coordinator persisted same message with different sequence number as the one from step 1, leading to corrupted journal

Code snippet from `ClusterShardingGuardian` for creating shard region:
```
val shardRegion = context.child(encName).getOrElse {
  if (context.child(cName).isEmpty) {
    val coordinatorProps =
      if (settings.stateStoreMode == ClusterShardingSettings.StateStoreModePersistence)
        ShardCoordinator.props(typeName, settings, allocationStrategy)
      else
        ShardCoordinator.props(typeName, settings, allocationStrategy, rep, majorityMinCap)
    val singletonProps =
      BackoffOpts
        .onStop(
          childProps = coordinatorProps,
          childName = "coordinator",
          minBackoff = coordinatorFailureBackoff,
          maxBackoff = coordinatorFailureBackoff * 5,
          randomFactor = 0.2)
        .props
        .withDeploy(Deploy.local)
    val singletonSettings = settings.coordinatorSingletonSettings.withSingletonName("singleton").withRole(role)
    context.actorOf(
      ClusterSingletonManager
        .props(singletonProps, terminationMessage = PoisonPill, singletonSettings)
        .withDispatcher(context.props.dispatcher),
      name = cName)
  }

  context.actorOf(
    ShardRegion
      .props(
        typeName = typeName,
        entityProps = entityProps,
        settings = settings,
        coordinatorPath = cPath,
        extractEntityId = extractEntityId,
        extractShardId = extractShardId,
        handOffStopMessage = handOffStopMessage,
        replicator = rep,
        majorityMinCap)
      .withDispatcher(context.props.dispatcher),
    name = encName)
}
```

Also Akka documentation states that PoisonPill should not be used when shutting down persistent actors - https://doc.akka.io/docs/akka/current/persistence.html#safely-shutting-down-persistent-actors.

I wonder if this could be the reason? Any suggestions on how to validate this in test?

Our setup:
jvm: 11.0.4
scala: 2.12.10
akka: 2.5.25
akka-persistence-cassandra: 0.62
rememberEntities: true

### PR DESCRIPTION
**Pull request by retriku**
## Purpose

Fixes #28093 by using `ShardCoordinator.Terminate` as a terminationMessage in `ClusterShardingGuardian` instead of `PoisonPill`

## Background Context

Akka docs say that persistent actors should not be terminated with PoisonPill. https://doc.akka.io/docs/akka/current/persistence.html#safely-shutting-down-persistent-actors

### CODE REVIEW

**Comment by johanandren** [comment]
OK TO TEST

File: akka-cluster-tools/src/main/scala/akka/cluster/singleton/ClusterSingletonManager.scala [hunk 1]
```diff
@@ -472,6 +472,11 @@ class ClusterSingletonManagerIsStuck(message: String) extends AkkaException(mess
  *   Note that [[akka.actor.PoisonPill]] is a perfectly fine
  *   `terminationMessage` if you only need to stop the actor.
  *
+ *   '''Caution:''' care must be taken when stopping persistent actors as
+ *   [[akka.actor.PoisonPill]] can be processed faster than actor persists
+ *   its state, leading to possibly corrupt journal.
+ *   See also [[https://doc.akka.io/docs/akka/current/persistence.html#safely-shutting-down-persistent-actors]]
+ *
```
Comment (johanandren) [inline akka-cluster-tools/src/main/scala/akka/cluster/singleton/ClusterSingletonManager.scala]: Not sure this belongs here even if it is true.

File: akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala [hunk 2]
```diff
@@ -210,6 +210,11 @@ object ShardCoordinator {
     }
   }
 
+  /**
+   * Used as a special termination message from [[ClusterSharding]]
+   */
+  private[cluster] case object Terminate extends DeadLetterSuppression
```
Comment (johanandren) [inline akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala]: Becomes public in Java so needs
```
* INTERNAL API 
*/
@InternalApi private[cluster]
```

**Comment by johanandren** [comment]
Needs some reformatting for the CI server to be happy, see contributor docs a bit down here: https://github.com/akka/akka/blob/master/CONTRIBUTING.md#sbt

File: akka-cluster-tools/src/main/scala/akka/cluster/singleton/ClusterSingletonManager.scala (hunk 1 above)
Comment (retriku) [reply akka-cluster-tools/src/main/scala/akka/cluster/singleton/ClusterSingletonManager.scala]: Should I remove it?

File: akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala (hunk 2 above)
Comment (retriku) [reply akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala]: Maybe better then to move this `Terminate` under `private[akka] object Internal { ....`?

Comment (retriku) [reply akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala]: I moved `Terminate` message under `object Internal` of `ShardCoordinator`, please, review

File: akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterSharding.scala [hunk 3]
```diff
@@ -761,7 +761,7 @@ private[akka] class ClusterShardingGuardian extends Actor {
             val singletonSettings = settings.coordinatorSingletonSettings.withSingletonName("singleton").withRole(role)
```
Comment (patriknw) [inline akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterSharding.scala]: In above `BackoffOpts` we must also add
```
.withFinalStopMessage(msg => msg ==ShardCoordinator.Internal.Terminate)
```

otherwise it's possible that the Terminate message is not handled if the coordinator has already been stopped (e.g. due to persist failure)

File: akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala [hunk 4]
```diff
@@ -690,6 +696,9 @@ abstract class ShardCoordinator(
         })
         sender() ! reply
 
+      case ShardCoordinator.Internal.Terminate =>
+        log.debug("{} received termination message", context.self.path)
```
Comment (patriknw) [inline akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala]: self.path is already included in logging (`akkaSource` MDC if using SLF4J)

other logging here is not including it so let's make it consistent by not including it in the log message

File: akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala [hunk 5]
```diff
@@ -950,6 +959,9 @@ class PersistentShardCoordinator(
 
   def waitingForStateInitialized: Receive =
     ({
+      case ShardCoordinator.Internal.Terminate =>
+        log.debug("{} received termination message before state was initialized", context.self.path)
```
Comment (patriknw) [inline akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala]: same about self.path

File: akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala [hunk 6]
```diff
@@ -950,6 +959,9 @@ class PersistentShardCoordinator(
 
   def waitingForStateInitialized: Receive =
```
Comment (patriknw) [inline akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala]: There are several `Receive` cases in `DDataShardCoordinator`, which might also have to handle Terminate. Most of them are stashing so it will be handled after unbecome

In `waitingForUpdate` I think it can stop immediately because that is during the startup phase.

`waitingForUpdate` I think it needs to keep track of if it has received Terminate and stop after UpdateTimeout, otherwise it may repeat the retries forever (until majority write is successful). Maybe it's a more safe option to actually not stop it if those updates fail, but I'm somewhat uncertain if we should limit the number of retries for this stopping scenario.

If you aren not familiar with Distributed Data I could follow up with the changes needed there.

File: akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterSharding.scala (hunk 3 above)
Comment (retriku) [reply akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterSharding.scala]: You are right! I added withFinalStopMessage

File: akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala (hunk 4 above)
Comment (retriku) [reply akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala]: Yes, self.path is included, I removed it where needed

File: akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala (hunk 6 above)
Comment (retriku) [reply akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala]: I am not very familiar with DData, so any help/advise is welcome. I added handling of Terminate command in DdataShardCoordinator as well, basically approach is as follows, actor is stopped if state is not yet collected. If state is collected and some update is pending when Terminate is received I stash that message and mark ShardCoordinator state as terminated. Upon receiving either XxxTimeout or ModifyFailure i call for `unbecome` and `unstashAll`.

**Comment by retriku** [comment]
@patriknw I think I addressed your comments, could you, please, review. It is important for us to have this fixed in akka 2.5

**Comment by patriknw** [comment]
Understood, we have been at company meeting this week and  will review this on Monday,

File: akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterSharding.scala [hunk 7]
```diff
@@ -756,12 +756,13 @@ private[akka] class ClusterShardingGuardian extends Actor {
                   minBackoff = coordinatorFailureBackoff,
                   maxBackoff = coordinatorFailureBackoff * 5,
                   randomFactor = 0.2)
+                .withFinalStopMessage(msg => msg == ShardCoordinator.Internal.Terminate)
```
Comment (patriknw) [inline akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterSharding.scala]: shorter, but not important, `_ == ShardCoordinator.Internal.Terminate`

File: akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala [hunk 8]
```diff
@@ -1137,26 +1172,49 @@ class DDataShardCoordinator(
...
+          writeMajority.timeout.toMillis,
+          evt)
+        onTerminated()
+      } else {
+        log.error(
+          "The ShardCoordinator was unable to update shards distributed state within 'updating-state-timeout': {} millis (retrying), event={}",
+          writeMajority.timeout.toMillis,
+          evt)
+        // repeat until UpdateSuccess
+        sendAllShardsUpdate(newShard)
```
Comment (patriknw) [inline akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala]: maybe worth reducing the amount of code by something like this instead:
```
         log.error(
           "The ShardCoordinator was unable to update shards distributed state within 'updating-state-timeout': {} millis ({}), event={}",
           writeMajority.timeout.toMillis,
           if (terminating) "terminating" else "retrying",
           evt)
         if (terminating)
           onTerminated()
         else
           sendAllShardsUpdate(newShard) // repeat until UpdateSuccess
```

File: akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala [hunk 9]
```diff
@@ -1120,13 +1146,22 @@ class DDataShardCoordinator(
...
-        evt)
-      // repeat until UpdateSuccess
-      sendCoordinatorStateUpdate(evt)
+      if (terminated) {
+        log.error(
+          "The ShardCoordinator was unable to update a distributed state within 'updating-state-timeout': {} millis (terminating). " +
+          "Perhaps the ShardRegion has not started on all active nodes yet? event={}",
+          writeMajority.timeout.toMillis,
+          evt)
+        onTerminated()
```
Comment (patriknw) [inline akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala]: I wonder if this is the right thing to do for the UpdateTimeout? Comparing `onTerminated` with `unbecomeAfterUpdate` the main difference is that the `afterUpdateCallback` isn't called, but it kind of continues with stashed messages anyway until it reaches the stashed `Terminate`.

Maybe a safer (more like it was before) option would be to `stop` here? Meaning that it will try to complete pending updates, but if UpdateTimeout it doesn't continue with more.

File: akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala [hunk 10]
```diff
@@ -1146,19 +1146,15 @@ class DDataShardCoordinator(
...
-          evt)
-        onTerminated()
+      log.error(
+        "The ShardCoordinator was unable to update a distributed state within 'updating-state-timeout': {} millis ({}). " +
+        "Perhaps the ShardRegion has not started on all active nodes yet? event={}",
+        writeMajority.timeout.toMillis,
+        if (terminating) "terminating" else "retrying",
+        evt)
+      if (terminating) {
+        onTerminating()
```
Comment (patriknw) [inline akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala]: my thoughts about stop vs `onTerminating` was for all the UpdateTimeout and ModifyFailure cases, also here I think it should stop

File: akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala [hunk 11]
```diff
@@ -1171,38 +1167,31 @@ class DDataShardCoordinator(
...
+      if (terminating) {
+        context.stop(self)
       } else {
-        log.error(
-          "The ShardCoordinator was unable to update shards distributed state within 'updating-state-timeout': {} millis (retrying), event={}",
-          writeMajority.timeout.toMillis,
-          evt)
         // repeat until UpdateSuccess
-        sendAllShardsUpdate(newShard)
+        sendCoordinatorStateUpdate(evt)
```
Comment (patriknw) [inline akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala]: is this change correct?
it's `UpdateTimeout(AllShardsKey`

Comment (retriku) [reply akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala]: It is not correct. Fixed

File: akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala (hunk 10 above)
Comment (retriku) [reply akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala]: You are right.

**Comment by retriku** [comment]
@patriknw could you, please, check why PR Validation failed. When this task is run locally it succeeds. I am working on JDK 1.8

**Comment by patriknw** [comment]
That's an unrelated test that started failing recently. Just merged an temporary ignore of that test. Trying this again.

**Comment by patriknw** [comment]
PLS BUILD

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by patriknw** [comment]
I'll setup a jenkins multi-node test for this branch, before we merge.

**Comment by patriknw** [comment]
Passed full multi-node testing https://jenkins.akka.io:8498/job/akka-multi-node-repeat4/929/

File: akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala [hunk 12]
```diff
@@ -1138,25 +1164,41 @@ class DDataShardCoordinator(
...
+      }
 
     case GetShardHome(shard) =>
       if (!handleGetShardHome(shard))
         stash() // must wait for update that is in progress
 
+    case ShardCoordinator.Internal.Terminate =>
+      log.debug("Received termination message while waiting for update")
+      terminating = true
+      stash()
```
Comment (johanandren) [inline akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala]: I find the fact that we both toggle and stash here a bit trickier than it needs to be, 

Given that we have the flag we have saved the fact that we got it, so when modify completes (successfully or with a failure) or times out we know we are stopping and can do that, so skip stash here and do it in the same way for all three cases instead?

**Review by johanandren — COMMENTED** [review]
Mostly looks good, added one possible small simplification about the DDataCoordinator.

File: akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala (hunk 12 above)
Comment (patriknw) [reply akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala]: The idea was to continue processing more messages already in the stash when the update completes with UpdateSuccess, but stop if it completes with UpdateFailure.

Comment (johanandren) [reply akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala]: Ah, I see. Thanks for clarifying.

**Review by johanandren — APPROVED** [review]
LGTM, thanks @retriku !

**Comment by johanandren** [comment]
Needs a forward port to 2.6/master I can do that.
