### PR TITLE
Don't use TestActorRef for async testing 

### LINKED ISSUE #23445: [Failed] jdocs.testkit.ParentChildTest.testingWithCustomProps
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/9880/testReport/junit/jdocs.testkit/ParentChildTest/testingWithCustomProps_2/

I'm quite surprised about this regression. I could not make it fail locally.

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #23445

### CODE REVIEW

File: akka-docs/src/test/java/jdocs/testkit/ParentChildTest.java [hunk 1]
```diff
@@ -123,26 +119,21 @@ public void testingWithoutParent() {
...
-    Props childProps = Props.create(MockedChild.class);
-    TestActorRef<DependentParent> parent = TestActorRef.create(system, Props.create(DependentParent.class, childProps));
+    final TestProbe probe = new TestProbe(system);
+    final Props childProps = Props.create(MockedChild.class);
+    final ActorRef parent = system.actorOf(Props.create(DependentParent.class, childProps, probe.ref()));
 
     probe.send(parent, "pingit");
 
-    // test some parent state change
-    assertTrue(parent.underlyingActor().ponged == true || parent.underlyingActor().ponged == false);
```
Comment (johanandren) [inline akka-docs/src/test/java/jdocs/testkit/ParentChildTest.java]: This was the faulty assert expecting async interaction between parent and child to be available through TestActorRef parent

**Review by patriknw — APPROVED** [review]
LGTM

**Review by raboof — APPROVED** [review]
Nice, unfortunately there seems to be a merge conflict
