### PR TITLE
#21145 ShardRestart shouldn't go to userspace

### LINKED ISSUE #21145: ShardRestart message can't be processed properly in case of defined messageExtractorId
In request #17871 `RestartShard` message was added, but it's not working properly [here](https://github.com/akka/akka/blob/master/akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala#L416) in case `messageExtractorId` is defined. It ends up with `private` `RestartShard` being exposed to userspace, which can't handle it properly anyway.
The consequence of it all is clearly pretty frustrating, but the fix is really straight forward: just swap order in `match` as `RestartShard` is handled in `deliverMessage`.
I can submit a PR, if needed. But it will also require being covered by test.

### PR DESCRIPTION
**Pull request by 412b**
Fixes #21145
Due to order in pattern match `ShardRestart` message can be received in user-defined `messageExtractorId` (when set via providing `MessageExtractor` which is not returning null in case of unknown messages).
To avoid this it's sufficient to only change the order in the pattern match.
Also added note to documentation for using `MessageExtractor` to clarify that it should return null in case of unhandled message.

Additionally I've added minor fix for shadowing in pattern match in `RebalanceWorker` and minor cleanups in `ShardRegion`.

### CODE REVIEW

**Comment by 412b** [comment]
@patriknw how should we proceed with tests, if at all?

**Comment by drewhk** [comment]
OK TO TEST

File: akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala [hunk 1]
```diff
@@ -413,8 +413,8 @@ class ShardRegion(
     case msg: CoordinatorMessage                 ⇒ receiveCoordinatorMessage(msg)
     case cmd: ShardRegionCommand                 ⇒ receiveCommand(cmd)
     case query: ShardRegionQuery                 ⇒ receiveQuery(query)
-    case msg if extractEntityId.isDefinedAt(msg) ⇒ deliverMessage(msg, sender())
     case msg: RestartShard                       ⇒ deliverMessage(msg, sender())
+    case msg if extractEntityId.isDefinedAt(msg) ⇒ deliverMessage(msg, sender())
```
Comment (drewhk) [inline akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala]: ah, I see now.

File: akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala [hunk 2]
```diff
@@ -546,7 +546,7 @@ class ShardRegion(
   }
 
   def receiveTerminated(ref: ActorRef): Unit = {
-    if (coordinator.exists(_ == ref))
+    if (coordinator.contains(ref))
```
Comment (drewhk) [inline akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala]: nice!

**Comment by drewhk** [comment]
LGTM

File: akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterSharding.scala [hunk 3]
```diff
@@ -258,7 +258,7 @@ class ClusterSharding(system: ExtendedActorSystem) extends Extension {
    * @param entityProps the `Props` of the entity actors that will be created by the `ShardRegion`
    * @param settings configuration settings, see [[ClusterShardingSettings]]
    * @param messageExtractor functions to extract the entity id, shard id, and the message to send to the
-   *   entity from the incoming message
+   *   entity from the incoming message, for `unhandled` messages it must return `null`
```
Comment (johanandren) [inline akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterSharding.scala]: This is also already mentioned on the `entityId` method of `MessageExtractor` which is what should return `null`, so this should refer to that method rather than the entire `messageExtractor `.

File: akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala [hunk 4]
```diff
@@ -367,8 +367,8 @@ object ShardCoordinator {
     }
 
     def stoppingShard: Receive = {
-      case ShardStopped(shard) ⇒ done(ok = true)
-      case ReceiveTimeout      ⇒ done(ok = false)
+      case ShardStopped(`shard`) ⇒ done(ok = true)
```
Comment (johanandren) [inline akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala]: good catch

File: akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala (hunk 1 above)
Comment (johanandren) [inline akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala]: So this is the actual fix and the rest is boyscouting, right?

**Comment by johanandren** [comment]
LGTM with one nitpick

**Comment by 412b** [comment]
@johanandren replaced comment with ref to `MessageExtractor`
squashed and force pushed

File: akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala (hunk 1 above)
Comment (412b) [inline akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala]: in general - yes

**Comment by johanandren** [comment]
Thanks, we'll merge as soon as validation passes!

**Comment by patriknw** [comment]
LGTM, thanks for contributing
