### PR TITLE
#22429 Resize connections array when needed

### LINKED ISSUE #22429: Review the materializer's and the GraphStagePhase's uses of arrays (ArrayList, ArrayDeque, etc)
For simplicity I just made this fixed size, but these will fail on larger graphs. These have to be fixed by resizing wherever/whenever necessary.

### PR DESCRIPTION
**Pull request by 2m**
With the `connections` beeing of size 8 and without the resize 96/1638 stream tests failed. WIth the size of 16 - only 9. Therefore I left 16 as the initial size.

Fixes #22429

### CODE REVIEW

File: akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala [hunk 1]
```diff
@@ -613,6 +613,9 @@ final class GraphStageIsland(
 
   def conn(slot: Int): Connection = {
     maxConnections = math.max(slot, maxConnections)
+    if (maxConnections >= connections.length) {
+      connections = connections.padTo(connections.length * 2, null)
+    }
```
Comment (johanandren) [inline akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala]: What was the motivation for exponential growth here?

File: akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala [hunk 2]
```diff
@@ -581,7 +581,7 @@ final class GraphStageIsland(
   private val logicArrayType = Array.empty[GraphStageLogic]
   private[this] val logics = new ArrayList[GraphStageLogic](64)
```
Comment (johanandren) [inline akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala]: Should this also start small and then resize?

**Review by johanandren — APPROVED** [review]
LGTM with some comments

File: akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala [hunk 3]
```diff
@@ -613,6 +613,9 @@ final class GraphStageIsland(
 
   def conn(slot: Int): Connection = {
     maxConnections = math.max(slot, maxConnections)
+    if (maxConnections >= connections.length) {
+      connections = connections.padTo(connections.length * 2, null)
```
Comment (patriknw) [inline akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala]: might not be done very often, but this is more efficient:

    connections = java.util.Arrays.copyOf(connections, connections.length * 2)

File: akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala (hunk 1 above)
Comment (2m) [inline akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala]: The only motivation was so that it does not grow too many times. From all of the stream test cases 9 need to grow this array once in order to pass.

File: akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala (hunk 2 above)
Comment (2m) [inline akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala]: This is an ArrayList so no explicit resize logic needs to be added. I will change it to have the same initial size, as it seems to be used in similar places as `connections` is.

File: akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala (hunk 1 above)
Comment (johanandren) [inline akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala]: Alright, thanks for clarifying!

**Review by patriknw — APPROVED** [review]
LGTM
