### PR TITLE
Cancel GroupBy when all substreams cancel

### LINKED ISSUE #24370: Unable to cancel "groupBy" when all substreams cancel
If a failure is raised *after* a `groupBy`, it'll never reach the upstream before the `groupBy`.

```scala
object Test extends App {

  implicit val system: ActorSystem                = ActorSystem()
  implicit val materializer: ActorMaterializer    = ActorMaterializer()
  implicit val executionContext: ExecutionContext = ExecutionContext.global

  var tick = 0

  Source
    .tick[Int](1 second, 1 second, 1)
    .map { _ =>
      tick += 1
      tick
    }
    .log("1")
    .buffer(100, OverflowStrategy.backpressure)
    .groupBy(10, identity)
    .log("2")
    .map(x => if (x == 10) throw new RuntimeException("foo") else x)
    .mergeSubstreams
    .log("3")
    .addAttributes(Attributes.logLevels(Logging.InfoLevel, Logging.InfoLevel, Logging.ErrorLevel))
    .runWith(Sink.ignore)
    .onComplete {
      case Failure(t) =>
        println(s"Stream completed with error", t)
      case Success(_) =>
        println(s"Stream completed successfully")
    }

  Thread.sleep(15000)

  system.terminate()

}
```

In this example you can see:
1. A failure is raised
2. the downstream "3" is properly completed
3. all substreams "2" (10 substreams in total) are properly cancelled 
4. "1" keeps working, pushing elements downstream

I would expect the whole stream to be cancelled upstream and all stages to be stopped.

Is this behaviour intended? I'm misusing `groupBy` or `mergeSubstreams`? There's some known limitation around it? It's a bug?

Thanks.

### PR DESCRIPTION
**Pull request by aserrallerios**
Fixes: https://github.com/akka/akka/issues/24370

Whenever a substream is cancelled, it attempts to cancel the GroupBy stage if its out port is closed. The last of the substreams cancelling will succesfully cancel the GroupBy stage.

Please, tell me if this approach is valid. If you're ok with it I'll add a test for it.

### CODE REVIEW

**Comment by johanandren** [comment]
OK TO TEST

**Comment by johanandren** [comment]
I think this looks good, please go ahead covering it with tests!

**Comment by patriknw** [comment]
But is it really the right semantics for groupBy? It could be that no of the groups are intersesting so far but after a while a more interesting group arrives and you want to consume that.

**Comment by aserrallerios** [comment]
Yeah, unless the downstream has finished (`isClosed(out) == true`), which can only happen if the groupBy is merged again, and the downstream after the merge finishes. 

Anyway, new keys would never execute, even if the GB stage were not finished itself, because downstream would not ask for new keys or "groups".

**Comment by patriknw** [comment]
Ok, I missed that out closed part, thanks

File: akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala [hunk 1]
```diff
@@ -250,6 +250,12 @@ import scala.collection.JavaConverters._
         true
       } else false
 
+    private def tryCancel(): Boolean =
+      if (activeSubstreamsMap.isEmpty || (activeSubstreamsMap.size == substreamWaitingToBePushed.size)) {
```
Comment (jrudolph) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala]: That new condition is quite subtle, why is it needed? It might be clearer if we clear `substreamWaitingToBePushed` in `onDownstreamFinish` and remove it from the `activeSubstreamsMap` as well. Otherwise, please add a comment explaining the condition.

Comment (aserrallerios) [reply akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala]: It is needed because a new key can be pending (because downstream backpressured) before the downstream cancels.

How could we remove it from `activeSubstreamsMap`? Maybe keep the key on a `var`? I can do that, or I can add a comment. WDYT?

**Comment by aserrallerios** [comment]
Test added.

**Comment by aserrallerios** [comment]
I cannot reach the build result, is it just me? Was the failure due to my changes?

**Comment by jrudolph** [comment]
No. It's #24444.

**Comment by aserrallerios** [comment]
I've added the comment requested by @jrudolph. It's ready to go from my side. More reviews/requests are welcome 😃

**Review by johanandren — APPROVED** [review]
LGTM

**Review by jrudolph — APPROVED** [review]
LGTM
