### PR TITLE
Fix java leases usage from java and scala

### LINKED ISSUE #28685: Leases implemented in Java don't work
If there is Lease created in Java by implementing `akka.coordination.lease.javadsl.Lease` there will be exception thrown:

```
09:23:08.369 [test-lease-akka.actor.default-dispatcher-11] ERROR a.c.lease.scaladsl.LeaseProvider - Invalid lease configuration for leaseName [test], configPath [test-lease] lease-class [com.test.MyLease]. The class must implement Lease and have constructor with LeaseSettings parameter and optionally ActorSystem parameter.
java.lang.ClassCastException: class akka.coordination.lease.scaladsl.Lease is not assignable from class com.test.MyLease
	at akka.actor.ReflectiveDynamicAccess.$anonfun$getClassFor$1(ReflectiveDynamicAccess.scala:31)
	at scala.util.Try$.apply(Try.scala:210)
	at akka.actor.ReflectiveDynamicAccess.getClassFor(ReflectiveDynamicAccess.scala:28)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:47)
	at akka.coordination.lease.scaladsl.LeaseProvider.akka$coordination$lease$scaladsl$LeaseProvider$$loadLease(LeaseProvider.scala:66)
	at akka.coordination.lease.scaladsl.LeaseProvider$$anon$1.apply(LeaseProvider.scala:57)
	at akka.coordination.lease.scaladsl.LeaseProvider$$anon$1.apply(LeaseProvider.scala:52)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at akka.coordination.lease.scaladsl.LeaseProvider.getLease(LeaseProvider.scala:52)
	at akka.coordination.lease.javadsl.LeaseProvider.getLease(LeaseProvider.scala:37)
	at com.test.TestLeaseMain.main(TestLeaseMain.java:21)
09:23:09.370 [main] ERROR com.test.TestLeaseMain - Error
java.lang.ClassCastException: class akka.coordination.lease.scaladsl.Lease is not assignable from class com.test.MyLease
	at akka.actor.ReflectiveDynamicAccess.$anonfun$getClassFor$1(ReflectiveDynamicAccess.scala:31)
	at scala.util.Try$.apply(Try.scala:210)
	at akka.actor.ReflectiveDynamicAccess.getClassFor(ReflectiveDynamicAccess.scala:28)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:47)
	at akka.coordination.lease.scaladsl.LeaseProvider.akka$coordination$lease$scaladsl$LeaseProvider$$loadLease(LeaseProvider.scala:66)
	at akka.coordination.lease.scaladsl.LeaseProvider$$anon$1.apply(LeaseProvider.scala:57)
	at akka.coordination.lease.scaladsl.LeaseProvider$$anon$1.apply(LeaseProvider.scala:52)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at akka.coordination.lease.scaladsl.LeaseProvider.getLease(LeaseProvider.scala:52)
	at akka.coordination.lease.javadsl.LeaseProvider.getLease(LeaseProvider.scala:37)
	at com.test.TestLeaseMain.main(TestLeaseMain.java:21)
```

Seems like the Akka internals are trying to cast it to `akka.coordination.lease.scaladsl.Lease`. My configuration is the following:

```
akka.actor.provider = cluster
test-lease {
  lease-class = "com.test.MyLease"
  heartbeat-timeout = 5s
  heartbeat-interval = 1s
  lease-operation-timeout = 5s
}
```

And the Lease implementation looks like this:

```java
package com.test;

import akka.coordination.lease.LeaseSettings;
import akka.coordination.lease.javadsl.Lease;

import java.util.Optional;
import java.util.concurrent.CompletionStage;
import java.util.function.Consumer;

public class MyLease extends Lease {

    private final LeaseSettings settings;

    public MyLease(LeaseSettings settings) {
        this.settings = settings;
    }

    @Override
    public LeaseSettings getSettings() {
        return settings;
    }

    @Override
    public CompletionStage<Boolean> acquire() {
        return null;
    }

    @Override
    public CompletionStage<Boolean> acquire(Consumer<Optional<Throwable>> leaseLostCallback) {
        return null;
    }

    @Override
    public CompletionStage<Boolean> release() {
        return null;
    }

    @Override
    public boolean checkLease() {
        return false;
    }
}
```

### PR DESCRIPTION
**Pull request by chbatey**
Leases are always stored as a ScalaLease and the Java LeaseProvider
unwraps the adapter.

It is important that the same lease can be used from java and scala for
mixed language code bases.

Fixes #28685

### CODE REVIEW

File: akka-coordination/src/main/scala/akka/coordination/lease/internal/LeaseAdapter.scala [hunk 1]
```diff
@@ -33,3 +34,19 @@ final private[akka] class LeaseAdapter(delegate: ScalaLease)(implicit val ec: Ex
   override def checkLease(): Boolean = delegate.checkLease()
   override def getSettings(): LeaseSettings = delegate.settings
 }
+
+/**
+ * INTERNAL API
+ */
+@InternalApi
+final private[akka] class LeaseAdapterToScala(val delete: JavaLease)(implicit val ec: ExecutionContext)
```
Comment (patriknw) [inline akka-coordination/src/main/scala/akka/coordination/lease/internal/LeaseAdapter.scala]: `delete`? do you mean `delegate`?

File: akka-coordination/src/main/scala/akka/coordination/lease/scaladsl/LeaseProvider.scala [hunk 2]
```diff
@@ -54,39 +61,53 @@ class LeaseProvider(system: ExtendedActorSystem) extends Extension {
...
             .getConfig(configPath)
             .withFallback(system.settings.config.getConfig("akka.coordination.lease"))
-          loadLease(LeaseSettings(leaseConfig, leaseName, ownerName), configPath)
+
+          val settings = LeaseSettings(leaseConfig, leaseName, ownerName)
+
+          // Try and load a scala implementation
+          val lease: Try[Lease] =
+            loadLease[Lease](settings).recoverWith {
+              case _: ClassCastException =>
```
Comment (patriknw) [inline akka-coordination/src/main/scala/akka/coordination/lease/scaladsl/LeaseProvider.scala]:
```
// and then try load java implementation
```

**Review by patriknw — APPROVED** [review]
LGTM, with minors

**Review by johanandren — APPROVED** [review]
LGTM

**Comment by patriknw** [comment]
mima problem

File: akka-coordination/src/main/scala/akka/coordination/lease/internal/LeaseAdapter.scala (hunk 1 above)
Comment (chbatey) [reply akka-coordination/src/main/scala/akka/coordination/lease/internal/LeaseAdapter.scala]: Si senor
