### PR TITLE
Return failed IOResult for non-existint file (closes #20590)

### LINKED ISSUE #20590: FileIO.fromPath should return IOResult with failure status
The following code can be used to reproduce the issue:

``` scala
import akka.actor.ActorSystem
import akka.stream.ActorMaterializer
import akka.stream.scaladsl.{FileIO, Sink}
import java.nio.file.Paths
import scala.concurrent.Await
import scala.concurrent.duration.DurationInt

object Test {

  def main(args: Array[String]): Unit = test()
  
  def test(): Unit = {
    implicit val system = ActorSystem()
    implicit val mat = ActorMaterializer()
    val result = FileIO.fromPath(Paths.get("this-file-must-not-exist"))
      .to(Sink.ignore)
      .run()
    assert(Await.result(result, 42.seconds).status.isFailure)
  }
}
```

Instead of an `IOResult` with a `status` holding a `Failure` with a `FileNotFoundException` or such, the `status` is `Success(Done)` (and the `count` is `0`).

### PR DESCRIPTION
**Pull request by hseeberger**

### CODE REVIEW

File: akka-stream-tests/src/test/scala/akka/stream/io/FileSourceSpec.scala [hunk 1]
```diff
@@ -138,13 +138,14 @@ class FileSourceSpec extends AkkaSpec(UnboundedMailboxConfig) {
...
-    "onError whent trying to read from file which does not exist" in assertAllStagesStopped {
-      val p = FileIO.fromPath(notExistingFile).runWith(Sink.asPublisher(false))
+    "onError with failure and return a failed IOResult when trying to read from file which does not exist" in assertAllStagesStopped {
+      val (r, p) = FileIO.fromPath(notExistingFile).toMat(Sink.asPublisher(false))(Keep.both).run()
       val c = TestSubscriber.manualProbe[ByteString]()
       p.subscribe(c)
 
       c.expectSubscription()
       c.expectError()
+      val ioResult = Await.result(r, 1.second).status.isFailure shouldBe true
```
Comment (ktoso) [inline akka-stream-tests/src/test/scala/akka/stream/io/FileSourceSpec.scala]: 3 seconds just because file access on Jenkins sometimes randomly goes into crawling slow more please :)

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
LGTM, thanks :)

File: akka-stream-tests/src/test/scala/akka/stream/io/FileSourceSpec.scala (hunk 1 above)
Comment (hseeberger) [inline akka-stream-tests/src/test/scala/akka/stream/io/FileSourceSpec.scala]: Maybe use `.dilated`?

Comment (hseeberger) [inline akka-stream-tests/src/test/scala/akka/stream/io/FileSourceSpec.scala]: OK, 3 seconds and dilated. Done.

**Comment by hseeberger** [comment]
WAT? Strange build result: "Permission denied, please try again."

**Comment by ktoso** [comment]
Oh yeah, this happens every blue moon... we believe it's flaky network infrastructure on those servers.
PR is good :-) thanks a lot!

File: akka-stream/src/main/scala/akka/stream/impl/io/FilePublisher.scala [hunk 2]
```diff
@@ -52,6 +52,7 @@ private[akka] final class FilePublisher(f: Path, completionPromise: Promise[IORe
       chan = FileChannel.open(f, FilePublisher.Read)
     } catch {
       case ex: Exception ⇒
+        completionPromise.success(IOResult(0L, Failure(ex)))
```
Comment (patriknw) [inline akka-stream/src/main/scala/akka/stream/impl/io/FilePublisher.scala]: There is also one completionPromise.success in `postStop` and now there is a risk that it will fail. Perhaps change that to `trySuccess`?

Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/impl/io/FilePublisher.scala]: is `Exception` the right type to catch?

Comment (hseeberger) [inline akka-stream/src/main/scala/akka/stream/impl/io/FilePublisher.scala]: @patriknw, that will only be executed if the channel is not null, so there is zero risk for a collision.
@viktorklang, I agree, but that's out of scope for this PR.

Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/impl/io/FilePublisher.scala]: Boyscouting is always in scope :-)

-- 
Cheers,
√

Comment (patriknw) [inline akka-stream/src/main/scala/akka/stream/impl/io/FilePublisher.scala]: I see, thanks for clarifying
changing to `NonFatal(ex)` wouldn't hurt

Comment (hseeberger) [inline akka-stream/src/main/scala/akka/stream/impl/io/FilePublisher.scala]: OK, I'll change to `NonFatal` and also use `trySuccess` to make the code more robust to future changes.

**Comment by patriknw** [comment]
LGTM, thanks
