### PR TITLE
Hidden protocol and interception

### LINKED ISSUE #25727: PersistentActorJavaDslTest: tapPersistentActor expected akka.persistence.typed.javadsl.PersistentActorJavaDslTest$Increment@4c84057d, found RecoveryPermitGranted
multi-node: https://jenkins.akka.io:8498/blue/rest/organizations/jenkins/pipelines/akka-multi-node/runs/2980/log/?start=0
```
[info] PersistentActorJavaDslTest:
[info] - chainableSideEffectsWithEvents
[info] - transformEvent
[info] - tapPersistentActor *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: expected akka.persistence.typed.javadsl.PersistentActorJavaDslTest$Increment@4c84057d, found RecoveryPermitGranted
[info]   at scala.Predef$.assert(Predef.scala:219)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage_internal(TestProbeImpl.scala:137)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage(TestProbeImpl.scala:120)
[info]   at akka.persistence.typed.javadsl.PersistentActorJavaDslTest.tapPersistentActor(PersistentActorJavaDslTest.java:454)
[info]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[info]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info]   at java.lang.reflect.Method.invoke(Method.java:497)
[info]   at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[info]   at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[info]   at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[info]   at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[info]   at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
[info]   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
[info]   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
[info]   at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[info]   at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[info]   at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[info]   at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[info]   at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[info]   at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
[info]   at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[info]   at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[info]   at org.junit.runners.Suite.runChild(Suite.java:128)
[info]   at org.junit.runners.Suite.runChild(Suite.java:27)
[info]   at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[info]   at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[info]   at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[info]   at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[info]   at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[info]   at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[info]   at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[info]   at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[info]   at org.junit.runner.JUnitCore.run(JUnitCore.java:105)
[info]   at org.junit.runner.JUnitCore.run(JUnitCore.java:94)
[info]   at org.scalatest.junit.JUnitSuiteLike.run(JUnitSuiteLike.scala:242)
[info]   at org.scalatest.junit.JUnitSuiteLike.run$(JUnitSuiteLike.scala:230)
[info]   at org.scalatest.junit.JUnitSuite.run(JUnitSuite.scala:71)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:507)
[info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:304)
[info]   at sbt.ForkMain$Run$$Lambda$435/1822630059.call(Unknown Source)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]   at java.lang.Thread.run(Thread.java:745)
```

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #25727

Somewhat of a hack, but on the other hand it is a corner case/one could argue that what we do with persistent actor is also a hack (accepting more messages than we say in the protocol rather than adapt them)

### CODE REVIEW

**Comment by johanandren** [comment]
Another option would perhaps be to use message adapters for the journal interaction, but that would be a bigger change to the persistent actor design so wanted to see what the team thinks of this first.

File: akka-actor-typed/src/main/scala/akka/actor/typed/BehaviorInterceptor.scala [hunk 1]
```diff
@@ -17,6 +17,13 @@ import akka.annotation.{ DoNotInherit, InternalApi }
 abstract class BehaviorInterceptor[O, I] {
   import BehaviorInterceptor._
 
+  /**
+   * Allows for bypassing the interceptor for certain messages. Useful if the official protocol and the actual
+   * protocol of an actor causes problems, for example class cast exceptions for a message not of type `O` that
+   * the actor still knows how to deal with.
+   */
+  def applyFor(message: Any): Boolean = true
```
Comment (helena) [inline akka-actor-typed/src/main/scala/akka/actor/typed/BehaviorInterceptor.scala]: Trying to grep why the message should be allowed through of not `O`, doesn't it leak the idea of how the typed actor idea is constructed or are we saying we now want something else.

Comment (helena) [reply akka-actor-typed/src/main/scala/akka/actor/typed/BehaviorInterceptor.scala]: Or perhaps we want a strongly typed and a declarable but separate middle ground actor that would allow and include this - vs having it available to be used here.

**Comment by helena** [comment]
I'm not sure we should allow the idea as a whole to bend overall for a corner case versus perhaps create a new declarable that is the only think which might allow it - to not have it leak?

File: akka-actor-typed/src/main/scala/akka/actor/typed/BehaviorInterceptor.scala (hunk 1 above)
Comment (hepin1989) [reply akka-actor-typed/src/main/scala/akka/actor/typed/BehaviorInterceptor.scala]: kind of `isDefinedAt`,isn't it?

Comment (patriknw) [reply akka-actor-typed/src/main/scala/akka/actor/typed/BehaviorInterceptor.scala]: I don't know exactly what the reason was but I recall that it was something that was suggested in the review but said that it didn't work.

Comment (patriknw) [reply akka-actor-typed/src/main/scala/akka/actor/typed/BehaviorInterceptor.scala]: A better API might be:
```
def interceptMessageType[M]: Class[M <: O]
```

then it's more like an optional ClassTag

Comment (johanandren) [reply akka-actor-typed/src/main/scala/akka/actor/typed/BehaviorInterceptor.scala]: More for the specific case but less powerful, because the current one allows for arbitrary selection of messages to select. Is it really better with the class one?

**Comment by helena** [comment]
@johanandren I really appreciate a good wiretap.

File: akka-actor-typed/src/main/scala/akka/actor/typed/BehaviorInterceptor.scala (hunk 1 above)
Comment (patriknw) [reply akka-actor-typed/src/main/scala/akka/actor/typed/BehaviorInterceptor.scala]: arbitrary selection can be done inside the `override def aroundReceive`

Comment (johanandren) [reply akka-actor-typed/src/main/scala/akka/actor/typed/BehaviorInterceptor.scala]: Fair enough

File: akka-actor-typed/src/main/scala/akka/actor/typed/BehaviorInterceptor.scala [hunk 2]
```diff
@@ -17,6 +17,17 @@ import akka.annotation.{ DoNotInherit, InternalApi }
...
 
+  /**
+   * Allows for applying the interceptor only to certain message types. Useful if the official protocol and the actual
+   * protocol of an actor causes problems, for example class cast exceptions for a message not of type `O` that
+   * the actor still knows how to deal with. Note that this is only possible to use when `O` and `I` are the same type.
+   *
+   * @return A subtype of `O` that should be intercepted or `null` to intercept all `O`s.
+   *         Subtypes of `O` matching this are passed directly to the inner behavior without interception.
+   */
+  // null for all to avoid having to deal with class tag/explicit class in the default case of no filter
```
Comment (patriknw) [inline akka-actor-typed/src/main/scala/akka/actor/typed/BehaviorInterceptor.scala]: doesn't a comment here remove the scaladoc/javadoc ?
add it inside the method, as an implementation note

**Review by patriknw — APPROVED** [review]
LGTM, as a power feature (workaround). We might want to revisit using adapters in the eventsourced behavior if it becomes painful to use with interceptors, but it can wait for now.

File: akka-actor-typed/src/main/scala/akka/actor/typed/BehaviorInterceptor.scala (hunk 2 above)
Comment (johanandren) [reply akka-actor-typed/src/main/scala/akka/actor/typed/BehaviorInterceptor.scala]: No, that's fine (double checked because your question made me less confident). I can move it anyway if you want.

File: akka-actor-typed/src/main/scala/akka/actor/typed/BehaviorInterceptor.scala [hunk 3]
```diff
@@ -17,6 +17,17 @@ import akka.annotation.{ DoNotInherit, InternalApi }
 abstract class BehaviorInterceptor[O, I] {
   import BehaviorInterceptor._
 
+  /**
+   * Allows for applying the interceptor only to certain message types. Useful if the official protocol and the actual
+   * protocol of an actor causes problems, for example class cast exceptions for a message not of type `O` that
+   * the actor still knows how to deal with. Note that this is only possible to use when `O` and `I` are the same type.
```
Comment (chbatey) [inline akka-actor-typed/src/main/scala/akka/actor/typed/BehaviorInterceptor.scala]: Should we create a new subtype for this that enforces rather than null turning this off?

**Review by chbatey — APPROVED** [review]
LGTM, I think this is fine as is but maybe consider making a specific sub class?

File: akka-actor-typed/src/main/scala/akka/actor/typed/BehaviorInterceptor.scala (hunk 3 above)
Comment (johanandren) [reply akka-actor-typed/src/main/scala/akka/actor/typed/BehaviorInterceptor.scala]: I don't think that's needed, it's a power user feature that will likely not be used much, if at all, and it is only called by our internals, and _when_ it is used it is by the user overriding and not returning null, so not much risk for surprise-NPE:ing-users.
