### PR TITLE
=act #18938 fix MetricsBasedResizerSpec

### LINKED ISSUE #18938: failed: MetricsBasedResizer
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3141/consoleFull

### PR DESCRIPTION
**Pull request by johanandren**
Maybe fixes #18938 

May be grasping at straws here, but, couldn't find anything wrong except test using wall clock for time measurement which may be affected by leap seconds etc?

### CODE REVIEW

**Comment by drewhk** [comment]
LGTM

File: akka-actor-tests/src/test/scala/akka/routing/MetricsBasedResizerSpec.scala [hunk 1]
```diff
@@ -244,8 +244,8 @@ class MetricsBasedResizerSpec extends AkkaSpec(ResizerSpec.config) with DefaultT
 
       resizer.reportMessageCount(router.routees, router.msgs.size)
 
-      val after = LocalDateTime.now
-      resizer.performanceLog(2).toMillis shouldBe (java.time.Duration.between(before, after).toMillis / 2 +- 1)
+      val after = System.nanoTime()
+      resizer.performanceLog(2).toMillis shouldBe ((before - after).nanos.toMillis / 2 +- 1)
```
Comment (patriknw) [inline akka-actor-tests/src/test/scala/akka/routing/MetricsBasedResizerSpec.scala]: what is this test doing? expecting something to happen within 1 millisecond?

Comment (johanandren) [inline akka-actor-tests/src/test/scala/akka/routing/MetricsBasedResizerSpec.scala]: performanceLog contains the average duration between two messages for a specific pool size (fixed to 2 in this case), so it passes two messages through, times that, and expects the duration to be half the time for two messages, give or take 1 millisecond.

Wait a minute, last time it failed it was with `0 was not 3 plus or minus 1`, so I guess that means time between first report and second was < 1 milli. I think I have to go back to thinking about this one.

Comment (patriknw) [inline akka-actor-tests/src/test/scala/akka/routing/MetricsBasedResizerSpec.scala]: ok, but what happens if there is some unexpected pause somewhere?
those CI machines are very sluggish

Comment (johanandren) [inline akka-actor-tests/src/test/scala/akka/routing/MetricsBasedResizerSpec.scala]: Yeah, I thought it was safe because of actually measuring, and basing on that, but, even so it would need an explicit sleep in-between the two operations to make sure it is not done super-quickly.

So maybe that plus the 'give-or-take' part as a factor of the total time rather, so that it is more forgiving on a slow machine...

**Comment by johanandren** [comment]
The fail above was the `VirtualProcessorSingleTest`, unrelated.

**Comment by patriknw** [comment]
LGTM
