### PR TITLE
Typed receptionist clashes with the clusterclient receptionist 

### LINKED ISSUE #26848: Cluster client and typed receptionist cannot co-exist
Both starts an actor at `/system/receptionist`, so if typed-cluster is on the class path it will always fail starting its receptionist by default.

Can be worked around by setting `akka.cluster.client.receptionist.name` to some other name than `receptionist`

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #26848

Couldn't think of a reasonable single name that didn't feel contrived, so made the typed local and cluster receptionist have different paths.

### CODE REVIEW

**Review by chbatey — APPROVED** [review]
LGTM

File: akka-actor-typed/src/main/scala/akka/actor/typed/internal/receptionist/LocalReceptionist.scala [hunk 1]
```diff
@@ -31,6 +32,8 @@ private[akka] final class LocalReceptionist
 @InternalApi
 private[akka] object LocalReceptionist extends ReceptionistBehaviorProvider {
 
+  override val name = "local-receptionist"
```
Comment (patriknw) [inline akka-actor-typed/src/main/scala/akka/actor/typed/internal/receptionist/LocalReceptionist.scala]: I think we mostly use the camel case naming convention for actor names (`localReceptionist`)

File: akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/receptionist/ClusterReceptionist.scala [hunk 2]
```diff
@@ -42,6 +42,8 @@ private[typed] object ClusterReceptionist extends ReceptionistBehaviorProvider {
 
   final val EmptyORMultiMap = ORMultiMap.empty[ServiceKey[_], Entry]
 
+  override val name = "cluster-receptionist"
```
Comment (patriknw) [inline akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/receptionist/ClusterReceptionist.scala]: `clusterReceptionist`

**Review by patriknw — COMMENTED** [review]
also add a note in migration guide about that change and that it means that a rolling update for a Typed cluster is not possible

File: akka-actor-typed/src/main/scala/akka/actor/typed/internal/receptionist/LocalReceptionist.scala (hunk 1 above)
Comment (johanandren) [reply akka-actor-typed/src/main/scala/akka/actor/typed/internal/receptionist/LocalReceptionist.scala]: 🐫

**Review by patriknw — APPROVED** [review]
LGTM
