### PR TITLE
Harden StreamTestKitSpec

### LINKED ISSUE #24956: Failed: StreamTestKitSpec
https://jenkins.akka.io:8498/job/akka-nightly-2.12/545/testReport/junit/akka.stream.testkit/StreamTestKitSpec/A_TestSink_Probe_must__expectNextWithTimeoutPF_should_fail_after_timeout_when_element_delayed/

```
Expected exception java.lang.AssertionError to be thrown, but no exception was thrown
	at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:528)
	at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:527)
	at akka.testkit.AkkaSpec.newAssertionFailedException(AkkaSpec.scala:60)
	at org.scalatest.Assertions.intercept(Assertions.scala:822)
	at org.scalatest.Assertions.intercept$(Assertions.scala:802)
	at akka.testkit.AkkaSpec.intercept(AkkaSpec.scala:60)
	at akka.stream.testkit.StreamTestKitSpec.$anonfun$new$23(StreamTestKitSpec.scala:146)
	at akka.stream.testkit.StreamTestKitSpec$$Lambda$377/919291663.apply(Unknown Source)
```

### PR DESCRIPTION
**Pull request by chbatey**
Closes #24956

### CODE REVIEW

File: akka-stream-testkit/src/test/scala/akka/stream/testkit/StreamTestKitSpec.scala [hunk 1]
```diff
@@ -184,11 +184,12 @@ class StreamTestKitSpec extends AkkaSpec {
     "#expectNextChainingPF should fail after timeout when element delayed" in {
       intercept[AssertionError] {
         val timeout = 100.millis
-        val overTimeout = timeout + (10.millis)
+        val overTimeout = timeout + 50.millis
```
Comment (johanandren) [inline akka-stream-testkit/src/test/scala/akka/stream/testkit/StreamTestKitSpec.scala]: I don't get it, the old one failed because 10ms is the granularity of tick or something like that?

Comment (chbatey) [reply akka-stream-testkit/src/test/scala/akka/stream/testkit/StreamTestKitSpec.scala]: I assumed that 10ms was quite tight. If `expectNextChainingPF` doesn't start its timeout within 10ms of the stream starting then it'll get the element and then fail

Comment (johanandren) [reply akka-stream-testkit/src/test/scala/akka/stream/testkit/StreamTestKitSpec.scala]: Ah, thx for clarifying

**Review by johanandren — APPROVED** [review]
LGTM

**Review by patriknw — APPROVED** [review]
LGTM, it will at least improve the situation
