### PR TITLE
2.5.10 wire protocol regression

### LINKED ISSUE #24622: 2.5.10 node joining 2.5.9 error
during rolling upgrade on the staging environment we've run into an issue, when node running 2.5.10 fails to join 2.5.9 cluster with the following warning in 2.4.9 nodes' logs
`akka.remote.EndpointReader - Serializer not defined for message with serializer id [6] and manifest []. Transient association error (association remains live). Cannot find manifest class [akka.cluster.InternalClusterAction$InitJoin] for serializer with id [5].`

As I haven't found anything related to rolling upgrades warnings, seems like a possible regression to me.

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #24622

Manually checked joining a 2.5.9 cluster with this change works, and that the other way around gives a config-checker warning disallowing the 2.5.9 node from joining a cluster with this pr applied.

### CODE REVIEW

File: akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala [hunk 1]
```diff
@@ -18,72 +18,65 @@ import scala.collection.JavaConverters._
...
+private[akka] object ClusterMessageSerializer {
+  // FIXME use short manifests when we can break wire compatibility
+  // needs to be full class names for backwards compatibility
+  val JoinManifest = classOf[InternalClusterAction.Join].getName
+  val WelcomeManifest = classOf[InternalClusterAction.Welcome].getName
+  val LeaveManifest = classOf[ClusterUserAction.Leave].getName
+  val DownManifest = classOf[ClusterUserAction.Down].getName
+  // #24622 wire compatibility
+  val InitJoinManifest = "akka.cluster.InternalClusterAction$InitJoin$" // use this to be able to roll up from 2.5.9
+  val InitJoinManifest2 = classOf[InternalClusterAction.InitJoin].getName // but also accept this from 2.5.10
```
Comment (johanandren) [inline akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala]: Not strictly necessary, but for completeness

File: akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala [hunk 2]
```diff
@@ -18,72 +18,65 @@ import scala.collection.JavaConverters._
...
+@InternalApi
+private[akka] object ClusterMessageSerializer {
+  // FIXME use short manifests when we can break wire compatibility
+  // needs to be full class names for backwards compatibility
+  val JoinManifest = classOf[InternalClusterAction.Join].getName
+  val WelcomeManifest = classOf[InternalClusterAction.Welcome].getName
+  val LeaveManifest = classOf[ClusterUserAction.Leave].getName
+  val DownManifest = classOf[ClusterUserAction.Down].getName
+  // #24622 wire compatibility
+  val InitJoinManifest = "akka.cluster.InternalClusterAction$InitJoin$" // use this to be able to roll up from 2.5.9
```
Comment (johanandren) [inline akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala]: This is the first half of the fix - `InitJoin` was a singleton but became a case class, we need to accept the old class-name/manifest and also send using that

File: akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala [hunk 3]
```diff
@@ -224,6 +226,73 @@ class ClusterMessageSerializer(val system: ExtendedActorSystem) extends BaseSeri
...
+            case cm.ConfigCheck.Type.IncompatibleConfig ⇒ IncompatibleConfig
+            case cm.ConfigCheck.Type.UncheckedConfig ⇒ UncheckedConfig
+          }
+        } else UncheckedConfig
+
+      InternalClusterAction.InitJoinAck(addressFromProto(i.getAddress), configCheck)
+    } catch {
+      case ex: akka.protobuf.InvalidProtocolBufferException =>
+        // nodes previous to 2.5.9 sends just an address
+        InternalClusterAction.InitJoinAck(addressFromBinary(bytes), UncheckedConfig)
```
Comment (johanandren) [inline akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala]: This is the other half of the fix - 2.5.9 would only send a serialized `Address` but `InitJoinAck` was changed and does now have a separate message. As we do not need to support joining a 2.5.9 node to a 2.5.10+ cluster, only the other way around, we can keep serializing and sending the `InitJoinAck` protobuf message.

File: akka-actor-tests/src/test/scala/akka/serialization/SerializeSpec.scala [hunk 4]
```diff
@@ -369,17 +369,10 @@ class SerializationCompatibilitySpec extends AkkaSpec(SerializationTests.mostlyR
...
-            "0000010200014c00076661696c75726574000e4c7363616c612f4f7074696f6e3b78707372000a73" +
-            "63616c612e536f6d65e2a09f87fc0836ae0200014c0001787400124c6a6176612f6c616e672f4f62" +
-            "6a6563743b7872000c7363616c612e4f7074696f6ee36024a8328a45e9020000787070"
-        } else {
-          "aced00057372001b616b6b612e64697370617463682e7379736d73672e4372656174650000000000" +
-            "0000010200014c00076661696c75726574000e4c7363616c612f4f7074696f6e3b78707372000a73" +
-            "63616c612e536f6d651122f2695ea18b740200014c0001787400124c6a6176612f6c616e672f4f62" +
-            "6a6563743b7872000c7363616c612e4f7074696f6efe6937fddb0e6674020000787070"
-        })
+        "aced00057372001b616b6b612e64697370617463682e7379736d73672e4372656174650000000000" +
```
Comment (jrudolph) [inline akka-actor-tests/src/test/scala/akka/serialization/SerializeSpec.scala]: "aced" :+1:

File: akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala [hunk 5]
```diff
@@ -18,72 +18,65 @@ import scala.collection.JavaConverters._
...
 /**
- * Protobuf serializer of cluster messages.
+ * INTERNAL API
  */
-class ClusterMessageSerializer(val system: ExtendedActorSystem) extends BaseSerializer {
+@InternalApi
+private[akka] object ClusterMessageSerializer {
+  // FIXME use short manifests when we can break wire compatibility
+  // needs to be full class names for backwards compatibility
+  val JoinManifest = classOf[InternalClusterAction.Join].getName
```
Comment (jrudolph) [inline akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala]: I wonder if we should replace them now with the current names?

File: akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala [hunk 6]
```diff
@@ -370,10 +439,10 @@ class ClusterMessageSerializer(val system: ExtendedActorSystem) extends BaseSeri
       setVersion(vectorClockToProto(status.version, hashMapping)).build()
   }
 
-  private def gossipEnvelopeFromBinary(bytes: Array[Byte]): GossipEnvelope =
+  private def deserializeGossipEnvelope(bytes: Array[Byte]): GossipEnvelope =
     gossipEnvelopeFromProto(cm.GossipEnvelope.parseFrom(bytes))
 
-  private def gossipStatusFromBinary(bytes: Array[Byte]): GossipStatus =
+  private def desrializeGossipStatus(bytes: Array[Byte]): GossipStatus =
```
Comment (jrudolph) [inline akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala]: "deserializeGossipStatus"

File: akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala (hunk 5 above)
Comment (johanandren) [reply akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala]: We can't because we need to be able to interact with (join) 2.5.9-nodes in a rolling upgrade.

Comment (johanandren) [reply akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala]: Or, you mean hardcode the names so we don't break if we refactor?

Comment (jrudolph) [reply akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala]: Yep, hardcoding seems safer.

Comment (johanandren) [reply akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala]: God point. I'll do that.

File: akka-cluster/src/test/scala/akka/cluster/protobuf/ClusterMessageSerializerSpec.scala [hunk 7]
```diff
@@ -82,6 +82,21 @@ class ClusterMessageSerializerSpec extends AkkaSpec(
       checkSerialization(InternalClusterAction.Welcome(uniqueAddress, g2))
     }
 
+    "be compatible with wire format of version 2.5.9 (using Init singleton instead of class)" in {
+      // we must use the old singleton class name so that the other side will see an InitJoin
+      // but discard the config as it does not know about the config check
+      val oldClassName = "akka.cluster.InternalClusterAction$InitJoin$"
+      serializer.manifest(InternalClusterAction.InitJoin(ConfigFactory.empty())) should ===(oldClassName)
```
Comment (jrudolph) [inline akka-cluster/src/test/scala/akka/cluster/protobuf/ClusterMessageSerializerSpec.scala]: I don't feel super confident with these kinds of tests that we really ensured compatibility again (and didn't break anything else). Could you create a test like the next one to make sure it still works at least for `InitJoin`?

**Review by jrudolph — COMMENTED** [review]
Changes LGTM, good to use the common style in the serializer. I'd feel better if there were comprehensive tests.

**Comment by raboof** [comment]
(jenkins failure is scalariform)

**Comment by johanandren** [comment]
@jrudolph there are quite comprehensive tests in `ClusterMessageSerializerSpec` doing serialization roundtrips for quite some variations of the messages etc. Would still not have caught the regression ofc but its not untested.

**Comment by johanandren** [comment]
Tested this commit with a separate 2.5.9 cluster as well, just to be sure I didn't break something with the hardcoded class names

File: akka-cluster/src/test/scala/akka/cluster/protobuf/ClusterMessageSerializerSpec.scala (hunk 7 above)
Comment (johanandren) [reply akka-cluster/src/test/scala/akka/cluster/protobuf/ClusterMessageSerializerSpec.scala]: Ah, missed this one. The thing is that it is then serialized to empty byte array, so that means that it is just about the class name passed to `fromBinary` which is tested on the rows below.

I should add one for the other half of the issue with the ack just being sent as address though.

File: akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala [hunk 8]
```diff
@@ -100,7 +92,25 @@ class ClusterMessageSerializer(val system: ExtendedActorSystem) extends BaseSeri
...
+      throw new IllegalArgumentException(s"Can't serialize object of type ${obj.getClass} in [${getClass.getName}]")
+  }
+
+  def fromBinary(bytes: Array[Byte], manifest: String): AnyRef = manifest match {
+    case HeartBeatManifest         ⇒ deserializeHeartBeat(bytes)
+    case HeartBeatRspManifest      ⇒ deserializeHeartBeatRsp(bytes)
+    case GossipStatusManifest      ⇒ deserializeGossipStatus(bytes)
+    case GossipEnvelopeManifest    ⇒ deserializeGossipEnvelope(bytes)
+    case InitJoinManifest          ⇒ deserializeInitJoin(bytes)
+    case InitJoinManifest2         ⇒ deserializeInitJoin(bytes)
```
Comment (patriknw) [inline akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala]: Is this needed/used?
If we ever want to change we should use short manifest strings, but that is out of scope for this fix.

File: akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala [hunk 9]
```diff
@@ -100,7 +92,25 @@ class ClusterMessageSerializer(val system: ExtendedActorSystem) extends BaseSeri
...
+    case InitJoinAckManifest       ⇒ deserializeInitJoinAck(bytes)
```
Comment (patriknw) [inline akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala]: Were there more objects that were changed to classes?

File: akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala [hunk 10]
```diff
@@ -224,6 +225,73 @@ class ClusterMessageSerializer(val system: ExtendedActorSystem) extends BaseSeri
...
+            case cm.ConfigCheck.Type.CompatibleConfig   ⇒ CompatibleConfig(ConfigFactory.parseString(i.getConfigCheck.getClusterConfig))
+            case cm.ConfigCheck.Type.IncompatibleConfig ⇒ IncompatibleConfig
+            case cm.ConfigCheck.Type.UncheckedConfig    ⇒ UncheckedConfig
+          }
+        } else UncheckedConfig
+
+      InternalClusterAction.InitJoinAck(addressFromProto(i.getAddress), configCheck)
+    } catch {
+      case ex: akka.protobuf.InvalidProtocolBufferException ⇒
+        // nodes previous to 2.5.9 sends just an address
```
Comment (patriknw) [inline akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala]: Were it not added as optional field?

Comment (patriknw) [reply akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala]: Somewhere there is supposed to be a special case for 2.5.10 joining 2.5.9 that ignores the config check. I don’t know how that was implemented and if the range must be extended to 2.5.11 joining 2.5.9. I think it was that the config was empty (not included), but that wouldn’t have worked if exc was thrown. perhaps ask Renato. (Sorry, on phone).

Also what will happen now when joining 2.5.11 to 2.5.10 (in case someone started with 2.5.10)?

Comment (johanandren) [reply akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala]: The problem is that 2.5.9 sends just an `Address` protobuf message back with the class/string manifest saying `InitJoinAck`, the `InitJoinAck` protobuf message was added in the config check PR, the optional field does not help, I guess it could even be required.

With 2.5.10 joining 2.5.11 both will be sending the `InitJoinAck` protobuf message and all should be working just fine.

File: akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala (hunk 8 above)
Comment (johanandren) [reply akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala]: This is to make 2.5.10 interop still work, but as it is `InitJoin` I guess that would be an old node joining a 2.5.11+ cluster and that is not really supported anyways. I'll remove it.

File: akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala (hunk 9 above)
Comment (johanandren) [reply akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala]: Nope, `InitJoin` is the only one

File: akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala (hunk 10 above)
Comment (jrudolph) [reply akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala]: That might be a reminder to use protobuf wrappers in more cases so it will be easier to extend later on? On the other hand, I think I also argued the other way round not to wrap stuff if not needed to safe space and use manifests for evolving the protocol.

File: akka-cluster/src/main/mima-filters/2.5.10.backwards.excludes [hunk 11]
```diff
@@ -0,0 +1,5 @@
+# #24622 wire compat regression
+ProblemFilters.exclude[FinalClassProblem]("akka.cluster.protobuf.ClusterMessageSerializer")
+ProblemFilters.exclude[FinalMethodProblem]("akka.serialization.SerializerWithStringManifest.includeManifest")
```
Comment (jrudolph) [inline akka-cluster/src/main/mima-filters/2.5.10.backwards.excludes]: Are these needed? `SerializerWithStringManifest` doesn't seem to be changed and also seems like a real compatibility problem.

File: akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala (hunk 10 above)
Comment (johanandren) [reply akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala]: Yeap, not sure there was anything wrong with the send-only-address, the issue was more using the old class-based serializer IMO. 

I wish there was a better API for "is this bytes this kind of protobuf message?" than catching an exception though.

**Comment by jrudolph** [comment]
> @jrudolph there are quite comprehensive tests in ClusterMessageSerializerSpec doing serialization roundtrips for quite some variations of the messages etc. Would still not have caught the regression ofc but its not untested.

Hmm, roundtrips don't help, though, when it's about compatibility and you don't test against input or output from an older version. Maybe let's not delay the release because of this but keep it as a reminder that we should invest in testing infrastructure.

File: akka-cluster/src/main/mima-filters/2.5.10.backwards.excludes (hunk 11 above)
Comment (johanandren) [reply akka-cluster/src/main/mima-filters/2.5.10.backwards.excludes]: Oh, that is weird indeed, good catch I think I zombie-copy-pasted-those. That should not have changed!

File: akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala (hunk 10 above)
Comment (patriknw) [reply akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala]: I think the intention was that the address bytes would be possible to parse as a InitJoinAck proto since it also has an address field first.

But not that 2.5.10 may send another manifest string that is not understood in 2.5.11. That was maybe solved by the manifest2 that I said should be removed, and then it must be added back again with a valid comment.

File: akka-cluster/src/main/mima-filters/2.5.10.backwards.excludes (hunk 11 above)
Comment (johanandren) [reply akka-cluster/src/main/mima-filters/2.5.10.backwards.excludes]: But they do fail MiMa, those methods has been final since 2015, I have no idea what is going on here. 

Why is mima even checking `akka.serialization` types when i run `akka-cluster/mimaReportBinaryIssues`? Running mima against `akka-actor` does not report anything. O.o

Comment (johanandren) [reply akka-cluster/src/main/mima-filters/2.5.10.backwards.excludes]:
```
[info] akka-cluster: found 2 potential binary incompatibilities while checking against com.typesafe.akka:akka-cluster_2.11:2.5.0  (filtered 65)
[error]  * method includeManifest()Boolean in class akka.serialization.SerializerWithStringManifest is declared final in current version
[error]    filter with: ProblemFilters.exclude[FinalMethodProblem]("akka.serialization.SerializerWithStringManifest.includeManifest")
[error]  * method fromBinary(Array[Byte],scala.Option)java.lang.Object in class akka.serialization.SerializerWithStringManifest is declared final in current version
[error]    filter with: ProblemFilters.exclude[FinalMethodProblem]("akka.serialization.SerializerWithStringManifest.fromBinary")
```

I have no clue here, those types are not in that jar-file. What is MiMa smoking?

File: akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala (hunk 10 above)
Comment (johanandren) [reply akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala]: I think we are mixing up classes here. 

`InitJoin` was a singleton in 2.5.9 and became a class in 2.5.10 so for that the manifest changed. 

`InitJoinAck` was always a class so the manifest never changed, it was serialized as adress only in 2.5.9 though, which the cluster config check PR did not handle correctly - this was another part of the regression not reported in the issue but found when I was manually joining a 2.5.9 cluster from this PR.

Comment (patriknw) [reply akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala]: Ok, i might have commented on wrong lines but i’m pretty sure 2.5.10 will not be able to join 2.5.11 because it will send InitJoin manifest that is not understood. Perhaps not important to support that direction.

Comment (johanandren) [reply akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala]: Alright, now I got it, that is correct, rolling downgrade will not work.

File: project/MiMa.scala [hunk 12]
```diff
@@ -10,7 +10,7 @@ import com.typesafe.tools.mima.plugin.MimaPlugin.autoImport._
 
 object MiMa extends AutoPlugin {
 
-  private val latestMinorOf25 = 9
+  private val latestMinorOf25 = 10
```
Comment (ktoso) [inline project/MiMa.scala]: good catch; we keep forgetting that heh;

File: akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala (hunk 5 above)
Comment (dwijnand) [reply akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala]: The rest of us try to make good points, but Johannes makes God points.
