### PR TITLE
Version checking utility 

### LINKED ISSUE #24030: Provide a fail-fast on version number too low for libraries
Sprung out of akka/akka-http#1538 

It would be useful for libraries if there was a fail fast when the Akka version pulled into a project is too low for the library to work (rather than later getting missing method errors etc). Something like a `requireAtLeast(akkaVersion)` that the library can call which will throw an error with a good error message explaining that "the library xxx needs at least Akka of version x.y.z but the one on the class path is a.b.c".

Probably needs to allow saying the requirement for multiple major versions. (For example 2.4.11 if on 2.4 or 2.5.7 if on 2.5)

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #24030 

Could use a mention in the docs as well I guess. The idea is that for example Akka HTTP could explicitly say what version it requires in the extension to fail fast with a better error message than getting a linkage error later when some method is missing etc.

### CODE REVIEW

File: akka-actor-tests/src/test/scala/akka/AkkaVersionSpec.scala [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+        AkkaVersion.require("AkkaVersionSpec", Set("2.5.6"), "2.5-SNAPSHOT")
+      }
+    }
+
+    "fail if required versions are invalid" in {
+      intercept[UnsupportedAkkaVersion] {
+        AkkaVersion.require("AkkaVersionSpec", Set("2.5-SNAPSHOT"), "2.5-SNAPSHOT")
+      }
+    }
+
```
Comment (ktoso) [inline akka-actor-tests/src/test/scala/akka/AkkaVersionSpec.scala]: should likely understand RCs though

Comment (johanandren) [reply akka-actor-tests/src/test/scala/akka/AkkaVersionSpec.scala]: Indeed!

File: akka-actor-tests/src/test/scala/akka/AkkaVersionSpec.scala [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+    "fail if patch version is too low" in {
+      intercept[UnsupportedAkkaVersion] {
+        AkkaVersion.require("AkkaVersionSpec", Set("2.5.6"), "2.5.5")
+      }
+    }
+
+    "fail if Akka version is SNAPSHOT or timestamped snapshot" in {
+      intercept[UnsupportedAkkaVersion] {
+        AkkaVersion.require("AkkaVersionSpec", Set("2.5.6"), "2.5-SNAPSHOT")
```
Comment (patriknw) [inline akka-actor-tests/src/test/scala/akka/AkkaVersionSpec.scala]: timestamped not tested

File: akka-actor/src/main/scala/akka/AkkaVersion.scala [hunk 3]
```diff
@@ -0,0 +1,56 @@
...
+
+object AkkaVersion {
+  /**
+   * Check that the version of Akka is a specific patch version or higher, potentially for multiple
+   * minor version, for example require("2.4.19", "2.5.6"). If the version requirement is not fulfilled
+   * an exception is thrown.
+   *
+   * @param libraryName The name of the library or component requiring the Akka version, used in the error message.
+   */
+  def require(libraryName: String, requiredVersions: String*): Unit = {
```
Comment (patriknw) [inline akka-actor/src/main/scala/akka/AkkaVersion.scala]: varargs annotation, for Java API

File: akka-actor-tests/src/test/scala/akka/AkkaVersionSpec.scala [hunk 4]
```diff
@@ -0,0 +1,44 @@
...
+      }
+    }
+
+    "fail if required versions are invalid" in {
+      intercept[UnsupportedAkkaVersion] {
+        AkkaVersion.require("AkkaVersionSpec", Set("2.5-SNAPSHOT"), "2.5-SNAPSHOT")
```
Comment (patriknw) [inline akka-actor-tests/src/test/scala/akka/AkkaVersionSpec.scala]: let's see, what does this mean? isn't this the case we will have if akka-http is built with 2.5-SNAPSHOT?

File: akka-actor-tests/src/test/scala/akka/AkkaVersionSpec.scala [hunk 5]
```diff
@@ -0,0 +1,44 @@
...
+import org.scalatest.{Matchers, WordSpec}
+
+class AkkaVersionSpec extends WordSpec with Matchers {
+
+  "The Akka version check" must {
+
+    "succeed if version is ok" in {
+      AkkaVersion.require("AkkaVersionSpec", Set("2.5.6"), "2.5.6")
+      AkkaVersion.require("AkkaVersionSpec", Set("2.5.6"), "2.5.7")
+      AkkaVersion.require("AkkaVersionSpec", Set("2.5.6", "2.4.19"), "2.4.19")
```
Comment (patriknw) [inline akka-actor-tests/src/test/scala/akka/AkkaVersionSpec.scala]: when will we be able to use multiple versions like this? thinking about akka-http 10.0. how will we define/generate the required versions there? won't that come from the build dependency, and then we know nothing about 2.5.x?

Comment (johanandren) [reply akka-actor-tests/src/test/scala/akka/AkkaVersionSpec.scala]: We'd have to manually put it in there, the version we actually depend on in the build ("2.4.19") we could probably get in but the 2.5.x version we require is either 2.5.0+ or some form of implicit knowledge, so that we would have to specify explicitly.

File: akka-actor-tests/src/test/scala/akka/AkkaVersionSpec.scala (hunk 4 above)
Comment (johanandren) [reply akka-actor-tests/src/test/scala/akka/AkkaVersionSpec.scala]: Yeah, I'm not sure how to deal with the snapshots given that we do a sidestep from what I think is normal SNAPSHOT naming in maven land (that would be x.y.z-SNAPSHOT which is a snapshot of a upcoming x.y.z version)

**Comment by patriknw** [comment]
would be good to complete this before the release, because I think it's important for the Akka Http 10.1 release.

File: akka-actor-tests/src/test/scala/akka/AkkaVersionSpec.scala (hunk 4 above)
Comment (patriknw) [reply akka-actor-tests/src/test/scala/akka/AkkaVersionSpec.scala]: Shouldn't we just ignore everything that has to do with SNAPSHOT or timestamp snapshots? Then you are on your own.

**Comment by johanandren** [comment]
Ok, will give it prio!

File: akka-actor-tests/src/test/scala/akka/AkkaVersionSpec.scala (hunk 5 above)
Comment (johanandren) [reply akka-actor-tests/src/test/scala/akka/AkkaVersionSpec.scala]: Could be a synthetic use case though, maybe skip this and only support single-version to start with?

File: akka-actor-tests/src/test/scala/akka/AkkaVersionSpec.scala (hunk 4 above)
Comment (johanandren) [reply akka-actor-tests/src/test/scala/akka/AkkaVersionSpec.scala]: Sounds reasonable

File: akka-actor-tests/src/test/scala/akka/AkkaVersionSpec.scala (hunk 5 above)
Comment (patriknw) [reply akka-actor-tests/src/test/scala/akka/AkkaVersionSpec.scala]: I was thinking that if you really need it you could make two calls

Comment (johanandren) [reply akka-actor-tests/src/test/scala/akka/AkkaVersionSpec.scala]: I think that wouldn't work as it would fail for one of them:
```
require("2.5.6")
require("2.4.19") 
```
There is no scenario where both are successful

Comment (johanandren) [reply akka-actor-tests/src/test/scala/akka/AkkaVersionSpec.scala]: The reason I thought why we will need it is because I remembered when we added some classes/queryInterface2 types to persistence query, which would then be something like `Set("2.4.8", "2.5.0")`, but now that I think about it again, maybe that wasn't anyways possible because we didn't make those bincomp, and actually changed the type names.

**Review by 2m — APPROVED** [review]
LGTM

File: akka-actor-tests/src/test/scala/akka/AkkaVersionSpec.scala [hunk 6]
```diff
@@ -0,0 +1,73 @@
...
+    }
+
+    "succeed if version is RC and ok" in {
+      AkkaVersion.require("AkkaVersionSpec", "2.5.6", "2.5.6-RC1")
+      AkkaVersion.require("AkkaVersionSpec", "2.5.6", "2.5.7-RC10")
+      AkkaVersion.require("AkkaVersionSpec", "2.4.19", "2.4.19-RC6")
+    }
+
+    "succeed if version is milestone and ok" in {
+      AkkaVersion.require("AkkaVersionSpec", "2.5.6", "2.5.6-M1")
```
Comment (patriknw) [inline akka-actor-tests/src/test/scala/akka/AkkaVersionSpec.scala]: should this succeed? someone is running with an old `2.5.6-M1` as current version but we have compiled with later `2.5.6`?

we should probably not support the other way either, we have compiled with old 2.5.6-M1 but later decide to remove a feature before the final 2.5.6 release

same with RCs

Comment (johanandren) [reply akka-actor-tests/src/test/scala/akka/AkkaVersionSpec.scala]: Ah, true, I thought about it backwards.

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by ktoso** [comment]
Nice!
