### PR TITLE
Do not interpret DeferredBehaviors on termination

### LINKED ISSUE #22687: something wrong in TypedSpecSpec
After the Deferred refactoring TypedSpecSpec is unhappy (but doesn't fail).

```
[ERROR] [04/06/2017 08:23:47.528] [TypedSpecSpec_A_u0020TypedSpec_CommonTests__anonfun_must_u0020report_u0020failures_1-akka.actor.default-dispatcher-2] [typed://TypedSpecSpec_A_u0020TypedSpec_CommonTests__anonfun_must_u0020report_u0020failures_1/user/failure] expected
org.scalatest.exceptions.TestFailedException: expected
	at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:528)
	at org.scalatest.refspec.RefSpec.newAssertionFailedException(RefSpec.scala:1331)
	at org.scalatest.Assertions$class.fail(Assertions.scala:1089)
	at org.scalatest.refspec.RefSpec.fail(RefSpec.scala:1331)
	at akka.typed.TypedSpecSpec$A$u0020TypedSpec$CommonTests$$anonfun$must$u0020report$u0020failures$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$2.apply(TypedSpec.scala:199)
	at akka.typed.TypedSpecSpec$A$u0020TypedSpec$CommonTests$$anonfun$must$u0020report$u0020failures$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$2.apply(TypedSpec.scala:199)
	at akka.typed.StepWise$.akka$typed$StepWise$$run(StepWise.scala:134)
	at akka.typed.StepWise$$anonfun$apply$1.apply(StepWise.scala:113)
	at akka.typed.StepWise$$anonfun$apply$1.apply(StepWise.scala:112)
	at akka.typed.scaladsl.Actor$Deferred.apply(Actor.scala:212)
	at akka.typed.Behavior$.undefer(Behavior.scala:159)
	at akka.typed.Behavior$.preStart(Behavior.scala:184)
	at akka.typed.internal.SupervisionMechanics$class.create(SupervisionMechanics.scala:73)
	at akka.typed.internal.SupervisionMechanics$class.processSignal(SupervisionMechanics.scala:54)
	at akka.typed.internal.ActorCell.processSignal(ActorCell.scala:68)
	at akka.typed.internal.ActorCell.liftedTree1$1(ActorCell.scala:384)
	at akka.typed.internal.ActorCell.processAllSystemMessages(ActorCell.scala:384)
	at akka.typed.internal.ActorCell.run(ActorCell.scala:281)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[ERROR] [04/06/2017 08:23:47.530] [TypedSpecSpec_A_u0020TypedSpec_CommonTests__anonfun_must_u0020report_u0020failures_1-akka.actor.default-dispatcher-2] [typed://TypedSpecSpec_A_u0020TypedSpec_CommonTests__anonfun_must_u0020report_u0020failures_1/user/failure] failure during PostStop
java.lang.IllegalArgumentException: deferred should not be passed to interpreter
	at akka.typed.Behavior$.interpret(Behavior.scala:214)
	at akka.typed.Behavior$.interpretSignal(Behavior.scala:209)
	at akka.typed.internal.SupervisionMechanics$class.finishTerminate(SupervisionMechanics.scala:93)
	at akka.typed.internal.ActorCell.finishTerminate(ActorCell.scala:68)
	at akka.typed.internal.SupervisionMechanics$class.terminate(SupervisionMechanics.scala:83)
	at akka.typed.internal.SupervisionMechanics$class.processSignal(SupervisionMechanics.scala:55)
	at akka.typed.internal.ActorCell.processSignal(ActorCell.scala:68)
	at akka.typed.internal.ActorCell.liftedTree1$1(ActorCell.scala:384)
	at akka.typed.internal.ActorCell.processAllSystemMessages(ActorCell.scala:384)
	at akka.typed.internal.ActorCell.run(ActorCell.scala:281)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

-> system LocalActorRef class akka.typed.scaladsl.Actor$Stateless status=0 nextMsg=null
   ⌊-> 1-receptionist LocalActorRef class akka.typed.scaladsl.Actor$Stateful status=0 nextMsg=null
   ⌊-> 2-eventStreamUnsubscriber LocalActorRef class akka.typed.scaladsl.Actor$Stateful status=0 nextMsg=null
   ⌊-> 3-log1-DefaultLogger LocalActorRef class akka.typed.Behavior$EmptyBehavior$ status=0 nextMsg=null
       ⌊-> logger LocalActorRef class akka.typed.scaladsl.Actor$Stateless status=0 nextMsg=null
-> user LocalActorRef class akka.typed.scaladsl.Actor$Stateful status=0 nextMsg=null
-> system LocalActorRef class akka.typed.scaladsl.Actor$Stateless status=0 nextMsg=null
   ⌊-> 1-receptionist LocalActorRef class akka.typed.scaladsl.Actor$Stateful status=0 nextMsg=null
   ⌊-> 2-eventStreamUnsubscriber LocalActorRef class akka.typed.scaladsl.Actor$Stateful status=0 nextMsg=null
   ⌊-> 3-log1-DefaultLogger LocalActorRef class akka.typed.Behavior$EmptyBehavior$ status=0 nextMsg=null
       ⌊-> logger LocalActorRef class akka.typed.scaladsl.Actor$Stateless status=0 nextMsg=null
-> user LocalActorRef class akka.typed.scaladsl.Actor$Stateful status=0 nextMsg=null
```

### PR DESCRIPTION
**Pull request by 2m**
The actual fix is in `SupervisionMechanics.scala`. Other changes are to unify undefer usage across various code places.

Fixes #22687

### CODE REVIEW

File: akka-typed/src/main/scala/akka/typed/Behavior.scala [hunk 1]
```diff
@@ -179,12 +175,8 @@ object Behavior {
   /**
    * Validate the given behavior as initial, initialize it if it is deferred.
    */
-  def preStart[T](behavior: Behavior[T], ctx: ActorContext[T]): Behavior[T] = {
-    validateAsInitial(behavior) match {
-      case d: DeferredBehavior[T] @unchecked ⇒ validateAsInitial(undefer(d, ctx))
-      case x                                 ⇒ x
-    }
-  }
+  def preStart[T](behavior: Behavior[T], ctx: ActorContext[T]): Behavior[T] =
```
Comment (patriknw) [inline akka-typed/src/main/scala/akka/typed/Behavior.scala]: I find the name `preStart` a bit confusing nowadays. Could you try to remove it and directly call `validateAsInitial` instead, since that is the purpose. Then `validateAsInitial` should probably perform the `undefer` as the first thing.

**Comment by 2m** [comment]
Removed preStart. Instead of adding undefer to validateAsInitial, I have replaced preStart with the composition of validateAsInitial and undefer. The reason was that validateAsInitial is used in some places where context is not accessible, and therefore it is not possible to call undefer from there.
