### PR TITLE
#20224: Fix onSubscribe-request-onNext reentrancy in VirtualProcessor

### LINKED ISSUE #20224: FAILED VirtualProcessorSingleTest
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3685/consoleFull

```
[info] - stochastic_spec103_mustSignalOnMethodsSequentially *** FAILED ***
[info]   java.lang.AssertionError: Illegal concurrent access detected (entering critical section)! Thread[pool-184-thread-1,5,main] emited onNext(0) signal, before null finished its onSubscribe() signal.
[info]   at org.testng.Assert.fail(Assert.java:89)
[info]   at org.reactivestreams.tck.TestEnvironment.flop(TestEnvironment.java:117)
[info]   at org.reactivestreams.tck.PublisherVerification$5$1$1$ConcurrentAccessBarrier.enterSignal(PublisherVerification.java:270)
[info]   at org.reactivestreams.tck.PublisherVerification$5$1$1.onNext(PublisherVerification.java:303)
[info]   at akka.stream.impl.VirtualProcessor.rec$5(StreamLayout.scala:647)
[info]   at akka.stream.impl.VirtualProcessor.onNext(StreamLayout.scala:666)
[info]   at org.reactivestreams.example.unicast.AsyncIterablePublisher$SubscriptionImpl.doSend(AsyncIterablePublisher.java:161)
[info]   at org.reactivestreams.example.unicast.AsyncIterablePublisher$SubscriptionImpl.doRequest(AsyncIterablePublisher.java:91)
[info]   at org.reactivestreams.example.unicast.AsyncIterablePublisher$SubscriptionImpl.run(AsyncIterablePublisher.java:204)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
```

### PR DESCRIPTION
**Pull request by drewhk**
As far as I see other code-paths are not problematic as they do not directly ferry signals between the upstream and downstream (except cancel/onComplete/onError, but they do not reenter as they have no response path).

Fixes #20224

### CODE REVIEW

File: akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala [hunk 1]
```diff
@@ -669,19 +677,52 @@ private[stream] final class VirtualProcessor[T] extends AtomicReference[AnyRef]
...
+    case object PassThrough extends SubscriptionState { override def demand: Long = 0 }
+    case class Buffering(demand: Long) extends SubscriptionState
+  }
+
+  // Extdending AtomicReference to make the hot memory location share the same cache line with the Subscription
+  private class WrappedSubscription(real: Subscription)
+    extends AtomicReference[WrappedSubscription.SubscriptionState] with Subscription {
+    import WrappedSubscription._
+
+    set(Buffering(0))
```
Comment (ktoso) [inline akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: would it be better to `extends AtomicReference[WrappedSubscription.SubscriptionState](Buffering(0))`?

**Comment by ktoso** [comment]
LGTM, thought through the edge case described in the ticket and code here – I think it looks good. 
The `bufferDemand`-ing shouldn't ever get pathological as well so we're good I believe.
Awesome work, thanks Endre.

File: akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala (hunk 1 above)
Comment (drewhk) [inline akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: Yep, I forgot that I can pass the constructor parameter directly :D

**Comment by drewhk** [comment]
It is mostly thanks to @rkuhn and @viktorklang though.

File: akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala [hunk 2]
```diff
@@ -669,19 +677,52 @@ private[stream] final class VirtualProcessor[T] extends AtomicReference[AnyRef]
...
+        // This does not violate the Spec though, since we are a "Processor" here and although we, in reality,
+        // proxy downstream requests, it is virtually *us* that emit the requests here and we are free to follow
+        // any pattern of emitting them.
+        // The only invariant we need to keep is to never emit more requests than the downstream emitted so far.
+        val current = get()
+        if (current eq PassThrough) real.request(n)
+        else {
+          @tailrec def bufferDemand(n: Long): Unit = {
+            if (get() eq PassThrough) real.request(n)
+            else if (!compareAndSet(current, Buffering(current.demand + n))) bufferDemand(n)
```
Comment (patriknw) [inline akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: This is not re-reading `current` in the CAS loop. Is that correct?

Comment (drewhk) [inline akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: No, that is not correct. I moved the `val` out for some strange reason.

File: akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala [hunk 3]
```diff
@@ -669,19 +677,52 @@ private[stream] final class VirtualProcessor[T] extends AtomicReference[AnyRef]
 
   private def noDemand = "spec violation: onNext was signaled from upstream without demand"
 
-  private class WrappedSubscription(real: Subscription) extends Subscription {
+  object WrappedSubscription {
+    sealed trait SubscriptionState { def demand: Long }
+    case object PassThrough extends SubscriptionState { override def demand: Long = 0 }
+    case class Buffering(demand: Long) extends SubscriptionState
```
Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: final

File: akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala (hunk 1 above)
Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: Have a cached Buffering.zero, no need to allocate new instances since they are immutable.

File: akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala [hunk 4]
```diff
@@ -669,19 +677,52 @@ private[stream] final class VirtualProcessor[T] extends AtomicReference[AnyRef]
...
+
+  // Extdending AtomicReference to make the hot memory location share the same cache line with the Subscription
+  private class WrappedSubscription(real: Subscription)
+    extends AtomicReference[WrappedSubscription.SubscriptionState] with Subscription {
+    import WrappedSubscription._
+
+    set(Buffering(0))
+
+    // Release
+    def ungateRequests(): Unit = {
```
Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: Isn't it more like `requestBufferedDemand`?

File: akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala (hunk 1 above)
Comment (drewhk) [inline akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: Good idea! In most cases it will be zero so this gains a lot.

File: akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala (hunk 4 above)
Comment (drewhk) [inline akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala]: actually, both. Ungates and requests the buffered ones :) `ungateDemandAndRequestBuffered`?

**Comment by patriknw** [comment]
LGTM

**Comment by drewhk** [comment]
Rebased
