### PR TITLE
Stabilize BalancingSpec

### LINKED ISSUE #30359: Failed: BalancingSpec
https://travis-ci.com/github/akka/akka/jobs/521145928

```
[info] - must deliver messages in a balancing fashion when overridden in config *** FAILED *** (359 milliseconds)
1151[info]   java.lang.AssertionError: assertion failed: received unexpected message RealMessage(1,Actor[akka://BalancingSpec/user/balancingPool-3/$a#1476506991]) after 0 millis
1152[info]   at akka.testkit.TestKitBase.expectNoMsg_internal(TestKit.scala:769)
1153[info]   at akka.testkit.TestKitBase.expectNoMessage(TestKit.scala:733)
1154[info]   at akka.testkit.TestKitBase.expectNoMessage$(TestKit.scala:159)
1155[info]   at akka.testkit.TestKit.expectNoMessage(TestKit.scala:973)
1156[info]   at akka.routing.BalancingSpec.test(BalancingSpec.scala:86)
1157[info]   at akka.routing.BalancingSpec.f$proxy3$1(BalancingSpec.scala:119)
1158[info]   at akka.routing.BalancingSpec.$init$$$anonfun$4$$anonfun$3(BalancingSpec.scala:115)
1159[info]   at org.scalatest.Transformer.apply$$anonfun$1(Transformer.scala:22)
1160
```

### PR DESCRIPTION
**Pull request by raboof**
It seems previously in some cases (despite the 'sleep'
in the first worker) it could happen that one worker
would never get a message. This more explicitly avoids
that scenario.

Hopefully fixes #30359

### CODE REVIEW

File: akka-actor/src/main/scala/akka/routing/Balancing.scala [hunk 1]
```diff
@@ -75,6 +75,7 @@ final case class BalancingPool(
     override val supervisorStrategy: SupervisorStrategy = Pool.defaultSupervisorStrategy,
     override val routerDispatcher: String = Dispatchers.DefaultDispatcherId)
     extends Pool {
+  println(s"XXX pool $this with $nrOfInstances")
```
Comment (johanandren) [inline akka-actor/src/main/scala/akka/routing/Balancing.scala:78]: Runaway println?

**Review by johanandren — APPROVED** [review]

File: akka-actor/src/main/scala/akka/routing/Balancing.scala (hunk 1 above)
Comment (raboof) [reply akka-actor/src/main/scala/akka/routing/Balancing.scala:78]: Oops, didn't intend to check those in indeed
