### PR TITLE
Fail FileSubscriber's Promise if it can't open the file

### LINKED ISSUE #24889: FileSubscriber completes with succesful Promise if it can't open the file
If you create a sink with ```FileIO.toPath("file.txt")``` and the file can't be opened the stream will complete, and a the Future[IOResult] will be successful with zero bytes written. This behavior can hide errors, in our broadcast flow everything seems normal if no bytes were written to the file and the other branches completed successfully.

### PR DESCRIPTION
**Pull request by filipmatusak**
resolves #24889

### CODE REVIEW

**Comment by raboof** [comment]
OK TO TEST

**Review by ktoso — APPROVED** [review]
LGTM

Resolves note put everywhere except the place where it works... :-)
Has to be in PR comment as we request in CONTRIBUTING.md: 

resolves #24889

File: akka-stream-tests/src/test/scala/akka/stream/io/FileSinkSpec.scala [hunk 1]
```diff
@@ -222,6 +223,13 @@ class FileSinkSpec extends StreamSpec(UnboundedMailboxConfig) {
         checkFileContents(f, TestLines.takeWhile(!_.contains('b')).mkString(""))
       }
     }
+
+    "complete with failure when file cannot be open" in {
+      val completion = Source.single(ByteString("42"))
+        .runWith(FileIO.toPath(Paths.get("/I/hope/this/file/doesnt/exist.txt")))
```
Comment (johanandren) [inline akka-stream-tests/src/test/scala/akka/stream/io/FileSinkSpec.scala]: Likely fast, but just for good measure, can we get the path from the in-memory fs that the other tests use instead of touching actually touching disk?

**Review by johanandren — CHANGES_REQUESTED** [review]
Looks mostly good, just one small thing with the test case.

**Review by johanandren — APPROVED** [review]
Great, thanks. LGTM!
