### PR TITLE
Normalize whitespace for resource paths

### LINKED ISSUE #17873: http: getFromResourceDirectory fails if the absolute path to the server contains a space
Example:
```scala
pathPrefix("assets") {
  getFromResourceDirectory("public")
}
```
Note the space in `/path/player 2/lib/...`:
```
[ERROR] [06/30/2015 23:28:01.375] [player-akka.actor.default-dispatcher-13] [ActorSystem(player)] Error during processing of request HttpRequest(HttpMethod(GET),http://localhost:8080/assets/stylesheets/common.css,...)
java.io.FileNotFoundException: /path/player%202/lib/player_2.11-0.1-SNAPSHOT-web-assets.jar (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:220)
	at java.util.zip.ZipFile.<init>(ZipFile.java:150)
	at java.util.zip.ZipFile.<init>(ZipFile.java:121)
	at akka.http.scaladsl.server.directives.FileAndResourceDirectives$ResourceFile$.apply(FileAndResourceDirectives.scala:210)
```

This is happening in this method: https://github.com/akka/akka/blob/releasing-akka-stream-and-http-experimental-1.0-RC4/akka-http/src/main/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectives.scala#L199.

Looks like it’s a [known problem with `j.u.z.ZipFile`](https://code.google.com/p/reflections/issues/detail?id=99). I was able to reproduce it on Windows 7 and on Ubuntu. *akka-http* version `RC4`.

### PR DESCRIPTION
**Pull request by aruediger**
Hard to unit test since I had to temporarily add a jar file with spaces to my path.

fixes #17873

### CODE REVIEW

**Comment by stanch** [comment]
Have you tried with other escaped characters?

**Comment by 2beaucoup** [comment]
No. If you have a test case I can check locally.

**Comment by stanch** [comment]
I don’t have anything distilled at the moment, but I can craft it in the evening (GMT). Anyway, it’s not necessary to modify the jar filenames, because the path is absolute. It’s enough to put the app itself into a directory with spaces or non-latin characters. Some Cyrillic stuff should expose the original issue: `/path/to/тест/app/...`.

**Comment by 2beaucoup** [comment]
Cyrillic doesn't work on my machine but umlauts do. I can only test on Win7 with German locale ATM.

I'm working via unit tests so there is no real "app" here. I can simulate the behaviour with the test classpath though.

**Comment by stanch** [comment]
> Cyrillic doesn't work on my machine but umlauts do.

Do you mean that the original issue manifests itself with Cyrillic? Or some other issue?

> I'm working via unit tests so there is no real "app" here. I can simulate the behaviour with the test classpath though.

In that case the app will be the test runner :) You can change the name of the directory where your akka code is contained. But I do understand that it’s not something you can control from within the tests to make them reproducible. I wonder if it’s possible to insert some wacky characters into the package names to the same effect (not sure if that’s permitted by Java/Scala).

**Comment by 2beaucoup** [comment]
You just have to create a jar with a funky name, put it in an even funkier directory, add it to the classpath and load things from it. ;)

The issue with Cyrillic is, that the class loader doesn't even recognise classes and resources contained in such a jar/folder and the ClassLoader.getResource always returns null in that case.

**Comment by stanch** [comment]
> The issue with Cyrillic is, that the class loader doesn't even recognise classes and resources contained in such a jar/folder and the ClassLoader.getResource always returns null in that case.

What if the folders inside the jar have latin names, but the outside folder has a Cyrillic name, like in my example? I know it will probably not help establishing a test case for this, but bear with me for a moment :)

**Comment by stanch** [comment]
@2beaucoup Could you try running this sample with your version of `akka-http-experimental`? https://github.com/stanch/akka-http-spaces

**Comment by 2beaucoup** [comment]
@stanch let's try the other way around: why don't you just clone https://github.com/2beaucoup/akka and `publishLocal` the `space-in-path` branch?

**Comment by stanch** [comment]
That was the first thing I tried, but I had problems building akka. I will try again tonight, I just thought that running my sample would take much less time :)

**Comment by 2beaucoup** [comment]
```
> Some(ResourceFile(jar:file:/[...]/akka-http-spaces/?????????%20?????/lib/test.jar!/test.txt,0,1435790924000))
```

**Comment by stanch** [comment]
That’s great! Thanks for running it :)

**Comment by 2beaucoup** [comment]
added a test for this

**Comment by 2beaucoup** [comment]
rebased. could someone plz trigger the tests?

**Comment by ktoso** [comment]
OK TO TEST

**Comment by stanch** [comment]
> I had problems building akka

For the record, I was just missing `graphviz`, but it was too late in the night for me to realize it. Other than that, I have to say that for such a big project akka is surprisingly easy to build!

**Comment by 2beaucoup** [comment]
> For the record, I was just missing graphviz, but it was too late in the night for me to realize it.

https://github.com/akka/akka/blob/master/akka-docs/rst/dev/building-akka.rst#scaladoc-dependencies ;)

**Comment by stanch** [comment]
@2beaucoup Thanks! I think this should be at the root of the repo ;)

**Comment by stanch** [comment]
@2beaucoup I tried to do `sbt +publishLocal` as well and got this error. Any ideas?

```
[error] /home/stanch/projects/akka/akka-http-core/src/main/scala/akka/http/impl/util/JavaMapping.scala:100: method with dependent type (scalaObject: SIn)inMapping.J cannot be converted to function value
[error]         scaladsl.Flow[SIn].map(inMapping.toJava).viaMat(javaObject)(scaladsl.Keep.right).map(outMapping.toScala)
[error]                                          ^
[error] /home/stanch/projects/akka/akka-http-core/src/main/scala/akka/http/impl/util/JavaMapping.scala:103: method with dependent type (javaObject: JIn)inMapping.S cannot be converted to function value
[error]           scaladsl.Flow[JIn].map(inMapping.toScala).viaMat(scalaObject)(scaladsl.Keep.right).map(outMapping.toJava)
[error]                                            ^
[info] No documentation generated with unsucessful compiler run
[error] two errors found
[info] Compiling 123 Scala sources and 114 Java sources to /home/stanch/projects/akka/akka-http-core/target/classes...
[error] /home/stanch/projects/akka/akka-http-core/src/main/scala/akka/http/impl/util/JavaMapping.scala:100: method with dependent type (scalaObject: SIn)inMapping.J cannot be converted to function value
[error]         scaladsl.Flow[SIn].map(inMapping.toJava).viaMat(javaObject)(scaladsl.Keep.right).map(outMapping.toScala)
[error]                                          ^
[error] /home/stanch/projects/akka/akka-http-core/src/main/scala/akka/http/impl/util/JavaMapping.scala:103: method with dependent type (javaObject: JIn)inMapping.S cannot be converted to function value
[error]           scaladsl.Flow[JIn].map(inMapping.toScala).viaMat(scalaObject)(scaladsl.Keep.right).map(outMapping.toJava)
[error]                                            ^
[error] two errors found
```

Sorry if I’m derailing this discussion :)

**Comment by 2beaucoup** [comment]
@jrudolph any objections from your side?

**Comment by 2beaucoup** [comment]
@stanch what exactly are you trying to publish?

File: akka-http/src/main/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectives.scala [hunk 1]
```diff
@@ -207,12 +207,11 @@ object FileAndResourceDirectives extends FileAndResourceDirectives {
         if (file.isDirectory) None
         else Some(ResourceFile(url, file.length(), file.lastModified()))
       case "jar" ⇒
-        val jarFile = url.getFile
-        val startIndex = if (jarFile.startsWith("file:")) 5 else 0
-        val bangIndex = jarFile.indexOf("!")
-        val jarFilePath = jarFile.substring(startIndex, bangIndex)
-        val resourcePath = jarFile.substring(bangIndex + 2)
-        val jar = new java.util.zip.ZipFile(jarFilePath)
+        val path = new URI(url.getPath).getPath // remove "file:" prefix and normailze whitespace
```
Comment (jrudolph) [inline akka-http/src/main/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectives.scala]: s/normailze/normalize/

File: akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectivesSpec.scala [hunk 2]
```diff
@@ -104,12 +104,18 @@ class FileAndResourceDirectivesSpec extends RoutingSpec with Inspectors with Ins
...
-    "reject requests to directory resources from an Archive " in {
+    "reject requests to directory resources from an archive " in {
       Get() ~> getFromResource("com/typesafe/config") ~> check { handled shouldEqual (false) }
     }
-    "reject requests to directory resources from an Archive with trailing slash" in {
+    "reject requests to directory resources from an archive with trailing slash" in {
       Get() ~> getFromResource("com/typesafe/config/") ~> check { handled shouldEqual (false) }
     }
+    "return the resource from an archive with spaces and umlauts" in {
+      Get() ~> getFromResource("test-resource.txt") ~> check {
```
Comment (jrudolph) [inline akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectivesSpec.scala]: Maybe add a comment that it will load this file from the jar file above. Easy enough to spot in the diff but not so easy if you just look at the test.

**Comment by jrudolph** [comment]
LGTM aside from the small things.

**Comment by stanch** [comment]
> @stanch what exactly are you trying to publish?

This:

> @stanch let's try the other way around: why don't you just clone https://github.com/2beaucoup/akka and publishLocal the space-in-path branch?

```
git clone git@github.com:2beaucoup/akka.git && \
  cd akka && \
  git checkout space-in-path && \
  sbt +publish-local
```

**Comment by 2beaucoup** [comment]
typo fixed, comment added and updated. thx @jrudolph!

**Comment by 2beaucoup** [comment]
@stanch cross-publishing fails for me with the same error. 2.10-only works though.

**Comment by jrudolph** [comment]
Maybe it really is broken, the failing lines are still somewhat new.

**Comment by jrudolph** [comment]
I created a ticket to fix that: https://github.com/akka/akka/issues/17943

**Comment by stanch** [comment]
@jrudolph Thanks! Shouldn’t Jenkins report that? Or it’s only testing with `2.10`?

**Comment by jrudolph** [comment]
Can you try the simple fix here: https://github.com/akka/akka/pull/17944? I couldn't reproduce the problem, how did you cross-build to get the error?

**Comment by 2beaucoup** [comment]
@jrudolph just add the `+` prefix like @stanch did [here](https://github.com/akka/akka/pull/17880#issuecomment-119575037).

**Comment by stanch** [comment]
Actually I think `crossScalaVersions` are not defined, so `+publich-local` is compiling with a default (old) version of `2.10`, hence the errors.

**Comment by jrudolph** [comment]
@stanch Yep, that's what I just figured as well. So, I just wrongly inferred that you must mean it fails under 2.11 when it was failing under 2.10.3.

**Comment by stanch** [comment]
What do you think about adding a cross-build config to avoid these surprises?

**Comment by 2beaucoup** [comment]
Confirmed. (Just build successfully against 2.11.7)

**Comment by drewhk** [comment]
LGTM. Is this mergeable? @jrudolph ?

**Comment by jrudolph** [comment]
Yep, LGTM.

**Comment by jrudolph** [comment]
Yay! Thanks once again @2beaucoup.

**Comment by 2beaucoup** [comment]
always a pleasure @jrudolph
