### PR TITLE
#20487: Fix race in FlowForeachParallelSpec

### LINKED ISSUE #20487: FAILED: SinkForeachParallelSpec
This looks like a genuine failure:

```
[info] - must finish after function thrown exception *** FAILED *** (29 milliseconds)
[info]   java.lang.AssertionError: assertion failed: not found [2] found unexpected [4]
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.checkMissingAndUnexpected(TestKit.scala:503)
[info]   at akka.testkit.TestKitBase$class.expectMsgAllOf_internal(TestKit.scala:512)
[info]   at akka.testkit.TestKitBase$class.expectMsgAllOf(TestKit.scala:484)
[info]   at akka.testkit.TestKit.expectMsgAllOf(TestKit.scala:734)
[info]   at akka.stream.scaladsl.SinkForeachParallelSpec$$anonfun$1$$anonfun$apply$mcV$sp$6$$anonfun$apply$mcV$sp$7.apply$mcV$sp(SinkForeachParallelSpec.scala:108)
[info]   at akka.stream.scaladsl.SinkForeachParallelSpec$$anonfun$1$$anonfun$apply$mcV$sp$6$$anonfun$apply$mcV$sp$7.apply(SinkForeachParallelSpec.scala:92)
[info]   at 
```

https://jenkins.akka.io:8498/job/akka-nightly/3306/consoleFull

### PR DESCRIPTION
**Pull request by drewhk**
Fixes #20487 

Was tricky to reproduce the issue even though the scenario was rather straightforward (had to find the right place to put a sleep). The modifications to the test enforce stricter ordering between events so the test has no chance to go wrong. Other tests seem to be correct though.

### CODE REVIEW

File: akka-stream-tests/src/test/scala/akka/stream/scaladsl/SinkForeachParallelSpec.scala [hunk 1]
```diff
@@ -90,30 +92,34 @@ class SinkForeachParallelSpec extends AkkaSpec {
...
-      latch.countDown()
+      // Only the first two messages are guaranteed to arrive due to their enforced ordering related to the time
+      // of failure.
       probe.expectMsgAllOf(1, 2)
+      element4Latch.countDown() // Release elements 4, 5, 6, ...
 
-      Await.ready(p, 1.seconds)
-
-      assert(p.isCompleted)
+      a[RuntimeException] must be thrownBy Await.result(p, 1.seconds)
```
Comment (patriknw) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/SinkForeachParallelSpec.scala]: too short timeout

**Comment by patriknw** [comment]
LGTM
