### PR TITLE
Fix #21760 - Close Tls connection if Inbound closed before receiving peer's close_notify (v.2)

### LINKED ISSUE #380: HttpEntity.CloseDelimited toStrict times out (on the client-side) when using SSL
HTTP Client fails to get all data in a CloseDelimited entity when requests are done over https.

The .toStrict method times out even though the remote end has closed the connection and all data has been sent.
This is only a problem with SSL connections, plaintext-connections work as expected.

I have confirmed this behaviour against akka http servers and other http servers.

The attachked file contains a scalatest test class to reproduce this problem using akka as client and server and also a keystore required for ssl to work.

[tostrict.zip](https://github.com/akka/akka-http/files/521655/tostrict.zip)

### LINKED ISSUE #21760: Close Tls connection if Inbound closed before receiving peer's close_notify
if Inbound closed before receiving peer's close_notify TlsActor is not terminating correctly and streams hung. This possible causes several known issues inside the akka-http: 

- https://github.com/akka/akka-http/issues/380 
- https://github.com/akka/akka-http/issues/87

### PR DESCRIPTION
**Pull request by sashagavrilov**
Fixes #21760
Also fixes akka/akka-http#380 and probably akka/akka-http#87

This is a second variant of testing the fix (an alternative is #21785)
Initial discussion is in #21761

When application closes inboud using engine.closeInbound the engine can generate an alert message and put it into writer.outboundList. As a result the engine can have a new data packet in outbound and its isOutboundDone will be false. We have to ensure that it will be flushed to the network, that's why we have to update lastHandshakeStatus via the actual status of the engine. Otherwise the actor will transition to the flushingOutbound state but will never flush outbound, since engineNeedsWrap precondition will be false.

Generally speaking whenever we signal something to the SSLEngine, weshould also read getHandshakeStatus afterwards to understand what we need to do next. This was done everywhere but for this engine.closeInbound.

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Thanks for the excellent research + writeup and fix.
Seems to make sense to me. I somehow prefer this alternative to the other one.
I know @jrudolph wanted to get deeper into this PR. I think your explanations seem good so if jenkins is happy I'd say it's LGTM

**Comment by ilucker** [comment]
Does not look like the failed test is related to this commit.

**Comment by ilucker** [comment]
retest this please

**Comment by ktoso** [comment]
PLS BUILD

**Review by johanandren — APPROVED** [review]
LGTM, I vote for this one.

File: akka-stream-tests/src/test/scala/akka/stream/io/TlsSpec.scala [hunk 1]
```diff
@@ -436,6 +436,36 @@ class TlsSpec extends StreamSpec("akka.loglevel=INFO\nakka.actor.debug.receive=o
...
+      val f =
+        Source(scenario.inputs)
+          .via(outFlow)
+          .via(inFlow)
+          .map(result ⇒ {
+            ks.shutdown(); result
+          })
+          .runWith(Sink.last)
+
+      Await.result(f, 8.second).utf8String should be(scenario.output.utf8String)
```
Comment (drewhk) [inline akka-stream-tests/src/test/scala/akka/stream/io/TlsSpec.scala]: Nice test!

File: akka-stream/src/main/scala/akka/stream/impl/io/TLSActor.scala [hunk 2]
```diff
@@ -292,6 +292,7 @@ class TLSActor(
       if (tracing) log.debug("closing inbound")
       try engine.closeInbound()
       catch { case ex: SSLException ⇒ outputBunch.enqueue(UserOut, SessionTruncated) }
+      lastHandshakeStatus = engine.getHandshakeStatus
```
Comment (drewhk) [inline akka-stream/src/main/scala/akka/stream/impl/io/TLSActor.scala]: ah, so this needs to be updated here. Thanks!

**Review by drewhk — APPROVED** [review]
LGTM

**Comment by ktoso** [comment]
Enough LGTMs I believe :)
Thanks again for digging into this!
