### PR TITLE
+str 18735: Added keepalive inject and initial delay ops

### LINKED ISSUE #18735: FAILED: RecipeKeepAlive
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/3923/consoleFull

```
info] Recipe for injecting keepalive messages
[info] - must work *** FAILED *** (43 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected OnNext(ByteString(11)), found OnNext(ByteString(3))
[info]   at scala.Predef$.assert(Predef.scala:179)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:339)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:315)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:718)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:252)
[info]   at docs.stream.cookbook.RecipeKeepAlive$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(RecipeKeepAlive.scala:55)
[info]   at docs.stream.cookbook.RecipeKeepAlive$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(RecipeKeepAlive.scala:11)
[info]   at docs.stream.cookbook.RecipeKeepAlive$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(RecipeKeepAlive.scala:11)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[info]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]   at akka.stream.testkit.AkkaSpec.withFixture(AkkaSpec.scala:55)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)
[info]   at akka.stream.testkit.AkkaSpec.runTest(AkkaSpec.scala:55)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:318)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:318)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
```

### PR DESCRIPTION
**Pull request by drewhk**
Also, improved documentation of timeout operations
Added missing Java DSL smoke tests

Fixes #18735

### CODE REVIEW

File: akka-docs-dev/rst/scala/code/docs/stream/cookbook/RecipeKeepAlive.scala [hunk 1]
```diff
@@ -10,68 +10,16 @@ class RecipeKeepAlive extends RecipeSpec {
...
-        val unfairMerge = builder.add(MergePreferred[ByteString](1))
-
-        // If data is available then no keepalive is injected
-        dataStream ~> unfairMerge.preferred
-        ticks ~> tickToKeepAlivePacket ~> unfairMerge ~> sink
-        ClosedShape
-      })
+      import scala.concurrent.duration._
+      val injectKeepAlive: Flow[ByteString, ByteString, Unit] =
+        Flow[ByteString].injectIfIdle(1.second, () => keepaliveMessage)
```
Comment (viktorklang) [inline akka-docs-dev/rst/scala/code/docs/stream/cookbook/RecipeKeepAlive.scala]: In order to keep permutations low, how about we repurpose `idleTimeout` to take a function () => B and then someone can have it be () => throw TimeoutException if they want?

File: akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala [hunk 2]
```diff
@@ -1013,10 +1030,52 @@ final class Flow[-In, +Out, +Mat](delegate: scaladsl.Flow[In, Out, Mat]) extends
...
+   *
+   * '''Emits when''' upstream emits an element if the initial delay already elapsed
+   *
+   * '''Backpressures when''' downstream backpressures or initial delay not yet elapsed
+   *
+   * '''Completes when''' upstream completes
+   *
+   * '''Cancels when''' downstream cancels
+   */
+  def delayInitial(delay: FiniteDuration): javadsl.Flow[In, Out, Mat] =
```
Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala]: Do we have a use-case for this? (I'm thinking it would be of more utility to have a `throttle` combinator rather than just the first element)

File: akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala [hunk 3]
```diff
@@ -1021,20 +1022,77 @@ trait FlowOps[+Out, +Mat] {
...
+   * '''Emits when''' upstream emits an element if the initial delay already elapsed
+   *
+   * '''Backpressures when''' downstream backpressures or initial delay not yet elapsed
+   *
+   * '''Completes when''' upstream completes
+   *
+   * '''Cancels when''' downstream cancels
    */
-  def idleTimeout(timeout: FiniteDuration): Repr[Out, Mat] = via(new Timeouts.Idle[Out](timeout))
+  def delayInitial(delay: FiniteDuration): Repr[Out, Mat] = via(new DelayInitial[Out](delay))
```
Comment (ktoso) [inline akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala]: temped to leave this one out until actually used/requested somewhere?

Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala]: +1

File: akka-docs-dev/rst/scala/code/docs/stream/cookbook/RecipeKeepAlive.scala (hunk 1 above)
Comment (drewhk) [inline akka-docs-dev/rst/scala/code/docs/stream/cookbook/RecipeKeepAlive.scala]: you mean implementing idleTimeout in terms of injectKeepAlive? It is not the same because this respects backpressure, i.e. this will not invoke the function at the timeout if there is backpressure from downstream. That is not something you want with the idleTimeout.

File: akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala (hunk 2 above)
Comment (drewhk) [inline akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala]: I use it in the test, and I will have uses of this for many tests. This is more useful than it seems if you combine it with contact if you want to test timing related things.

File: akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala (hunk 3 above)
Comment (drewhk) [inline akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala]: I disagree, this is quite useful actually.

File: akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala (hunk 2 above)
Comment (drewhk) [inline akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala]: Also, `throttle` has nothing to do with this one.

File: akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala (hunk 3 above)
Comment (ktoso) [inline akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala]: I'm OK with keeping it

File: akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala [hunk 4]
```diff
@@ -1021,20 +1022,77 @@ trait FlowOps[+Out, +Mat] {
...
+   *
+   * '''Emits when''' upstream emits an element or if the upstream was idle for the configured period
+   *
+   * '''Backpressures when''' downstream backpressures
+   *
+   * '''Completes when''' upstream completes
+   *
+   * '''Cancels when''' downstream cancels
+   */
+  def injectIfIdle[U >: Out](maxIdle: FiniteDuration, injectedElem: () ⇒ U): Repr[U, Mat] =
```
Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala]: Hmmm, I'm not 100% onboard with the name. Any other suggestions?

File: akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala (hunk 2 above)
Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala]: At the very least, can we have it consistent with `initialTimeout` and call it `initialDelay`?

Comment (drewhk) [inline akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala]: yes, sure!

File: akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala (hunk 4 above)
Comment (drewhk) [inline akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala]: I don't have any. I used `idleInject` before, but that was not descriptive enough.

File: akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala (hunk 2 above)
Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala]: deal :)

File: akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala (hunk 4 above)
Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala]: Perhaps: `def maxLatency(duration: FiniteDuration, whenExceeded: () => U): Repr[U, Mat]`

Comment (ktoso) [inline akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala]: -1 to `maxLatency` sounds weird since we don't emit when back-pressured so it doesn't guarantee anything about latencies

Comment (ktoso) [inline akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala]: My preference would be `injectWhenIdle`... can be one of the others proposed by @drewhk tho

Comment (drewhk) [inline akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala]: I like `injectWhenIdle`. We can call it `keepAlive` as well, since that would be the 90% of the use cases.

Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala]: I'd much more prefer `keepAlive`

Comment (ktoso) [inline akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala]: `keepAlive` :+1:

Comment (drewhk) [inline akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala]: Ok
