### PR TITLE
Slf4jLogger expects also null as a marker to support Warning4 events

### LINKED ISSUE #26042: NullPointerException in Slf4jLogger
I use Akka `2.5.18` with `akka-slf4j` and `logback`.

This logging statement results in `NullPointerException`:

```scala
  log.warning(new IllegalArgumentException(), "Some message")
```

error stack:

```
java.lang.NullPointerException: null
	at akka.event.slf4j.Slf4jLogger.akka$event$slf4j$Slf4jLogger$$markerIfPresent(Slf4jLogger.scala:117)
	at akka.event.slf4j.Slf4jLogger$$anonfun$receive$1.$anonfun$applyOrElse$2(Slf4jLogger.scala:76)
	at akka.event.slf4j.Slf4jLogger.withMdc(Slf4jLogger.scala:103)
	at akka.event.slf4j.Slf4jLogger$$anonfun$receive$1.applyOrElse(Slf4jLogger.scala:75)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.event.slf4j.Slf4jLogger.aroundReceive(Slf4jLogger.scala:54)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

I traced the issue into [Slf4jLogger:117](https://github.com/akka/akka/blob/fafc59b19d9b6fb6371c08cc16039caf64bdb05c/akka-slf4j/src/main/scala/akka/event/slf4j/Slf4jLogger.scala#L117) and the following assumption is invalid:

```scala
    event match {
      case m: LogEventWithMarker ⇒
        m.marker match {
          case slf4jMarker: Slf4jLogMarker ⇒ slf4jMarker.marker
          case marker                      ⇒ MarkerFactory.getMarker(marker.name)
        }
      case _ ⇒ null
    }
```

This code assumes existence of a marker when a class is instance of `LogEventWithMarker`, which is unfortunatelly invalid.

Invocation of `log.warn` results in calling [`Warning(cause.get, logSource, logClass, message, mdc, marker.orNull.asInstanceOf[UntypedLM])
 `](https://github.com/akka/akka/blob/fafc59b19d9b6fb6371c08cc16039caf64bdb05c/akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/LoggerAdapterImpl.scala#L392), which creates instance of:

``` scala
class Warning4(logSource: String, logClass: Class[_], message: Any, override val mdc: MDC, override val marker: LogMarker, override val cause: Throwable)
    extends Warning2(logSource, logClass, message, mdc) with LogEventWithMarker with LogEventWithCause
```

but with the marker set to `null`.

### PR DESCRIPTION
**Pull request by KarelCemus**
Fixes #26042 

The binary compatible fix not changing the signature (see the discussion).

I've also implemented a binary incompatible fix [here](https://github.com/KarelCemus/akka/commit/652ca013fd671ab8f00792d79b5375a2a987cf77). Should I open another PR? What would be a target branch?

### CODE REVIEW

File: akka-slf4j/src/test/scala/akka/event/slf4j/Slf4jLoggerSpec.scala [hunk 1]
```diff
@@ -155,6 +155,14 @@ class Slf4jLoggerSpec extends AkkaSpec(Slf4jLoggerSpec.config) with BeforeAndAft
       s should include("msg=[Message with custom MDC values]")
     }
 
+    "support null marker" in {
+      producer ! StringWithMarker("security-wise interesting message", null)
```
Comment (raboof) [inline akka-slf4j/src/test/scala/akka/event/slf4j/Slf4jLoggerSpec.scala]: It would be cool to reproduce it via `log.warn(cause, ...)` as well. Optional IMHO though.

File: akka-slf4j/src/main/scala/akka/event/slf4j/Slf4jLogger.scala [hunk 2]
```diff
@@ -113,6 +113,7 @@ class Slf4jLogger extends Actor with SLF4JLogging with RequiresMessageQueue[Logg
     event match {
       case m: LogEventWithMarker ⇒
```
Comment (raboof) [inline akka-slf4j/src/main/scala/akka/event/slf4j/Slf4jLogger.scala]: Perhaps we should add a comment to LogEventWithMarker explaining `marker` may be `null`, as that is rather uncommon?

**Review by raboof — APPROVED** [review]

**Comment by raboof** [comment]
OK TO TEST

File: akka-slf4j/src/main/scala/akka/event/slf4j/Slf4jLogger.scala (hunk 2 above)
Comment (KarelCemus) [reply akka-slf4j/src/main/scala/akka/event/slf4j/Slf4jLogger.scala]: Into the trait or at this line?

File: akka-slf4j/src/test/scala/akka/event/slf4j/Slf4jLoggerSpec.scala (hunk 1 above)
Comment (KarelCemus) [reply akka-slf4j/src/test/scala/akka/event/slf4j/Slf4jLoggerSpec.scala]: Well, the test already exists but somehow does not fail ....

https://github.com/akka/akka/blob/9941f7d80086cb602fdaac86feabbe82733731aa/akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/ActorLoggingSpec.scala#L124

Comment (raboof) [reply akka-slf4j/src/test/scala/akka/event/slf4j/Slf4jLoggerSpec.scala]: Aah, that test tests via the `akka.testkit.TestEventListener`, so it wouldn't see any problems in `Slf4jLogger`. OK then :+1:

File: akka-slf4j/src/main/scala/akka/event/slf4j/Slf4jLogger.scala (hunk 2 above)
Comment (raboof) [reply akka-slf4j/src/main/scala/akka/event/slf4j/Slf4jLogger.scala]: In the trait would be the most clear IMHO

Comment (KarelCemus) [reply akka-slf4j/src/main/scala/akka/event/slf4j/Slf4jLogger.scala]: Added this comment line into the trait

```
Marker attribute is nullable due to backward binary compatibility in the class `Warning4`
```

**Review by johanandren — APPROVED** [review]
