### PR TITLE
Fix MatchError when asking an ActorRefAdapter

### LINKED ISSUE #19947: MatchError with akka.typed.AskPattern
If the typed ask pattern is used on an ActorRef which refers to a nonexistent actor, the AskPattern implementation throws a MatchError (see below; full code is here: https://github.com/durban/akka-typed-examples/blob/8625c5404d109b30a2a5fa0e85137baa7ed2e41f/src/main/scala/com/example/ask/TypedAsk.scala). The reason seems to be that a destructuring val definition tries to match a 3-tuple, but in this case a 2-tuple is returned.

```
[info] Running com.example.ask.TypedAsk 
[ERROR] [03/04/2016 10:34:10.155] [MySys-akka.actor.default-dispatcher-4] [akka.actor.LocalActorRefProvider(akka://MySys)] guardian failed, shutting down system
scala.MatchError: (Actor[akka://MySys/deadLetters],scala.concurrent.impl.Promise$KeptPromise@1603220d) (of class scala.Tuple2)                                
        at akka.typed.AskPattern$PromiseRef.<init>(Ask.scala:42)                                                                                              
        at akka.typed.AskPattern$PromiseRef$.apply(Ask.scala:60)                                                                                              
        at akka.typed.AskPattern$.ask(Ask.scala:64)                                                                                                           
        at akka.typed.AskPattern$Askable$.$qmark$extension(Ask.scala:38)                                                      
        at com.example.ask.TypedAsk$$anonfun$root$1$$anonfun$apply$2.apply(TypedAsk.scala:26)                                 
        at com.example.ask.TypedAsk$$anonfun$root$1$$anonfun$apply$2.apply(TypedAsk.scala:22)                                 
        at akka.typed.ScalaDSL$Static.message(ScalaDSL.scala:240)                                                             
        at akka.typed.ActorAdapter$$anonfun$receive$1.applyOrElse(Impl.scala:31)                                              
        at akka.actor.Actor$class.aroundReceive(Actor.scala:480)                                                              
        at akka.typed.ActorAdapter.aroundReceive(Impl.scala:17)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[ERROR] [03/04/2016 10:34:10.160] [MySys-akka.actor.default-dispatcher-4] [akka://MySys/user] (Actor[akka://MySys/deadLetters],scala.concurrent.impl.Promise$KeptPromise@1603220d) (of class scala.Tuple2)
scala.MatchError: (Actor[akka://MySys/deadLetters],scala.concurrent.impl.Promise$KeptPromise@1603220d) (of class scala.Tuple2)
        at akka.typed.AskPattern$PromiseRef.<init>(Ask.scala:42)
        at akka.typed.AskPattern$PromiseRef$.apply(Ask.scala:60)
        at akka.typed.AskPattern$.ask(Ask.scala:64)
        at akka.typed.AskPattern$Askable$.$qmark$extension(Ask.scala:38)
        at com.example.ask.TypedAsk$$anonfun$root$1$$anonfun$apply$2.apply(TypedAsk.scala:26)
        at com.example.ask.TypedAsk$$anonfun$root$1$$anonfun$apply$2.apply(TypedAsk.scala:22)
        at akka.typed.ScalaDSL$Static.message(ScalaDSL.scala:240)
        at akka.typed.ActorAdapter$$anonfun$receive$1.applyOrElse(Impl.scala:31)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:480)
        at akka.typed.ActorAdapter.aroundReceive(Impl.scala:17)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

^C
```

### PR DESCRIPTION
**Pull request by dilation**
Fixes #19947.

/cc @rkuhn

### CODE REVIEW

File: akka-typed/src/main/scala/akka/typed/Ask.scala [hunk 1]
```diff
@@ -59,6 +61,10 @@ object AskPattern {
         val b = adapter.ActorRefAdapter[U](a)
         (b, a.result.future.asInstanceOf[Future[U]], a)
       }
+
+    val ref: ActorRef[U] = _ref
+    val future: Future[U] = _future
```
Comment (patriknw) [inline akka-typed/src/main/scala/akka/typed/Ask.scala]: those two could still be in the above pattern match?

File: akka-typed/src/test/scala/akka/typed/AskSpec.scala [hunk 2]
```diff
@@ -0,0 +1,82 @@
+/**
+ * Copyright (C) 2014-2017 Lightbend Inc. <http://www.lightbend.com>
```
Comment (patriknw) [inline akka-typed/src/test/scala/akka/typed/AskSpec.scala]: 2017 is enough here

**Review by patriknw — COMMENTED** [review]
looking good, with one comment

File: akka-typed/src/main/scala/akka/typed/Ask.scala (hunk 1 above)
Comment (dilation) [inline akka-typed/src/main/scala/akka/typed/Ask.scala]: Yes, but then `_promiseRef` couldn't be `private[this]` (since `ref` and `future` need to be public).

Comment (patriknw) [inline akka-typed/src/main/scala/akka/typed/Ask.scala]: I see

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by dilation** [comment]
I'm not familiar with the process, does this need something else to be merged?

**Comment by ktoso** [comment]
We usually merge after 2 LGTMs (step 10 as shown here https://github.com/akka/akka/blob/master/CONTRIBUTING.md#general-workflow ).
This seems uncontroversial, thanks for the PR!

FYI @rkuhn in case there's something to look deeper into here.

**Review by ktoso — APPROVED** [review]
LGTM

**Comment by dilation** [comment]
@ktoso Great, thank you!

One followup question: what's the next release which will contain this fix? I.e., will it be included in the 2.4 series, or only in 2.5?

**Comment by ktoso** [comment]
Since 2.5 is very backwards compatible (also binary) with 2.4, and this
module is experimental right now I'd say we keep it in 2.5 only (so 2.5-RC1
is the next one that this will be in)


On 2 March 2017 at 12:51:28, Daniel Urban (notifications@github.com) wrote:

@ktoso <https://github.com/ktoso> Great, thank you!

One followup question: what's the next release which will contain this fix?
I.e., will it be included in the 2.4 series, or only in 2.5?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/akka/akka/pull/22347#issuecomment-283633437>, or mute
the thread

**Comment by dilation** [comment]
Fair enough, thanks for the quick answer.
