### PR TITLE
Fixes to one of the tests in FlowGroupBySpec 

### LINKED ISSUE #27662: Failed: FlowGroupBySpec
https://jenkins.akka.io:8498/job/akka-nightly/6908/testReport/junit/akka.stream.scaladsl/FlowGroupBySpec/groupBy_must_work_with_random_demand/

One of the tests leaking streams somehow.

I thought I fixed this in one of the materializer PRs but apparently not.

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #27662

### CODE REVIEW

File: akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowGroupBySpec.scala [hunk 1]
```diff
@@ -552,24 +553,19 @@ class FlowGroupBySpec extends StreamSpec("""
...
-
-      case class SubFlowState(probe: TestSubscriber.Probe[ByteString], hasDemand: Boolean, firstElement: ByteString)
-      val map = new util.HashMap[Int, SubFlowState]()
+      val probes = IndexedSeq.tabulate(100)(_ => Promise[TestSubscriber.Probe[ByteString]]())
 
       final class ProbeSink(val attributes: Attributes, shape: SinkShape[ByteString])(implicit system: ActorSystem)
           extends SinkModule[ByteString, TestSubscriber.Probe[ByteString]](shape) {
+
+        // materialized on demand by GroupBy so we need thread safety here
+        val materializationCounter = new AtomicInteger(0)
```
Comment (johanandren) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowGroupBySpec.scala]: The thread unsafe counter in `probesTopWrite` (and array population) was not causing the issue but still worth fixing

File: akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowGroupBySpec.scala [hunk 2]
```diff
@@ -552,24 +553,19 @@ class FlowGroupBySpec extends StreamSpec("""
...
-
-      val probes = new java.util.ArrayList[Promise[TestSubscriber.Probe[ByteString]]](100)
-      (0 to 99).foreach(_ => probes.add(Promise[TestSubscriber.Probe[ByteString]]()))
-
-      var probesWriterTop = 0
-      var probesReaderTop = 0
-
-      case class SubFlowState(probe: TestSubscriber.Probe[ByteString], hasDemand: Boolean, firstElement: ByteString)
-      val map = new util.HashMap[Int, SubFlowState]()
+      val probes = IndexedSeq.tabulate(100)(_ => Promise[TestSubscriber.Probe[ByteString]]())
```
Comment (johanandren) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowGroupBySpec.scala]: Not sure why the test was using Java collections throughout, changed to Scala counterparts.

File: akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowGroupBySpec.scala [hunk 3]
```diff
@@ -643,7 +643,16 @@ class FlowGroupBySpec extends StreamSpec("""
...
+
+      // complete has some try to feed downstream logic, we're not testing that here
+      // we just want to kill all substreams so lets fail the stream instead
+      upstreamSubscription.sendError(TE("killing this stream"))
+      map.values.foreach { subFlowState =>
+        // not all may have seen a subscription because random selection above
+        subFlowState.probe.ensureSubscription()
+        subFlowState.probe.expectError()
+
+      }
```
Comment (johanandren) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowGroupBySpec.scala]: This was the actual problem, the test would randomly cause buffered elements for the downstreams which means they wouldn't be completed until there was demand and therefore sometimes staying running after test was otherwise complete.

File: akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowGroupBySpec.scala (hunk 2 above)
Comment (raboof) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowGroupBySpec.scala]:
```suggestion
      val probes = IndexedSeq.fill(100)(Promise[TestSubscriber.Probe[ByteString]]())
```

**Review by raboof — APPROVED** [review]

**Review by patriknw — APPROVED** [review]
LGTM
