### PR TITLE
Actually check the shutdown status before materializing anything

### LINKED ISSUE #24240: FAILED akka.stream.ActorMaterializerSpec.ActorMaterializer must refuse materialization after shutdown
https://jenkins.akka.io:8498/job/akka-nightly/5107/testReport/junit/akka.stream/ActorMaterializerSpec/ActorMaterializer_must_refuse_materialization_after_shutdown/

```
Error Message

org.scalatest.exceptions.TestFailedException: Expected exception java.lang.IllegalStateException to be thrown, but java.util.concurrent.TimeoutException was thrown

Stacktrace

sbt.ForkMain$ForkError: org.scalatest.exceptions.TestFailedException: Expected exception java.lang.IllegalStateException to be thrown, but java.util.concurrent.TimeoutException was thrown
	at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:138)
	at org.scalatest.MatchersHelper$.checkExpectedException(MatchersHelper.scala:306)
	at org.scalatest.words.ResultOfBeWordForAnType.thrownBy(ResultOfBeWordForAnType.scala:44)
	at akka.stream.ActorMaterializerSpec$$anonfun$1$$anonfun$apply$mcV$sp$5.apply(ActorMaterializerSpec.scala:40)
	at akka.stream.ActorMaterializerSpec$$anonfun$1$$anonfun$apply$mcV$sp$5.apply(ActorMaterializerSpec.scala:37)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
	at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
	at akka.stream.testkit.StreamSpec.withFixture(StreamSpec.scala:26)
	at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
	at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
	at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
	at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:59)
	at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
	at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1147)
	at akka.testkit.AkkaSpec.runTests(AkkaSpec.scala:59)
	at org.scalatest.Suite$class.run(Suite.scala:1147)
	at akka.testkit.AkkaSpec.org$scalatest$WordSpecLike$$super$run(AkkaSpec.scala:59)
	at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
	at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1192)
	at akka.testkit.AkkaSpec.org$scalatest$BeforeAndAfterAll$$super$run(AkkaSpec.scala:59)
	at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
	at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
	at akka.testkit.AkkaSpec.run(AkkaSpec.scala:59)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
	at sbt.ForkMain$Run$2.call(ForkMain.java:300)
	at sbt.ForkMain$Run$2.call(ForkMain.java:290)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: sbt.ForkMain$ForkError: java.util.concurrent.TimeoutException: Futures timed out after [20000 milliseconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:223)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:227)
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.Await$.result(package.scala:190)
	at akka.stream.impl.ExtendedActorMaterializer.actorOf(ActorMaterializerImpl.scala:64)
	at akka.stream.impl.GraphStageIsland.onIslandReady(PhasedFusingActorMaterializer.scala:742)
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:507)
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:420)
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:415)
	at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:524)
	at akka.stream.scaladsl.Source.runWith(Source.scala:93)
	at akka.stream.scaladsl.Source.runForeach(Source.scala:139)
	at akka.stream.ActorMaterializerSpec$$anonfun$1$$anonfun$apply$mcV$sp$5$$anonfun$apply$2.apply(ActorMaterializerSpec.scala:41)
	at akka.stream.ActorMaterializerSpec$$anonfun$1$$anonfun$apply$mcV$sp$5$$anonfun$apply$2.apply(ActorMaterializerSpec.scala:41)
	at org.scalatest.MatchersHelper$.checkExpectedException(MatchersHelper.scala:299)
	... 49 more
```

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #24240

Somehow threw IllegalState later in the process before, but I think it needs to be like this to work as expected.

### CODE REVIEW

File: akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala [hunk 1]
```diff
@@ -420,6 +420,7 @@ private final case class SavedIslandData(islandGlobalOffset: Int, lastVisitedOff
     defaultAttributes: Attributes,
     defaultPhase:      Phase[Any],
     phases:            Map[IslandTag, Phase[Any]]): Mat = {
+    if (isShutdown) throw new IllegalStateException("Trying to materialize stream after materializer has been shutdown")
```
Comment (patriknw) [inline akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala]: what would happen if the materialization starts in one thread, and half ways through another thread calls `shutdown`?

Comment (johanandren) [reply akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala]: It has sent a `PoisonPill` to the supervisor, so it would maybe not throw an IllegalState, but it shouldn't leak anything. Maybe we should check in the end as well to be able to provide this clear error rather than potentially fail silently

Comment (patriknw) [reply akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala]: sounds good to do the same check at the end of this method

File: akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala [hunk 2]
```diff
@@ -496,11 +497,22 @@ private final case class SavedIslandData(islandGlobalOffset: Int, lastVisitedOff
...
+    try {
+      islandTracking.getCurrentPhase.onIslandReady()
+      islandTracking.allNestedIslandsReady()
+
+      if (Debug) println("--- Finished materialization")
+      matValueStack.peekLast().asInstanceOf[Mat]
+
+    } catch {
+      case ex: IllegalStateException if isShutdown && ex.getMessage == "cannot create children while terminating or terminated" ⇒
+        throw shutdownWhileMaterializingFailure
```
Comment (patriknw) [inline akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala]: is this `catch` needed? looks like the `finally` would be enough

Comment (johanandren) [reply akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala]: I wanted to give a nicer error message than that "cannot create children while terminating or terminated"

Comment (patriknw) [reply akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala]: yes, but you will only throw that `shutdownWhileMaterializingFailure` when `isShutdown` is `true`, and that would be handled by the `finally` also. Also, the exception you throw inside the catch will be replaced by the exception you throw in the finally anyway.

```
scala> try throw new Exception("e1") catch {case e: Exception => throw new Exception("e2") } finally throw new Exception("e3")
java.lang.Exception: e3
```

Comment (johanandren) [reply akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala]: Ok, catch-silence and check+throw in finally it is then

Comment (johanandren) [reply akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala]: I managed to misunderstand a second time, I'll blame it on mondays.

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by johanandren** [comment]
Wha?

```
[error] /localhome/jenkinsakka/workspace/pr-validator-per-commit-jenkins/akka-cluster-typed/src/test/scala/docs/akka/cluster/typed/BasicClusterExampleSpec.scala:195:19: value expectNoMsg is not a member of akka.testkit.typed.scaladsl.TestProbe[akka.cluster.ClusterEvent.MemberEvent]
[error]         testProbe.expectNoMsg(1000.millis)
[error] 
```

**Comment by johanandren** [comment]
PLS BUILD

**Review by ktoso — CHANGES_REQUESTED** [review]
Looks good I think, LGTM

**Review by ktoso — APPROVED** [review]
