### PR TITLE
Better recovery timeout for persistent actors #20738

### LINKED ISSUE #20738: setReceiveTimeout issue on persistenct actor since 2.4.7
Since akka 2.4.7 (and #20698), setting receive timeout in prestart does not work in persistent actor.
If I set it in receiveRecover/RecoveryCompleted, it works.

I did not analyse the code but I saw in EventSourced  class that a "previousRecieveTimeout" is backuped and restored, maybe it does not work well in some cases ?

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #20738 by using the scheduler instead of `receiveTimeout` additionally it will therefore not be affected by non-recovery messages passing by into the stash of the persistent actor.

### CODE REVIEW

File: akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala [hunk 1]
```diff
@@ -514,44 +523,56 @@ private[persistence] trait Eventsourced extends Snapshotter with PersistenceStas
    *
    * All incoming messages are stashed.
    */
-  private def recovering(recoveryBehavior: Receive, previousReceiveTimeout: Duration) =
+  private def recovering(recoveryBehavior: Receive) =
     new State {
+
+      // protect against snapshot stalling forever because of journal overloaded and such
+      val timeout = extension.journalConfigFor(journalPluginId).getMillisDuration("recovery-event-timeout")
```
Comment (patriknw) [inline akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala]: perhaps pass as a param, to avoid reading the config twice

Comment (johanandren) [inline akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala]: Will do.

Comment (johanandren) [inline akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala]: Could I even put it in a place so it doesn't have to be read once per persistent actor start?

File: akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala [hunk 2]
```diff
@@ -514,44 +523,56 @@ private[persistence] trait Eventsourced extends Snapshotter with PersistenceStas
...
             updateLastSequenceNr(p)
             Eventsourced.super.aroundReceive(recoveryBehavior, p)
           } catch {
             case NonFatal(t) ⇒
+              timeoutCancellable.cancel()
               try onRecoveryFailure(t, Some(p.payload)) finally context.stop(self)
           }
         case RecoverySuccess(highestSeqNr) ⇒
-          resetRecieveTimeout()
+          timeoutCancellable.cancel()
```
Comment (patriknw) [inline akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala]: there is a small chance that a `RecoveryTick` is already enqueued in the mailbox here and will be delivered to user's `receive`. That could be filtered out inn`ProcessingState` or at least ignored in `unhandled`.

**Comment by patriknw** [comment]
LGTM

File: akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala (hunk 1 above)
Comment (patriknw) [inline akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala]: You can't put it in the trait because that would break bin compat.
We could change `journalConfigFor` to return a `Settings` object that would read such things once,  but I don't think it's worth it. It's rather costly to start a persistent actor anyway.

**Comment by drewhk** [comment]
LGTM

File: akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala (hunk 2 above)
Comment (johanandren) [inline akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala]: Ah, yes, I was going to ask about that. Will look into it.

File: akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala [hunk 3]
```diff
@@ -615,6 +635,10 @@ private[persistence] trait Eventsourced extends Snapshotter with PersistenceStas
       case WriteMessagesFailed(_) ⇒
         writeInProgress = false
         () // it will be stopped by the first WriteMessageFailure message
+
+      case _: RecoveryTick =>
+        // we may have one of these scheduled before the scheduled timeout
+        // is cancelled, just consume it so the concrete actor never sees it
```
Comment (johanandren) [inline akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala]: that was weird phrasing, will redo

File: akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala [hunk 4]
```diff
@@ -31,6 +31,9 @@ private[persistence] object Eventsourced {
   private final case class StashingHandlerInvocation(evt: Any, handler: Any ⇒ Unit) extends PendingHandlerInvocation
   /** does not force the actor to stash commands; Originates from either `persistAsync` or `defer` calls */
   private final case class AsyncHandlerInvocation(evt: Any, handler: Any ⇒ Unit) extends PendingHandlerInvocation
+
+  /** message used to detect that recovery timed out */
+  private case class RecoveryTick(snapshot: Boolean)
```
Comment (patriknw) [inline akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala]: `final`

**Comment by patriknw** [comment]
LGTM
