### PR TITLE
#19342 Eliminated race in SubstreamSubscriptionTimeoutSpec due to concat

### LINKED ISSUE #19342: FAILED: SubstreamSubscriptionTimeoutSpec
```
[info] SubstreamSubscriptionTimeoutSpec:
Coroner Thread Count starts at 25 in akka.stream.scaladsl.SubstreamSubscriptionTimeoutSpec
[info] groupBy and splitwhen
[info] - must timeout and cancel substream publishers when no-one subscribes to them after some time (time them out) *** FAILED *** (1 second, 578 milliseconds)
[info]   3 did not equal "expected" (SubstreamSubscriptionTimeoutSpec.scala:78)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
[info]   at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6231)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6277)
[info]   at akka.stream.scaladsl.SubstreamSubscriptionTimeoutSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$5.apply(SubstreamSubscriptionTimeoutSpec.scala:78)
[info]   at akka.stream.scaladsl.SubstreamSubscriptionTimeoutSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$5.apply(SubstreamSubscriptionTimeoutSpec.scala:43)
[info]   at akka.stream.testkit.Utils$.assertAllStagesStopped(Utils.scala:26)
[info]   at akka.stream.scaladsl.SubstreamSubscriptionTimeoutSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(SubstreamSubscriptionTimeoutSpec.scala:43)
[info]   at akka.stream.scaladsl.SubstreamSubscriptionTimeoutSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(SubstreamSubscriptionTimeoutSpec.scala:43)
[info]   at akka.stream.scaladsl.SubstreamSubscriptionTimeoutSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(SubstreamSubscriptionTimeoutSpec.scala:43)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[info]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]   at akka.stream.testkit.AkkaSpec.withFixture(AkkaSpec.scala:58)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)
[info]   at akka.stream.testkit.AkkaSpec.runTest(AkkaSpec.scala:58)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:318)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:318)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
[info]   at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1021)
[info]   at akka.stream.testkit.AkkaSpec.runTests(AkkaSpec.scala:58)
[info]   at org.scalatest.Suite$class.run(Suite.scala:1424)
[info]   at akka.stream.testkit.AkkaSpec.org$scalatest$WordSpecLike$$super$run(AkkaSpec.scala:58)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
[info]   at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1067)
[info]   at akka.stream.testkit.AkkaSpec.org$scalatest$BeforeAndAfterAll$$super$run(AkkaSpec.scala:58)
[info]   at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257)
[info]   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256)
[info]   at akka.stream.testkit.AkkaSpec.run(AkkaSpec.scala:58)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:466)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:677)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:84)
[info]   at sbt.TestRunner.run(TestFramework.scala:94)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:219)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:219)
[info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:207)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:219)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:219)
[info]   at sbt.TestFunction.apply(TestFramework.scala:224)
[info]   at sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:211)
[info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:217)
[info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:217)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:45)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:45)
[info]   at sbt.std.Transform$$anon$4.work(System.scala:64)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
[info]   at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
[info]   at sbt.Execute.work(Execute.scala:244)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
[info]   at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
[info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]   at java.lang.Thread.run(Thread.java:745)
```

### PR DESCRIPTION
**Pull request by drewhk**
Fixes #19342

### CODE REVIEW

File: akka-stream-tests/src/test/scala/akka/stream/scaladsl/SubstreamSubscriptionTimeoutSpec.scala [hunk 1]
```diff
@@ -74,7 +73,8 @@ class SubstreamSubscriptionTimeoutSpec(conf: String) extends AkkaSpec(conf) {
       // sleep long enough for it to be cleaned up
       Thread.sleep(1500)
 
-      val f = s3.runWith(Sink.head).recover { case _: SubscriptionTimeoutException ⇒ "expected" }
+      // Must be a Sink.seq, otherwise there is a race due to the concat in the `lift` implementation
+      val f = s3.runWith(Sink.seq).recover { case _: SubscriptionTimeoutException ⇒ "expected" }
```
Comment (drewhk) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/SubstreamSubscriptionTimeoutSpec.scala]: this is the actual fix, rest is just boy-scouting.

Comment (rkuhn) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/SubstreamSubscriptionTimeoutSpec.scala]: Well, I can see how this may prevent a certain race condition from being relevant, but there still is another, no? I.e. this test will not be fully deterministic if the scheduled timeout has not happened within the duration that this test procedure thread has slept (plus signal propagation delays).

File: akka-stream/src/main/scala/akka/stream/impl/StreamOfStreamProcessors.scala [hunk 2]
```diff
@@ -224,204 +224,3 @@ private[akka] abstract class MultiStreamOutputProcessor(_settings: ActorMaterial
...
-    super.fail(e)
-  }
-
-  override def pumpFinished() = {
-    finishInputs()
-    super.pumpFinished()
-  }
-
-  override def activeReceive = primaryInputs.subreceive orElse primaryOutputs.subreceive orElse inputSubstreamManagement
-}
```
Comment (rkuhn) [inline akka-stream/src/main/scala/akka/stream/impl/StreamOfStreamProcessors.scala]: bolstering our negative counts are we? :-)

**Comment by rkuhn** [comment]
LGTM

File: akka-stream/src/main/scala/akka/stream/impl/StreamOfStreamProcessors.scala (hunk 2 above)
Comment (drewhk) [inline akka-stream/src/main/scala/akka/stream/impl/StreamOfStreamProcessors.scala]: I just found those lying around ;)

File: akka-stream-tests/src/test/scala/akka/stream/scaladsl/SubstreamSubscriptionTimeoutSpec.scala (hunk 1 above)
Comment (drewhk) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/SubstreamSubscriptionTimeoutSpec.scala]: Yes, but do you know a better way to test this? Currently we rely on that the 300ms subscription timeout does not overcome the 1500 ms sleep.

Comment (rkuhn) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/SubstreamSubscriptionTimeoutSpec.scala]: Yes, and if I had a better idea I would have implemented it long ago :-(

Comment (drewhk) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/SubstreamSubscriptionTimeoutSpec.scala]: ok, then let's be happy for now with fixing one race that reliably happened even locally :)
