### PR TITLE
#20829 Fix double pull in GroupBy

### LINKED ISSUE #20829: GroupBy Graph Stage, tries to pull twice in certain condition
I'm encountered problem with GroupBy graph stage in very specific env.

I have following flow configured:
```
 Flow[ShardMessage].groupBy(Int.MaxValue, f => f.userId).to(actorGroupFlow) //userId - Int value

val actorGroupFlow = GraphDSL.create() { implicit builder =>
  val fanOut = builder.add(Broadcast[ShardMessage](1))

  fanOut ~> Sink.ignore
  SinkShape(fanOut.in)
}
```

And i receive following exception.
```
java.lang.IllegalArgumentException: requirement failed: Cannot pull port (GroupBy.in) twice
	at scala.Predef$.require(Predef.scala:224)
	at akka.stream.stage.GraphStageLogic.pull(GraphStage.scala:348)
	at akka.stream.stage.GraphStageLogic.tryPull(GraphStage.scala:358)
	at akka.stream.impl.fusing.GroupBy$$anon$1.onPull(StreamOfStreams.scala:272)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:608)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:542)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:472)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:415)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:604)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:619)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:530)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

It only reproduce itself on the very specific HW/SW configuration:
```
CentOS Linux release 7.2.1511 (Core)
java version "1.8.0_92"
```

Machine itself is 32 physical core Hardware server. I cannot reproduce following exception on my local dev or VM machines (much slower machines).

Any attempt to create async boundary around it did not yield any results.

### PR DESCRIPTION
**Pull request by drewhk**
Fixes #20829

### CODE REVIEW

File: akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala [hunk 1]
```diff
@@ -269,7 +269,7 @@ final class GroupBy[T, K](maxSubstreams: Int, keyFor: T ⇒ K) extends GraphStag
               subSubstreamSource.push(nextElementValue)
               clearNextElement()
             }
-          } else tryPull(in)
+          } else if (!hasBeenPulled(in)) tryPull(in)
```
Comment (yoks) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala]: hasBeenPulled already checks if port has been closed, can be changed to just pull?

Comment (drewhk) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala]: true

Comment (ktoso) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala]: Sanity checked this myself too, yeah `tryPull` => `pull` here

**Comment by ktoso** [comment]
LGTM (after tryPull => pull)

File: akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala (hunk 1 above)
Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala]: That's really confusing, ain't it? Why would `pull` work but not `tryPull`?

Comment (ktoso) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala]: hm? That's not what we're saying.
`tryPull` works, `pull` works. `tryPull` does additional `isClosed` checks, which we don't need to do, because we guard the pull already with the `hasBeenPulled`

Comment (drewhk) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala]: both work. It is just it is redundant to call tryPull in this case.

Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala]: Ah, sorry, I'll go hide under a rock.

Comment (drewhk) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala]: well, `hasBeenPulled` *is* confusing, but we can't fix it until 2.5 :(

Comment (ktoso) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala]: want to add a new name for it or what?
(2.5 we want to be bin compatible still)

Comment (drewhk) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala]: I would deprecate the current one (but not remove) and replace it with `canBePulled` or something more sane. Also replace `isAvailable` with `hasElementPending`. The names are ofc just working names, my point is to make it less surprising and more in-line with the output port (`isAvailable` -> `canBePushed`). Something like that.

Comment (ktoso) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala]: I think we could do these things still in 2.4.x, and keep the old ones deprecated. Maybe ticket worthy?

Comment (drewhk) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala]: I don't think it is a good idea to deprecate in a stable version.

**Comment by patriknw** [comment]
LGTM

**Comment by drewhk** [comment]
It needs to be tryPull it seems. But why..

**Comment by yoks** [comment]
Hmm, yea looks like `hasBeenPulled` do not guard against stream which was closed before it was pulled?

`needToPull` does same check, it checks for `hasBeenPulled` and `isClosed`. We can guard it with `needToPull`, or use `tryPull`. But in our case we already checked for `hasNextElement` before, so `tryPull` seems like best option here.
