### PR TITLE
Attempt to fix multi-jvm failure when untyped system is adapted from typed system

### LINKED ISSUE #26779: Cannot migrate to Akka typed if there are multi-jvm/multi-node tests in project
We are using akka 2.5.22 and we have been in process of migrating our project to typed. We replaced all our untyped actors to typed and now we are trying to replace our top level untyped actor system to typed.

We got stuck in replacing our actor system to typed because we have multi-jvm/multi-node tests in our project.

We extend `MultiNodeSpec` for our multi-jvm test and it happens to take untyped actor system to create actors internally via `untypedSystem.actorOf`. And we want to keep our top level actor system to be typed. So, When we create a typed system, adapt it to untyped and pass it to `MultiNodeSpec` then, the test fails with the following exception:

```
[error] Exception in thread "main" java.lang.UnsupportedOperationException: cannot create top-level actor from the outside on ActorSystem with custom user guardian
[error] 	at akka.actor.ActorSystemImpl.actorOf(ActorSystem.scala:786)
[error] 	at App1$.delayedEndpoint$App1$1(App1.scala:12)
[error] 	at App1$delayedInit$body.apply(App1.scala:6)
[error] 	at scala.Function0.apply$mcV$sp(Function0.scala:39)
[error] 	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error] 	at scala.App.$anonfun$main$1$adapted(App.scala:80)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at scala.App.main(App.scala:80)
[error] 	at scala.App.main$(App.scala:78)
[error] 	at App1$.main(App1.scala:6)
[error] 	at App1.main(App1.scala)
```

So, while tracing back the exception, we got to know that `untypedSystem.actorOf` checks if a custom guardian is wired or not, if it is then it throws the above mentioned exception and in case of untypedSystem being created from typed system will always have a guardian actor (in our case guardian actor is an actor with empty behavior).

For more details about this error please refer this [discussion](https://discuss.lightbend.com/t/migrating-project-to-typed-actor-system/3971).

To fix the error we can make internal actors of `MultiNodeSpec` to be created in system space instead of user space as as `untypedSystem.systemActorOf` does not throw above exception when untypedSystem is adapted from typedSystem.

To know more about the fix please refer this [discussion](https://discuss.lightbend.com/t/cannot-migrate-to-akka-typed-if-there-are-multi-jvm-multi-node-tests-in-project/4013).

### PR DESCRIPTION
**Pull request by skvithalani**
Spawn system space actors instead of user space internally in akka-multi-node-testkit

## Purpose

Resolves #26779

## References

https://discuss.lightbend.com/t/cannot-migrate-to-akka-typed-if-there-are-multi-jvm-multi-node-tests-in-project/4013

## Background Context

Internal actors of `MultiNodeSpec` need to be created in system space instead of user space as `untypedSystem.systemActorOf` does not throw exception when untypedSystem is adapted from typedSystem.

### CODE REVIEW

**Comment by johanandren** [comment]
OK TO TEST

**Review by raboof — APPROVED** [review]

**Comment by patriknw** [comment]
I tried multi-jvm tests locally and some are failing (those are not running in pr validation). I'm investigating what is causing that.

File: akka-multi-node-testkit/src/main/scala/akka/remote/testconductor/Player.scala [hunk 1]
```diff
@@ -88,8 +88,8 @@ trait Player { this: TestConductorExt =>
     import Settings.BarrierTimeout
 
     if (_client ne null) throw new IllegalStateException("TestConductorClient already started")
-    _client = system.actorOf(Props(classOf[ClientFSM], name, controllerAddr), "TestConductorClient")
-    val a = system.actorOf(Player.waiterProps)
+    _client = system.systemActorOf(Props(classOf[ClientFSM], name, controllerAddr), "TestConductorClient")
```
Comment (patriknw) [inline akka-multi-node-testkit/src/main/scala/akka/remote/testconductor/Player.scala]: @skvithalani Some timing/ordering when shutting down the Player vs terminating the ActorSystem is changed when running this as systemActorOf. It is fixed by changing `stay` to `stop()` here: https://github.com/akka/akka/blob/master/akka-multi-node-testkit/src/main/scala/akka/remote/testconductor/Player.scala#L282

Please add that change.

Use `stop()` for the other TerminateMsg as well, https://github.com/akka/akka/blob/master/akka-multi-node-testkit/src/main/scala/akka/remote/testconductor/Player.scala#L285

Comment (skvithalani) [reply akka-multi-node-testkit/src/main/scala/akka/remote/testconductor/Player.scala]: Sure

Comment (skvithalani) [reply akka-multi-node-testkit/src/main/scala/akka/remote/testconductor/Player.scala]: I have pushed the changes for Player.scala. Wondering if Conductor.scala requires the same changes?

Comment (patriknw) [reply akka-multi-node-testkit/src/main/scala/akka/remote/testconductor/Player.scala]: That shouldn't be needed (or would be wrong). It's only when it's immediately calls `system.terminate()`

**Review by patriknw — APPROVED** [review]
LGTM

File: akka-multi-node-testkit/src/main/scala/akka/remote/testconductor/Player.scala (hunk 1 above)
Comment (skvithalani) [reply akka-multi-node-testkit/src/main/scala/akka/remote/testconductor/Player.scala]: sure.

**Comment by skvithalani** [comment]
The fix is marked in 2.6.0-M1 but this fix is quite crucial for us to migrate our whole project to typed actor system. So, is it possible to give this fix in 2.6.0 instead ? Otherwise we will end up maintaining our feature branch for a longer time before we can merge it to our master.

**Comment by patriknw** [comment]
I have backported it in #26803 and it will be released with 2.5.23 within a few weeks. The issue is marked with that milestone.

**Comment by skvithalani** [comment]
Okay that sounds great thanks !!!
