### PR TITLE
Fix BoundedBlockingQueueSpec against spurious wakeups

### LINKED ISSUE #24991: Failed: BoundedBlockingQueueSpec
https://jenkins.akka.io:8498/job/akka-nightly/5444/consoleFull

```
[info] - must block for less than the timeout when the queue becomes not full *** FAILED *** (15 milliseconds)
[info]   false did not equal true (BoundedBlockingQueueSpec.scala:275)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
[info]   at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6668)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6716)
[info]   at akka.util.BoundedBlockingQueueSpec$$anonfun$8$$anonfun$apply$mcV$sp$26.apply(BoundedBlockingQueueSpec.scala:275)
[info]   at akka.util.BoundedBlockingQueueSpec$$anonfun$8$$anonfun$apply$mcV$sp$26.apply(BoundedBlockingQueueSpec.scala:265)
```

### PR DESCRIPTION
**Pull request by txsmith**
So I think I found the issue for the failing test in #24991.
The test can only fail in the way it did if the call to [`offer(...)`](https://github.com/akka/akka/blob/master/akka-actor-tests/src/test/scala/akka/util/BoundedBlockingQueueSpec.scala#L270) times out. This in turn can only be caused when [`awaitNanos(...)`](https://github.com/akka/akka/blob/master/akka-actor-tests/src/test/scala/akka/util/BoundedBlockingQueueSpec.scala#L748) in the mocked `Condition` returns `0`. Previously it did this as soon as the `await()` returned. Since this can happen unexpectedly in the case of a spurious wakeup, I fixed it by returning the remaining time to wait instead.

This is a bit tricky though since I can't reproduce the issue locally (tried to run the test *lots* of times, no failures came up), so I can only kind of guess. 

Maybe someone can confirm whether this makes sense or whether I'm missing something. 
(I also fixed some review comments from the previous PR in the second commit)

Fixes #24991

### CODE REVIEW

**Comment by raboof** [comment]
OK TO TEST

File: akka-actor-tests/src/test/scala/akka/util/BoundedBlockingQueueSpec.scala [hunk 1]
```diff
@@ -115,6 +114,7 @@ class BoundedBlockingQueueSpec
       val f = Future(queue.put("b"))
 
       after(10 milliseconds) {
+        f.isCompleted should be(false)
         queue.take()
       }
```
Comment (patriknw) [inline akka-actor-tests/src/test/scala/akka/util/BoundedBlockingQueueSpec.scala]: no reason to have such tight timeout 100 milliseconds on next line, see https://github.com/akka/akka/blob/master/CONTRIBUTING.md#preferred-ways-to-use-timeouts-in-tests

Comment (patriknw) [reply akka-actor-tests/src/test/scala/akka/util/BoundedBlockingQueueSpec.scala]: in the light of that, are there other assumptions about time in this test that will not work on slow machines with hiccups?

**Review by patriknw — CHANGES_REQUESTED** [review]

File: akka-actor-tests/src/test/scala/akka/util/BoundedBlockingQueueSpec.scala (hunk 1 above)
Comment (txsmith) [reply akka-actor-tests/src/test/scala/akka/util/BoundedBlockingQueueSpec.scala]: The `Await.result` might indeed trigger a failure if it times out too early.

Some other assumptions:
- when the code in `after(..)` runs, I assume the future above to be started and blocked. A slow thread might cause the order of `take` and `put` to be reversed but this should not cause the test to fail when it shouldn't.
- calls to `mustBlockFor` also have this 100 ms timeout. I can raise this to the 3 seconds as specified in the guidelines, but this would definitely make 7 tests quite a bit slower.

In both cases, chances are that a slow thread will cause a regression to remain undetected, but it will never trigger a false positive.

For now I'll increase the `Await.result` timespans. If there's anything else, let me know.

**Review by patriknw — APPROVED** [review]
LGTM, thanks

**Review by johanandren — APPROVED** [review]
