### PR TITLE
Fix race condition in StreamConverters.asOutputStream()

### LINKED ISSUE #25983: Responding with stream created with StreamConverters.asOutputStream() causes responses to be truncated.
When creating streaming response using `StreamConverters.asOutputStream` the returned data is sometimes truncated. Response code is ok.
I created simple example that reproduces this issue:
https://github.com/Vistritium/akka-http-stramconverters-asoutputstream-truncated/blob/master/src/test/scala/com/example/Test.scala
(it's only 73 lines of code)
When I create steam using other methods it works correctly. When using `StreamConverters.asOutputStream` it usually fails between 1st and 5th request.

There is no issue with akka-http-testkit, I have this issue with real application.

Akka version: 2.5.18
Akka-http version: 10.1.5

Full project showing the issue with failing test: https://github.com/Vistritium/akka-http-stramconverters-asoutputstream-truncated (5 files)

Additional details:
The test usually shows empty string response, but in real application this is usually truncated in half of the response, some data is sent and some data is dropped.
In the test the issue is usually happening between 1st and 5th request but in my app it happens less frequently: 1 in 50 or even 1 in 100 times.

### PR DESCRIPTION
**Pull request by raboof**
Fixes #25983

### CODE REVIEW

File: akka-stream-tests/src/test/scala/akka/stream/io/OutputStreamSourceSpec.scala [hunk 1]
```diff
@@ -68,22 +68,17 @@ class OutputStreamSourceSpec extends StreamSpec(UnboundedMailboxConfig) {
...
-
-      expectTimeout(f, timeout)
-      probe.expectNoMsg(Zero)
-
-      s.request(1)
-      expectSuccess(f, ())
-      probe.expectNext(byteString)
-
-      outputStream.close()
-      probe.expectComplete()
```
Comment (johanandren) [inline akka-stream-tests/src/test/scala/akka/stream/io/OutputStreamSourceSpec.scala]: Yeah, probably not that useful a feature anyways...

File: akka-stream-tests/src/test/scala/akka/stream/io/OutputStreamSourceSpec.scala [hunk 2]
```diff
@@ -68,22 +68,17 @@ class OutputStreamSourceSpec extends StreamSpec(UnboundedMailboxConfig) {
...
+    "not truncate the stream on close" in assertAllStagesStopped {
+      for (_ ← 1 to 10) {
+        val (outputStream, result) =
+          StreamConverters.asOutputStream()
+            .toMat(Sink.fold[ByteString, ByteString](ByteString.empty)(_ ++ _))(Keep.both)
+            .run
+        outputStream.write(bytesArray)
+        outputStream.close()
+        result.futureValue should be(ByteString(bytesArray))
+      }
```
Comment (johanandren) [inline akka-stream-tests/src/test/scala/akka/stream/io/OutputStreamSourceSpec.scala]: Would this truncate on every run or was it more random?

File: akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala [hunk 3]
```diff
@@ -172,29 +108,16 @@ private[akka] class OutputStreamAdapter(
   private[this] def sendData(data: ByteString): Unit =
     send(() ⇒ {
       try {
-        dataQueue.put(data)
+        // FIXME take into account writeTimeout here.
```
Comment (johanandren) [inline akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala]: fixme, isn't that just a `tryAcquire(permits, timeout, unit)`?

File: akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala [hunk 4]
```diff
@@ -172,29 +108,16 @@ private[akka] class OutputStreamAdapter(
...
+        unfulfilledDemand.acquire()
+        sendToStage(Send(data))
       } catch { case NonFatal(ex) ⇒ throw new IOException(ex) }
       if (downstreamStatus.get() == Canceled) {
         isPublisherAlive = false
         throw publisherClosedException
       }
```
Comment (johanandren) [inline akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala]: Existing logic, but, is it really worth saving four lines of code at the cost of allocating a lambda on each `sendData` call? (the send param) I think that it could be expressed imperatively and be reused instead, something like 
```
throwIfCannotSend()
doStuffBecauseCanSend() ...
```

File: akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala [hunk 5]
```diff
@@ -172,29 +108,16 @@ private[akka] class OutputStreamAdapter(
   private[this] def sendData(data: ByteString): Unit =
     send(() ⇒ {
       try {
-        dataQueue.put(data)
+        // FIXME take into account writeTimeout here.
+        unfulfilledDemand.acquire()
+        sendToStage(Send(data))
       } catch { case NonFatal(ex) ⇒ throw new IOException(ex) }
       if (downstreamStatus.get() == Canceled) {
```
Comment (johanandren) [inline akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala]: Shouldn't this check if the stage is cancelled be before sending? with this logic the element could potentially be accepted and sent to the stage successfully but still throw here.

What about using the async invokeWithFeedback so we get a failure on submitting instead? That could also allow us to block here until we know the element was accepted into the buffer of the stage.

File: akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala [hunk 6]
```diff
@@ -41,119 +39,57 @@ final private[stream] class OutputStreamSourceStage(writeTimeout: FiniteDuration
...
+      private val upstreamCallback: AsyncCallback[AdapterToStageMessage] =
         getAsyncCallback(onAsyncMessage)
 
-      def wakeUp(msg: AdapterToStageMessage): Future[Unit] = {
-        val p = Promise[Unit]()
-        upstreamCallback.invoke((msg, p))
-        p.future
-      }
+      def wakeUp(msg: AdapterToStageMessage): Unit =
+        upstreamCallback.invoke(msg)
```
Comment (johanandren) [inline akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala]: That's not waking anything up anymore though? Maybe just skip this and do ETA expansion when we pass it to the adapter?

File: akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala [hunk 7]
```diff
@@ -41,119 +39,57 @@ final private[stream] class OutputStreamSourceStage(writeTimeout: FiniteDuration
...
 
-      private def onAsyncMessage(event: (AdapterToStageMessage, Promise[Unit])): Unit =
-        event._1 match {
-          case Flush ⇒
-            flush = Some(event._2)
-            sendResponseIfNeed()
+      private def onAsyncMessage(event: AdapterToStageMessage): Unit = {
+        event match {
+          case Send(data) ⇒
+            emit(out, data)
```
Comment (johanandren) [inline akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala]: Wait wat, how do we know we can just emit here?

File: akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala [hunk 8]
```diff
@@ -41,119 +39,57 @@ final private[stream] class OutputStreamSourceStage(writeTimeout: FiniteDuration
 
     require(maxBuffer > 0, "Buffer size must be greater than 0")
 
-    val dataQueue = new LinkedBlockingQueue[ByteString](maxBuffer)
+    // Semaphore counting the number of elements we are ready to accept,
+    // which is the demand plus the size of the buffer.
+    val semaphore = new Semaphore(maxBuffer, /* fair =*/ true)
```
Comment (johanandren) [inline akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala]: What buffer?

**Review by johanandren — COMMENTED** [review]
Added a bunch of question marks ;)

File: akka-stream-tests/src/test/scala/akka/stream/io/OutputStreamSourceSpec.scala (hunk 2 above)
Comment (raboof) [reply akka-stream-tests/src/test/scala/akka/stream/io/OutputStreamSourceSpec.scala]: This test failed pretty reliability after 2-5 iterations of the loop

File: akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala (hunk 8 above)
Comment (raboof) [reply akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala]: we accept `maxBuffer` 'write' actions before blocking and waiting for downstream demand to make more room. The buffer is not very visible because we use `emit` which does the buffering when there is no demand yet.

Comment (johanandren) [reply akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala]: Ah, I see. push vs emit.

File: akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala (hunk 5 above)
Comment (johanandren) [reply akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala]: I think that would mean we could skip the atomic

File: akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala (hunk 7 above)
Comment (raboof) [reply akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala]: if I understand correctly, unlike `push`, `emit` doesn't need there to be demand first, and will 'buffer' messages by 'stacking' OutHandlers https://doc.akka.io/docs/akka/current/stream/stream-customize.html

Of course we want to avoid unbounded growth of the number of elements buffered in `emit`, but that's what the semaphore takes care of: it makes sure there are a maximum of `maxBuffer` `Send` messages accepted beyond what there's demand for.

File: akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala (hunk 3 above)
Comment (raboof) [reply akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala]: It is, I hadn't noticed `tryAcquire` there :smile:

File: akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala (hunk 7 above)
Comment (johanandren) [reply akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala]: Yeah, we just use it seldom enough internally that I had forgotten about the semantics

File: akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala (hunk 5 above)
Comment (raboof) [reply akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala]: Great idea, that cleans up very nicely

File: akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala (hunk 4 above)
Comment (raboof) [reply akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala]: This can even evaporate entirely with invokeWithFeedback

File: akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala (hunk 8 above)
Comment (johanandren) [reply akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala]: Maybe mention that in the comment, just if there is some other moron like me who doesn't get it reading the sources.

**Review by johanandren — COMMENTED** [review]
Wow, that is crazy how much simplified it got. Fingers crossed it also works  ;)

File: akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala [hunk 9]
```diff
@@ -41,159 +41,59 @@ final private[stream] class OutputStreamSourceStage(writeTimeout: FiniteDuration
...
-      if (downstreamStatus.get() == Canceled) {
-        isPublisherAlive = false
-        throw publisherClosedException
-      }
-    })
+    val invocationResult =
+      sendToStage.invokeWithFeedback(Send(data))
+        .recoverWith {
+          case NonFatal(e) ⇒ throw new IOException(e)
+        }(ExecutionContexts.sameThreadExecutionContext)
```
Comment (johanandren) [inline akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala]: Same thread must not be used when an exception is thrown if I don't misremember

Comment (johanandren) [reply akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala]: But since we block on it below we can just try-catch there instead?

Comment (raboof) [reply akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala]: Nicer still! :+1:

**Review by johanandren — APPROVED** [review]
LGTM, but I'll benchmark it a bit and post numbers here (I think this is used quite a lot by our users).

**Comment by johanandren** [comment]
Results:

```
akka-bench-jmh/jmh:run -f 1 -wi 10 -i 10 .*AsOutputStreamBenchmark.*
[info] Benchmark                               Mode  Cnt      Score     Error   Units
[info] AsOutputStreamBenchmark.consumeWrites  thrpt   10  91601.483 ± 214.890  ops/ms (this PR)
[info] AsOutputStreamBenchmark.consumeWrites  thrpt   10  91878.603 ± 494.709  ops/ms (master)
```

Bench: 
```
object AsOutputStreamBenchmark {
  final val WritesPerBench = 10000
}
@State(Scope.Benchmark)
@OutputTimeUnit(TimeUnit.MILLISECONDS)
@BenchmarkMode(Array(Mode.Throughput))
class AsOutputStreamBenchmark {
  import AsOutputStreamBenchmark.WritesPerBench
  implicit val system = ActorSystem("AsOutputStreamBenchmark")
  implicit val materializer = ActorMaterializer()

  private val bytes: Array[Byte] = Array.emptyByteArray

  private var os: OutputStream = _
  private var done: Future[Done] = _

  @Benchmark
  @OperationsPerInvocation(WritesPerBench)
  def consumeWrites(): Unit = {
    val (os, done) = StreamConverters.asOutputStream()
      .toMat(Sink.ignore)(Keep.both)
      .run()
    new Thread(new Runnable {
      def run(): Unit = {
        var counter = 0
        while (counter > WritesPerBench) {
          os.write(bytes)
          counter += 1
        }
        os.close()
      }
    }).start()
    Await.result(done, 30.seconds)
  }

  @TearDown
  def shutdown(): Unit = {
    Await.result(system.terminate(), 5.seconds)
  }

}
```

**Comment by johanandren** [comment]
Could be that bench is rather measuring materialization, but at least it looks the same as master.

File: akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala [hunk 10]
```diff
@@ -206,11 +104,18 @@ private[akka] class OutputStreamAdapter(
   }
 
   @scala.throws(classOf[IOException])
-  override def flush(): Unit = sendMessage(Flush)
+  override def flush(): Unit =
+    // Flushing does nothing: at best we could guarantee that our own buffer
```
Comment (jrudolph) [inline akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala]: :+1:

File: akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala [hunk 11]
```diff
@@ -41,159 +41,57 @@ final private[stream] class OutputStreamSourceStage(writeTimeout: FiniteDuration
...
-          //Publisher considered to be terminated at earliest convenience to minimize messages sending back and forth
-          isPublisherAlive = false
-          throw publisherClosedException
-        }
-      } catch {
-        case e: IOException ⇒ throw e
-        case NonFatal(e)    ⇒ throw new IOException(e)
-      })
+    try {
+      Await.result(sendToStage.invokeWithFeedback(Send(data)), writeTimeout)
```
Comment (jrudolph) [inline akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala]: Do you piggy back here on `invokeWithFeedback` for failing if the stage is already closed? Or is it just ignored in that case?

File: akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala [hunk 12]
```diff
@@ -41,159 +41,57 @@ final private[stream] class OutputStreamSourceStage(writeTimeout: FiniteDuration
...
-              dataQueue.take()
-            } catch {
-              case _: InterruptedException ⇒
-                Thread.interrupted()
-                ByteString.empty
-            } finally {
-              blockingThreadRef.compareAndSet(currentThread, null);
-            }
-          }.onComplete(downstreamCallback.invoke)
+          semaphore.release()
```
Comment (jrudolph) [inline akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala]: Does that really work correctly? `onPull` will only be called if the `emit` queue is empty, so it seems like the semaphore would only switch between 0 and 1. Or do I miss something?

File: akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala [hunk 13]
```diff
@@ -6,23 +6,23 @@ package akka.stream.impl.io
...
 import scala.util.control.NonFatal
-import scala.util.{ Failure, Success, Try }
 
 private[stream] object OutputStreamSourceStage {
   sealed trait AdapterToStageMessage
-  case object Flush extends AdapterToStageMessage
+  case class Send(data: ByteString) extends AdapterToStageMessage
   case object Close extends AdapterToStageMessage
 
   sealed trait DownstreamStatus
```
Comment (jrudolph) [inline akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala]: Is DownstreamStatus still used?

**Review by jrudolph — COMMENTED** [review]
Wow, great simplification. It seems almost too simple (see comments below) ;)

It seems there could be further simplifications:

 * remove the possibility to configure the `InputBuffer` size at all (at least in this way)
 * just buffer a fixed amount of *bytes* in a single ByteString and block if new data doesn't fit in (but how to configure the buffer?)

File: akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala (hunk 13 above)
Comment (helena) [reply akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala]: Yes, see below in `val downstreamStatus = new AtomicReference[DownstreamStatus](Ok)`

File: akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala (hunk 12 above)
Comment (raboof) [reply akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala]: Excellent point!

**Comment by raboof** [comment]
new/old:
```
[info] Benchmark                                        Mode  Cnt      Score     Error   Units
[info] OutputStreamSourceStageBenchmark.consumeWrites  thrpt   10  48661.553 ± 304.240  ops/ms
[info] OutputStreamSourceStageBenchmark.consumeWrites  thrpt   10  47021.572 ± 354.983  ops/ms
```

**Comment by jrudolph** [comment]
PLS BUILD

**Review by jrudolph — APPROVED** [review]
LGTM
