### PR TITLE
FanoutPublisherSink leaking actors on upstream failure 

### LINKED ISSUE #25634: FanoutPublisherSink leaks actors on upstream failure
The implementation for `FanoutPublisherSink` doesn't terminate the actor `FanoutProcessorImpl` on upstream failure, leaving any elements buffered in `FanoutOutputs` strongly reachable from the `StreamSupervisor` instance.

I've tested this against the latest v2.5.16.

At the bottom of [`FanoutputProcessorImpl.fail`](https://github.com/akka/akka/blob/v2.5.16/akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala#L129), a comment indicates that the actor will be stopped after flushing... but if you take a look at [`FanoutOutput.error`](https://github.com/akka/akka/blob/v2.5.16/akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala#L50) you can see that the failure flow never calls `afterShutdown`, which is how the actor is terminated by normal completion.

Example to reproduce:
```scala
// needs to be in akka package for access to StreamSupervisor
package akka.stream

import java.util.concurrent.CountDownLatch

import akka.NotUsed
import akka.actor._
import akka.stream.scaladsl._
import akka.stream.impl.StreamSupervisor

private case object Go
class MyActor(latch: CountDownLatch, numRepeat: Int, sourceF: () => Source[String, NotUsed]) extends Actor {
  implicit lazy val mat = ActorMaterializer()

  private var count = 0

  override def preStart(): Unit = self ! Go
  override def postStop(): Unit = latch.countDown()
  override def receive: Receive = {
    case Go if count < numRepeat =>
      count += 1
      val (_, source) = sourceF().preMaterialize()
      source.runForeach(_ => ()).onComplete(_ => self ! Go)(context.dispatcher)
    case Go =>
      mat.supervisor ! StreamSupervisor.GetChildren
    case StreamSupervisor.Children(xs) =>
      // this should report 0
      println("size=" + xs.size)
      context.stop(self)
  }
}

object ActorLeakTest extends App {
  val system = ActorSystem()
  val bigString = scala.util.Random.nextString(1000 * 1000) * 50

  locally {
    println("ABORT")
    val latch = new CountDownLatch(1)
    system.actorOf(Props(new MyActor(latch, 1000,
      () =>
        // if you uncomment this line, then there will be 1000x 50MB strings on the heap at the end of the test
        //Source.single((bigString + "0").dropRight(1)) ++
        Source.failed(new RuntimeException()))))
    latch.await()
  }

  locally {
    println("SHUTDOWN")
    val latch = new CountDownLatch(1)
    system.actorOf(Props(new MyActor(latch, 1000, () => Source.single("hello"))))
    latch.await()
  }

  system.terminate()
}
```

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #25634

### CODE REVIEW

File: akka-stream-tests/src/test/scala/akka/stream/impl/FanoutProcessorSpec.scala [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+import akka.stream.testkit.StreamSpec
+import akka.stream.testkit.Utils.TE
+import akka.testkit.TestProbe
+
+class FanoutProcessorSpec extends StreamSpec {
+
+  "The FanoutProcessor" must {
+
+    // #25634
+    "not leak running actors on failed upstream without subscription" in {
```
Comment (patriknw) [inline akka-stream-tests/src/test/scala/akka/stream/impl/FanoutProcessorSpec.scala]: would `assertAllStagesStopped` catch this issue? then perhaps add that also?

File: akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala [hunk 2]
```diff
@@ -126,7 +126,7 @@ import org.reactivestreams.Subscriber
       log.debug("fail due to: {}", e.getMessage)
     primaryInputs.cancel()
     primaryOutputs.error(e)
-    // Stopping will happen after flush
+    context.stop(self)
   }
```
Comment (patriknw) [inline akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala]: now this is identical to super.fail in ActorProcessorImpl

Do we know why was it overridden in the first place?

File: akka-stream-tests/src/test/scala/akka/stream/impl/FanoutProcessorSpec.scala [hunk 3]
```diff
@@ -0,0 +1,68 @@
...
+      val boom = TE("boom")
+      promise.failure(boom)
+
+      probe.expectTerminated(publisherRef)
+      completed1.failed.futureValue should ===(boom)
+      completed2.failed.futureValue should ===(boom)
+    }
+
+  }
+
```
Comment (patriknw) [inline akka-stream-tests/src/test/scala/akka/stream/impl/FanoutProcessorSpec.scala]: add test for upstream completed successfully also?

File: akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala (hunk 2 above)
Comment (patriknw) [reply akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala]: why doesn't the the `def afterShutdown(): Unit = afterFlush()` work?

Comment (viktorklang) [reply akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala]: Perhaps @johanandren missed the comments. :)

File: akka-stream-tests/src/test/scala/akka/stream/impl/FanoutProcessorSpec.scala (hunk 1 above)
Comment (johanandren) [reply akka-stream-tests/src/test/scala/akka/stream/impl/FanoutProcessorSpec.scala]: It might, as the publisher sink actor is actually spawned as a child to the stream supervisor.

File: akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala (hunk 2 above)
Comment (johanandren) [reply akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala]: `afterFlush()` is a local method only called from `FanoutOutputs.afterShutdown` which in turn is only called from `FanoutOutputs.shutdown` and that is only invoked when downstream completes, or when the last subscriber unregisters, in the scenario of no registered subscribers-yet none of those two happens. 

I first thought that it was only for the no-registered downstreams scenario, but the added tests shows that it does in fact never work as implied by the comment that was here, even with subscribers. I'm not sure how is supposed to work - debugging I can see that no further callbacks whatsoever happens after that `failure`. Explicitly completing seems to work and doesn't not break the tck or any other tests, so I'm hoping this is fine.

File: akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala [hunk 4]
```diff
@@ -121,14 +121,6 @@ import org.reactivestreams.Subscriber
     primaryOutputs.enqueueOutputElement(primaryInputs.dequeueInputElement())
   }
 
-  override def fail(e: Throwable): Unit = {
-    if (settings.debugLogging)
-      log.debug("fail due to: {}", e.getMessage)
-    primaryInputs.cancel()
-    primaryOutputs.error(e)
-    // Stopping will happen after flush
-  }
```
Comment (patriknw) [inline akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala]: always scary to change/remove something that someone else has consciously added and even commented, but obviously there is a problem and no other test fails

**Review by patriknw — APPROVED** [review]
LGTM, let's move on

File: akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala (hunk 4 above)
Comment (johanandren) [reply akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala]: Yeah, I wonder if it was true at some point but other things changed around it perhaps. Or some assumption was wrong.

Comment (edwinchoi) [reply akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala]: With all due respect, I’m a bit surprised at the questions being raised here. If you take the comment at face value, you can easily disprove the claim. If it did happen to be that the behavior was changed due to an unintended consequence, the idea that the corner case would not have been documented seems flawed, unless you assume the second author was less diligent than the first.

For me, this issue caused the process to run out of memory in a non obvious and way, with no workaround without a redesign. While I can appreciate the desire to be attentive to risks that can lead to unexpected regressions, but arbitrary risk aversion has costs. I think you guys created a great product with easy to grasp abstracions that clearly show a respect for the user experience, and I appreciate the thought and consideration you and your team put into it.

My issue is though that by investing a little more time in learning rxjava2 or monix, there are far less surprises.

**Review by chbatey — APPROVED** [review]
LGTM
