### PR TITLE
Wip 2.0 fixes rk

### LINKED ISSUE #19235: Document fusing

### PR DESCRIPTION
**Pull request by rkuhn**
fixes #19235 #19267 #19261

### CODE REVIEW

**Comment by rkuhn** [comment]
also includes rebase of #19166 (/cc @viktorklang)

**Comment by drewhk** [comment]
`.tif`??

**Comment by rkuhn** [comment]
Yes, I drew it with SketchBook.

File: akka-stream-tests/src/test/java/akka/stream/javadsl/BidiFlowTest.java [hunk 1]
```diff
@@ -272,4 +272,10 @@ public Integer apply(String arg) {
     Arrays.sort(rr);
     assertArrayEquals(new Long[] { 3L, 12L }, rr);
   }
+  
+  public void mustSuitablyOverrideAttributeHandlingMethods() {
+    @SuppressWarnings("unused")
+    final BidiFlow<Integer, Long, ByteString, String, BoxedUnit> b =
+        bidi.withAttributes(Attributes.name("")).addAttributes(Attributes.asyncBoundary()).named("");
```
Comment (drewhk) [inline akka-stream-tests/src/test/java/akka/stream/javadsl/BidiFlowTest.java]: this does not test the suitably override part, or what do I miss?

File: akka-stream-tests/src/test/scala/akka/stream/FusingSpec.scala [hunk 2]
```diff
@@ -124,6 +124,25 @@ class FusingSpec extends AkkaSpec with ScalaFutures with ConversionCheckedTriple
...
+      Source(0 to 9)
+        .map(x ⇒ { testActor ! ref; x })
+        .flatMapMerge(5, i ⇒ Source.single(i).viaAsync(flow))
+        .grouped(1000)
+        .runWith(Sink.head)
+        .futureValue
+        .sorted should ===(0 to 9)
+      val refs = receiveN(20)
+      withClue(s"refs=\n${refs.mkString("\n")}") {
+        refs.toSet.size should ===(11)
```
Comment (drewhk) [inline akka-stream-tests/src/test/scala/akka/stream/FusingSpec.scala]: maybe comment why 11

Comment (drewhk) [inline akka-stream-tests/src/test/scala/akka/stream/FusingSpec.scala]: (10 substreams + 1 main)

File: akka-stream-tests/src/test/java/akka/stream/javadsl/BidiFlowTest.java (hunk 1 above)
Comment (rkuhn) [inline akka-stream-tests/src/test/java/akka/stream/javadsl/BidiFlowTest.java]: Without the overrides the returned type would be a `Graph[BidiShape[...], ...]` instead of a BidiFlow.

File: akka-stream/src/main/scala/akka/stream/javadsl/BidiFlow.scala [hunk 3]
```diff
@@ -192,6 +192,28 @@ final class BidiFlow[-I1, +O1, -I2, +O2, +Mat](delegate: scaladsl.BidiFlow[I1, O
...
   override def withAttributes(attr: Attributes): BidiFlow[I1, O1, I2, O2, Mat] =
     new BidiFlow(delegate.withAttributes(attr))
+
+  /**
+   * Add the given attributes to this Source. Further calls to `withAttributes`
+   * will not remove these attributes. Note that this
+   * operation has no effect on an empty Flow (because the attributes apply
+   * only to the contained processing stages).
+   */
+  override def addAttributes(attr: Attributes): BidiFlow[I1, O1, I2, O2, Mat] =
```
Comment (drewhk) [inline akka-stream/src/main/scala/akka/stream/javadsl/BidiFlow.scala]: +1

File: akka-docs-dev/rst/java/stream-flows-and-basics.rst [hunk 4]
```diff
@@ -220,8 +225,62 @@ which will be running on the thread pools they have been configured to run on -
...
+  Without fusing (i.e. up to version 2.0-M2) each stream processing stage had an implicit input buffer
+  that holds a few elements for efficiency reasons. If your flow graphs contain cycles then these buffers
+  may have been crucial in order to avoid deadlocks. With fusing these implicit buffers are no longer
+  there, data elements are passed without buffering between fused stages. In those cases where buffering
+  is needed in order to allow the stream to run at all, you will have to insert explicit buffers with the
+  ``.buffer()`` combinator—typically a buffer of size 2 is enough to allow a feedback loop to function.
+
+The new fusing behavior can be disabled by setting the configuration parameter ``akka.stream.materializer.auto-fusing=off``.
+In that case you can still manually fuse those graphs which shall run on less Actors. With the exception of the
+:class:`SslTlsStage` and the ``groupB`` operator all built-in processing stages can be fused.
```
Comment (drewhk) [inline akka-docs-dev/rst/java/stream-flows-and-basics.rst]: groupBy

File: akka-stream-tests/src/test/java/akka/stream/javadsl/BidiFlowTest.java (hunk 1 above)
Comment (drewhk) [inline akka-stream-tests/src/test/java/akka/stream/javadsl/BidiFlowTest.java]: ok, got it

**Comment by drewhk** [comment]
LGTM. A bit terse, but we will improve this part.

**Comment by rkuhn** [comment]
Yes, this is a band-aid (I’m on vacation).

File: akka-stream-tests/src/test/scala/akka/stream/FusingSpec.scala (hunk 2 above)
Comment (rkuhn) [inline akka-stream-tests/src/test/scala/akka/stream/FusingSpec.scala]: done

File: akka-docs-dev/rst/java/stream-flows-and-basics.rst (hunk 4 above)
Comment (rkuhn) [inline akka-docs-dev/rst/java/stream-flows-and-basics.rst]: thanks

**Comment by rkuhn** [comment]
@ktoso merge at will (after validation)

**Comment by ktoso** [comment]
LGTM, thanks a lot @rkuhn
