### PR TITLE
!str #15089 add flatMapMerge

### LINKED ISSUE #15089: add flattening for streams: merge
Merge elements from a configurable maximum number of simultaneously open substreams, using a configurable merge strategy (see #15079). Fail as soon as a substream fails.

### PR DESCRIPTION
**Pull request by rkuhn**
fixes #15089

### CODE REVIEW

File: akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowFlattenMergeSpec.scala [hunk 1]
```diff
@@ -0,0 +1,129 @@
...
+import org.scalactic.ConversionCheckedTripleEquals
+import akka.stream.testkit.TestPublisher
+import org.scalatest.exceptions.TestFailedException
+import akka.stream.testkit.scaladsl.TestSink
+
+class FlowFlattenMergeSpec extends AkkaSpec with ScalaFutures with ConversionCheckedTripleEquals {
+  implicit val mat = ActorMaterializer()
+  import system.dispatcher
+
+  def src(i: Int) = Source((10 * i) until (10 * i + 10))
```
Comment (drewhk) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowFlattenMergeSpec.scala]: i would remove the multiplication. `Source(List(src(0), src(10), src(20), src(30)))` is easier for me to mentally relate to the actual ranges of 10.

File: akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowFlattenMergeSpec.scala [hunk 2]
```diff
@@ -0,0 +1,129 @@
...
+  def blocked = Source(Promise[Int].future)
```
Comment (drewhk) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowFlattenMergeSpec.scala]: you can use Source.maybe

File: akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowFlattenMergeSpec.scala [hunk 3]
```diff
@@ -0,0 +1,129 @@
...
+      val sink = Source(List(Source(p1), Source(p2)))
+        .flatMapMerge(5, identity)
+        .runWith(TestSink.probe)
+      sink.request(1)
+      p1.expectRequest()
+      p2.expectRequest()
+      sink.cancel()
+      p1.expectCancellation()
+      p2.expectCancellation()
+    }
```
Comment (ktoso) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowFlattenMergeSpec.scala]: maybe add a test to see make sure `flatMapMerge(5, throw Boom)` is handled correctly?

File: akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala [hunk 4]
```diff
@@ -0,0 +1,121 @@
...
+
+  override def createLogic(attr: Attributes) = new GraphStageLogic(shape) {
+
+    var sources = Vector.empty[LocalSource[T]]
+    var haveData = 0
+
+    val readyFilter = (src: LocalSource[T]) ⇒ src.elem != null
+    def pushOut(): Unit = {
+      val idx = ThreadLocalRandom.current.nextInt(haveData)
+      val src = sources.iterator.filter(readyFilter).drop(idx).next()
```
Comment (drewhk) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala]: hm. This is one option, another is to have a queue of ready sources.

File: akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowFlattenMergeSpec.scala (hunk 1 above)
Comment (rkuhn) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowFlattenMergeSpec.scala]: okay

File: akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowFlattenMergeSpec.scala (hunk 2 above)
Comment (rkuhn) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowFlattenMergeSpec.scala]: yeah, but it doesn’t really make a difference

File: akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowFlattenMergeSpec.scala (hunk 3 above)
Comment (rkuhn) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowFlattenMergeSpec.scala]: good point

File: akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala (hunk 4 above)
Comment (rkuhn) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala]: So, do you have an opinion on which one it should be?

Comment (rkuhn) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala]: Hmm, trying out a fixed-size queue triggered the thought that we might want to gracefully deal with `breadth == Int.MaxValue`, which means not allocating an 8GB or 16GB array. OTOH dropping from that iterator also becomes O(n), so a queue is better. But it needs to be dynamic, so I’m implementing that now.

**Comment by rkuhn** [comment]
it is ready now

File: akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala [hunk 5]
```diff
@@ -0,0 +1,162 @@
...
+import java.{ util ⇒ ju }
+
+class FlattenMerge[T, M](breadth: Int) extends GraphStage[FlowShape[Source[T, M], T]] {
+  private val in = Inlet[Source[T, M]]("flatten.in")
+  private val out = Outlet[T]("flatten.out")
+  override val shape = FlowShape(in, out)
+
+  override def createLogic(attr: Attributes) = new GraphStageLogic(shape) {
+
+    var sources = Set.empty[LocalSource[T]]
```
Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala]: Do not care if it is a TreeSet or HashSet? (also: LocalSource doesn't implement equals or hashCode so I assume you want identity based equality?)

File: akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala [hunk 6]
```diff
@@ -0,0 +1,162 @@
...
+    def activeSources = sources.size
+
+    private trait Queue {
```
Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala]: Put these in companion object?

File: akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala [hunk 7]
```diff
@@ -0,0 +1,162 @@
...
+          tail += 1
+        }
+      def dequeue(): LocalSource[T] = {
+        val ret = queue(head & Mask)
+        head += 1
+        ret
+      }
+    }
+
+    private class DynamicQueue(queue: ju.Queue[LocalSource[T]]) extends Queue {
```
Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala]: May as well extend ju.LinkedList to avoid the indirection (and It's only used in one place anyway)

File: akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala [hunk 8]
```diff
@@ -0,0 +1,162 @@
...
+import akka.stream.scaladsl._
+import akka.stream.actor.ActorSubscriberMessage
+import akka.stream.actor.ActorSubscriberMessage._
+import akka.stream.actor.ActorPublisherMessage
+import akka.stream.actor.ActorPublisherMessage._
+import scala.concurrent.forkjoin.ThreadLocalRandom
+
+import java.{ util ⇒ ju }
+
+class FlattenMerge[T, M](breadth: Int) extends GraphStage[FlowShape[Source[T, M], T]] {
```
Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala]: How much of this implementation could be "reused" for `interleave`?

Comment (rkuhn) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala]: Do we really want a dynamic interleave? I thought that was only for static topologies …

File: akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala (hunk 5 above)
Comment (rkuhn) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala]: yes, identity it is

File: akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala (hunk 6 above)
Comment (rkuhn) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala]: nope, needs to set a private field in the logic

File: akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala (hunk 7 above)
Comment (rkuhn) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala]: good point

File: akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala (hunk 8 above)
Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala]: True, I don't have a good use case but it would indeed be symmetric to have one.

File: akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala [hunk 9]
```diff
@@ -0,0 +1,173 @@
...
+    var sources = Set.empty[LocalSource[T]]
+    def activeSources = sources.size
+
+    private trait Queue {
+      def hasData: Boolean
+      def enqueue(src: LocalSource[T]): Unit
+      def dequeue(): LocalSource[T]
+    }
+
+    private class FixedQueue extends Queue {
```
Comment (drewhk) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala]: Nice approach. I had a similar idea about having a circular linked list of arrays as a reusable dynamic, but cache friendly queue. Not for this ticket though, but it seems to be useful in many places to be investigated further.

**Comment by drewhk** [comment]
LGTM

File: akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala [hunk 10]
```diff
@@ -1009,10 +1016,23 @@ trait FlowOps[+Out, +Mat] {
...
+   *
+   * '''Backpressures when''' downstream backpressures
+   *
+   * '''Completes when''' upstream completes and all consumed substreams complete
+   *
+   * '''Cancels when''' downstream cancels
    */
-  def flatMapConcat[T](f: Out ⇒ Source[T, _]): Repr[T, Mat] =
-    deprecatedAndThen(ConcatAll(f.asInstanceOf[Any ⇒ Source[Any, _]]))
+  def flatMapMerge[T, M](breadth: Int, f: Out ⇒ Source[T, M]): Repr[T, Mat] = map(f).via(new FlattenMerge[T, M](breadth))
```
Comment (ktoso) [inline akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala]: I guess you have a reason - but why don't we provide identity as a default for `f`?

**Comment by ktoso** [comment]
LGTM, great :)

File: akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala (hunk 10 above)
Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala]: Then you need to add an implicit evidence that Out <:< T

Comment (ktoso) [inline akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala]: Oh I see, thanks!
