### PR TITLE
Fix for UdpConnected actor going away on PortUnreachableException 

### LINKED ISSUE #26903: UDP Connected actor stops when UDP server is unavailable.
The Akka documentation allows for a simple [client / server demo](https://doc.akka.io/docs/akka/current/io-udp.html). If I build two applications accordingly with 'connected UDP' on the client size,  and let them talk over a the internal  network, for example the localhost (but an IP number reacts the same, dns is not used in this case), this works as long as the server remains available. If that is manually stopped, and just one packet is send from the client side to the now absent server, the [UdpConnection Actor](https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/io/UdpConnection.scala#L23) that manages the transmission dies without sending the expected ```UdpConnected.Disconnected``` message. If i activate a firewall in between (so that packets are silently dropped) the actor keeps running. 

Would the following not be better: if the underlying transport layer is aware of a problem to send a ```UdpConnected.Unavailable``` message and keep running? UPD should be 'send and forget' as much as possible and leave problem solving to the layers above. 

Even if a ```UdpConnected.Disconnected``` was send, that behaviour is probably not intended too. 
I switched on logging on UDP level and got this after trying to send a packet:

```
[DEBUG] [05/10/2019 10:47:57.128] [base-akka.actor.default-dispatcher-13] [akka://base/system/IO-UDP-CONN/selectors/$a/4] null
[DEBUG] [05/10/2019 10:47:57.130] [base-akka.actor.default-dispatcher-10] [akka://base/system/IO-UDP-CONN/selectors/$a/4] Closing DatagramChannel after being stopped
 ...
[INFO]  [05/10/2019 10:48:01.543] [base-akka.actor.default-dispatcher-4] [akka://base/system/IO-UDP-CONN/selectors/$a/4] Message [akka.io.UdpConnected$Send] 
        from Actor[akka://base/user/$c/Connector:system:0:1/topicWorker:error#2117057478] to Actor[akka://base/system/IO-UDP-CONN/selectors/$a/4#-1205848350] 
         was not delivered. [1] dead letters encountered. If this is not an expected behavior, then [Actor[akka://base/system/IO-UDP-CONN/selectors/$a/4#-1205848350]] 
         may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 
         'akka.log-dead-letters-during-shutdown'.
```
The logging of just a `null` is suspicious, i could not find the source of that message. The next log message stems from the overridden ```postStop()``` in de [```private class UdpSender```](https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/io/UdpConnection.scala#L148)

The [instruction](https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/io/WithUdpSend.scala#L80) in the code that handles the actual writing:
```Scala
  val writtenBytes = channel.send(buffer, pendingSend.target) 
```

probably raises some kind of [IO exception](https://docs.oracle.com/javase/8/docs/api/java/nio/channels/DatagramChannel.html#write-java.nio.ByteBuffer:A-) which is not (properly) handled.  

I would appreciate comments, this behaviour *may* qualify as a bug.

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #26903

### CODE REVIEW

File: akka-actor-tests/src/test/scala/akka/io/UdpConnectedIntegrationSpec.scala [hunk 1]
```diff
@@ -94,6 +95,41 @@ class UdpConnectedIntegrationSpec extends AkkaSpec("""
...
+
+      expectMsg(Udp.Received(data1, clientAddress))
+
+      server ! Udp.Unbind
+      expectMsg(Udp.Unbound)
+      Thread.sleep(1000) // if it stops that takes a bit of time, give it that time
+
+      // bug was that the commander would fail on next read/write
+      clientCommander ! UdpConnected.Send(ByteString("data to trigger fail"), 1)
+      expectMsg(1)
```
Comment (raboof) [inline akka-actor-tests/src/test/scala/akka/io/UdpConnectedIntegrationSpec.scala]: Kind of weird to have those acks in UDP... but OK I guess.

File: akka-actor-tests/src/test/scala/akka/io/UdpConnectedIntegrationSpec.scala [hunk 2]
```diff
@@ -94,6 +95,41 @@ class UdpConnectedIntegrationSpec extends AkkaSpec("""
...
+      // and at this time the commander would have stopped
+      clientCommander ! UdpConnected.Send(ByteString("data to trigger fail"), 2)
+      expectMsg(2)
+
+      // when a new server appears at the same port it it should be able to receive
+      val serverIncarnation2 = bindUdp(serverAddress, testActor)
+      val dataToNewIncarnation = ByteString("Data to new incarnation")
+      clientCommander ! UdpConnected.Send(dataToNewIncarnation, 3)
+      expectMsg(3)
+      expectMsg(Udp.Received(dataToNewIncarnation, clientAddress))
```
Comment (raboof) [inline akka-actor-tests/src/test/scala/akka/io/UdpConnectedIntegrationSpec.scala]: :+1:

File: akka-actor/src/main/scala/akka/io/UdpConnection.scala [hunk 3]
```diff
@@ -120,7 +120,10 @@ private[io] class UdpConnection(
     }
     val buffer = bufferPool.acquire()
     try innerRead(BatchReceiveLimit, buffer)
-    finally {
+    catch {
+      case _: PortUnreachableException =>
+        if (TraceLogging) log.debug("Ignoring PortUnreachableException in doRead")
```
Comment (raboof) [inline akka-actor/src/main/scala/akka/io/UdpConnection.scala]: would be kind of nice to log this at INFO or even WARN once, but indeed it would be excessive to send it for each read and adding logic/state here would probably not be worth it. so :+1:

**Review by raboof — APPROVED** [review]

File: akka-actor-tests/src/test/scala/akka/io/UdpConnectedIntegrationSpec.scala (hunk 1 above)
Comment (johanandren) [reply akka-actor-tests/src/test/scala/akka/io/UdpConnectedIntegrationSpec.scala]: It's only an ack that the udp connection actor enqueued the byte string to the os buffers.

File: akka-actor/src/main/scala/akka/io/UdpConnection.scala (hunk 3 above)
Comment (johanandren) [reply akka-actor/src/main/scala/akka/io/UdpConnection.scala]: I think that it can be debug/trace as it is the expected behavior with UDP

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by patriknw** [comment]
Do we consider it important enough to backport?

**Comment by johanandren** [comment]
I don't think so. Let's ask the reporter. @devlaam is this something you have had problems with and need in 2.5 or only something you noticed while exploring the samples?

**Comment by devlaam** [comment]
This was indeed something i ran into when developing a service for our IoT platform. My reference to the examples was just to make it easy to reproduce. Currently we are on Akka 2.5.13. As long as Agents are supported we are able to upgrade. If 2.6 does not support Agents (it is deprecated already in 2.5), i would be very pleased if this patch is backported, for we do not have a realistic alternative for Agents just yet.

**Comment by johanandren** [comment]
We'll back port it then.

**Comment by devlaam** [comment]
Thanks guys, for fixing this so quickly! Today i tested it via the snapshot and it works nicely. Well done!
