### PR TITLE
#23484 Guard against double pull

### LINKED ISSUE #23484: Failed: akka.stream.scaladsl.RestartSpec
https://jenkins.akka.io:8498/job/akka-nightly/4657/testReport/junit/akka.stream.scaladsl/RestartSpec/A_restart_with_backoff_flow_should_restart_on_cancellation/

```
java.lang.AssertionError: Expected OnNext(_), yet no element signaled during 3 seconds
      at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:290)
      at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:281)
      at akka.stream.scaladsl.RestartSpec$$anonfun$3$$anonfun$apply$mcV$sp$14.apply(RestartSpec.scala:362)
      at akka.stream.scaladsl.RestartSpec$$anonfun$3$$anonfun$apply$mcV$sp$14.apply(RestartSpec.scala:351)
```

### PR DESCRIPTION
**Pull request by 2m**
Fixes #23484

Double pull error became visible when I added `.log(...)` after the restart flow in the test setup.

https://github.com/akka/akka/blob/72b32547ba9df9228e5d635791a4f138a99f6675/akka-stream-tests/src/test/scala/akka/stream/scaladsl/RestartSpec.scala#L329

Otherwise errors from upstream are not reported by the `TestSink.probe`. Therefore the error was not immediately obvious from the logs.

### CODE REVIEW

File: akka-stream/src/main/scala/akka/stream/scaladsl/Restart.scala [hunk 1]
```diff
@@ -298,7 +298,9 @@ private abstract class RestartWithBackoffLogic[S <: Shape](
       override def onPull() = if (isAvailable(in)) {
         sourceOut.push(grab(in))
       } else {
-        pull(in)
+        if (!hasBeenPulled(in)) {
```
Comment (patriknw) [inline akka-stream/src/main/scala/akka/stream/scaladsl/Restart.scala]: ok, some misunderstanding of the relation between `isAvailable` and `hasBeenPulled`. Scaladoc mention some invariants, but the opposite of them are probably not true.

**Review by patriknw — APPROVED** [review]
LGTM

**Review by raboof — APPROVED** [review]
Pretty subtle, would be cool to have a reliably-reproducing test case so we're not left wondering if this check is really required here later.
