### PR TITLE
#22246 cluster-sharding PersistentShardCoordinator with remember-entities doesn't recover properly

### LINKED ISSUE #22246: cluster-sharding PersistentShardCoordinator with remember-entities doesn't recover properly
this one appeared as a big problem in sharding with persistence and remember entities.
the problem shortly:
when `State` is persisted (a snapshot is saved) `rememberEntities` value is not included, which I do understand and it's ok. But when the snapshot is loaded `rememberEntities` is not set from settings, that makes messages replay end up with wrong state as some of the message are processed with `rememberEntities` taken into account.
luckily the fix is really simple, I will submit a PR right away.

### PR DESCRIPTION
**Pull request by 412b**
Fixes #22246
when `State` is persisted (a snapshot is saved) `rememberEntities` value is not included, but when the snapshot is loaded `rememberEntities` is not set from settings, that makes messages replay end up with wrong state as some of the message are processed with `rememberEntities` taken into account.

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

File: akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala [hunk 1]
```diff
@@ -782,12 +782,11 @@ class PersistentShardCoordinator(typeName: String, settings: ClusterShardingSett
...
       // thus it will be null.
-      if (st.unallocatedShards == null)
-        state = st.copy(unallocatedShards = Set.empty)
-      else
-        state = st
+      if (state.unallocatedShards == null)
+        state = state.copy(unallocatedShards = Set.empty)
 
     case RecoveryCompleted ⇒
       state = state.withRememberEntities(settings.rememberEntities)
```
Comment (patriknw) [inline akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala]: wouldn't this set it to the right value?

Comment (patriknw) [inline akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala]: ah, I see, it's used when replaying the events after the snapshot

**Review by patriknw — APPROVED** [review]
LGTM

**Review by johanandren — APPROVED** [review]
LGTM
