### PR TITLE
=str #16553: Fix TCP stream shutdown scenarios

### LINKED ISSUE #16653: HTTP Form upload hangs if the server has been port scanned with nc (GNU netcat 0.7.1)
So we now have an issue where if we check for server availability from the outside by using nc, the following curl upload will fail.

This fails on Linux with GNU netcat 0.7.1 and on OS X if you install GNU netcat by doing `brew install netcat`. The default OS X nc command doesn't provoke this behavior.

Reproducer coming shortly.

/cc @sirthias @jrudolph

### PR DESCRIPTION
**Pull request by drewhk**
Properly handle various stream and TCP shutdown scenarios
- Upgraded tests to cover various closing scenarios
- Even upon downstream cancel we pull the events from TCP by sending ResumeReading and draining ignored bytes if needed
- Now also tests if the test connection actor terminates
- workaround for #16552, before we wait on close events in the tests, we send a ResumeReading first
- tests even cancellation after PeerClosed by trying to write (otherwise no ErrorClosed is generated)

Fixes #16653

### CODE REVIEW

File: akka-stream/src/main/scala/akka/stream/impl/io/TcpConnectionStream.scala [hunk 1]
```diff
@@ -86,8 +80,21 @@ private[akka] abstract class TcpStreamActor(val settings: MaterializerSettings)
...
     override def cancel(): Unit = {
-      closed = true
-      pendingElement = null
+      if (!closed) {
+        closed = true
+        pendingElement = null
+        if (tcpOutputs.isClosed && (connection ne null))
+          connection ! Abort
+        else
+          connection ! ResumeReading
```
Comment (patriknw) [inline akka-stream/src/main/scala/akka/stream/impl/io/TcpConnectionStream.scala]: can `connection` be null here?

Comment (drewhk) [inline akka-stream/src/main/scala/akka/stream/impl/io/TcpConnectionStream.scala]: I guess so. The null guard ended up in the wrong place.

**Comment by patriknw** [comment]
LGTM

File: akka-stream-tests/src/test/scala/akka/stream/io/StreamTcpSpec.scala [hunk 2]
```diff
@@ -77,36 +79,177 @@ class StreamTcpSpec extends AkkaSpec with TcpHelper {
...
+      serverConnection.read(5)
+      serverConnection.waitRead() should be(testData)
+
+      // Close client side write
+      tcpWriteProbe.close()
+
+      // Need a write on the server side to detect the close event
       serverConnection.write(testData)
-      tcpReadProbe.subscriberProbe.expectNoMsg(1.second)
+      serverConnection.write(testData)
```
Comment (rkuhn) [inline akka-stream-tests/src/test/scala/akka/stream/io/StreamTcpSpec.scala]: We should document this: if the client cancels reading before completing the writing then a passive server will just hang.

File: akka-stream-tests/src/test/scala/akka/stream/io/StreamTcpSpec.scala [hunk 3]
```diff
@@ -77,36 +79,177 @@ class StreamTcpSpec extends AkkaSpec with TcpHelper {
...
+      val serverConnection = server.waitAccept()
+
+      // Client can still write
+      tcpWriteProbe.write(testData)
       serverConnection.read(5)
+      serverConnection.waitRead() should be(testData)
+
+      // Close client side write
+      tcpWriteProbe.close()
+      serverConnection.expectClosed(PeerClosed)
```
Comment (rkuhn) [inline akka-stream-tests/src/test/scala/akka/stream/io/StreamTcpSpec.scala]: this case is better because the server at least gets some notification

File: akka-stream-tests/src/test/scala/akka/stream/io/StreamTcpSpec.scala (hunk 2 above)
Comment (drewhk) [inline akka-stream-tests/src/test/scala/akka/stream/io/StreamTcpSpec.scala]: Yep, unfortunately I found no way around it. An idle timeout stage will help of course.

**Comment by rkuhn** [comment]
LGTM, great fixes!
