### PR TITLE
Subscription timeouts not working

### LINKED ISSUE #19980: Subscription timeouts not working
These tests need to be added to TimeoutsSpec and the implementation needs to pass them:

``` scala
  "Subscription timeouts" must {

    implicit val materializer = ActorMaterializer(
      ActorMaterializerSettings(system).withSubscriptionTimeoutSettings(
        StreamSubscriptionTimeoutSettings(
          StreamSubscriptionTimeoutTerminationMode.cancel, 100.millis)))

    "be effective for dangling downstream (no fanout)" in Utils.assertAllStagesStopped {
      val upstream = TestPublisher.probe()
      val (sub, pub) = Flow[Int].map(_.toString).runWith(Source.asSubscriber, Sink.asPublisher(false))
      upstream.subscribe(sub)
      upstream.expectCancellation()
    }

    "be effective for dangling downstream (with fanout)" in Utils.assertAllStagesStopped {
      val upstream = TestPublisher.probe()
      val (sub, pub) = Flow[Int].map(_.toString).runWith(Source.asSubscriber, Sink.asPublisher(true))
      upstream.subscribe(sub)
      upstream.expectCancellation()
    }

    "be effective for dangling upstream" in Utils.assertAllStagesStopped {
      val downstream = TestSubscriber.probe[String]()
      val (sub, pub) = Flow[Int].map(_.toString).runWith(Source.asSubscriber, Sink.asPublisher(false))
      pub.subscribe(downstream)
      downstream.ensureSubscription()
      downstream.expectError() shouldBe a[SubscriptionTimeoutException]
    }

    "be effective for dangling Processors" in Utils.assertAllStagesStopped {
      Flow[Int].map(_.toString).runWith(Source.asSubscriber, Sink.asPublisher(false))
    }

  }
```

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #19980 (mostly)

You didn't see this one coming, did you?!

### CODE REVIEW

File: akka-stream-tests/src/test/scala/akka/stream/impl/TimeoutsSpec.scala [hunk 1]
```diff
@@ -356,6 +356,42 @@ class TimeoutsSpec extends StreamSpec {
...
+    "be effective for dangling upstream" in pendingUntilFixed(Utils.assertAllStagesStopped {
+      val downstream = TestSubscriber.probe[String]()
+      val (sub, pub) = Flow[Int].map(_.toString).runWith(Source.asSubscriber, Sink.asPublisher(false))
+      pub.subscribe(downstream)
+      downstream.ensureSubscription()
+      downstream.expectError() shouldBe a[SubscriptionTimeoutException]
+    })
+
+    "be effective for dangling Processors" in Utils.assertAllStagesStopped {
+      Flow[Int].map(_.toString).runWith(Source.asSubscriber, Sink.asPublisher(false))
```
[the remark this answers is not in the document]
Comment (johanandren) [reply akka-stream-tests/src/test/scala/akka/stream/impl/TimeoutsSpec.scala]: Hmmmmmmmm. Doesn't seem to test anything, does it?

[the remark this answers is not in the document]
Comment (johanandren) [reply akka-stream-tests/src/test/scala/akka/stream/impl/TimeoutsSpec.scala]: Ah, I think it fails if the timeout doesn't work because of the `assertAllStagesStopped`. I'll add a comment.

[the remark this answers is not in the document]
Comment (johanandren) [reply akka-stream-tests/src/test/scala/akka/stream/impl/TimeoutsSpec.scala]: Or not, because it actually does provide a subscriber and a publisher....

**Comment by johanandren** [comment]
Unrelated failure.

**Comment by johanandren** [comment]
PLS BUILD

**Review by raboof — APPROVED** [review]
Needs to resolve a conflict in the mima filters, and perhaps good to add that 'internal API' comment&annotation, otherwise seems reasonable

**Comment by johanandren** [comment]
Hmm, how is that still a conflict when I just rebased?

**Comment by johanandren** [comment]
ah, had forgotten to update local master

File: akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala [hunk 2]
```diff
@@ -16,13 +16,16 @@ import org.reactivestreams.Subscriber
     val maxBufferSize: Int,
     val initialBufferSize: Int,
     self: ActorRef,
-    val pump: Pump)
+    val pump: Pump,
+    var subscribed: Boolean = false)
```
Comment (patriknw) [inline akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala]: there is only one implementation of this `FanoutOutputs` so I think we can remove the default param value, but I also think it would be better to remove the parameter and make the `var` private with a public getter.

**Review by patriknw — COMMENTED** [review]
I'm not quite sure why we have been so afraid of approving this? Maybe because that VirtualPublisher is a scary thing with bad track record. Maybe we should merge it after branching so that it can mature for 2.6?

File: akka-stream-tests/src/test/scala/akka/stream/impl/TimeoutsSpec.scala [hunk 3]
```diff
@@ -336,6 +336,37 @@ class TimeoutsSpec extends StreamSpec {
...
+    "be effective for dangling upstream" in pendingUntilFixed(assertAllStagesStopped {
+      val downstream = TestSubscriber.probe[String]()
+      val (sub, pub) = Flow[Int].map(_.toString).runWith(Source.asSubscriber, Sink.asPublisher(false))
+      pub.subscribe(downstream)
+      downstream.ensureSubscription()
+      downstream.expectError() shouldBe a[SubscriptionTimeoutException]
+    })
+
+  }
+
```
Comment (helena) [inline akka-stream-tests/src/test/scala/akka/stream/impl/TimeoutsSpec.scala]: nit: No line?

File: akka-stream/src/main/mima-filters/2.5.21.backwards.excludes [hunk 4]
```diff
@@ -43,3 +43,7 @@ ProblemFilters.exclude[DirectMissingMethodProblem]("akka.stream.impl.ActorRefSou
 ProblemFilters.exclude[IncompatibleMethTypeProblem]("akka.stream.impl.ActorRefSource.this")
 ProblemFilters.exclude[MissingClassProblem]("akka.stream.impl.ActorRefSourceActor$")
 ProblemFilters.exclude[MissingClassProblem]("akka.stream.impl.ActorRefSourceActor")
+
+# #19980 subscription timeouts for streams
+ProblemFilters.exclude[ReversedMissingMethodProblem]("akka.stream.impl.ActorProcessorImpl.subTimeoutHandling")
+ProblemFilters.exclude[DirectMissingMethodProblem]("akka.stream.impl.FanoutOutputs.this")
```
Comment (helena) [inline akka-stream/src/main/mima-filters/2.5.21.backwards.excludes]: Needs a line below

File: akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala [hunk 5]
```diff
@@ -6,7 +6,7 @@ package akka.stream.impl
 
 import akka.actor.{ Actor, ActorRef, Deploy, Props }
 import akka.annotation.{ DoNotInherit, InternalApi }
-import akka.stream.{ ActorMaterializerSettings, Attributes }
+import akka.stream.{ ActorMaterializerSettings, Attributes, StreamSubscriptionTimeoutTerminationMode }
```
Comment (helena) [inline akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala]: Aren't we putting these all on their own lines now, wonder if scalafmt or IntelliJ should have caught that.

File: akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala [hunk 6]
```diff
@@ -130,4 +139,19 @@ import org.reactivestreams.Subscriber
   def afterFlush(): Unit = context.stop(self)
 
   initialPhase(1, running)
+
+  def subTimeoutHandling: Receive = {
+    case ActorProcessorImpl.SubscriptionTimeout ⇒
```
Comment (helena) [inline akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala]:
```suggestion
    case ActorProcessorImpl.SubscriptionTimeout =>
```

File: akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala [hunk 7]
```diff
@@ -130,4 +139,19 @@ import org.reactivestreams.Subscriber
...
+      import StreamSubscriptionTimeoutTerminationMode._
+      if (!primaryOutputs.subscribed) {
+        settings.subscriptionTimeoutSettings.mode match {
+          case CancelTermination ⇒
```
Comment (helena) [inline akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala]: same with this unicode arrow

File: akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala [hunk 8]
```diff
@@ -130,4 +139,19 @@ import org.reactivestreams.Subscriber
...
+            primaryInputs.cancel()
+            context.stop(self)
+          case WarnTermination ⇒
+            context.system.log.warning("Subscription timeout for {}", this)
+          case NoopTermination ⇒ // won't happen
```
Comment (helena) [inline akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala]: and these

File: akka-stream/src/main/scala/akka/stream/impl/Sinks.scala [hunk 9]
```diff
@@ -84,7 +84,16 @@ import akka.util.ccompat._
...
   override def create(context: MaterializationContext): (AnyRef, Publisher[In]) = {
+
     val proc = new VirtualPublisher[In]
+    context.materializer match {
+      case am: ActorMaterializer ⇒
+        if (am.settings.subscriptionTimeoutSettings.mode != StreamSubscriptionTimeoutTerminationMode.noop)
+          am.scheduleOnce(am.settings.subscriptionTimeoutSettings.timeout, new Runnable {
+            def run(): Unit = proc.onSubscriptionTimeout(am)
+          })
+      case _ ⇒ // not possible to setup timeout
```
Comment (helena) [inline akka-stream/src/main/scala/akka/stream/impl/Sinks.scala]: these two arrows

**Review by helena — APPROVED** [review]
Aside from line spaces where needed - see comments, maybe just in the mima filter file, and changing unicode arrows to =>, LGTM

**Comment by patriknw** [comment]
Some remaining comments here, but otherwise we should get this merged

File: akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala (hunk 5 above)
Comment (johanandren) [reply akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala]: It's a manual thing, scalafmt can't detect afair.

**Comment by patriknw** [comment]
@johanandren Some unicode `⇒` here which makes the 2.13 build fail
