### PR TITLE
Avoid ActorsLeakSpec failure

### LINKED ISSUE #25316: Failed: ActorsLeakSpec
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/6159/testReport/junit/akka.remote/ActorsLeakSpec/Remoting_must_not_leak_actors/

```
sbt.ForkMain$ForkError: java.lang.AssertionError: received 1 excess messages on WarningFilter(None,Right(Association with remote system),false)
	at akka.testkit.EventFilter.intercept(TestEventListener.scala:116)
	at akka.remote.ActorsLeakSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$4.apply(ActorsLeakSpec.scala:164)
	at akka.remote.ActorsLeakSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$4.apply(ActorsLeakSpec.scala:141)
	at scala.collection.immutable.Range.foreach(Range.scala:160)
	at akka.remote.ActorsLeakSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ActorsLeakSpec.scala:141)
	at akka.remote.ActorsLeakSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ActorsLeakSpec.scala:69)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scal
```

### PR DESCRIPTION
**Pull request by raboof**
Would fail when we see two termination warnings right
after each other. It would be nicer if we could add a
flag to ignore excess messages like we have in the
typed testkit, but it doesn't seem worth it to overhaul
the API to add that.

Fixes #25316

### CODE REVIEW

File: akka-remote/src/test/scala/akka/remote/classic/ActorsLeakSpec.scala [hunk 1]
```diff
@@ -209,9 +209,7 @@ class ActorsLeakSpec extends AkkaSpec(ActorsLeakSpec.config) with ImplicitSender
         remoteSystem.terminate()
       }
 
-      EventFilter.warning(pattern = "Association with remote system", occurrences = 1).intercept {
-        Await.ready(remoteSystem.whenTerminated, 10.seconds)
-      }
+      Await.ready(remoteSystem.whenTerminated, 10.seconds)
```
Comment (patriknw) [inline akka-remote/src/test/scala/akka/remote/classic/ActorsLeakSpec.scala:212]: are we sure we want to use `Await.ready` and not `Await.result` here? `ready` will not throw

there is another `ready` earlier in this test

**Comment by raboof** [comment]
PLS BUILD

File: akka-remote/src/test/scala/akka/remote/classic/ActorsLeakSpec.scala [hunk 2]
```diff
@@ -203,15 +203,13 @@ class ActorsLeakSpec extends AkkaSpec(ActorsLeakSpec.config) with ImplicitSender
...
       } finally {
         remoteSystem.terminate()
       }
 
-      EventFilter.warning(pattern = "Association with remote system", occurrences = 1).intercept {
-        Await.ready(remoteSystem.whenTerminated, 10.seconds)
-      }
+      Await.result(remoteSystem.whenTerminated, 10.seconds)
 
       EventFilter[TimeoutException](occurrences = 1).intercept {}
```
Comment (patriknw) [inline akka-remote/src/test/scala/akka/remote/classic/ActorsLeakSpec.scala:214]: this is somewhat weird, but I guess that's how to do it with the EventFilter testkit

**Review by patriknw — APPROVED** [review]
LGTM
