### PR TITLE
Typed Java testkit

### LINKED ISSUE #24551: Java typed testkit
The current testkit doesn't work well with JUnit as it has the system as a member but @AfterClass needs to be static. Make it like the untyped testkit?

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #24551 

Provides separate Java and Scala testkit APIs for pretty much all things.

This is on top of #24550 so a bit hard to review, just wanted to get this up here so it doesn't look like I was watching cat videos all day.

### CODE REVIEW

**Comment by johanandren** [comment]
Summing the stuff up:

* Mostly separate APIs under akka.testkit.typed.(scaladsl|javadsl) with idiomatic types
* TestKit -> ActorTestKit to be concise with BehaviorTestKit
* Just a single trait for mixin of Scala ActorTestKit instead of trait + abstract class (fewer options when there is no clear pro/con FTW)
* Built in ExternalResource for use with JUnit in Java (junit dep is optional though)
* Simplified Java APIs where possible and Scala has implicits

File: project/Dependencies.scala [hunk 1]
```diff
@@ -118,6 +117,8 @@ object Dependencies {
 
       val levelDB = "org.iq80.leveldb" % "leveldb" % "0.10" % "optional;provided" // ApacheV2
       val levelDBNative = "org.fusesource.leveldbjni" % "leveldbjni-all" % "1.8" % "optional;provided" // New BSD
+
+      val junit = Compile.junit % "optional;provided;test"
```
Comment (patriknw) [inline project/Dependencies.scala]: good to have it provided, remember to add to reference docs that the dependency must be added when using the `TestKitJunitResource`

File: akka-testkit-typed/src/main/scala/akka/testkit/typed/scaladsl/ActorTestKit.scala [hunk 2]
```diff
@@ -0,0 +1,106 @@
...
+  implicit final def system: ActorSystem[Nothing] = internalSystem
+
+  implicit def scheduler = system.scheduler
+  private val childName: Iterator[String] = Iterator.from(0).map(_.toString)
+
+  implicit val timeout = testkitSettings.DefaultTimeout
+
+  final def shutdownTestKit(): Unit = {
+    // FIXME separate default timeout for shutdown?
+    ActorTestKit.shutdown(system, timeout.duration)
```
Comment (patriknw) [inline akka-testkit-typed/src/main/scala/akka/testkit/typed/scaladsl/ActorTestKit.scala]: I think it can be important to fix this timeout, default 3 seconds might be too short

File: akka-testkit-typed/src/main/scala/akka/testkit/typed/scaladsl/ActorTestKit.scala [hunk 3]
```diff
@@ -0,0 +1,106 @@
...
+    spawn(behavior, name, Props.empty)
+
+  /**
+   * Spawn the given behavior. This is created as a child of the test kit
+   * guardian
+   */
+  final def spawn[T](behavior: Behavior[T], name: String, props: Props): ActorRef[T] =
+    Await.result(internalSystem ? (ActorTestKitGuardian.SpawnActor(name, behavior, _, props)), timeout.duration)
+
+  // FIXME needed for Akka internal tests but, users shouldn't spawn system actors?
```
Comment (patriknw) [inline akka-testkit-typed/src/main/scala/akka/testkit/typed/scaladsl/ActorTestKit.scala]: I agree, even if `ExtendedActorSystem.systemActorOf` is public I think we should start out like this.

File: akka-testkit-typed/src/main/scala/akka/testkit/typed/scaladsl/ActorTestKit.scala [hunk 4]
```diff
@@ -0,0 +1,106 @@
...
+   */
+  def config: Config = ConfigFactory.empty()
+
+  /**
+   * TestKit settings used in the tests, override or provide custom config to customize
+   */
+  protected implicit def testkitSettings = TestKitSettings(system)
+
+  private val internalSystem: ActorSystem[ActorTestKitGuardian.TestKitCommand] =
+    if (config == ConfigFactory.empty) ActorSystem(ActorTestKitGuardian.testKitGuardian, name)
```
Comment (patriknw) [inline akka-testkit-typed/src/main/scala/akka/testkit/typed/scaladsl/ActorTestKit.scala]: If the `config` is not defined this will load `application.conf`. I'm on the fence, but that might be an alright default also for tests (even though I personally would never use it like that). Anyway it should be clearly documented.

It might be slightly strange since `ActorSystem(guardian, "Sys", config = Some(ConfigFactory.empty))` doesn't have the same semantics. Perhaps make it `def config: Option[Config] = None`?

File: akka-testkit-typed/src/main/scala/akka/testkit/typed/internal/TestKitUtils.scala [hunk 5]
```diff
@@ -0,0 +1,71 @@
...
+/**
+ * INTERNAL API
+ */
+@InternalApi
+private[akka] object TestKitUtils {
+
+  // common internal utility impls for Java and Scala
+  private val TestKitRegex = """akka\.testkit\.typed\.(?:javadsl|scaladsl)\.ActorTestKit(?:\$.*)?""".r
+
+  def testNameFromCallStack(classToStartFrom: Class[_]): String = {
```
Comment (patriknw) [inline akka-testkit-typed/src/main/scala/akka/testkit/typed/internal/TestKitUtils.scala]: do we have tests for this? is it also used from java tests and does it work there?

File: akka-testkit-typed/src/main/scala/akka/testkit/typed/javadsl/BehaviorTestKit.scala [hunk 6]
```diff
@@ -0,0 +1,84 @@
...
+
+  /**
+   * Is the current behavior alive or stopped
+   */
+  def isAlive: Boolean
+
+  /**
+   * Send the msg to the behavior and record any [[Effect]]s
+   */
+  def run(msg: T): Unit
```
Comment (patriknw) [inline akka-testkit-typed/src/main/scala/akka/testkit/typed/javadsl/BehaviorTestKit.scala]: I think we have an open PR for adding something here. Please merge that first.

File: akka-testkit-typed/src/main/scala/akka/testkit/typed/scaladsl/TestProbe.scala [hunk 7]
```diff
@@ -3,137 +3,79 @@
...
 
 object FishingOutcomes {
-
   /**
-   * Consume this message, collect it into the result, and continue with the next message
+   * Complete fishing and return all messages up until this
    */
-  case object Continue extends FishingOutcome
-
+  val complete = FishingOutcome.Complete
```
Comment (patriknw) [inline akka-testkit-typed/src/main/scala/akka/testkit/typed/scaladsl/TestProbe.scala]: explicit return type?

File: akka-testkit-typed/src/main/scala/akka/testkit/typed/Effect.scala [hunk 8]
```diff
@@ -0,0 +1,102 @@
...
+@ApiMayChange
+object Effect {
+
+  // FIXME is this one really a useful subgroup?
+  abstract class SpawnedEffect extends Effect
+
+  final case class Spawned[T](behavior: Behavior[T], childName: String, props: Props = Props.empty) extends SpawnedEffect
+
+  /**
+   * Java API:
```
Comment (patriknw) [inline akka-testkit-typed/src/main/scala/akka/testkit/typed/Effect.scala]: too complicated to separate this in scaladsl, javadsl?

**Review by patriknw — COMMENTED** [review]
looking good

**Review by patriknw — COMMENTED** [review]
by the way, I assume that some reference docs and example showing junit and scalatest "templates" will also be included here

File: akka-testkit-typed/src/main/scala/akka/testkit/typed/Effect.scala (hunk 8 above)
Comment (johanandren) [reply akka-testkit-typed/src/main/scala/akka/testkit/typed/Effect.scala]: Hmm, I guess that is better. Maybe we could keep the actual classes/objects in the Scala API and have methods only on the Java side. (I did it like this because I thought it would then be easy to miss when adding factory methods, but I guess we won't really be adding new effects very often)

File: akka-testkit-typed/src/main/scala/akka/testkit/typed/javadsl/BehaviorTestKit.scala (hunk 6 above)
Comment (johanandren) [reply akka-testkit-typed/src/main/scala/akka/testkit/typed/javadsl/BehaviorTestKit.scala]: Yeap, saw that one. Will do.

File: akka-testkit-typed/src/main/scala/akka/testkit/typed/internal/TestKitUtils.scala (hunk 5 above)
Comment (johanandren) [reply akka-testkit-typed/src/main/scala/akka/testkit/typed/internal/TestKitUtils.scala]: Yes, both tests from Scala direct and derived spec and Java (old impl didn't cut it for all those cases). Also, verified it with all tests in akka-actor-typed-tests

File: akka-testkit-typed/src/main/scala/akka/testkit/typed/scaladsl/ActorTestKit.scala (hunk 4 above)
Comment (johanandren) [reply akka-testkit-typed/src/main/scala/akka/testkit/typed/scaladsl/ActorTestKit.scala]: I started with an option but it felt messy for the tests, just overloading and providing config is so much nicer I think it is worth it. What about providing some other minimal placeholder testkit-specific config instance to compare with?

File: akka-testkit-typed/src/main/scala/akka/testkit/typed/scaladsl/ActorTestKit.scala (hunk 2 above)
Comment (johanandren) [reply akka-testkit-typed/src/main/scala/akka/testkit/typed/scaladsl/ActorTestKit.scala]: I'll add another setting, for `TestKit.shutdown(system)` I hardcoded a value but I realize I could just create read that same setting in that case as well.

File: akka-testkit-typed/src/main/scala/akka/testkit/typed/scaladsl/ActorTestKit.scala (hunk 4 above)
Comment (patriknw) [reply akka-testkit-typed/src/main/scala/akka/testkit/typed/scaladsl/ActorTestKit.scala]: yes, such placeholder (comparing with `eq`) would be fine

**Comment by johanandren** [comment]
Yes, that sounds good with the docs, I'll do that next

**Comment by johanandren** [comment]
Ready for final review now.

**Comment by johanandren** [comment]
I realized now that I fixed some extra tests still using the old constructor based testkit, that the entire reason why we put config in the companion is because it would be unwieldy to do that in a constructor param, I wonder if I should move those into the test classes now that it is less messy

File: akka-testkit-typed/src/main/scala/akka/testkit/typed/scaladsl/ActorTestKit.scala [hunk 9]
```diff
@@ -0,0 +1,130 @@
...
+  def shutdown(
+    system:               ActorSystem[_],
+    timeout:              Duration,
+    throwIfShutdownFails: Boolean        = false): Unit =
+    TestKitUtils.shutdown(system, timeout, throwIfShutdownFails)
+
+  // place holder for no custom config specified to avoid the boilerplate
+  // of an option for config in the trait
+  private val noConfigSet = ConfigFactory.parseString("")
+
```
Comment (patriknw) [inline akka-testkit-typed/src/main/scala/akka/testkit/typed/scaladsl/ActorTestKit.scala]: we could add factory methods for creating `ActorTestKit` here also (as alternative to extending), similar to the javadsl, but we can do that later if needed

**Review by patriknw — APPROVED** [review]
LGTM

File: akka-testkit-typed/src/main/scala/akka/testkit/typed/scaladsl/ActorTestKit.scala (hunk 9 above)
Comment (johanandren) [reply akka-testkit-typed/src/main/scala/akka/testkit/typed/scaladsl/ActorTestKit.scala]: I think we should make people do it in one way rather than provide two almost the same ways out of the box. Let's add that if someone asks for it.

Comment (patriknw) [reply akka-testkit-typed/src/main/scala/akka/testkit/typed/scaladsl/ActorTestKit.scala]: I'd say that "use as a tool" is better than inheriting. E.g. you can more easily create multiple in same test. There is no risk of name clashes when we add more methods. We have started using that style in several of the testing tools, such as TestProbe, BehaviorTestkit.

So if I have to pick one style I'd choose that one.
On the other hand I have some understanding for ScalaTest style which loves mixing in stuff.

Comment (johanandren) [reply akka-testkit-typed/src/main/scala/akka/testkit/typed/scaladsl/ActorTestKit.scala]: Hmm, that's a fair point, I think I leaned this direction just because of the old testkit design. Maybe we should default like that, just like we do for the Java API then.

Comment (patriknw) [reply akka-testkit-typed/src/main/scala/akka/testkit/typed/scaladsl/ActorTestKit.scala]: Let's merge this and follow up on this topic separately

Comment (johanandren) [reply akka-testkit-typed/src/main/scala/akka/testkit/typed/scaladsl/ActorTestKit.scala]: Made a separate issue to track it #24598

**Review by 2m — APPROVED** [review]
This one is a biggie. LGTM
