### PR TITLE
Stabilise InmemPersistentActorSpec

### LINKED ISSUE #30498: [failed] InmemPersistentActorSpec able to opt-out from stashing messages
https://github.com/akka/akka/pull/30449/checks?check_run_id=3262134926#step:5:8234

```
[info] - must be able to opt-out from stashing messages until all events have been processed *** FAILED *** (4 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected y, found x-1
[info]   at scala.Predef$.assert(Predef.scala:279)
[info]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:462)
[info]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:438)
[info]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:438)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:973)
[info]   at akka.persistence.PersistentActorSpec.$anonfun$new$23(PersistentActorSpec.scala:1217)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
...
[info] akka.persistence.InmemPersistentActorSpec *** ABORTED *** (115 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected List(a-1, a-2), found y
[info]   at scala.Predef$.assert(Predef.scala:279)
[info]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:462)
[info]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:438)
[info]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:438)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:973)
[info]   at akka.persistence.PersistentActorSpec.beforeEach(PersistentActorSpec.scala:957)
[info]   at org.scalatest.BeforeAndAfterEach.runTest(BeforeAndAfterEach.scala:233)
[info]   at org.scalatest.BeforeAndAfterEach.runTest$(BeforeAndAfterEach.scala:227)
[info]   at akka.persistence.PersistenceSpec.runTest(PersistenceSpec.scala:22)
...
```

### PR DESCRIPTION
**Pull request by ignasi35**
Hopefully fixes #30498

### CODE REVIEW

File: akka-persistence/src/test/scala/akka/persistence/PersistentActorSpec.scala [hunk 1]
```diff
@@ -1213,10 +1213,8 @@ abstract class PersistentActorSpec(config: Config) extends PersistenceSpec(confi
       val persistentActor = asyncPersistPersistentActor
       persistentActor ! Cmd("x")
       persistentActor ! Cmd("y")
-      expectMsg("x")
-      expectMsg("y") // "y" command was processed before event persisted
-      expectMsg("x-1")
-      expectMsg("y-2")
+      val messages = receiveN(4)
+      messages.toSet should equal(Set("x", "y", "x-1", "y-2"))
```
Comment (raboof) [inline akka-persistence/src/test/scala/akka/persistence/PersistentActorSpec.scala:1217]: While this will surely make the test more stable, also it doesn't test what it was intended to test anymore ;).

The test was intended to check that the actor can start processing the command "y" (evidenced by the reply "y") before the persist of the command "x" has completed. With this change, the test will also succeed when then implementation no longer allows that.

If the 'persist' operation is fast, however, it is entirely possible that the event handling would finish before the processing of "y", so seeing x-1 sooner is not 'wrong' per se.

While we should not over-use it, perhaps an `awaitAssert`/`eventually` around this whole test might be justifiable?

Comment (ignasi35) [reply akka-persistence/src/test/scala/akka/persistence/PersistentActorSpec.scala:1217]: > If the 'persist' operation is fast, however, it is entirely possible that the event handling would finish before the processing of "y", so seeing x-1 sooner is not 'wrong' per se.

I think observing `Set("x", "x-1", "y", "y-2")` in the test is valid output but it's not proving the feature is correct. `eventually` sounds like a good plan to me.

Comment (raboof) [reply akka-persistence/src/test/scala/akka/persistence/PersistentActorSpec.scala]: > I think observing `Set("x", "x-1", "y", "y-2")` in the test is valid output but it's not proving the feature is correct.

completely agree!

**Review by raboof — APPROVED** [review]
