### PR TITLE
=str #19721 Failing FlowConflateSpec and NPE in Batch fixed

### LINKED ISSUE #19721: FAILED akka.stream.scaladsl.FlowConflateSpec
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/5135/consoleFull

```
- must restart when `aggregate` throws and a restartingDecider is used *** FAILED *** (32 milliseconds)
[info]   "[on]e" did not equal "[thre]e" (FlowConflateSpec.scala:200)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.shouldEqual(Matchers.scala:6303)
[info]   at akka.stream.scaladsl.FlowConflateSpec$$anonfun$1$$anonfun$apply$mcV$sp$18.apply$mcV$sp(FlowConflateSpec.scala:200)
[info]   at akka.stream.scaladsl.FlowConflateSpec$$anonfun$1$$anonfun$apply$mcV$sp$18.apply(FlowConflateSpec.scala:176)
[info]   at akka.stream.scaladsl.FlowConflateSpec$$anonfun$1$$anonfun$apply$mcV$sp$18.apply(FlowConflateSpec.scala:176)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
```

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #19721

### CODE REVIEW

File: akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowConflateSpec.scala [hunk 1]
```diff
@@ -168,6 +169,8 @@ class FlowConflateSpec extends AkkaSpec {
       sub.expectRequest(1)
       sub.sendNext(3)
 
+      sinkProbe.expectNoMsg(100.millis)
```
Comment (drewhk) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowConflateSpec.scala]: add a comment that this is to avoid race between the above sendNext and the request below (fuzzer is fun ;) ).

File: akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowConflateSpec.scala [hunk 2]
```diff
@@ -231,6 +238,8 @@ class FlowConflateSpec extends AkkaSpec {
       sub.expectRequest(1)
       sub.sendNext(4)
 
+      sinkProbe.expectNoMsg(100.millis)
```
Comment (drewhk) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowConflateSpec.scala]: same here

**Comment by drewhk** [comment]
LGTM

**Comment by johanandren** [comment]
PLS BUILD

File: akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowConflateSpec.scala [hunk 3]
```diff
@@ -168,6 +169,9 @@ class FlowConflateSpec extends AkkaSpec {
       sub.expectRequest(1)
       sub.sendNext(3)
 
+      // delay requesting to avoid race condition
```
Comment (rkuhn) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowConflateSpec.scala]: What race condition? If there is one, then sleeping 100ms will not be good enough (CI builds run on weird systems).

File: akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowConflateSpec.scala [hunk 4]
```diff
@@ -190,14 +194,19 @@ class FlowConflateSpec extends AkkaSpec {
...
+
       sub.expectRequest(4)
       sub.sendNext("one")
       sub.sendNext("two")
       sub.sendNext("three")
       sub.sendComplete()
 
+      // delay requesting to avoid race condition
+      sinkProbe.ensureSubscription()
+      sinkProbe.expectNoMsg(100.millis)
```
Comment (rkuhn) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowConflateSpec.scala]: This can be done deterministically and faster by using a TestLatch that is opened within the aggregate function before throwing the exception.

**Comment by rkuhn** [comment]
LGTM after fixing those race conditions :-)

File: akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowConflateSpec.scala (hunk 3 above)
Comment (drewhk) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowConflateSpec.scala]: The race is between the sendNext above and the request below (even though they come next to each other in the code) due to the interpreter in fuzzing mode reordering events that otherwise would be sequential due to the enclosing actor's mailbox.

**Comment by johanandren** [comment]
Crap.

**Comment by ktoso** [comment]
LGTM, merging to stop fleakieness in other PRs :)
