### PR TITLE
=str - 19109 - Unbreaking SinkForeachParallelSpec

### LINKED ISSUE #19109: Failed test SinkForeachParallelSpec
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/4404/consoleFull

### PR DESCRIPTION
**Pull request by viktorklang**
Fixes #19109

### CODE REVIEW

File: akka-stream-tests/src/test/scala/akka/stream/scaladsl/SinkForeachParallelSpec.scala [hunk 1]
```diff
@@ -82,13 +82,11 @@ class SinkForeachParallelSpec extends AkkaSpec {
           Await.ready(latch, 10.seconds)
         }
       }).withAttributes(supervisionStrategy(resumingDecider)))
-      p.onFailure { case e ⇒ assert(e.getMessage.equals("err1")); Unit }
 
       latch.countDown()
       probe.expectMsgAllOf(1, 2, 4)
 
       Await.result(p, 5.seconds)
-      assert(p.isCompleted)
```
Comment (viktorklang) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/SinkForeachParallelSpec.scala]: That's a nonsense-assert after waiting for the result. And we don't care about the result itself unless it's an exception, which would indicate failure, and would be rethrown by Await.

File: akka-stream-tests/src/test/scala/akka/stream/scaladsl/SinkForeachParallelSpec.scala [hunk 2]
```diff
@@ -82,13 +82,11 @@ class SinkForeachParallelSpec extends AkkaSpec {
           Await.ready(latch, 10.seconds)
         }
       }).withAttributes(supervisionStrategy(resumingDecider)))
-      p.onFailure { case e ⇒ assert(e.getMessage.equals("err1")); Unit }
```
Comment (viktorklang) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/SinkForeachParallelSpec.scala]: This is a non-sense assert as this would be executed and thrown in some other thread.

**Comment by drewhk** [comment]
LGTM
