### PR TITLE
Fixes intermittent "Could not create directory" issue

### LINKED ISSUE #27661: Failed: Could not create directory,  file exists and is not a directory: / Multi-jvm / assembly / assembledMappings
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/7278/console

```
[error] java.lang.RuntimeException: Could not create directory /localhome/jenkinsakka/workspace/akka-multi-node-nightly/akka-cluster-typed/target/streams/multi-jvm/assemblyOption/$global/streams/assembly/7c9e372c6314ee0628ee1dc84f3ff20a457e8168_af7e2274bc4c9d6aab59e1b84f68383d14ab7935_da39a3ee5e6b4b0d3255bfef95601890afd80709
[error] 	at scala.sys.package$.error(package.scala:26)
[error] 	at sbt.io.IO$.createDirectory(IO.scala:326)
[error] 	at sbtassembly.AssemblyUtils$.unzipStream(AssemblyUtils.scala:42)
[error] 	at sbtassembly.AssemblyUtils$.$anonfun$unzip$1(AssemblyUtils.scala:37)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbtassembly.AssemblyUtils$.unzip(AssemblyUtils.scala:37)
[error] 	at sbtassembly.Assembly$.$anonfun$assembleMappings$9(Assembly.scala:220)
[error] 	at scala.collection.parallel.AugmentedIterableIterator.map2combiner(RemainsIterator.scala:112)
[error] 	at scala.collection.parallel.AugmentedIterableIterator.map2combiner$(RemainsIterator.scala:109)
[error] 	at scala.collection.parallel.immutable.ParVector$ParVectorIterator.map2combiner(ParVector.scala:62)
[error] 	at scala.collection.parallel.ParIterableLike$Map.leaf(ParIterableLike.scala:1052)
[error] 	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:49)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:63)
[error] 	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:52)
[error] 	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:46)
[error] 	at scala.collection.parallel.ParIterableLike$Map.tryLeaf(ParIterableLike.scala:1049)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:156)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:153)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:436)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:146)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:145)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:436)
[error] 	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
[error] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[error] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[error] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[error] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[error] (akka-cluster-typed / Multi-jvm / assembly / assembledMappings) Could not create directory /localhome/jenkinsakka/workspace/akka-multi-node-nightly/akka-cluster-typed/target/streams/multi-jvm/assemblyOption/$global/streams/assembly/7c9e372c6314ee0628ee1dc84f3ff20a457e8168_af7e2274bc4c9d6aab59e1b84f68383d14ab7935_da39a3ee5e6b4b0d3255bfef95601890afd80709
[error] Total time: 3496 s, completed Sep 7, 2019 6:26:29 AM
```

### PR DESCRIPTION
**Pull request by eed3si9n**
Fixes #27661
This was a collaboration work with @helena 

I saw that MultiJVM's assembly/fullClasspath contains a bunch of duplicates in the form of:

```
[info] * Attributed(/Users/eed3si9n/work/akka/akka-cluster-sharding/../akka-protobuf-v3/target/akka-protobuf-v3-assembly-2.6-SNAPSHOT.jar)
[info] * Attributed(/Users/eed3si9n/work/akka/akka-cluster/../akka-protobuf-v3/target/akka-protobuf-v3-assembly-2.6-SNAPSHOT.jar)
```

Helena pointed out to me that project/Protobuf.scala introduces `/../` in the middle of an unmaged JAR path:

```
    // this keeps intellij happy for files that use the shaded protobuf
    Compile / unmanagedJars ++= Seq(
        baseDirectory.value / ".." / "akka-protobuf-v3" / "target" / s"akka-protobuf-v3-assembly-${version.value}.jar"),
```

While that may keep IntelliJ, sbt-assembly is not very happy with the duplicated protobuf jars.

This works around the issue by calling `getCanonicalFile` to make the path canonical.

### CODE REVIEW

File: project/AkkaBuild.scala [hunk 1]
```diff
@@ -251,6 +253,14 @@ object AkkaBuild {
...
     docLintingSettings,
     JdkOptions.targetJdkSettings,
+
+    // a workaround for https://github.com/akka/akka/issues/27661
+    // see also project/Protobuf.scala that introduces /../ to make "intellij happy"
+    MultiJvm / assembly / fullClasspath := {
+      val old = (MultiJvm / assembly / fullClasspath).value.toVector
+      val files = old.map(_.data.getCanonicalFile).distinct
+      files map { x => Attributed.blank(x) }
+    },
```
Comment (helena) [inline project/AkkaBuild.scala]: This will help in conjunction with https://github.com/akka/akka/pull/28055
but specifically help as well given https://github.com/akka/akka/blob/master/project/Protobuf.scala#L32-L33

**Review by helena — APPROVED** [review]
LGTM

**Comment by helena** [comment]
And thanks @eed3si9n 👍

**Review by patriknw — APPROVED** [review]
LGTM, thanks for helping @eed3si9n

**Comment by helena** [comment]
OK TO TEST

**Comment by helena** [comment]
I just found another, oddly, in build.sbt
`.settings(Protobuf.importPath := Some(baseDirectory.value / ".." / "akka-remote" / "src" / "main" / "protobuf"))` which I will PR the fix for today.

**Review by jrudolph — COMMENTED** [review]
Great finding, @eed3si9n. We might only be fixing symptoms here, though. Have we understood why it turns up on the classpath multiple times in the first place and non-deterministically?

**Comment by helena** [comment]
@jrudolph I agree on symptoms, I've been suspicious and we do have to clean up the classpath duplication. I was digging into and not yet finding it so the saga continues on root cause.
