### PR TITLE
Fix race in CircuitBreakerSpec #23413

### LINKED ISSUE #23413: Failed: CircuitBreakerSpec
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5107/consoleFull

<details>
<pre>
[info]   - when exception is defined as Success *** FAILED *** (2 seconds, 23 milliseconds)
[info]     java.lang.AssertionError: assertion failed: timeout 2 seconds expired:
[info]     at scala.Predef$.assert(Predef.scala:170)
[info]     at akka.testkit.TestKitBase$class.poll$1(TestKit.scala:276)
[info]     at akka.testkit.TestKitBase$class.awaitCond(TestKit.scala:282)
[info]     at akka.testkit.TestKit.awaitCond(TestKit.scala:831)
[info]     at akka.pattern.CircuitBreakerSpec$$anonfun$14$$anonfun$apply$mcV$sp$42$$anonfun$apply$mcV$sp$43.apply$mcV$sp(CircuitBreakerSpec.scala:672)
[info]     at akka.pattern.CircuitBreakerSpec$$anonfun$14$$anonfun$apply$mcV$sp$42$$anonfun$apply$mcV$sp$43.apply(CircuitBreakerSpec.scala:668)
[info]     at akka.pattern.CircuitBreakerSpec$$anonfun$14$$anonfun$apply$mcV$sp$42$$anonfun$apply$mcV$sp$43.apply(CircuitBreakerSpec.scala:668)
[info]     at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]     at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]     at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]     at org.scalatest.Transformer.apply(Transformer.scala:20)
...
</pre>
</details>

### PR DESCRIPTION
**Pull request by chbatey**
The successful Future could complete after one of the Failure futures as
they're all a call to Future.apply so scheduled on different threads.

Fixes #23413

### CODE REVIEW

File: akka-actor-tests/src/test/scala/akka/pattern/CircuitBreakerSpec.scala [hunk 1]
```diff
@@ -666,10 +666,11 @@ class CircuitBreakerSpec extends AkkaSpec with BeforeAndAfter with MockitoSugar
 
     "reset failure count after exception in call" when {
       "exception is defined as Success" in {
-        val breaker = CircuitBreakerSpec.multiFailureCb()
-        breaker().withCircuitBreaker(Future(sayHi))
-        for (n ← 1 to 4) breaker().withCircuitBreaker(Future(throwException))
-        awaitCond(breaker().currentFailureCount == 4, awaitTimeout)
+        val breaker: CircuitBreakerSpec.Breaker = CircuitBreakerSpec.multiFailureCb()
+        breaker().withCircuitBreaker(Future.successful(sayHi))
```
Comment (patriknw) [inline akka-actor-tests/src/test/scala/akka/pattern/CircuitBreakerSpec.scala]: isn't this just slightly less racy, but still racy? `f.onComplete` is used inside the CircuitBreaker

Is this first successful needed at all, or is the test still valid without it?

Comment (chbatey) [reply akka-actor-tests/src/test/scala/akka/pattern/CircuitBreakerSpec.scala]: afaik oncomplete for a completed future executes on the calling thread but you're right we don't need any successes before the failures. Will remove

**Review by patriknw — APPROVED** [review]
LGTM

**Review by ktoso — APPROVED** [review]
LGTM
