### PR TITLE
=str - 19149 - Corrects the behavior of FlowOps.sliding

### LINKED ISSUE #19149: stream (2.0-M2): bug in Flow.sliding
Follow up on: https://groups.google.com/forum/#!topic/akka-user/fhlCbYJ8kOc

Flow.sliding does not correspond exactly with the Seq.sliding behaviour, as was apparently intended. A  minimised example for this bug is:

```scala
Source(Stream.from(0)).take(2).sliding(1, 3)
```
This will place two elements on the stream: {0} and {0, 1}. The correct behaviour would only have placed the former on the stream.

Because I had it lying around by now, a test that should fail for all generated test-cases, but right now succeeds for all of them. Perhaps this will prove useful:
```scala
import akka.actor.ActorSystem
import akka.stream.ActorMaterializer
import akka.stream.scaladsl.Source
import akka.testkit.TestKit
import org.scalacheck.{Gen, Shrink}
import org.scalatest.concurrent.{Eventually, ScalaFutures}
import org.scalatest.prop.GeneratorDrivenPropertyChecks
import org.scalatest.{FlatSpecLike, Matchers}

import scala.concurrent.Future

/**
 * Created by merlijn on 10/12/15.
 */
class SlidingWindowTest extends TestKit(ActorSystem("test")) with FlatSpecLike with Matchers with GeneratorDrivenPropertyChecks with Eventually with ScalaFutures {

  implicit def noShrink[T]: Shrink[T] = Shrink.shrinkAny[T]

  implicit val materializer = ActorMaterializer()

  def test(count: Int, window: Int, step: Int): Future[Seq[Seq[Int]]] = Source(Stream.from(0))
    .take(count)
    .sliding(window, step)
    .runFold(Seq.empty[Seq[Int]]) { case (total, slice) =>
      total :+ slice
    }

  "Sliding" should "never pass this test" in {
    val windowStep = for {
      window <- Gen.choose(1, 10)
      step <- Gen.choose(window + 2, 20)
    } yield (window, step)

    forAll(windowStep) {
      case (window, step) =>

        val incompatibleElementCount = for {
          n <- Gen.choose(1, 20)
          count <- Gen.choose(step * n + window + 1, step * (n + 1) - 1)
        } yield count

        forAll(incompatibleElementCount) { count =>
          whenReady(test(count, window, step)) { testResult =>
            testResult.last.size should be > (window) //For correct behaviour, this test should pass by reversing the assertion: testResult.last.size should be <= (window)
          }
        }
    }
  }
}
```

In essence, the problem pops up (as far as I observed) when the next step in sliding exceeds the last available element in the stream, and some of the elements of the terminated stream were not included in the previous window. In that case, it will create a new window with the same lowerBound as the previous window, and include all elements up to the last one.

### PR DESCRIPTION
**Pull request by viktorklang**
Generatively attempts to verify that it behaves exactly like the
collections library

Fixes #19149

### CODE REVIEW

File: akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala [hunk 1]
```diff
@@ -318,55 +318,35 @@ private[akka] final case class Grouped[T](n: Int) extends PushPullStage[T, immut
...
-    if (ctx.isFinishing) {
-      val emit = buf.result()
-      if (emit.size == n) {
-        ctx.finish()
-      } else {
-        ctx.pushAndFinish(emit)
-      }
-    } else ctx.pull()
+    if (!ctx.isFinishing) ctx.pull()
+    else if (buf.size == n || step > n) ctx.finish()
```
Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala]: This line fixes the bug, the rest is testing and code cleanup.

File: akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowSlidingSpec.scala [hunk 2]
```diff
@@ -3,128 +3,39 @@
...
-    "work with n = 3, step = 6" in assertAllStagesStopped {
-      Source(1 to 12).sliding(n = 3, step = 6).runForeach(testActor ! _) onSuccess {
-        case _ ⇒ testActor ! "done"
+      forAll(gen) {
+        case (len, win, step) ⇒
+          val done = s"done: $len $win $step"
+          val as = Source(() ⇒ Iterator.from(0).take(len)).sliding(win, step)
+          val cs = Source(() ⇒ Iterator.from(0).take(len).sliding(win, step))
+          as.zipWith(cs)(_ should be(_)).runFold(done)(Keep.left) pipeTo testActor
+          expectMsg(done)
```
Comment (rkuhn) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowSlidingSpec.scala]: As nice as this looks there must be something wrong with it because it should fail for len 1, win 2, step 3.

File: akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala (hunk 1 above)
Comment (rkuhn) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala]: But this line is not free from bugs: when the buffer is not yet full enough, we must emit regardless of whether `step > n` or not.

File: akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala [hunk 3]
```diff
@@ -318,55 +318,32 @@ private[akka] final case class Grouped[T](n: Int) extends PushPullStage[T, immut
...
-    bufferedElements += 1
-    if (bufferedElements < n) {
+    buf :+= elem
+    if (buf.size < n) {
+      ctx.pull()
+    } else if (buf.size == n) {
+      ctx.push(buf)
+    } else if (step > n) {
+      if (buf.size == step)
+        buf = Vector.empty
```
Comment (rkuhn) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala]: This is pretty wasteful for large `step` values: we would build up a huge vector for no reason.

Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala]: My thinking was to defer opting it until it becomes a graphstage.
Right now it is buggy and I'd rather have an impl which is easy to reason
about than a buggy fast one. This PR is what my very limited time can offer
right now :-/

-- 
Cheers,
√

File: akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowSlidingSpec.scala (hunk 2 above)
Comment (viktorklang) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowSlidingSpec.scala]: I can try it with that specifically but ScalaCheck tends not to lie.
I'll also add tests to verify that it throws when it should.

-- 
Cheers,
√

File: akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala (hunk 1 above)
Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala]: What do you mean in terms of code? (I can try that)

-- 
Cheers,
√

File: akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowSlidingSpec.scala (hunk 2 above)
Comment (rkuhn) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowSlidingSpec.scala]: Well, I tried it in the REPL and got different results :-)

Comment (viktorklang) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowSlidingSpec.scala]: Then I definitely need to tweak ScalaCheck to be more thurough!

-- 
Cheers,
√

Comment (viktorklang) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowSlidingSpec.scala]: I found the error, the failure is always in that one of them is too short, and of course zipWith just completes. So I have fixed the scalacheck both to generate more values but also verify lengths.

Pushing my (failing) branch now.

**Comment by viktorklang** [comment]
@rkuhn Alright, I both fixed the bug, made the test better and have some awesome cheese.

File: akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala (hunk 3 above)
Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala]: Also, speaking of building up a huge vector for no reason, look at the occurrences of `buf.result()` in the code I replaced. *shrug*

Comment (rkuhn) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala]: Yes, I know: boy-scout rule :-) Anyway, I agree with first getting it right.

Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala]: At least the newly pushed branch seems right, and I split the checks out in 3 different ones, testing step less than window, equals to window and greater than window.

Now we have a decent test suite, which will hopefully make it easier to migrate the code to GraphStage and optimize it down the road.

File: akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala [hunk 4]
```diff
@@ -318,55 +318,32 @@ private[akka] final case class Grouped[T](n: Int) extends PushPullStage[T, immut
...
-    if (ctx.isFinishing) {
-      val emit = buf.result()
-      if (emit.size == n) {
-        ctx.finish()
-      } else {
-        ctx.pushAndFinish(emit)
-      }
-    } else ctx.pull()
+    if (!ctx.isFinishing) ctx.pull()
+    else if (buf.size >= n) ctx.finish()
```
Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala]: This line is the bugfix

**Comment by rkuhn** [comment]
LGTM, thanks!

**Comment by viktorklang** [comment]
@rkuhn

I just realized that step may end up 0 here:
https://github.com/akka/akka/pull/19153/files#diff-17e38cb6b9c5bd357a7eb5abb6de7a9fR32

should be Gen.choose(1, math.max(1, win - 1))

-- 
Cheers,
√

**Comment by rkuhn** [comment]
That’s not a problem, Gen.choose(1, 0) will just not emit anything.

**Comment by viktorklang** [comment]
Ok, surprising but good

-- 
Cheers,
√

File: akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowSlidingSpec.scala (hunk 2 above)
Comment (drewhk) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowSlidingSpec.scala]: btw, this is what I don't like about ScalaCheck - the list of cases being checked is not visible explicitly. Maybe an IDE plugin to generate test files using ScalaCheck like rules what I would be happy with.

Comment (rkuhn) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowSlidingSpec.scala]: On the contrary, the list is very succinct and visible: assume that all cases covered by the generators will (eventually) be tested. This is so much easier for humans to understand and verify than an incomplete listing of manually enumerated corner cases.
