### PR TITLE
fix ActorPublisher state machine, fixes #20031 (backport)

### LINKED ISSUE #20031: FileIO publisher invokes onComplete twice
Akka version: 2.4.2
OS: Ubuntu 15.10

`FileIO` violates section 1.7 of the reactive streams spec, *Once a terminal state has been signaled (onError, onComplete) it is REQUIRED that no further signals occur.*

Reproducer:

```scala
import akka.actor._
import akka.util.ByteString
import akka.stream._
import akka.stream.scaladsl._
import org.reactivestreams._

implicit val system = ActorSystem()
implicit val mat = ActorMaterializer()
val file = new java.io.File(/* insert any existing file here */ "/home/jroper/bike.jpg")
val subscriber = new Subscriber[ByteString] {
  var s: Subscription = _
  def onSubscribe(s: Subscription) = {
    println("onSubscribe")
    this.s = s
    s.request(1)
  }
  def onNext(b: ByteString) = s.request(1)
  def onError(t: Throwable) = println(t)
  def onComplete = println("onComplete")
}

FileIO.fromFile(file).runWith(Sink.fromSubscriber(subscriber))
```

Running it:

```
scala> FileIO.fromFile(file).runWith(Sink.fromSubscriber(subscriber))
res0: akka.NotUsed = NotUsed

scala> onSubscribe
onComplete
onComplete
```

### PR DESCRIPTION
**Pull request by drewhk**
(cherry picked from commit 19d0bdb)

### CODE REVIEW

File: akka-stream/src/main/scala/akka/stream/impl/io/InputStreamPublisher.scala [hunk 1]
```diff
@@ -47,7 +47,7 @@ private[akka] class InputStreamPublisher(is: InputStream, bytesReadPromise: Prom
   def readAndSignal(): Unit =
     if (isActive) {
       readAndEmit()
```
Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/impl/io/InputStreamPublisher.scala]: I assume this means that `readAndEmit()` can flip the `isActive` flag?

Comment (drewhk) [inline akka-stream/src/main/scala/akka/stream/impl/io/InputStreamPublisher.scala]: this is a cherry-pick commit, a backport to 2.0.x

Comment (viktorklang) [inline akka-stream/src/main/scala/akka/stream/impl/io/InputStreamPublisher.scala]: I know (it would be nice to have in the title btw), I just meant that oftentimes mutable state is the Devil.

Comment (drewhk) [inline akka-stream/src/main/scala/akka/stream/impl/io/InputStreamPublisher.scala]: It is too much effort to switch contexts right now, but if you think there is an issue/improvement possibility here then please open a ticket. I am busy backporting now :)
