### PR TITLE
Artery tests: use config to determine TCP/UDP free port + use the correct host

### LINKED ISSUE #26130: FAILED: RemoteConnectionSpec
akka.remote.artery.RemoteConnectionSpec.Remoting between systems should allow other system to connect even if it's not there at first

https://jenkins.akka.io:8498/job/akka-nightly/6150/testReport/junit/akka.remote.artery/RemoteConnectionSpec/Remoting_between_systems_should_allow_other_system_to_connect_even_if_it_s_not_there_at_first/

```
Error Message

akka.remote.RemoteTransportException: Inbound Aeron channel is in errored state. See Aeron logs for details.

Stacktrace

sbt.ForkMain$ForkError: akka.remote.RemoteTransportException: Inbound Aeron channel is in errored state. See Aeron logs for details.
	at akka.remote.artery.aeron.ArteryAeronUdpTransport.retry$1(ArteryAeronUdpTransport.scala:235)
	at akka.remote.artery.aeron.ArteryAeronUdpTransport.blockUntilChannelActive(ArteryAeronUdpTransport.scala:226)
	at akka.remote.artery.aeron.ArteryAeronUdpTransport.runInboundStreams(ArteryAeronUdpTransport.scala:305)
	at akka.remote.artery.ArteryTransport.start(ArteryTransport.scala:456)
	at akka.remote.RemoteActorRefProvider.init(RemoteActorRefProvider.scala:222)
	at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:874)
	at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:870)
	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:870)
	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:891)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:246)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:289)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:264)
	at akka.remote.artery.ArteryMultiNodeSpec.newRemoteSystem(ArteryMultiNodeSpec.scala:51)
	at akka.remote.artery.RemoteConnectionSpec.$anonfun$new$5(RemoteConnectionSpec.scala:67)
```

### PR DESCRIPTION
**Pull request by chbatey**
* Select a free port on the same interface for the second actor system
rather than the random one

Fixes #26130

### CODE REVIEW

File: akka-remote/src/test/scala/akka/remote/artery/RemoteConnectionSpec.scala [hunk 1]
```diff
@@ -51,23 +51,24 @@ class RemoteConnectionSpec extends ArteryMultiNodeSpec("akka.remote.retry-gate-c
...
 
       val localPort = port(localSystem)
+      val localHost = address(localSystem).host.get
       muteSystem(localSystem)
 
       val localProbe = new TestProbe(localSystem)
       localSystem.actorOf(TestActors.echoActorProps, "echo")
 
-      val remotePort = temporaryServerAddress(udp = true).getPort
+      val remotePort = temporaryServerAddress(localHost, udp = true).getPort
```
Comment (patriknw) [inline akka-remote/src/test/scala/akka/remote/artery/RemoteConnectionSpec.scala]: We should adjust these tests so that they select upd/tcp port based on the Artery transport.
We already run them like that in https://jenkins.akka.io:8498/job/akka-artery-tcp-remote-tests/
```
sbt -Dakka.remote.artery.transport=tcp akka-remote/test akka-remote-tests/test
```

Comment (chbatey) [reply akka-remote/src/test/scala/akka/remote/artery/RemoteConnectionSpec.scala]: Aha will also do that

**Review by raboof — APPROVED** [review]

File: akka-remote/src/test/scala/akka/remote/artery/ArteryMultiNodeSpec.scala [hunk 2]
```diff
@@ -69,3 +75,14 @@ abstract class ArteryMultiNodeSpec(config: Config) extends AkkaSpec(config.withF
...
 }
+
+object ArteryMultiNodeSpec {
+  def arteryUdpEnabled(systemConfig: Config): Boolean = {
+    val arterySettings = ArterySettings(systemConfig.getConfig("akka.remote.artery"))
+    arterySettings.Transport == ArterySettings.AeronUpd
+  }
+
+  def freePort(systemConfig: Config): Int = {
+    SocketUtil.temporaryLocalPort(ArteryMultiNodeSpec.arteryUdpEnabled(ConfigFactory.load()))
```
Comment (patriknw) [inline akka-remote/src/test/scala/akka/remote/artery/ArteryMultiNodeSpec.scala]: use `systemConfig`

**Review by patriknw — APPROVED** [review]
good, one small thing...
