### PR TITLE
Fix a bug in viaMat for Identity flow optimization

### LINKED ISSUE #22899: IllegalArgumentException with identity flow
This code
```scala
Flow.fromSinkAndSource[Any, Int](
    Sink.ignore
  , Source
    .single(1)
    .via(Flow[Int])
)
```
leads to 
```
java.lang.IllegalArgumentException: Port GraphStages$Identity$.out(2108763062) cannot be accessed in this builder
        at akka.stream.impl.LinearTraversalBuilder.offsetOfModule(TraversalBuilder.scala:767)
        at akka.stream.impl.CompositeTraversalBuilder.add(TraversalBuilder.scala:1265)
        at akka.stream.impl.CompletedTraversalBuilder.add(TraversalBuilder.scala:460)
        at akka.stream.scaladsl.GraphDSL$Builder.add(Graph.scala:1102)
        at akka.stream.scaladsl.GraphApply.create(GraphApply.scala:42)
        at akka.stream.scaladsl.GraphApply.create$(GraphApply.scala:38)
        at akka.stream.scaladsl.GraphDSL$.create(Graph.scala:1035)
        at akka.stream.scaladsl.Flow$.fromSinkAndSourceMat(Flow.scala:329)
        at akka.stream.scaladsl.Flow$.fromSinkAndSource(Flow.scala:319)
```

Not sure what is going on here...

EDIT: akka version is 2.5.1

### PR DESCRIPTION
**Pull request by richardimaoka**
Closes #22899 

The implementation got quite ugly :frowning: .... so any advice to make it cleaner welcomed.

## intention

The signature of viaMat:
https://github.com/akka/akka/blob/282a9b65f200299282dcfe66be195df6e02df67f/akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala#L47

can be illustrated as follows:

2017-10-16_04h24_49

## if combine == Keep.left

We can just return `this`.

2017-10-16_04h24_59

## if combine == Keep.right or combine == Keep.both

`source.viaMat(identity)(combine)` is materialized to `NotUsed` in both cases, since `identity` is materialized to `NotUsed`. We need to call `.append` to modify the traversal builder, but `LinearTraversalBuilder.empty()` can be passed.

2017-10-16_04h25_10

## if combine == Keep.both

No optimization is performed.

2017-10-16_04h25_27

### CODE REVIEW

File: akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphMatValueSpec.scala [hunk 1]
```diff
@@ -235,6 +235,25 @@ class GraphMatValueSpec extends StreamSpec {
       m4 should ===(NotUsed)
     }
 
+    "build more complicated graph with flows optimized for identity flows" in {
```
Comment (richardimaoka) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphMatValueSpec.scala]: Following the test case right above, but use `fromSinkAndSourceMat` as the #22899 issue is realized when building more complicated graphs.

File: akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala [hunk 2]
```diff
@@ -45,15 +45,23 @@ final class Source[+Out, +Mat](
...
-        LinearTraversalBuilder.empty()
+    if (flow.traversalBuilder eq Flow.identityTraversalBuilder)
+      if(combine == Keep.left)
+        //optimization by returning this
+        this.asInstanceOf[Source[T, Mat3]] //Mat == Mat3, due to Keep.left
+      else if(combine == Keep.right || combine == Keep.none) // Mat3 = NotUsed
+        //optimization with LinearTraversalBuilder.empty()
+        new Source[T, Mat3](
+          traversalBuilder.append(LinearTraversalBuilder.empty(), flow.shape, combine),
+          SourceShape(shape.out).asInstanceOf[SourceShape[T]])
```
Comment (richardimaoka) [inline akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala]: Using `SourceShape(shape.out)` (not `flow.shape.out`) to avoid the outport-inconsistency issue as in  #22899.

**Comment by johanandren** [comment]
OK TO TEST

File: akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphMatValueSpec.scala [hunk 3]
```diff
@@ -235,6 +235,25 @@ class GraphMatValueSpec extends StreamSpec {
...
+      val flow1 = Flow.fromSinkAndSourceMat(Sink.ignore, Source.single(1).viaMat(Flow[Int])(Keep.both))(Keep.both)
+      val (mA, (m1, m2)) = Source.single(8).viaMat(flow1)(Keep.right).to(Sink.ignore).run()
+      Await.result(mA, 1.second) should === (Done) //from Sink.ignore
```
Comment (johanandren) [inline akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphMatValueSpec.scala]: `.futureValue` is a bit more concise than `Await.result` and picks up the default/right timeout from the test setup rather than using an arbitrary timeout everywhere

**Review by johanandren — APPROVED** [review]
LGTM, with minor nitpick in the test

**Comment by johanandren** [comment]
Failure is formatting, make sure you compile both tests and sources one time before committing to get them autoformatted

**Comment by richardimaoka** [comment]
Fixed formatting. 

Do we better wait until @drewhk implements a long-term solution, or merge this interim solution so that the issue is resolved for now?

> drewhk commented 
> I will. I had an idea how to solve this properly but had no time to PR.

**Comment by drewhk** [comment]
This is exactly how I imagined it, so this is perfectly fine. I don't think there is really a better long-term solution, this is an optimization path and somewhat of a corner case. 

So LGTM on my side.

**Review by johanandren — APPROVED** [review]
LGTM, thanks!

**Comment by johanandren** [comment]
(Counted Endres LGTM as a team LGTM for this one :) )
