### PR TITLE
=str #17323 Source.actorRef now emits buffered els before completion

### LINKED ISSUE #17323: Possible bug: sending Status.Success message to an Source.actorRef can discard previous messages
I was experimenting with akka-streams 1.0-RC1 and was confused by the behavior of a sample program I wrote:

```
import akka.actor.ActorSystem
import akka.actor.Status
import akka.actor.actorRef2Scala
import akka.stream._
import akka.stream.OverflowStrategy
import akka.stream.scaladsl.Sink
import akka.stream.scaladsl.Source

object PossibleBug extends App {
  implicit val system = ActorSystem()
  implicit val mat = ActorFlowMaterializer()
  
  val a = Source.actorRef(10, OverflowStrategy.fail).to(Sink.foreach(println)).run()
  a ! "abc"
  a ! "def"
  Thread.sleep(100)           // (1)
  a ! Status.Success("ok")    // (2)
  
  Console.readLine()
  
  system.shutdown()
}
```

The program as it is prints two messages: "abc" and "def"
With Thread.sleep (line (1)) commented out it doesn't print anything
With Status.Success (line (2)) commented out it prints two messages: "abc" and "def"

it looks like there is a race between consuming regular messages and Status.Success message.

### PR DESCRIPTION
**Pull request by ktoso**
Landed and pushed :-)
Resolves #17323 and also avoids a possible NPE which would happen if `bufferSize = 0` and demand is signalled - the condition in the while loop was not completely correct (did not guard from `buffer = null`).

### CODE REVIEW

File: akka-stream/src/main/scala/akka/stream/impl/ActorRefSourceActor.scala [hunk 1]
```diff
@@ -32,18 +32,19 @@ private[akka] class ActorRefSourceActor(bufferSize: Int, overflowStrategy: Overf
   def receive = {
     case _: Request ⇒
       // totalDemand is tracked by super
-      while (totalDemand > 0L && !buffer.isEmpty)
-        onNext(buffer.dequeue())
+      if (bufferSize != 0)
```
Comment (ktoso) [inline akka-stream/src/main/scala/akka/stream/impl/ActorRefSourceActor.scala]: otherwise NPE happens, added a test which shows this

File: akka-stream/src/main/scala/akka/stream/impl/ActorRefSourceActor.scala [hunk 2]
```diff
@@ -63,12 +64,31 @@ private[akka] class ActorRefSourceActor(bufferSize: Int, overflowStrategy: Overf
...
+      context.stop(self)
+
+    case Status.Failure(cause) if isActive ⇒
+      // errors must be signalled as soon as possible,
+      // even if previously valid completion was requested via Status.Success
+      onErrorThenStop(cause)
+
+    case _: Request ⇒
+      // totalDemand is tracked by super
+      while (totalDemand > 0L && !buffer.isEmpty)
```
Comment (ktoso) [inline akka-stream/src/main/scala/akka/stream/impl/ActorRefSourceActor.scala]: // here we know buffer is not null

File: akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala [hunk 3]
```diff
@@ -355,11 +353,14 @@ object Source extends SourceApply {
...
-   * [[akka.actor.Status.Success]] to the actor reference.
+   * The stream can be completed successfully by sending the actor referende an [[akka.actor.Status.Success]]
+   * messagein which case already buffered elements will be signalled before signalling completion,
+   * or by sending a [[akka.actor.PoisonPill]] in which case completion will be signalled immediatly.
    *
    * The stream can be completed with failure by sending [[akka.actor.Status.Failure]] to the
-   * actor reference.
+   * actor reference. In case the Actor is still draining its internal buffer (after having received
+   * an [[akka.actor.Status.Success]]) before signalling completion and it receives a [[akka.actor.Status.Failure]],
+   * the failure will be signalled downstream immediatly (instead of the completion signal).
```
Comment (ktoso) [inline akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala]: I guess we should stick to UK spelling or US spelling... We have a mix currently ("ll" is UK)

File: akka-stream/src/main/scala/akka/stream/impl/ActorRefSourceActor.scala (hunk 1 above)
Comment (patriknw) [inline akka-stream/src/main/scala/akka/stream/impl/ActorRefSourceActor.scala]: good catch

**Comment by patriknw** [comment]
LGTM

**Comment by drewhk** [comment]
LGTM

**Comment by ktoso** [comment]
Failure was SSL
